### ISSUE TITLE
sudo node inito.js ERROR running Dashcoin

### ISSUE THREAD

**Issue by hiroshi2701** [dashpay/dash#1036]
Hi guys,

Can you guys help me please? I'm having a problem when I starting my mining pool for dashcoin. Here's the error I'm getting:

[2016-09-20 11:27:48.124] [DEBUG] [default] - Pool dash Thread 2 Share processing setup with redis (127.0.0.1:6379)
[2016-09-20 11:27:57.046] [DEBUG] [default] - Master CLI CLI listening on port 17117
[2016-09-20 11:27:57.645] [INFO] [default] - New Relic
[2016-09-20 11:27:57.649] [INFO] [default] - POSIX Not Installed
[2016-09-20 11:27:57.649] [INFO] [default] - Run Workers
[2016-09-20 11:27:57.659] [INFO] [default] - New Relic
[2016-09-20 11:27:57.662] [INFO] [default] - POSIX Not Installed
[2016-09-20 11:27:57.662] [INFO] [default] - Run Workers

**[2016-09-20 11:27:57.677] [ERROR] [default]** - Payments dash Error with payment processing daemon {"type":"offline","message":"connect ECONNREFUSED"}
[2016-09-20 11:27:57.713] [DEBUG] [default] - Website Server Website started on 45.32.51.56:80
**[2016-09-20 11:27:57.780] [ERROR] [default]** - Website dash Could not dumpprivkey for dash {"type":"offline","message":"connect ECONNREFUSED"}

![2016-09-20_1936](https://cloud.githubusercontent.com/assets/22319918/18668775/0ff9b240-7f6a-11e6-92e1-08e46c018b8b.png)

Any help will be appreciated! Thank you!

Best Regards,
Mark
Sigway Higgs

**Comment by UdjinM6** [comment]
I doubt that this error has smth to do with Dash Core tbh. Please check your unomp pool settings https://github.com/UNOMP/unified-node-open-mining-portal#pool-config specifically "daemons", "auxex" -> "daemon" and "paymentProcessing" -> "daemon". If all looks good and you still have no luck trying to start your pool you should probably create an issue there https://github.com/UNOMP/unified-node-open-mining-portal/issues. Alternatively you can ask for help on our forum in mining section https://www.dash.org/forum/topic/questions-and-help.70/ but I'm not sure how many people are running nomp/unomp these days.

**Comment by hiroshi2701** [comment]
Thank you for your response UdjinM6. I'm kinda new with dashcoin. I wanted to add a currency to my mining pool. So what I did is just copy pasted the content of pool_configs>litecoin.json.example into dash.json and made the appropriate changes from there. But I'm not sure if I covered it all. Do you have a dash.json.example that you can provide? I really appreciate it UdjinM6. 

Here's what my dash.json looked like

{
    "enabled": true,
    "coin": "dash.json",

    "auxes": [],
    "address": "[my-address]",

    "rewardRecipients": {
        "n37vuNFkXfk15uFnGoVyHZ6PYQxppD3QqK": 1.5,
        "22851477d63a085dbc2398c8430af1c09e7343f6": 0.1
    },

    "paymentProcessing": {
        "enabled": true,
        "paymentInterval": 30,
        "minimumPayment": 0.01,
        "daemon": {
            "host": "127.0.0.1",
            "port": 19332,
            "user": "[my-username]",
            "password": "[my-password]"
        }
    },

    "ports": {
        "3008": {
            "diff": 8
        },
        "3032": {
            "diff": 32,
            "varDiff": {
                "minDiff": 8,
                "maxDiff": 512,
                "targetTime": 15,
                "retargetTime": 90,
                "variancePercent": 30
            }
        },
        "3256": {
            "diff": 256
        }
    },

    "daemons": [
        {
            "host": "127.0.0.1",
            "port": 19332,
            "user": "[my-username]",
            "password": "[my-password]"
        }
    ],

    "p2p": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 19333,
        "disableTransactions": false
    },

    "mposMode": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 3306,
        "user": "me",
        "password": "mypass",
        "database": "ltc",
        "checkPassword": false,
        "autoCreateWorker": false
    }

}

Thanks,
Mark

**Comment by UdjinM6** [comment]
Well, as I already mentioned you are probably asking in the wrong place since this repo is for Dash Core, not for the unomp mining pool you are using. And no, I'm not running one.

One more thing I can advise you however is to change ports in every "daemon" section to 9998 and port in "p2p" section to 9999. Also make sure that "[my-username]" and "[my-password]" match you settings in ~/.dash/dash.conf

If that doesn't help, you really should ask unomp community to help you https://github.com/UNOMP/unified-node-open-mining-portal/issues

**Comment by hiroshi2701** [comment]
Thanks very much UdjinM6! I'll try this right now. :)

**Comment by hiroshi2701** [comment]
This fixed the problem UdjinM6. Thank you very much. You're a lifesaver!! :)

**Comment by Visionmeks** [comment]
I have the same problem, how to solve it? Is there an additional code or other configuration?
