### ISSUE TITLE
[v0.12.1.x testnet] Masternode stays in state "PRE_ENABLED"

### ISSUE THREAD

**Issue by crowning-** [dashpay/dash#1043]
I'm running a hot/cold Masternode on testnet for a couple of days now and it gets regular MN-payments.

The problem is, it's listed in status "PRE_ENABLED" with an "Active" time of "00m:00s". That shouldn't be.

If you need logs just give me an email address to send them to.

**Update:** the wallet with the 1000 tDASH vin reports it as "PRE_ENABLED". The remote dashd (and probably the rest of the world) sees the status "ENABLED", so it should be correct to receive payments.

**Comment by UdjinM6** [comment]
Re update: yep, I don't see any pre-enabled either.
Can I have local debug.log? UdjinM6@dash.org [zip it first pls :)]

**Comment by crowning-** [comment]
Email sent!

**Comment by UdjinM6** [comment]
Ok, so if I get debug.log output correctly you are using dash.conf hot/cold setup and it's quite possible that something doesn't play quite right in that kind of setup. Try masternode.conf instead. If that helps I would rather not fix this one because... you know why :D

**Comment by crowning-** [comment]
Yep, masternode.conf works as expected... I think when I'll find some more time this week I'll have a look  into what's needed to completely deprecate masternoding via dash.conf
