### ISSUE TITLE
[12.1 testnet] protocol version of masternodelist

### ISSUE THREAD

**Issue by chaeplin** [dashpay/dash#1059]
I have checked debug log and found the protocol version of a node is 70201.
But 'masternode list'  shows protocol version of the node as 70202.

macos sierra, Dash Core version v0.12.1.0-1eb399c (64-bit)
```
2016-10-03 17:13:33 receive version message: /Dash Core:0.12.1/: version 70201, us=xxx, , peer=12, peeraddr=aa.48.185.55:19999
```

```
  "e62ebae735969f203c91a4b48e5b8c8e22332abbda5f5c756dc18751ecf35047-0": "  ENABLED 70202 yTCez9XVLgi3v1TmSNfrTjAmGwe875f7wv 1475514486   235428 1475514814  79721 aa.48.185.55:19999",
  "f6e282fb3bab4ccfcc53e1fa029613225791b5ad3d81bede9810f0ce7d6af7a1-1": "  ENABLED 70202 yio3QxN6uHjpbgyYQ9erpqMdDEhqb7yCAq 1475514594   235526 1475237062  77965 aa.48.185.55:19999",
  "5e681bca84fcbec216c7f43434bee90f7008c6c623f620e206057d7285f48326-0": "  ENABLED 70202 yXRE5LbE5shk85vdnBnA8bKNcQds7HSJuL 1475514587   235525 1475513811  79713 aa.48.185.55:19999",
  "07f1fc88a1b1e6a6bf0ffa744d270d9f13224bb1ef7c245014d30bdf649e12d2-0": "  ENABLED 70202 yb7zPDqVVVrFEx2tvKYduo35ojfEvEYuNV 1475514622   235555 1475504423  79651 aa.48.185.55:19999",
```

*edited : ip is masked

**Comment by tgflynn** [comment]
Also note that the IP address is obviously invalid here.  I'm surprised we aren't validating those before considering an MN to be enabled, or accepting a peer connection.

**Comment by chaeplin** [comment]
@tgflynnI have changed the ip. aa is actually 45 and xxx is my ip.

**Comment by tgflynn** [comment]
@chaeplin Ah, OK, thanks for clarifying that.

**Comment by UdjinM6** [comment]
`masternodelist` itself is fine and works as it should. The reason for results you see is that you node is a "real" one and all other nodes in `masternodelist` are nodes of an attacker who is reusing your IP. That's a known issue, but thanks for reporting anyway :)

**Comment by chaeplin** [comment]
thanks
