### ISSUE TITLE
InstantSend 1000 Dash Errors

### ISSUE THREAD

**Issue by ryansd92** [dashpay/dash#1099]
From the Receive tab, I requested 1000 Dash with "request InstantSend" checked. Then from the Send tab, I tried to send 1000 Dash to that address (copied to clipboard) with the InstantSend box checked.

I suppose it failed because I did not have the "Subtract Fee from amount" checked and the actual amount was greater than 1000. From a UX perspective this is confusing. Perhaps allow 1000 Dash+fee to go through or make it clearer why it failed.

<img width="1242" alt="screen shot 2016-10-26 at 12 19 43 pm" src="https://cloud.githubusercontent.com/assets/1169569/19734694/87f808fa-9b76-11e6-81d6-98c4fa2c35c9.png">

**Comment by ryansd92** [comment]
FYI - unchecking InstantSend permitted me to complete the transaction.

**Comment by ryansd92** [comment]
I am using the Mac wallet and had downloaded the most recent version moments prior to this transaction.

**Comment by chaeplin** [comment]
As fee is 0.001,  If  'Subtract fee from amount' is checked  --> 1000 is ok, else 999.999

```
Status: 1/unconfirmed (InstantSend verification in progress - 5 of 10 signatures), broadcast through 6 nodes
Date: 27/10/2016 19:35
To: yTEYrJX5gxXdvT9uCB6SdkbnK9jqV9s1e3
Debit: -999.99900000 tDASH
Transaction fee: -0.00100000 tDASH
Net amount: -1000.00000000 tDASH
Transaction ID: 42c17084ea169e8c98c09aa787ad62673f71ad8e89e18abf70a7534544cc7842-000
```

```
Status: 0/unconfirmed (InstantSend verification in progress - 5 of 10 signatures), broadcast through 13 nodes
Date: 27/10/2016 19:36
To: yTEYrJX5gxXdvT9uCB6SdkbnK9jqV9s1e3
Debit: -999.99900000 tDASH
Transaction fee: -0.00100000 tDASH
Net amount: -1000.00000000 tDASH
Transaction ID: 75f3175b4ecd0e2d37223879713955e2f391f9ee5566bd05897fddf5e193a6b5-000
```

**Comment by chaeplin** [comment]
Have tested. Previous input was 1000.
Looks like transaction is not 0.001 always.

1) 1000 with 'Subtract fee from amount' --> OK
http://i.imgur.com/E5S3JWE.png

2) 1000 without 'Subtract fee from amount' --> Warning
http://i.imgur.com/4v7DDla.png

3) 999.999 without 'Subtract fee from amount' ---> OK
http://i.imgur.com/yhi82xI.png

**Comment by ryansd92** [comment]
I love it. I think this is a great improvement.

**Comment by chaeplin** [comment]
One more test coin control(11 input) with 'Subtract fee from amount' : failed

I think red box show how it failed. 

![image](http://i.imgur.com/cRLsSzE.png)

**Comment by nmarley** [comment]
Hi Sean, is this still an issue with the current version of the software?

**Comment by nmarley** [comment]
Closing as solution / explanation provided by @chaeplin .
