### ISSUE TITLE
WATCHDOG_EXPIRED on New Masternode (12.1 testnet)

### ISSUE THREAD

**Issue by ryansd92** [dashpay/dash#1101]
I sent 1000 Dash to a new address, spun up a masternode, issued a Start Missing and the status was immediately WATCHDOG_EXPIRED.  I logged into the masternode and have the following status.

{
  "vin": "CTxIn(COutPoint(0000000000000000000000000000000000000000000000000000000000000000, 4294967295), coinbase )",
  "service": "52.71.2.46:19999",
  "status": "Node just started, not yet activated"
}

WATCHDOG EXPIRED is showing from the wallet, the masternode itself, and another non-masternode daemon.

I think the status should be PRE_ENABLED.

**Comment by tgflynn** [comment]
If you're running sentinel on the masternode it should switch to PRE_ENABLED within 2 minutes.

**Comment by ryansd92** [comment]
I am running sentinel and it's still WATCHDOG_EXPIRED. It has been more than 15 minutes now.

**Comment by tgflynn** [comment]
Are you sure you're running the current version of sentinel ?

**Comment by ryansd92** [comment]
Pretty sure. Here is some more information.

Ubuntu 14.04.5 LTS
Sentinel from https://github.com/nmarley/sentinel.git (and up-to-date)
dashd updated about an hour ago.
