### ISSUE TITLE
Is or Isn't?

### ISSUE THREAD

**Issue by spencerlievens** [dashpay/dash#1159]
if(service.GetPort() != 9999) {
                notCapableReason = strprintf("Invalid port: %u - only 9999 is supported on mainnet."
                
else if(service.GetPort() == 9999) {
            notCapableReason = strprintf("Invalid port: %u - 9999 is only supported on mainnet."

This code is from activemasternode.cpp

I read this as:

If it's not port 9999 throw an error telling the user that 9999 is not supported.
If it is port 9999 throw an error telling the user that 9999 is not supported.

How are masternodes on the network even starting if this contradicts itself?

**Comment by UdjinM6** [comment]
Full code:
```
        if(Params().NetworkID() == CBaseChainParams::MAIN) {
            if(service.GetPort() != 9999) {
                notCapableReason = strprintf("Invalid port: %u - only 9999 is supported on mainnet.", service.GetPort());
                LogPrintf("CActiveMasternode::ManageStatus() - not capable: %s\n", notCapableReason);
                return;
            }
        } else if(service.GetPort() == 9999) {
            notCapableReason = strprintf("Invalid port: %u - 9999 is only supported on mainnet.", service.GetPort());
            LogPrintf("CActiveMasternode::ManageStatus() - not capable: %s\n", notCapableReason);
            return;
        }
```
i.e. if (it's mainnet AND port is not 9999) OR (if it's not mainnet AND port is 9999) then throw some corresponding error

**Comment by spencerlievens** [comment]
Where does it say if it's not mainnet?

I see the code contained in one if statement, if MAIN.

**Comment by tgflynn** [comment]
There's an if(mainnet) statement that has an else clause.  The else clause applies if it's not mainnet.

**Comment by spencerlievens** [comment]
surely having it in another if statement makes much more sense i.e.

        if(Params().NetworkID() == CBaseChainParams::MAIN) {
            if(service.GetPort() != 9999) {
                notCapableReason = strprintf("Invalid port: %u - only 9999 is supported on mainnet.", service.GetPort());
                LogPrintf("CActiveMasternode::ManageStatus() - not capable: %s\n", notCapableReason);
                return;
            }
        } else if(Params().NetworkID() != CBaseChainParams::MAIN && service.GetPort() == 9999) {
            notCapableReason = strprintf("Invalid port: %u - 9999 is only supported on mainnet.", service.GetPort());
            LogPrintf("CActiveMasternode::ManageStatus() - not capable: %s\n", notCapableReason);
            return;
        }

**Comment by tgflynn** [comment]
That would be adding redundant logic.

**Comment by spencerlievens** [comment]
ok how about:

        if(Params().NetworkID() == CBaseChainParams::MAIN) {
            if(service.GetPort() != 9999) {
                notCapableReason = strprintf("Invalid port: %u - only 9999 is supported on mainnet.", service.GetPort());
                LogPrintf("CActiveMasternode::ManageStatus() - not capable: %s\n", notCapableReason);
                return;
            }
        }

        if(Params().NetworkID() != CBaseChainParams::MAIN {
            if(service.GetPort() == 9999) {
                notCapableReason = strprintf("Invalid port: %u - 9999 is only supported on mainnet.", service.GetPort());
                LogPrintf("CActiveMasternode::ManageStatus() - not capable: %s\n", notCapableReason);
                return;
            }
        }

**Comment by spencerlievens** [comment]
I like things to be easy to read and understandable. Sorry if you find this trivial.

**Comment by tgflynn** [comment]
I guess it's sort of easy to misread if you don't look closely at where the braces are due to visual effects (ie. the eye tends to want to associate the two service.GetPort conditions), but I don't think there's really anything wrong with the code as it is.

**Comment by spencerlievens** [comment]
That was more my point after the "else" was pointed out.
