### ISSUE TITLE
Governance object deletion vote syncing

### ISSUE THREAD

**Issue by tgflynn** [dashpay/dash#1165]
There is a scenario where governance objects are not properly deleted from certain nodes.

Governance objects are deleted from dashd when a sufficient number of masternodes have voted to delete the object.  

A node receives object A and then goes offline.  While the node is offline the network votes to delete object A.  Once the deletion quorum is reached object A is marked for deletion on all running nodes and 10 minutes later it is deleted from them.  All of object A's votes are also deleted along with the object.

At some subsequent time the node is brought back online.  It has object A stored in governance.dat and so object A is present on the node.  It syncs objects and votes from peers but receives no deletion votes for object A because its votes have already been deleted from the network.

The result is that the node has object A in its object list and will retain it indefinitely.

Note that this isn't a major concern for triggers (ie. superblocks) because dashd deletes outdated trigger objects automatically without requiring deletion votes.

It could however lead to a node retaining invalid proposals and, if it is a masternode, creating superblocks containing them.

**Comment by UdjinM6** [comment]
should be fixed by #1167 #1170
