### ISSUE TITLE
 有人吗 谁能告诉我How to find it  "peerMagic": "？？？？？？？？",

### ISSUE THREAD

**Issue by wuhuaping** [dashpay/dash#1209]
How to find it
 "peerMagic": "？？？？？？？？",
I didn't find it in /dash/src/main.cpp.
谁能告诉我怎么样才能找到它
我在/dash/src/main.cpp 中没有找到它

 atiger7758@163.com

**Comment by schinzelh** [comment]
https://github.com/dashpay/dash/blob/master/src/chainparams.cpp#L123-L126

**Comment by wuhuaping** [comment]
Thank you very much for your help.


"peerMagic": "bf0c6bbd",
    "peerMagicTestnet": "？？？？？？"  how do find it  





在 2016-12-17 20:26:54，"Holger Schinzel" <notifications@github.com> 写道：


https://github.com/dashpay/dash/blob/master/src/chainparams.cpp#L123-L126

**Comment by schinzelh** [comment]
https://github.com/dashpay/dash/blob/master/src/chainparams.cpp#L211-L214

**Comment by wuhuaping** [comment]
谢谢  Thanks for your advice and encouragement.

**Comment by wuhuaping** [comment]
谢谢 Thanks for your advice and encouragement.

在 2016-12-17 20:48:25，"Holger Schinzel" <notifications@github.com> 写道：


https://github.com/dashpay/dash/blob/master/src/chainparams.cpp#L211-L214
