### ISSUE TITLE
12.1 Mac Wallet WATCHDOG_EXPIRED but Really ENABLED

### ISSUE THREAD

**Issue by ryansd92** [dashpay/dash#1215]
I spun up three masternodes Dec 19 around 4pm. The following morning, all masternodes were running as expected but the status in my wallet was `WATCHDOG_EXPIRED` for all three masternodes. All three nodes were paid several times throughout the 15 hours or so they have been running. They are in fact `ENABLED` on the network according to each other. I believe the actual problem may be the desktop wallet.

    yQ3PAPRw8gAZNU5CtUaxziyFxb3kqukj2P
    yiHKzBUKCf2inMHz4t4e5UipbZQQ2naTwi
    yXbSxmuv4ji4HkiGgQqs2CdXbegEEYvSpe

I have the three debug.log files from the masternodes as well as the wallet itself if needed. I am not sure what other information I should provide but I'll be available to provide everything I can.

**Comment by tgflynn** [comment]
4pm in what timezone ?

The network is currently undergoing a protocol upgrade that could have caused issues like that but I don't know if it spans the time when this was observed.

**Comment by UdjinM6** [comment]
If you have "new" wallet (70204) but "old" MNs (70203) then such a wallet will not be able to see watchdogs from your MNs

**Comment by ryansd92** [comment]
Apologies: ET zone / NYC.

More info. My wallet are masternodes were all on 70203. Though I just ran a script a minute ago to upgrade them all to the latest build from a few hours ago. That may impact the protocol, if it's new.

I was able to make my wallet see them all as ENABLED after a simple wallet restart. I did not remove mncache.dat.

**Comment by tgflynn** [comment]
If it happened this morning I suspect it's somehow related to the protocol update even if your wallet wasn't upgraded at the time.  It's possible all your peers upgraded to 70204 (especially if you were peered with Holger's nodes) and there was no 70203 path in the network between your wallet and your masternodes.

**Comment by ryansd92** [comment]
@tgflynn I bet you are right. I'm in the process of moving to the new protocol now anyway. Perhaps this issue can be closed?

**Comment by ryansd92** [comment]
Ok some more info. All three masternodes and my wallet are on `70204`. After it was sync'd, my wallet showed all nodes as `ENABLED`. Now, maybe 30 minutes later, they all show as `WATCHDOG_EXPIRED`. Further, the wallet shows all the masternodes as on `70203`.

**Comment by tgflynn** [comment]
You may need to restart the masternodes (ie. with start-alias) after the protocol upgrade.

**Comment by UdjinM6** [comment]
Hmm, interesting... have you issued "masternode start-many" for them?

**Comment by ryansd92** [comment]
Ugh, I never issued a remote start. I forgot a remote start is needed after a protocol change. That said, the wallet was entirely misleading.

**Comment by ryansd92** [comment]
I only realized this after running sentinel manually and it yelled at me :)

**Comment by ryansd92** [comment]
Closing this issue because it probably had to do with the protocol change originally, and then my need for a remote start.

Thank you all for the help.
