### ISSUE TITLE
Starting WATCHDOG_EXPIRED

### ISSUE THREAD

**Issue by ryansd92** [dashpay/dash#1224]
I changed three of my masternodes IP addresses, restarted the daemons, and eventually they moved into the WATCHDOG_EXPIRED state. That makes sense because `dash-cli masternode list full` shows the old IP but the actual IP in the dash.conf is different. I'm pretty sure the solution is to issue a remote start but it isn't clear from the wallet how to do that. There are three options: Start Alias, Start Missing, and Start All. My understanding was that WATCHDOG_EXPIRED is treated as missing but i guess not. I just tried "start missing" and that wasn't it. I had to issue a start alias. If I have a lot of WATCHDOG_EXPIRED (like 100) I don't want to issue that many starts.

I think we need to better communicate to the user what to do. Maybe add another button to start WATCHDOG_EXPIRED.

The reason I think this is important is because if a user clicks "Start All," all their masternodes are pushed to the back of the queue regardless of state. Right?

That said, maybe a little more clarity on the consequences/expectations of selecting each option is needed.

**Comment by schinzelh** [comment]
IMHO a "start watchdog expired" does not make sense, as this state relies solely on sentinel.

A "started" masternode has three states it can reach: pre_enabled, enabled and watchdog expired.

**Comment by thelazier** [comment]
IMHO, the real problem is how to properly change masternode ip address.
If I have 100 masternode's ip address being changed, I would create a special masternode.conf to include just these 100 masternode new ip and use start all.

**Comment by ryansd92** [comment]
@schinzelh - yes, I agree. We know this but users have no real understanding of the many different states that exist. Or, more precisely, we shouldn't assume a user knows the difference. Perhaps "reset" is a better term to use?

@thelazier yes, you may be right, and I can generate current masternode.conf files for my customers. I don't really know the right answer but I did want to raise an issue bring the concern to light, from my perspective.

**Comment by techliff** [comment]
Hi, how can I fix this error in my vivo wallet (watchdog_expired) ? I'm new so I do not know what to do. I use windows wallet , not vps.
Thank you.

**Comment by schinzelh** [comment]
Should be fixed in current version of Sentinel/Dash

@techliff we do not offer support for 3rd party wallets
