### ISSUE TITLE
12.1.x wallet upgrade (windows)

### ISSUE THREAD

**Issue by perrywoodin** [dashpay/dash#1230]
When upgrading the **Windows** wallet from 12.0.58 to 12.1.0, the data directory defaults to `Dash` instead of `DashCore`. As a result, the wallet cannot be started until you delete the `mncache.dat` file. 

If you do a clean install of 12.1.0 where the `Dash` data directory does not exist, you will see the default data directory gets set to `Dash` instead of `DashCore`

To replicate the upgrade issue with the `mncache.dat` error, I do the following:

* Confirm that `AppData\Roaming\Dash` does not exist.
* Install 12.0.58.
* Accept the default data directory of `AppData\Roaming\Dash`
* Close the wallet.
* Install 12.1.0
* Note that you are not prompted to set a data directory.
* Receive the error `Cannot obtain a lock on data directory C:\Users\username\AppData\Roaming\Dash. Dash Core is probably already running`
* Click OK
* Delete `mncache.dat`
* Restart wallet.

**Comment by UdjinM6** [comment]
Can confirm but only partially - I get different error: "Can't load masternode cache from mncache.dat". "Lock" error should only occur if you started another copy of the wallet before you closed the other one (make sure small window "wait for..." disappears). Anyway, thanks for reporting the issue need to be addressed in some way for sure.

**Comment by UdjinM6** [comment]
should be fixed  by #1287
