### ISSUE TITLE
Inaccurate/Misleading Masternode Status after "Start All"

### ISSUE THREAD

**Issue by ryansd92** [dashpay/dash#1233]
I updated all my nodes today, including my wallet for 12.1 testnet.

I have 9 entries in my masternode.conf file. 4 of those entries were EXPIRED because I took those nodes offline. The other are still online.

When I clicked "Start All", all 9 masternodes transitioned to PRE_ENABLED in the wallet. Obviously, 4 of them should not have transitioned at all. I am not sure if this is a bug or a side effect of assuming the status is PRE_ENABLED until the masternodes transition to ENABLED (or other).

**Comment by tgflynn** [comment]
Other nodes have no way of knowing that those MN's aren't running.

They see a new broadcast for the MN's which causes them to transition to PRE_ENABLED until the ping time has elapsed.  After that, not seeing a ping from the MN's, they should transition to EXPIRED.

This is expected behavior as far as I know.

**Comment by ryansd92** [comment]
Ok, I understand. May I make a suggestion? Instead of PRE_ENABLED, change it to PENDING, or PENDING_ACCEPTANCE, or something more reflective of why it's not ENABLED. I realize this might be late in the game for a change like this but I did notice a new status this morning so it's not out of the range of possibilities :)

Otherwise, I'l close this ticket.

**Comment by ryansd92** [comment]
Oh, what is the ping time? I started the masternodes 23 minutes ago and they are still PRE_ENABLED.

**Comment by tgflynn** [comment]
10 min but IIRC it can compound with a second 10 min wait.  However after 23 min they should have expired if the MN's aren't active.

Can you send me the vin's for these MN's so I can check the state on some other nodes ?  (You can send them in the slack #development channel if that's easier).

**Comment by ryansd92** [comment]
I can send them to you but I can see that all 5 of my masternodes are behind on blocks. I am going to attempt to re-install. If that doesn't work, I can send you what you asked for. Stay tuned.

**Comment by ryansd92** [comment]
I am closing this issue because I worked with @tgflynn via slack to work through the particular issue I was having. I am opening a new ticket related to status changes over time that were unexpected.
