### ISSUE TITLE
--disable-wallet fail

### ISSUE THREAD

**Issue by Singman33** [dashpay/dash#124]
If you enable the option --disable-wallet in configure step, the compilation will fail at link time.

**Comment by freynder** [comment]
Can confirm this:
rpcdarksend, activemasternode and darksend rely on wallet references. Will consider to exclude relevant parts for rpcdarksend and activemasternode when rewriting those parts.

**Comment by schinzelh** [comment]
This also explains why 'masternode *' commands do not work if disablewallet=1 is set at runtime.

**Comment by schinzelh** [comment]
@UdjinM6 could you have a look if we can resolve this by moving includes around?
