### ISSUE TITLE
dash-cli -datadir and -conf seem to be ignored.

### ISSUE THREAD

**Issue by taw00** [dashpay/dash#1262]
Environment: Fedora 24, 12.1 (build 771 - latest as of today), and latest sentinel. This is a running, fully enabled masternode (because I muddled through this). Read on...

I am experimenting with `dashd` (a testnet masternode in this case) running as a proper service (bitcoin allows this as well). When you do that, your datadir should be installed someplace other than `~/.dashcore`. And likely, you'll put your `dash.conf` in a different location as well separate from the datadir. But `dash-cli` seems to only understand `~/.dashcore`...

1. no matter what you set -datadir or -conf to... it will look for `dash.conf` in `$HOME/.dashcore/`
2. no matter what you set -datadir to, it seems to want all the data to reside in `$HOME/.dashcore/`

Example:    
_Again, `/var/lib/dashcore` and `/etc/dashcore/dash.conf` represent a running, working masternode_
```
[root@X ~]# dash-cli getinfo -datadir=/var/lib/dashcore
error: Could not locate RPC credentials. No authentication cookie could be found, and no rpcpassword is set in the configuration file (/root/.dashcore/dash.conf)
```

Example:    
_Again, `/var/lib/dashcore` and `/etc/dashcore/dash.conf` represent a running, working masternode_
```
[root@X ~]# dash-cli getinfo -conf=/etc/dashcore/dash.conf -datadir=/var/lib/dashcore
error: Could not locate RPC credentials. No authentication cookie could be found, and no rpcpassword is set in the configuration file (/root/.dashcore/dash.conf)
```

Example:    
_Again, `/var/lib/dashcore` and `/etc/dashcore/dash.conf` represent a running, working masternode_
```
[root@X ~]# dash-cli getinfo -datadir=/var/lib/dashcore -conf=lkajsdflkjsd.conf
error: Could not locate RPC credentials. No authentication cookie could be found, and no rpcpassword is set in the configuration file (/root/.dashcore/dash.conf)
```

So, I then created a `~/.dashcore` directory and symlinked the `dash.conf` file in there. and with that, I got and error that suggested it couldn't find the data, because, of course, it is looking for it in `~/.dashcore/`
```
[root@X ~]# mkdir ~/.dashcore
[root@X ~]# ln -s /etc/dashcore/dash.conf ~/.dashcore/dash.conf
[root@X ~]# dash-cli getinfo -datadir=/var/lib/dashcore
error code: -1
error message:
getinfo
Returns an object containing various state info.

Result:
{
  "version": xxxxx,           (numeric) the server version
  "protocolversion": xxxxx,   (numeric) the protocol version
...etc...
``` 

## WORKAROUND:

I symlinked the `/var/lib/dashcore` directory to `~/.dashcore` and then symlinked `/etc/dashcore/dash.conf` to `~/.dashcore/dash.conf` and finally the `dash-cli` command on the masternode did what it was supposed to do, no matter what I set -datadir or -conf to.

```
[root@X ~]# rm -rf ~/.dashcore
[root@X ~]# ln -s /var/lib/dashcore ~/.dashcore
[root@X ~]# ln -s /etc/dashcore/dash.conf ~/.dashcore/dash.conf
[root@X ~]# dash-cli getinfo
...all the output one expects...
```

We really can't relocate datadir and the conf file?

**Comment by UdjinM6** [comment]
For this to work properly you need to specify the same `-conf` on `dashd` start i.e. `dashd -conf=/etc/dashcore/dash.conf`

**Comment by schinzelh** [comment]
Yep, dashd and dash-cli are distinct programs, so you need to pass the same parameters for conf dir to both.

**Comment by taw00** [comment]
Doesn't matter... -conf is ignored. As for dashd, UdjinM6...
```
[root@X ~]# systemctl status dash
● dash.service - Dash Core daemon
   Loaded: loaded (/usr/lib/systemd/system/dash.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2017-01-14 16:22:53 UTC; 4h 22min ago
 Main PID: 14810 (dashd)
    Tasks: 15 (limit: 512)
   CGroup: /system.slice/dash.service
           └─14810 /usr/sbin/dashd -daemon -conf=/etc/dashcore/dash.conf -datadir=/var/lib/dashcore -pid=/run/dashd/dashd.pid -testnet -disable-wallet
```

**Comment by UdjinM6** [comment]
>/usr/sbin/dashd -daemon -conf=/etc/dashcore/dash.conf -datadir=/var/lib/dashcore -pid=/run/dashd/dashd.pid -testnet -disable-wallet

If `-testnet` is not a part of `/etc/dashcore/dash.conf` file you need to specify it in `dash-cli` call too i.e. `dash-cli -conf=/etc/dashcore/dash.conf -testnet getinfo`.

Another thing to note that you are using `dash-cli` incorrectly:
```
> dash-cli -?
Dash Core RPC client version v0.12.0.60-637a93c

Usage:
  dash-cli [options] <command> [params]  Send command to Dash Core
....
```
i.e. first you need to specify options, not the command.

**Comment by taw00** [comment]
BOOM! That was it. The ordering. Working as expected now. Unfortunately, the error messaging is horrid and doesn't tell you anything. (and note, testnet=1 is in the conf file)

`dash-cli -datadir=/var/lib/dashcore -conf=/etc/dashcore/dash.conf getinfo`    
...and not...    
`dash-cli getinfo -datadir=/var/lib/dashcore -conf=/etc/dashcore/dash.conf`

What is this, commandlines from the 1990s? (industry standard is --option by the way) ;)

Oi. Anyway. RFE for consideration: I think 2017 and moving towards Evolution needs to include some prioritized effort towards polish, design, architecture improvements for all the tooling. Config files have overloaded function; commandline tools and options are exceptionally twitchy and work differently dependent on context; and troubleshooting is often incredibly difficult. Help files are so-so, documentation needs work, and everything could use a solid man page (if the --help isn't enough).

Anyway... I will likely try to help in some of this, but I thought I would voice my thoughts.

Thanks for investigating this red herring wrapped in a wild goose chase. :)

**Comment by UdjinM6** [comment]
ok, cool :)
