### ISSUE TITLE
dash with chromecast

### ISSUE THREAD

**Issue by djmaxisauce** [dashpay/dash#1263]
Hi,

I am working with an ionic app, and it works with DASH player ( http://dashif.org/reference/players/javascript/v2.3.0/samples/dash-if-reference-player/index.html )

I need to send video to the chromecast, is it possible ? any  recommendations?

**Comment by UdjinM6** [comment]
I guess you are in the wrong repo, should probably ask there https://github.com/Dash-Industry-Forum/dash.js/issues :)
