### ISSUE TITLE
rpcmasternode.cpp - status list update

### ISSUE THREAD

**Issue by MrDefacto** [dashpay/dash#1266]
Hi,

Line 475 in rpcmasternode.cpp should be updated. In 12.1 there is no REMOVE status and actual list of statuses looks like this:
PRE_ENABLED / ENABLED / EXPIRED / OUTPOINT_SPENT / UPDATE_REQUIRED / WATCHDOG_EXPIRED / NEW_START_REQUIRED / POSE_BAN / UNKNOWN

**Comment by UdjinM6** [comment]
Thanks! `UNKNOWN` is an internal one so user should never see it but other than that - will fix!

**Comment by MrDefacto** [comment]
I didn't analyze that so deeply :-) I'm working on my Dash project and was checking source code to find all statuses and found those... and REMOVE was only in this one place ;-) i thought that i let know about my finding.

**Comment by UdjinM6** [comment]
fixed by #1272
