### ISSUE TITLE
Getblocktemplate output issue   So to solve him.  Thank you

### ISSUE THREAD

**Issue by wuhuaping** [dashpay/dash#1275]
root@ecs-8edf:\~# dash-cli  getblocktemplate
{
    "capabilities" : [
        "proposal"
    ],
    "version" : 3,
    "previousblockhash" : "0000000000002f28a6c3cd0b03c52df481c09
    "transactions" : [
    ],
    "coinbaseaux" : {
        "flags" : ""
    },
    "coinbasevalue" : 388010205,
    "longpollid" : "0000000000002f28a6c3cd0b03c52df481c097af78ef
    "target" : "000000000000c11000000000000000000000000000000000
    "mintime" : 1484834562,
    "mutable" : [
        "time",
        "transactions",
        "prevblock"
    ],
    "noncerange" : "00000000ffffffff",
    "sigoplimit" : 20000,
    "sizelimit" : 1000000,
    "curtime" : 1484835527,
    "bits" : "1b00c110",
    "height" : 606599,
    "votes" : [
    ],
    "payee" : "XxcsxadHStBWYyKvwAHe9yTy6ygibVHACP",
    "payee_amount" : 194005101,
    "masternode_payments" : true,
    "enforce_masternode_payments" : true
}
root@ecs-8edf:~# node 
>  Math.ceil(388010205*0.375)
145503827

atiger7758@163.com

**Comment by UdjinM6** [comment]
Try 50% (which is the correct current MN/miner reward split)
>Math.ceil(388010205*0.5)
194005103

Looks closer now? ;) BUT you should NOT calculate it that way because it's a multi-step calculation, see `GetMasternodePayment()` in main.cpp for more details. You should just use `getblocktemplate`'s `"payee_amount" : 194005101,` instead.

**Comment by wuhuaping** [comment]
Thank you very much for your explanation.
I see the explanation on your website
Need to modify  unomp 
Is this the way to modify it
 unomp 
transactions.js
if (rpcData.payee) {
-        var payeeReward = Math.ceil(reward / 5);
+    if (rpcData.payee) { 
+	var payeeReward = 0;
+
+        if (rpcData.payee_amount) {
+            payeeReward = rpcData.payee_amount;
+        } else {
+            payeeReward = Math.ceil(reward / 5);
+        }
 
         reward -= payeeReward;
         rewardToPool -= payeeReward;

**Whether there is a need to modify it

 UdjinM6  You are really something.

Thank you very much.

**Comment by schinzelh** [comment]
Hi,

please be aware that Dash 0.12.1 which is schedule to launch on 5th February 2017 uses a new GBT and needs another nomp patch.

--> https://github.com/UNOMP/node-merged-pool/pull/5

**Comment by UdjinM6** [comment]
This ^^^, also not sure why would you want to patch unomp manually - it already has all patches and all you need is to pull latest source from its repo.

**Comment by wuhuaping** [comment]
Thank your  UdjinM6   schinzelh  for helping me
@schinzelh  Where to modify it   UNOMP/node-merged-pool/  ?  
Thank you very much.

**Comment by schinzelh** [comment]
Assuming you are using unomp you just need to do

```$ npm update````

to get the latest version.

**Comment by wuhuaping** [comment]
Well, thank you
@schinzelh  Thank you for your help.
I'll test it tomorrow after work
My English is not good.
I use the translation software
If no correct translation please forgive me

**Comment by schinzelh** [comment]
You are welcome, your English is far better than my Chinese :)

If you need help setting up unomp just let me know.

**Comment by wuhuaping** [comment]
Thank you @schinzelh 
 It takes a little time to test it.
You are a humorous friend
.I like to talk to you
You are a good friend
.Have a chance to
Welcome to  China

**Comment by wuhuaping** [comment]
This port connection is temporary
Test use
http://117.78.52.199:5858
Cannot find block
Dug all night, but no
@schinzelh 

/NOMP# vi package.json 

"dependencies": {
        "stratum-pool": "git://github.com/UNOMP/node-merged-pool.git",
        "dateformat": "1.0.12",
        "node-json-minify": "*",

**Comment by schinzelh** [comment]
Hi,

i think your expectations are off :)

From the stats i see you are mining with a hashrate of 500MH/s, which means you will have to wait 6days(!) on average to find a block. Beside that your setup looks good.

Holger

**Comment by wuhuaping** [comment]
Thank you very much Holger Sir
expectations are off ? How to solve it
I use the P2P mode 『NOMP』
 500MH/s,   wait 12days(!)  find 1 block    i think Is it unreasonable  error

before I use this It is P2P
https://github.com/dashpay/p2pool-dash   p2pool-dash calculated 500MH/s  to 1-2 hours Can find block

I would like to use NOMP to find the block through P2P
 If the test passes
I'll dig alone

But it didn't find a block for 8 hours  P2P
I use NOMP to test dig fedoracoin  "algorithm": "scrypt"  to 1-2 hours Can find block
x11 dashcoin   Can not  find block

**Comment by wuhuaping** [comment]
I don't know. @UdjinM6 Sir     you give me any help?
 How do you solve it? 
I see you've solved it Official website
But I can't repeat your test
Thank you

**Comment by schinzelh** [comment]
Hi,

this is not a error, it is math :)

Current network hashrate is 2360 GHs = 2360000 MHs, which mines 554 blocks/day
    
```
2360000	MH/s	-->	554 	blocks/day
500	MH/s	-->	0.117	blocks/day
```
So to get 1 block you will need to mine ~8.5 days.

**Comment by UdjinM6** [comment]
I don't think there is any error at all. The math is pretty straightforward: network hashrate is ~2.5Th/s, you hashrate is 500 Mh/s i.e. it's 1/5000th of the network hashrate meaning that you should be able to find 1 block in 5000 on avg if there were no pools. Pools help miners to rise their "luck" so you real rate will be even lower.

In the last 24h p2pool found 14-15 blocks which corresponds with 1-2h per block you expected: https://www.dashninja.pl/blocks.html#perminer but p2pool is a distributed pool, it's not just your node - it's a combined effort of all miners who run their p2pool nodes i.e. it mines with the total hashpower of all of them. What you get when you mine using p2pool is not a full block reward but a share, just like you would get mining on someone's else centralized pool.

**Comment by wuhuaping** [comment]
Thank you  UdjinM6  schinzelh
Maybe you are right.
If so, I need to test it
But not now  I will test it in the future
Thanks you very much to help me
