### ISSUE TITLE
Small issue with building dashd on FreeBSD 11

### ISSUE THREAD

**Issue by MrDefacto** [dashpay/dash#1277]
Hi,

Rather standard configure line:

`./configure --enable-debug --with-gui=no --disable-shared --with-pic --without-miniupnpc --disable-tests --enable-hardening`

and during build there is an error:

`  CXX      leveldb/db/leveldb_libleveldb_a-builder.o
In file included from <built-in>:347:
<command line>:4:21: warning: ISO C99 requires whitespace after the macro name [-Wc99-extensions]
#define OS_FREEBSD11.0 1
                    ^
In file included from leveldb/db/builder.cc:7:
In file included from ./leveldb/db/filename.h:14:
In file included from ./leveldb/port/port.h:14:
./leveldb/port/port_posix.h:38:12: fatal error: 'endian.h' file not found
  #include <endian.h>
           ^
1 warning and 1 error generated.
gmake[2]: *** [Makefile:4394: leveldb/db/leveldb_libleveldb_a-builder.o] Error 1`

It looks that configure script incorrectly define OS. Manualy changing two Makefile to "LEVELDB_TARGET_FLAGS = -DOS_FREEBSD" lets it build correctly.

**Comment by rscaper** [comment]
@MrDefacto Is it working on your system after this change to Makefile ?
For me, its building correctly with your suggestion, but when I run it:
Segmentation fault
(dashd),  exited on signal 11

FreeBSD 10.3
dash-0.12.1.0 - dash-0.12.1.3

**Comment by MrDefacto** [comment]
Yes. I got no issues. I've even run 0.12.1.4. But i'm running on FreeBSD 11.0

**Comment by clinta** [comment]
@MrDefacto, Thanks. With your tips I've been able to get a dash build script working again.

https://gist.github.com/clinta/e9e300a33546b0a78489fb1052ffb9c0

**Comment by MrDefacto** [comment]
Great! I glad that i could help You :-)
