### ISSUE TITLE
[PS] Mixing completion % is wrong

### ISSUE THREAD

**Issue by akijuh** [dashpay/dash#1279]
v0.12.1.0-348c001
PS mixing completion % is wrong, see the pic.

![image](https://cloud.githubusercontent.com/assets/6022297/22173693/704e3296-dfd3-11e6-9828-b630acc64890.png)

**Comment by UdjinM6** [comment]
Well, it depends how you define progress. This is the way it's now: https://github.com/dashpay/dash/blob/v0.12.1.x/src/qt/overviewpage.cpp#L389-L420

**Comment by akijuh** [comment]
Yep, but real % is 12.6% (101 of 800).
If average user see this (48%), its wrong and they complain that.

**Comment by UdjinM6** [comment]
12.6% is not real, 12.6% is for the last round only. Average user won't see this bar anymore, it's only available in "advanced ui" mode.

**Comment by akijuh** [comment]
Ok, is there really need to have a % at all then.

**Comment by UdjinM6** [comment]
That's standard OS-defined progress bar. I don't have any % visible on my mac for example. Also you can hover mouse over it and it will show some more %% about each "logical step" of mixing which could be helpful for advanced users.

**Comment by akijuh** [comment]
Yes, i can see that now, i close this, thanks.
