### ISSUE TITLE
[GUI] Masternodes tab date have a wrong format

### ISSUE THREAD

**Issue by akijuh** [dashpay/dash#1280]
v0.12.1.0-348c001
Masternodes tab date have a wrong format, it should follow same format as in transactions tab.

Masternodes tab:
![image](https://cloud.githubusercontent.com/assets/6022297/22173723/19c18080-dfd4-11e6-914e-d48212d6594a.png)

Transactions tab:
![image](https://cloud.githubusercontent.com/assets/6022297/22173726/2c24ea8c-dfd4-11e6-9e13-90a36d592e20.png)

**Comment by UdjinM6** [comment]
Unfortunately, the function that does this conversion to local format is superslow. It works ok-ish for a static list of transactions but not for a live list of 4000+ items, even with some cool downs. That's a know qt bug which have not been fixed for a long time.

**Comment by akijuh** [comment]
Damn, what if you do conversion only rows which is visible, not all 4k?

**Comment by UdjinM6** [comment]
This probably can be achieved by throwing out current naive implementation and rewriting the tab from scratch in data-driven way. Not in 12.1, or at least not on release, or at least not by me :)

**Comment by akijuh** [comment]
Ok, should i close this or leave it open?

**Comment by UdjinM6** [comment]
I would leave it open, nothing wrong with having some issues postponed for later imo.

**Comment by akijuh** [comment]
Ok, thanks.

**Comment by akijuh** [comment]
Bump, anyone :))

**Comment by nmarley** [comment]
@akijuh Is this still happening with the latest version? If yes, can you share your OS and system locale?

**Comment by akijuh** [comment]
@nmarley Yes this is still valid with latest version.

**Comment by codablock** [comment]
Not sure if it's worth the effort to fix this. With DIP3, the masternode tab in its current form will get obsolete and might require a partial rewrite.

**Comment by akijuh** [comment]
Obsolete, how/why?

**Comment by codablock** [comment]
@akijuh We are internally working on a quite large change in how masternodes are handled in the network. If this is accepted and deployed in the network, a lot will get obsolete/deprecated. We will release details in the next weeks.

**Comment by akijuh** [comment]
Aha, then this is indeed obsolete issue.
Should i close this case?

**Comment by codablock** [comment]
Yepp, makes sense to close it.
