### ISSUE TITLE
Wallet Beneficiary Address

### ISSUE THREAD

**Issue by rubyxroot** [dashpay/dash#1284]
Hi,

Is there a way to integrate a beneficiary address to the QT core Wallet. 

If unaccessed lets say for 3 or 6 months? the funds in the wallet will  be sent to the beneficary address?

Thanks and more Power!

**Comment by schinzelh** [comment]
rubyxroot [9:57 AM] 
I was thinking we should have a beneficary address in the  wallet in case someone "retires in this world"....  then maybe after 3 or 6 months of un accessed wallet all the funds will be sent to the benificary address.

**Comment by nmarley** [comment]
I don't believe this is feasible from a Qt wallet perspective. It is possible to set up a plan / dead-man's switch, but it doesn't seem like a good idea to do this in the Dash-Qt wallet software.

@UdjinM6 @codablock your thoughts?

**Comment by UdjinM6** [comment]
Qt wallet should not be used to store any significant amount of money imo, users should use hardware wallets for this and develop their own dead-man's switch strategy via some legal procedures probably, not via purely technical solutions.

**Comment by nmarley** [comment]
I agree, closing as this is not feasible nor advisable.
