### ISSUE TITLE
v12.1 Masternode health check is too crude

### ISSUE THREAD

**Issue by taw00** [dashpay/dash#1285]
Our current heuristics for determining if a masternode is up, running, and ready to perform all tasks is really very crude. See below. I.e., At this time, apparently only a masternode ping(?) is required to consider a masternode still "ENABLED".

But that does not really represent the true state of probably a significant chunk of the Masternodes. For example, right now I am staring at a masternode (testnet) currently in this situation:
* `getblockcount`: 142057
* Height of blockchain according to <https://test.explorer.dash.org>: 142337
* Result of `masternode list full | grep MY_MN_IP_ADDRESS`: ENABLED

ENABLED implies a MN able to perform a host of activities. But it really can't. I see this is a significant issue.

Thanks. -t0dd

**Comment by schinzelh** [comment]
I think you have missed Sentinel :)

You assumption is true for 12.0, but with 12.1 we have introduced the concept of Sentinel/Watchdogs. So in your case above the node will drop offline after 2hrs because the watchdog will not get updated.

**Comment by taw00** [comment]
You are correct. Well... I assume you are correct. Sentinel is running just fine, but the tMN has entered WATCHDOG_EXPIRED state.

**Comment by taw00** [comment]
You are correct. Well... I assume you are correct. Sentinel is running just fine, but the tMN has entered WATCHDOG_EXPIRED state.

CLOSING ISSUE
