### ISSUE TITLE
12.1 Masternode is on the wrong chain. The log files are silent on this issue.

### ISSUE THREAD

**Issue by taw00** [dashpay/dash#1286]
_Note: It's possible I am missing some indicator in the log files, but I picked through them fairly thoroughly..._

My tMN went down the wrong chain many hours ago (I noticed a getblockcount different than height). I then noticed that getblockcount slowly incrementing. I did a reconsiderblock and got a "Block not found" .... so wrong chain.

Looking at the masternode list, my tMN was still listed as ENABLED but eventually it did switch to WATCHDOG_EXPIRED. Apparently, this is Sentinel watching the masternode and taking it out of the ENABLED pool, so to speak. This situation lead to me opening and then closing this issue: <https://github.com/dashpay/dash/issues/1285>

BUT...

Picking through the debug.log file and the syslog journal... there is zero indication that anything is amiss. It just looks like a masternode just doing its thing.

**(a)** Why isn't Sentinel (note, I have SENTINEL_DEBUG=1 always on) sending a "your masternode is off-chain" message in the logs every time it runs? I even ran it from the commandline... silence.

**(b)** When it is obvious the MN is off-chain, why not fix the situation? Maybe this part (b) is more of an RFE. Add into dash.conf some value like "auto-reindex=1" or some such?

**Comment by nmarley** [comment]
From the perspective of this dash core daemon, it was on the "right" chain. The software will switch to what it thinks is the "right" chain (e.g. most proof-of-work). Sentinel only trusts the Core daemon, and doesn't know anything about an "off-chain" status. From the perspective of that node, it's correct.
