### ISSUE TITLE
getrawtransaction fails only on transaction in genesis block

### ISSUE THREAD

**Issue by MarkusTeufelberger** [dashpay/dash#133]
getrawtransaction e0028eb9648db56b1ac77cf090b99048a8007e2bb64b68f092c03c7f56a662c7 returns with "No information available".

I ran with txindex=1 and -reindex, so far *all* other transactions seem to be available. Before I start to sync with a completely new data folder from network, is this happening to others too or is this just an error on my end that I need to debug further? I use v0.11.0.13-g90ad641-beta, seems to be the latest version at the moment.

**Comment by schinzelh** [comment]
e0028eb9648db56b1ac77cf090b99048a8007e2bb64b68f092c03c7f56a662c7  is the coinbase transaction of the genesis block, which has by design no transaction.

See also https://github.com/bitcoin/bitcoin/issues/3303

**Comment by MarkusTeufelberger** [comment]
http://explorer.darkcoin.io/block/00000ffd590b1485b3caadc19b22e6379c733355108f107a430458cdf3407ab6 seems to have been able to retrieve + decode (?!) this transaction:
http://explorer.darkcoin.io/tx/e0028eb9648db56b1ac77cf090b99048a8007e2bb64b68f092c03c7f56a662c7

Anyways, as far as I understand it, while the merkle root in the genesis block of course can be used to calculate a theoretical TXID, the value in the genesis merkle root actually is not pointing to any valid transaction at all for bootstrapping reasons. Right? The I'll just mask out this specific "TXID" and move on...

**Comment by schinzelh** [comment]
explorer is only able to decode it, because the tx is hardcoded in the abe code

https://github.com/bitcoin-abe/bitcoin-abe/blob/master/Abe/genesis_tx.py#L52-L54

My understanding of the genesis block bootstrapping matches yours.
