### ISSUE TITLE
Hi ,  after  update to 12.1 dashd command never  returns

### ISSUE THREAD

**Issue by staier** [dashpay/dash#1333]
What  i   did:  
system centos 6.5
- $dash-cli stop
- copied over new dash executables 
- $dashd

What  i  observe:
command never returns to  shell
but  system  seems to  work  ,  if i  open   another  shell i  can  communicate to  dashd  with dash-cli no problem

as a workaround i  run dashd in  screen
Any  thoughts?

**Comment by schinzelh** [comment]
12.1 is using a different datadir, so currently your dashd does not use any dash.conf file

First stop/kill dashd, then delete the new dir again

```
rm -Rf ~/.dashcore
```

then copy your old datadir to the new location.

```
mv ~/.dash ~/.dashcore
```

Then start dashd again.

**Comment by staier** [comment]
Thanks .
now another problem :
```
# dashd
Dash Core server starting
# : Error loading block database.

Do you want to rebuild the block database now?

```

**Comment by schinzelh** [comment]
Stop dashd and restart with

```dashd -reindex```

**Comment by staier** [comment]
# dashd -reindex
Dash Core server starting
# Error: Failed to load masternode cache from mncache.dat

**Comment by chaeplin** [comment]
stop dashd if running.

rm ~/.dashcore/mncache.dat ~/.mnpayments.dat

use dashnation slack channel for fast support.

http://www.dashnation.com/chat/

**Comment by staier** [comment]
Thank you . Resolved .
