### ISSUE TITLE
Dynamic IP of Masternode

### ISSUE THREAD

**Issue by windz2009** [dashpay/dash#1334]
Hello! What to do if IP was changed. 
`Not capable masternode: Specified IP doesn't match our external address.`
i got this message issueing "dash-cli masternode debug"
ip in dash.conf and real external IP are the same. If i restart MN I'll loose the MN score. What should i do to not loose the score?

**Comment by schinzelh** [comment]
Wont fix, this is by design: Running a masternode requires a static IP.
