### ISSUE TITLE
Dash.conf maxconnections limit

### ISSUE THREAD

**Issue by akijuh** [dashpay/dash#1337]
Dash.conf maxconnections=xx limit does not work.
Connections goes over this limit.

Any explanation or is this bug?

**Comment by UdjinM6** [comment]
This is probably due to mnb recovery and mn verify things to not care about this limit, which means final number of connections can be up to 10 connections more.

**Comment by akijuh** [comment]
Aha, so its semilimit then :)

**Comment by UdjinM6** [comment]
Yeah, kind of :) It's a limit for "normal" connections. Special connections are temporary ones and they are kept alive only for 1 minute. Maybe we should add some additional comments about this in `maxconnections` help though -`Maintain at most <n> connections to peers, _excluding temporary service connections_` or smth like that. Thoughts?

**Comment by akijuh** [comment]
Yes, good idea to prevent user false alarms.
