### ISSUE TITLE
[BUG] Masternodes tab does not update anymore

### ISSUE THREAD

**Issue by akijuh** [dashpay/dash#1338]
@UdjinM6  @tgflynn 

Windows 7, 64bit - v0.12.1.0

My masternodes tab does not update anymore, its been stuck over 29 hours now.
All nodes are running ok and payments are flowing in, but qt-wallet masternodes tab is stuck.

Dash ninja say all mn:s are active, also server side all mn:s dash-cli getinfo, dash-cli mnsync status and dash-cli masternode status all OK.

![image](https://cloud.githubusercontent.com/assets/6022297/22978421/4d62324c-f39b-11e6-88c4-03bce6ad8d66.png)

**Comment by akijuh** [comment]
I speak particularly My Masternodes sub tab,
debug.log available if needed.

**Comment by tgflynn** [comment]
This is an issue that is known but not fully understood.  It seems to occur on some nodes but not consistently.  

A workaround is to shutdown the wallet, delete mncache.dat and mnpayments.dat and restart.

**Comment by akijuh** [comment]
Ok, tested, deleted mncache.dat and mnpayments.dat and it is ok now.

Thanks, and good bug hunting.

**Comment by akijuh** [comment]
Damn, this 'my masternodes tab' stuck bug is PITA.
Just a moment ago, suddenly all my masternodes got watchdog expired,
deleted mncache.dat and mnpayments.dat restarted wallet, and after loong sync,
still got 2 nodes stuck, but they are in fact ok, after few mins they are now all enabled.

**Comment by schinzelh** [comment]
Yeah, i have many customer complaints as well - the status on the masternode tab is often misleading and i told them to IGNORE the status column for now...

**Comment by akijuh** [comment]
Yep, but but its so nice to check mns status in there...

Also i hope we some day get also a governance tab, with listed proposals and vote buttons and all :),
or is this planned to Evolution?

**Comment by schinzelh** [comment]
Evolution will have it all - and a solution for world hunger :)

**Comment by akijuh** [comment]
This issue is still live in v12.1.4

**Comment by akijuh** [comment]
Actually its been better now, i will monitor this...

**Comment by Technologov** [comment]
+1. Big problem for me. I have no ideas if my Masternodes are up or down or what.

**Comment by akijuh** [comment]
This issue is better now, but its not completely solved.

**Comment by akijuh** [comment]
I think this issue is no more, closing.
