### ISSUE TITLE
Dash Core Version v0.12.1.0 (64-Bit) on WIN10 resolution problem

### ISSUE THREAD

**Issue by shoggoth72** [dashpay/dash#1339]
Some text of the desktop app on my Surface appears very small - almost unreadable while when making the window smaller, text gets shoved over each other and becomes unreadable.
I made 2 screenshots trying to show this...

![dash-core_readability_win10-64b](https://cloud.githubusercontent.com/assets/25435203/22982224/c7b2a876-f39e-11e6-8c2f-280738ef71f8.JPG)
![dash-core_readability_win10-64b-2](https://cloud.githubusercontent.com/assets/25435203/22982223/c794540c-f39e-11e6-91e2-f705e84e3a94.JPG)

...fearfully I state the resolution the surface is running on by default: 2736 x 1824 ... *duck* ;-)

**Comment by crowning-** [comment]
Do you have some fancy OS-theme and/or unusual font-sizes customized?

Thinks like this are not hard to fix, however without actually owning a Surface it's almost impossible.
I don't even know someone who owns one...

@snogcel , do YOU know someone with a Surface to resolve this issue?

**Comment by bertlebbert** [comment]
Wallet font sizes are based on different windows objects - each of which you can customize:

Right click Desktop -> Personalize -> Display -> Play around with settings of menu, titleboxes, icons, messageboxes, tooltips, etc.

Beware though that changing these settings will be universal and effect display of all apps and windows.

**Comment by snogcel** [comment]
@crowning- unfortunately not, though I do recall from troubleshooting them in the past that they use scaling to help make things more readable at that super high screen resolution. 

I found this article from Microsoft that describes a few tactics that can be used when applications look funky, @shoggoth72 maybe try one of the solutions offered here? https://www.microsoft.com/surface/en-us/support/apps-and-windows-store/app-display-issues?os=windows-10&=undefined

**Comment by shoggoth72** [comment]
First of all - Thanks for the replys.
I have no fancy stuff @crowning- just the rather default setup.
I will try the suggestions of @bertlebbert and @snogcel - though I do fear bertleberts hint on all other apps....
And for the Windows page - dont you just love MS and its help:
"Solution 4: Change your main display
Solution 5: Check with the publisher of the desktop app"
...its a surface for god sake..."changing display"...
I guess, you can then close the issue. I may try just resetting the display values when the wallet is open....
Happy $20Dash weekend to you all ;-)
