### ISSUE TITLE
[BUG] v0.12.1.2 Its synced but out of sync is still visible

### ISSUE THREAD

**Issue by akijuh** [dashpay/dash#1363]
v0.12.1.2 Its synced but its not.
Loaded qt-wallet as i normal do, win 7 x64, sync was also normal, but out of sync is still visible.
Weird glitch, see the pic.

![dashv1212](https://cloud.githubusercontent.com/assets/6022297/23325566/058d841a-faff-11e6-828d-a56085c81908.png)

**Comment by tgflynn** [comment]
What is the output of running "mnsync status" in the debug console ?

Also is this reproducible ?  Does it happen on every start or only sometimes ?

**Comment by akijuh** [comment]
Sorry, it was late and bed time.
This was first time ever.
Just started wallet again and no problem, i will monitor this.

**Comment by SCDeveloper** [comment]
Everytime a block is found your wallet isn't in sync until its actually in sync. The Qt wallet will hit (out of sync) each time a block is found or governance is syncing.

**Comment by schinzelh** [comment]
Yep, I can confirm this, this also happens on mnsync status

**Comment by SCDeveloper** [comment]
However, it hasn't caused issues here when testing.

**Comment by SCDeveloper** [comment]
That is because the v12.0 branch didn't have half the governance sync checks that happen now.

**Comment by SCDeveloper** [comment]
Maybe a governance out of sync message should be created, a secondary out-of-sync, located somewhere else on the UI.

**Comment by akijuh** [comment]
Its happened again.
Sync was just about to complete and same time 'out of sync' appeared, maybe a new block,
wallet was fully synced but 'out of sync' still visible and does not go away.

![clipboard02](https://cloud.githubusercontent.com/assets/6022297/23816669/bc129a7a-05f6-11e7-8d60-7f81d0baf7a9.png)

**Comment by akijuh** [comment]
And:
mnsync status
{
  "AssetID": 999,
  "AssetName": "MASTERNODE_SYNC_FINISHED",
  "Attempt": 0,
  "IsBlockchainSynced": true,
  "IsMasternodeListSynced": true,
  "IsWinnersListSynced": true,
  "IsSynced": true,
  "IsFailed": false
}

**Comment by SCDeveloper** [comment]
So you are synced......

**Comment by akijuh** [comment]
Indeed, just 'out of sync' is visible.
This is rare problem, happened only 2 times after 12.1 release.

**Comment by SCDeveloper** [comment]
I am going to investigate on our codebase too. We launch publicly this evening, but currently the only time 'out of sync' shows is the moment a new block is found or governance is syncing.

**Comment by akijuh** [comment]
Wallet is synced, as you can see in my first pic,
so, how is that message correct if wallet is in sync?

If wallet is in sync, then 'out of sync' should NOT be visible.

**Comment by akijuh** [comment]
Closing this, in v.12.1.5 this does not occur any more.
