### ISSUE TITLE
blocknotify broken 0.12.1

### ISSUE THREAD

**Issue by miningpoolhub** [dashpay/dash#1368]
blocknotify is broken at 0.12.1
It did work well before but after I update it doesn't work anymore.

**Comment by chaeplin** [comment]
hello, tested and works.
```
coind@s01:~ $ grep blocknotify .dashcore/dash.conf 
blocknotify=/home/coind/121/winners.py
```

**Comment by UdjinM6** [comment]
Thanks for reporting. Mind providing a bit more info?

>hello, tested and works.

Indeed, works for me too
```
>dashd -blocknotify="echo %s" -daemon
...later...
000000000000962c47ade0fdcd23b2e3b3200abf340bbb80a9ca3adbc4daa450
>dash-cli getbestblockhash
000000000000962c47ade0fdcd23b2e3b3200abf340bbb80a9ca3adbc4daa450
```

**Comment by miningpoolhub** [comment]
Oh.. my bad. Sorry.
I was looking at .dash/dash.conf not .dashcore/dash.conf
All is working fine.
