### ISSUE TITLE
[SPORK] sporkkey/privkey/pubkey

### ISSUE THREAD

**Issue by spencerlievens** [dashpay/dash#1378]
Under testing I have populated chainparams.cpp with a valid Spork PubKey from a valid keypair.

However, upon adding the PrivKey of the pair to dash.conf; sporkkey=[privkey] and attempting to start the wallet, this message pops up: "Unable to sign spork message, wrong key?"

The key is definitely valid. I am testing this on a closed network, new chain.

This is the same with the master branch of Dash and I am worried that you guys cannot broadcast Spork messages i.e. Masternode Payment Enforcement, or is there something I am missing?

**Comment by UdjinM6** [comment]
Make sure [privkey] is in WIF format

**Comment by spencerlievens** [comment]
Ah ha. Thank you UdjinM6, btw can you email me your Skype contact details please - spencerlievens@gmail.com

**Comment by UdjinM6** [comment]
No, I'm not sharing my Skype, sorry.

**Comment by spencerlievens** [comment]
I have tried with a WIF format privkey and it has the same error message. Is there a problem with CheckSignature in spork.cpp?

**Comment by tgflynn** [comment]
Sporks are known to work in dash so must be an issue with your code base.

**Comment by spencerlievens** [comment]
It is your codebase.

**Comment by spencerlievens** [comment]
I have a feeling that Evan or another Dash dev did something to Sporks, to not make it easy to screw the network. This isn't just a feeling. It is what I heard.

**Comment by CryptoGeekJD** [comment]
Hi, I have the exception.
I used process detailed in below URL to generate WIF key. Here in place of 80 I used different random 2 digit number like 20,FF for version byte.
https://gist.github.com/t4sk/ac6f2d607c96156ca15f577290716fcc

Is that the right of generating WIF key? Is your problem resolved?

Would be grateful if you can help me out in this.

**Comment by nmarley** [comment]
Instead of manually serializing your key, I'd recommend using something like `masternode genkey` to generate the key. You will have to ensure the compression of the WIF format key matches the compression of the hard-coded spork public key (or spork address, if using the develop branch).

This has been working in Dash for years, I've verified this myself on testnet.

**Comment by CryptoGeekJD** [comment]
thanks @nmarley 
Actually I have a different problem and hence working around spork keys.
I cloned the source code , generated all around a new genesis block set up my vps nodes and other VM is with linux qt wallet. when my wallet is connected to the VPS which have my private working model, it is stuck at syncing sporks data (syncing additional data 25% phase). When i start mining using "setgenerate true", blocks are also getting generated. But the sporks data is still at 25%.
I thought of generating my own spork pub & private key(it is in WIF format) and succeeded now. able to use my new spork key pair. Still the wallet is at "Synchronising sporks data" .

Would be grateful if someone can advise to get me out of this problem!

**Comment by nmarley** [comment]
What does the `debug.log` file say?

**Comment by CryptoGeekJD** [comment]
Qt is not able to fund the spork data from existing local spork db and
failing to get it from connected peer which is my own VPS on which daemon
running.

I have entered spork private key in qt contained VM machine and not on VPS
on which daemon running.

below is the snippet from debug log related to spork


2018-05-01 21:57:20 ProcessMessage(getsporks, 0 bytes) FAILED peer=1
2018-05-01 21:57:21 asking peer for sporks
2018-05-01 22:21:40 CSporkManager::SetPrivKey - Successfully initialized as
spork signer
2018-05-01 22:21:40 LoadSporksFromDB : no previous value for
SPORK_2_SWIFTTX found in database
2018-05-01 22:21:40 LoadSporksFromDB : no previous value for
SPORK_3_SWIFTTX_BLOCK_FILTERING found in database
2018-05-01 22:21:40 LoadSporksFromDB : no previous value for
SPORK_5_MAX_VALUE found in database
2018-05-01 22:21:40 LoadSporksFromDB : no previous value for
SPORK_7_MASTERNODE_SCANNING found in database
2018-05-01 22:21:40 LoadSporksFromDB : no previous value for
SPORK_8_MASTERNODE_PAYMENT_ENFORCEMENT found in database
2018-05-01 22:21:40 LoadSporksFromDB : no previous value for
SPORK_9_MASTERNODE_BUDGET_ENFORCEMENT found in database
2018-05-01 22:21:40 LoadSporksFromDB : no previous value for
SPORK_10_MASTERNODE_PAY_UPDATED_NODES found in database
2018-05-01 22:21:40 LoadSporksFromDB : no previous value for
SPORK_13_ENABLE_SUPERBLOCKS found in database
2018-05-01 22:21:40 LoadSporksFromDB : no previous value for
SPORK_14_NEW_PROTOCOL_ENFORCEMENT found in database
2018-05-01 22:21:40 LoadSporksFromDB : no previous value for
SPORK_15_NEW_PROTOCOL_ENFORCEMENT_2 found in database
2018-05-01 22:21:40 LoadSporksFromDB : no previous value for
SPORK_16_ZEROCOIN_MAINTENANCE_MODE found in database

thanks in advance. Would you mind to ping me on discord? 'cryptogeek'

**Comment by CryptoGeekJD** [comment]
Qt is not able to fund the spork data from existing local spork db and
failing to get it from connected peer which is my own VPS on which daemon
running.

I have entered spork private key in qt contained VM machine and not on VPS
on which daemon running.

below is the snippet from debug log related to spork


2018-05-01 21:57:20 ProcessMessage(getsporks, 0 bytes) FAILED peer=1
2018-05-01 21:57:21 asking peer for sporks
2018-05-01 22:21:40 CSporkManager::SetPrivKey - Successfully initialized as
spork signer
2018-05-01 22:21:40 LoadSporksFromDB : no previous value for
SPORK_2_SWIFTTX found in database
2018-05-01 22:21:40 LoadSporksFromDB : no previous value for
SPORK_3_SWIFTTX_BLOCK_FILTERING found in database
2018-05-01 22:21:40 LoadSporksFromDB : no previous value for
SPORK_5_MAX_VALUE found in database
2018-05-01 22:21:40 LoadSporksFromDB : no previous value for
SPORK_7_MASTERNODE_SCANNING found in database
2018-05-01 22:21:40 LoadSporksFromDB : no previous value for
SPORK_8_MASTERNODE_PAYMENT_ENFORCEMENT found in database
2018-05-01 22:21:40 LoadSporksFromDB : no previous value for
SPORK_9_MASTERNODE_BUDGET_ENFORCEMENT found in database
2018-05-01 22:21:40 LoadSporksFromDB : no previous value for
SPORK_10_MASTERNODE_PAY_UPDATED_NODES found in database
2018-05-01 22:21:40 LoadSporksFromDB : no previous value for
SPORK_13_ENABLE_SUPERBLOCKS found in database
2018-05-01 22:21:40 LoadSporksFromDB : no previous value for
SPORK_14_NEW_PROTOCOL_ENFORCEMENT found in database
2018-05-01 22:21:40 LoadSporksFromDB : no previous value for
SPORK_15_NEW_PROTOCOL_ENFORCEMENT_2 found in database
2018-05-01 22:21:40 LoadSporksFromDB : no previous value for
SPORK_16_ZEROCOIN_MAINTENANCE_MODE found in database

thanks in advance. Would you mind to ping me on discord? 'cryptogeek'

**Comment by nmarley** [comment]
I agree that Discord (or the Dash forum) is probably a better support channel for this -- let's continue discussion elsewhere. But for this ^, you'll want to make sure you set spork defaults, as well as ensure the spork signatures validate. So you'll need to make sure the public key that's hard-coded in `chainparams.cpp` matches network spork signatures and that the private key you set is the correct one (matches the hard-coded public key).

Since this is for a fork of Dash, it's getting a bit off-topic, so gonna close discussion here.
