### ISSUE TITLE
'mnsync next' can be used to mine and not pay masternodes

### ISSUE THREAD

**Issue by SCDeveloper** [dashpay/dash#1428]
this fixes it:

https://github.com/duality-solutions/Dynamic/commit/cdf63d88c84fae2cf9c6bf6c047238bc2276f7ed

I am trying to think of a better way to code this, but for now this will cover the issue.

**Comment by SCDeveloper** [comment]
With you guys, you don't use mining the same as us, so your miner check will need to change to something else for GBT.

**Comment by SCDeveloper** [comment]
<img width="553" alt="screen shot 2017-04-08 at 23 10 08" src="https://cloud.githubusercontent.com/assets/13606170/24832434/92a44b68-1cb0-11e7-8074-3b7170f45f4b.png">

**Comment by UdjinM6** [comment]
Such block won't be accepted by the network. The only person who will suffer is the miner himself (so he probably shouldn't use this in the first place).

**Comment by coin-info-net** [comment]
They are accepted , because the Miner wallet shows full syncd by skipping the Masternode Sync
So the miner have no Enabled Masternodes in his list and Masternode Rewards are only
payd to those Enabled Masternodes
For other Masternodes u will find an error in the logs that payment cant be done due an not reachable Masternode

**Comment by UdjinM6** [comment]
They could be accepted _locally_ but no other fully synced node on the network will accept such blocks.

**Comment by SCDeveloper** [comment]
For the sake of a few lines of code to seal up a potential issue, either local or otherwise, it might be worth it.

**Comment by SCDeveloper** [comment]
Otherwise maybe not....

**Comment by UdjinM6** [comment]
@SCDeveloper 

As you correctly pointed out above there is no mining-in-the-wallet on mainnet anymore these days in Dash so `mnsync next` can only cause issues on testnet/regtest. On the other hand it can be used to cause issues intentionally to prove that rejection by other nodes actually works ;)

As for GBT - this rpc shouldn't be used in the first place and the patch doesn't help anyway. GBT miners should query `mnsync status` and wait for `IsSynced` (or at least `IsWinnersListSynced`) to become `true` before even starting to work on the next block.

**Comment by SCDeveloper** [comment]
Yes as GBT has a check for dynode sync i.e. Sporks before letting users mine.

**Comment by UdjinM6** [comment]
Post-close comment :)

Yep, GBT should simply fail too if node isn't synced yet (rpcmining.cpp#466)
```
if (!masternodeSync.IsSynced())
    throw JSONRPCError(RPC_CLIENT_IN_INITIAL_DOWNLOAD, "Dash Core is syncing with network...");
```
So, basically, miners should either try querying `getblocktemplate` until it succeeds or query `mnsync status` and wait for `true` as I described above. Either way should work for them and shouldn't allow them to create invalid blocks (and waste their electricity/money).
