### ISSUE TITLE
not found

### ISSUE THREAD

**Issue by bloomx11** [dashpay/dash#1433]
--- Building for trusty amd64 ---
Stopping target if it is up
Making a new image copy
cp: cannot stat ‘base-trusty-amd64’: No such file or directory
./bin/gbuild:21:in `system!': failed to run make-clean-vm --suite trusty --arch amd64 (RuntimeError)
        from ./bin/gbuild:57:in `build_one_configuration'
        from ./bin/gbuild:285:in `block (2 levels) in <main>'
        from ./bin/gbuild:280:in `each'
        from ./bin/gbuild:280:in `block in <main>'
        from ./bin/gbuild:278:in `each'
        from ./bin/gbuild:278:in `<main>'

**Comment by schinzelh** [comment]
Did you run 

```
$ bin/make-base-vm --lxc --arch amd64 --suite trusty
```

before trying `gbuild`?
