### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by MarcinWieczorek** [dashpay/dash#1434]
Hello.
I'm having trouble building dash. Please modify the title of this issue so it tells more about the issue, I couldn't think of one.
This is the error: https://hastebin.com/raw/setinebeya
I've tried with gcc 4.9.4, 6.3.1 and 5.4.0, same issue. I think I have all dependencies and this log doesn't look like missing imports.

**Comment by UdjinM6** [comment]
Qt5 5.7+ requires C++11 which Dash Core doesn't fully support yet, Qt5 5.6.2 has some other issues, so make sure to install Qt version < 5.6.2 (5.6.1-1 is recommended).

**Comment by MarcinWieczorek** [comment]
When will it be done? I need it for qt 5.8.
Thanks for your reply.

**Comment by UdjinM6** [comment]
Should be fixed in 12.2
