### ISSUE TITLE
Not building, help me, i'm completely a newbee

### ISSUE THREAD

**Issue by bloomx11** [dashpay/dash#1435]
Getting this after running `/bin/gbuild --commit dash=v0.12.0.x ../dash/contrib/gitian-descriptors/gitian-win.yml`

`--- Building for trusty amd64 ---
Stopping target if it is up
Making a new image copy
sudo: unable to resolve host gitian
stdin: is not a tty
Reading package lists... Done
Building dependency tree... Done
The following packages will be REMOVED:
  rsyslog ubuntu-minimal
0 upgraded, 0 newly installed, 2 to remove and 0 not upgraded.
After this operation, 1639 kB disk space will be freed.
(Reading database ... 16661 files and directories currently installed.)
Removing ubuntu-minimal (1.325) ...
Removing rsyslog (7.4.4-1ubuntu2) ...
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
 * Stopping enhanced syslogd rsyslogd
   ...done.
Adding 'local diversion of /sbin/initctl to /sbin/initctl.distrib'
Adding 'local diversion of /usr/bin/ischroot to /usr/bin/ischroot.distrib'
Adding 'local diversion of /usr/sbin/policy-rc.d to /usr/sbin/policy-rc.d.distrib'
Starting target
Checking if target is up
Preparing build environment
Updating apt-get repository (log in var/install.log)
Installing additional packages (log in var/install.log)
Upgrading system, may take a while
Creating package manifest
stdin: is not a tty
Creating build script (var/build-script)
Running build script (log in var/build.log)
./bin/gbuild:21:in `system!': failed to run on-target setarch x86_64 bash -x < var/build-script > var/build.log 2>&1 (RuntimeError)
        from ./bin/gbuild:149:in `build_one_configuration'
        from ./bin/gbuild:285:in `block (2 levels) in <main>'
        from ./bin/gbuild:280:in `each'
        from ./bin/gbuild:280:in `block in <main>'
        from ./bin/gbuild:278:in `each'
        from ./bin/gbuild:278:in `<main>'
`

**Comment by UdjinM6** [comment]
>Getting this after running /bin/gbuild --commit dash=v0.12.0.x ../dash/contrib/gitian-descriptors/gitian-win.yml

try v0.12.**1**.x
