### ISSUE TITLE
Dash Core GUI crash on MN "start alias" on unlocked wallet

### ISSUE THREAD

**Issue by Technologov** [dashpay/dash#1487]
Dash Core v0.12.1.5 for Windows x64.

Steps:
1. Unlock wallet (either via GUI : "Settings->Unlock wallet") or via CLI:
> walletpassphrase "passphrase" timeout
2. "My Masternodes" Tab
3. "Start alias" on several MNs.

Actual results:
1. GUI becomes unresponsive. Only way is to kill "Dash Qt"

-Technologov, 02.06.2017.

**Comment by troydash** [comment]
Maybe same as https://github.com/dashpay/dash/issues/646 ?

**Comment by schinzelh** [comment]
Duplicate
