### ISSUE TITLE
[feature-request] New address type for "InstantSend"

### ISSUE THREAD

**Issue by Technologov** [dashpay/dash#1559]
assume a retail merchant wants to accept ONLY InstantSend transactions.
Today there is no way to make it happen. A retailer accepting Dash may get a normal transaction, and get double-spend attacked. This technique will improve zero-confirmation security from the retailer point of view.
I would like to propose a new Dash address type (starting with "IX..." or "D..."), which will only accept InstantSend transaction types.

-Technologov, 31.07.2017

**Comment by nmarley** [comment]
Due to how IX works currently, I am not sure how feasible this request is. This might be possible after v13 with a L2 solution. @UdjinM6 @codablock any thoughts?

**Comment by codablock** [comment]
Didn't think much about it, but I believe that in the end it would just be a normal address with a different prefix. Core would just enable IX by default when such an address is used.

**Comment by nmarley** [comment]
I read this more as protocol-level change (new address / script type) which would only allow IX transactions and reject normal ones, instead of considering the wallet software behaviour. But IX locks as currently implemented are not at the blockchain level, and this would require blockchain protocol to have knowledge of higher tiers (e.g. the MN tier).

**Comment by codablock** [comment]
Ah ok. We could come up with something that involves a new standard script type which would be used when sent to such an address. But whatever we come up with, it won't fully prevent all possibilities and people could still manually create normal P2PKH transactions. So the merchant would still be forced to handle the case of non-IX transactions, which devalues the effort we'd have to put into such a feature too much. So in the end, it won't have many benefits compared to a solution that only involves a change to the default behavior (use IX by default with new address prefix).

**Comment by UdjinM6** [comment]
I don't think you can enforce IS via address type, we'll probably just try to lock every tx instead (i.e. no special `txlock` msg to initiate IS).

**Comment by nmarley** [comment]
I agree, wasn't sure how far we were on the "IX all the transactions" idea, but initial plans are in the works.
