### ISSUE TITLE
[Bug] listreceivedbyaddress includes send addresses

### ISSUE THREAD

**Issue by jimbursch** [dashpay/dash#1576]
I was using this command:
`./dash-cli listreceivedbyaddress 0 true`

to generate a list of unused addresses (0 confirmations and 0 amount) to assign to users for payment processing until I discovered that send addresses (external addresses where Dash was sent) are included in the list. This is a legacy bug from Bitcoin Core that is described here:

https://bitcointalk.org/index.php?topic=13011.0

discussed here:

https://www.dash.org/forum/threads/bug-listreceivedbyaddress-includes-send-addresses.16294/

@UdjinM6 observed:

> Ah, I see what's going on! They list all addresses saved in wallet's address book BUT address book also stores addresses you sent to a) with some label attached to it or b) via payment request. You can check these addresses in "File" -> "Sending addresses...". I'm not sure if that's a feature or a bug but given the fact that amount is always "0" and no actual txes are listed I guess it's indeed a bug

**Comment by nmarley** [comment]
Hi Jim,

It looks like this was fixed in #1664. Can you confirm?

**Comment by nmarley** [comment]
Fixed in #1664, closing.
