### ISSUE TITLE
BIP32 and change addresses. 

### ISSUE THREAD

**Issue by staier** [dashpay/dash#1587]
Hello , in order  to  restore address keys in  case  of a loss ,  i'd like to  have possibility  to  use deterministic addresses  with  dashcore .

According  to  this 
   https://dashpay.atlassian.net/wiki/spaces/DOC/pages/10158245/DIY+Deterministic+Addresses+BIP32

 i  can use them  if i  imoprt them  in to  the wallet
,  however   normal  operation is  impossible without  change addresses. And methiks i  cannot  control  generation of those . 
Is this correct ?

**Comment by chaeplin** [comment]
external address use m/44'/5'/x'/0/y : x - account_no, y - addres_index
internal address use m/44'/5'/x'/1/y : x - account_no, y - addres_index (change)

You can use standalone tool(offline) like https://iancoleman.github.io/bip39/


With 12.2.x(in developing), you can use mnemonic seed with DashCore but only one internal/external account yet.

**Comment by staier** [comment]
> external address use m/44'/5'/x'/0/y : x - account_no, y - addres_index

Could  you  give me  some link for a reference ,  i  have no idea  what  is it .
Thanks.

**Comment by chaeplin** [comment]
check https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki and https://github.com/satoshilabs/slips/blob/master/slip-0044.md

**Comment by staier** [comment]
Thanks.
Last quick  question.
Does this mean  ,  i  can  generate address and set the  key type to internal  ,  so  after  importing  it  to dashd it will be used as a changeaddress?  Or i  should read  the  doc to  understand the whole thing? ;)

**Comment by chaeplin** [comment]
I think you should read the doc.

BIP39 Mnemonic code for generating deterministic keys

BIP32 Hierarchical Deterministic Wallets

BIP43 Purpose Field for Deterministic Wallets

BIP44 Multi-Account Hierarchy for Deterministic Wallets

https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki

https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki

https://github.com/bitcoin/bips/blob/master/bip-0043.mediawiki

https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki

Current DashCore(12.1.5) is not compatible with bip32 wallet. But you can import all the wif to DashCore.  Some wallets use two path one for External and one for Internal, some use just one External.

**Comment by staier** [comment]
Thanks again ,  will try  to  grok  it.
i think   the issue can  be closed ,  as there  is nothing  todo.
