### ISSUE TITLE
GUI: extremaly small fonts on 3200x1800 14' screen

### ISSUE THREAD

**Issue by maky22** [dashpay/dash#1602]
I got Lenovo Yoga with 3200x1800 resolution. Fonts in DASH Core are slightly above 1mm tall. To small for me. How about possibility to resize in options or checking resolution by program and corect font size?

**Comment by chuckwilliams37** [comment]
Core Team, I've heard a few people request this one to my face, FYI.

**Comment by nmarley** [comment]
Closing as this was fixed in #1712
