### ISSUE TITLE
GUI: masternodes tab - columns resize problem

### ISSUE THREAD

**Issue by maky22** [dashpay/dash#1603]
Each time when I start DASH Core I must resize 'Alias', 'Address', 'Protocol', 'Status', 'Active', 'Last seen'. They are too narrow. After I close app all my resize 'job' is lost.
How about memorize last settings or automatic resize columns to the widest content?

**Comment by kevinschoen** [comment]
[Dash Core Wallet v0.13.0.0-rc11](http://dashcorewallet.org/Dash-Core-Walletv0.13.0.0-rc11/index.php)

**Comment by PastaPastaPasta** [comment]
DIP3 based MN List page makes this issue obsolete. Feel free to open another issue if you have any other suggestions/requests
