### ISSUE TITLE
Three node-setup using regtest chain staying forever in "Dash Core is syncing with network..."

### ISSUE THREAD

**Issue by oliverw** [dashpay/dash#1627]
I've created a [docker test image](https://hub.docker.com/r/coinfoundry/dash-private-testnet/) utilizing three instances of dashd for the purpose of testing mining-pool code. While all three nodes come up without error and blocks can be generated just fine using <code>generate</code>, a <code>getblocktemplate</code> RPC issued to any of the daemons initially returns:

`{"result":null,"error":{"code":-10,"message":"Dash Core is syncing with network..."},"id":"curltest"}`

Waiting a couple seconds, one single time a valid block-template is returned. Subsequent <code>getblocktemplate</code> requests always return the result listed above.

The source to the docker image can be found [here](https://github.com/coinfoundry/dash-private-testnet).

**Comment by flound1129** [comment]
I get this for about 10-15 minutes now whenever I have to restart my dashd.

**Comment by nmarley** [comment]
@codablock Do you know if this is expected behaviour on regtest? I know you were working thru some issues with regtest and IBD a few weeks back.

**Comment by oliverw** [comment]
The issue actually goes away after generating a block and waiting a couple seconds.
