### ISSUE TITLE
pkg-config not found while installing

### ISSUE THREAD

**Issue by dsslimshaddy** [dashpay/dash#1634]
when running `./configure` gives the error 

```
...
checking for exit in -lboost_thread... yes
checking whether the Boost::Chrono library is available... yes
checking for exit in -lboost_chrono... yes
checking whether the Boost::Unit_Test_Framework library is available... yes
checking for dynamic linked boost test... yes
configure: error: pkg-config not found.
```

`dpkg -l | grep pkg-config`
shows 
`ii  pkg-config                             0.29.1-0ubuntu1                              amd64        manage compile and link flags for libraries`

**Comment by bobsawey** [comment]
does...
`cat config.log | grep pkg-config`
show any additional information?

**Comment by sergeybelobrov** [comment]
I met same error and `cat` showing configure:25898: error: pkg-config not found.

**Comment by nmarley** [comment]
This is an external dependency for Dash and must be installed first.

**Comment by nmarley** [comment]
Note that if your system package manager shows it's installed and your configure script can't find it, you will need to ensure proper installation and that `pkg-config` is within your `$PATH`.
