### ISSUE TITLE
[feature request] Backport smart fees from bitcoin core

### ISSUE THREAD

**Issue by karel-3d** [dashpay/dash#1669]
Bitcoin core has a better fee algorithm in 0.15.0

See bitcoin/bitcoin#10199 and other commits in the directory

It returns more accurate fees and returns fees even for small / big block targets. (With very empty chains, current algoritm returns -1 for small targets, and for targets >= 25)

The more accurate fees are maybe not important for emptier blockchains like Dash, but the API is already better, because it doesn't return -1 for either too small targets or too big targets.

**Comment by nmarley** [comment]
Bitcoin 0.15 backports are slated for the Dash 0.12.4 maintenance release, and should be implemented after the Dash 0.12.3 release (coming soon, currently in change freeze).

**Comment by PastaPastaPasta** [comment]
fixed by #3036
