### ISSUE TITLE
compilation error in qt/masternodelist.cpp ERROR: ‘class QDateTime’ has no member named ‘offsetFromUtc’

### ISSUE THREAD

**Issue by demodun** [dashpay/dash#1671]
hi there. I was trying to compile dash and the make command stopped here:

> 
>  CXX      qt/qt_libbitcoinqt_a-masternodelist.o
> qt/masternodelist.cpp: In member function ‘void MasternodeList::updateMyMasternodeInfo(QString, QString, masternode_info_t&)’:
> qt/masternodelist.cpp:193:172: **error: ‘class QDateTime’ has no member named ‘offsetFromUtc’**
>  Mn.fInfoValid ? infoMn.nTimeLastPing + QDateTime::currentDateTime().offsetFromUtc() : 0)));
>                                                                      ^~~~~~~~~~~~~
> qt/masternodelist.cpp: In member function ‘void MasternodeList::updateNodeList()’:
> qt/masternodelist.cpp:276:173: error: ‘class QDateTime’ has no member named ‘offsetFromUtc’
>  %Y-%m-%d %H:%M", mn.lastPing.sigTime + QDateTime::currentDateTime().offsetFromUtc())));
>                                                                      ^~~~~~~~~~~~~
> At global scope:
> cc1plus: warning: unrecognized command line option ‘-Wno-self-assign’
> Makefile:6850: recipe for target 'qt/qt_libbitcoinqt_a-masternodelist.o' failed
> make[2]: *** [qt/qt_libbitcoinqt_a-masternodelist.o] Error 1
> make[2]: Leaving directory '/home/d/src3/dash/src'
> Makefile:9045: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory '/home/d/src3/dash/src'
> Makefile:652: recipe for target 'all-recursive' failed
> make: *** [all-recursive] Error 1

Does anyone knows whats wrong?
I am using Qt version 4.8.7 in /usr/lib/i386-linux-gnu

**Comment by demodun** [comment]
Should I add --with-gui=qt4  in ./configure?
I ll try it.

**Comment by demodun** [comment]
It still shows the same error.
what can I do?

**Comment by demodun** [comment]
http://doc.qt.io/qt-5/qdatetime.html

http://doc.qt.io/qt-4.8/qdatetime.html

ok... this is obvious a problem!

Please fix the bug and support qt4.8
Not all of us have qt 5

**Comment by UdjinM6** [comment]
should be fixed by #1672
