### ISSUE TITLE
sentinel.conf and dash.conf. Trim the spaces!

### ISSUE THREAD

**Issue by demodun** [dashpay/dash#1703]
sentinel.conf and dash.conf. Trim the spaces!

sentinel.conf
`rpcuser=demo`
dash.conf
`rpcuser=demo `

Does it look the same? well it is NOT!!!  **There is a space after demo in dash.conf**
As a result of this misconfiguration in dash.conf and sentinel.conf, sentinel cannot authenticate with dashd!!!

This is bug or at least a deficiency. You don't expect amateurs to know that a space matters when they edit the configuration files, do you?

**Comment by Alex-Werner** [comment]
Hi @demodun, 
May this instead concern only https://github.com/dashpay/sentinel ? 
As far as I know, there is already a trim made on .conf file (using boost)

**Comment by demodun** [comment]
It concerns both sentinel and dashd.
They both have to trim the spaces, at the end of rpcuser tag.
this should be valid
<code>rpcuser=demodun is demo</code>
but this
<code>rpcuser=demodun is demo </code>
should be trimmed to
<code>rpcuser=demodun is demo</code>

**Comment by Alex-Werner** [comment]
While I may admit that this exist in sentinel (not tested yet). 
Can you explain me how did you isolate that this is a bug occurring in dashd (which I tested to be sure and found as not existing) ?

**Comment by demodun** [comment]
There was something after demo word
dash.conf
<code>rpcuser=demo<something invisible><code> 
sentinel.conf
<code>rpcuser=demo<code> 
Maybe it wasnt a space, but a special invisible character (in linux debian), which I delete it.
If space doesnt work, then try all possible [invisible characters](https://www.unix.com/shell-programming-and-scripting/6439-hidden-control-characters-unix-text-file.html).

**Comment by Alex-Werner** [comment]
Hum. 
But if the user voluntarely decide to use a invisible characters, which is a valid characters and therefore a valid wish from the user, why should we take the decision to tell the user "fuck off with your characters, you, user, have it wrong, we,  dev, have it right and decide to remove it"? 

Trimming for standard space, or handling /n and similar is logic, because it's a logical UX improvement right ? 
But it's not the case if the user decide to go fun with invisible chars, 

Also : https://github.com/minimaxir/big-list-of-naughty-strings

**Comment by demodun** [comment]
Special characters may occur by mistake, if you are using vi editor.

**Comment by UdjinM6** [comment]
Not a bug imo, so not going to "fix" this.

**Comment by demodun** [comment]
Not even a warning comment in the configuration file?

**Comment by Alex-Werner** [comment]
If he use VI, he knows about invisible characters.
I agree with Udjin that this could stay closed.

**Comment by demodun** [comment]
@Alex-Werner @UdjinM6 
Let me report here, that I repeat it with a single space and, it was a bug!!!
Please do it.
add
dash.conf
[code]rpcuser=demo[space][code]
sentinel.conf
[code]rpcuser=demo[code]

and you will se that sentinel cannot connect to dashd.
This is obviously a bug!
