### ISSUE TITLE
Crash on Thread 10, startup MacOS

### ISSUE THREAD

**Issue by domspassive** [dashpay/dash#1708]
When I click on Dash-Qt in Applications, it prompts me to give permission from unknown developer or something like that, i click ok. Program starts up then promptly terminates and generates a Problem Report.
I am not certain if this is enough information or even the right information to find the solution, I apologize for Im newish to this.

<img width="787" alt="screen shot 2017-11-01 at 02 16 38" src="https://user-images.githubusercontent.com/33116592/32268116-e77a8f3e-beaa-11e7-90d2-42d5c0abddcc.png">
<img width="599" alt="screen shot 2017-11-01 at 02 16 26" src="https://user-images.githubusercontent.com/33116592/32268128-f828ae7e-beaa-11e7-9553-7729228a0b02.png">
<img width="789" alt="screen shot 2017-10-31 at 23 28 42" src="https://user-images.githubusercontent.com/33116592/32268131-fefeed12-beaa-11e7-90a1-ba2429ac5c67.png">

**Comment by chaeplin** [comment]
Current Dash-QT version is 12.1.

Please update first.

With 12.1 Data folder name changed from `Dash` to `DashCore`.
Check following guide updating guide. 
https://dashpay.atlassian.net/wiki/spaces/DOC/pages/103911601/Updating+to+12.1+-+Users

**Comment by nmarley** [comment]
Closing per solution given by @chaeplin ^
