### ISSUE TITLE
Dash wallet "No block source available..."

### ISSUE THREAD

**Issue by Patrikas17** [dashpay/dash#1716]
Hello, could someone help me with my Dash wallet ? First time when I tried to launch it, it  was "out of sync" and just nothing happen. In the right side down corner was written "0 active connections  to Dash network" then I started searching for solution. What I tried:
1) Check Firewall (its fine)
2) Delete peers.data and launch it again with reindex (no reaction)
3) Donwload bootstrap.dat and put it in the folder and launch it again with reindex (stopped at 6 days behind and "no block source available...")
4) Then I add these nodes to dash.conf  (still no changes)
addnode=[2001:1608:10:25:10::101e:7241]:19999
addnode=[2001:1608:10:25:10::10d2:f4d1]:19999
addnode=[2001:1608:45:3::242:ac11:2]:19999
addnode=[2001:1608:45:3::242:ac11:3]:19999
addnode=[2001:1608:45:3::242:ac11:4]:19999
addnode=[2001:1608:45:3::242:ac11:5]:19999
addnode=[2001:1608:45:3::242:ac11:6]:19999
addnode=[2001:1608:45:3::242:ac11:7]:19999
addnode=[2001:19f0:9000:2042::2]:19999
addnode=[2001:19f0:9000:2049::2]:19999 

That was everything what I found on the internet and it still doesn't work, PLEASE help me !

![capture png2](https://user-images.githubusercontent.com/33431850/32461575-fc356d0c-c33e-11e7-96dc-68e5f36fd0ea.PNG)
![capture](https://user-images.githubusercontent.com/33431850/32461576-fc4ee048-c33e-11e7-8140-44a939eea4f3.PNG)

**Comment by UdjinM6** [comment]
19999 is a port for testnet so these nodes won't help you, not sure where you got them from... Wallet should find correct nodes on it's own, you shouldn't add nodes manually. If you are still having issues and want to add some nodes manually pls pick some masternodes instead https://www.dashninja.pl/masternodes.html

**Comment by Patrikas17** [comment]
Sorry I am begginer and I don't want to add something manually, I just want to make my wallet active, so I tried everything what I found. At the moment it shows "No block source available..."(photo above) Do you have any suggestions to me, what should I do with these masternodes ?

**Comment by Patrikas17** [comment]
In addition there is no network traffic and no active peers.

**Comment by UdjinM6** [comment]
Well, you already did when you added "addnode=" strings to your dash.conf ;)
Ok, so remove all these strings you added previously and add few new ones where IPs are picked from the page I linked to above e.g. 
```
addnode=45.32.176.120:9999
addnode=194.135.82.81:9999
addnode=212.24.100.254:9999
```
etc. I just picked a few random ones from that list - you can use them I guess, they should work. Or you can pick other nodes from the list if you care about privacy a lot and don't want to leave any links to your wallet activities in open conversations. It's also usually a good idea to pick nodes from different network subsets (i.e. different first numbers in IP addresses).

**Comment by Patrikas17** [comment]
unfortunately I added these string, but no reaction, same 0 active connections... Should dash.conf be empty ?

**Comment by UdjinM6** [comment]
Can you send me debug.log pls? udjinm6@dash.org

**Comment by Patrikas17** [comment]
Of course.

**Comment by UdjinM6** [comment]
Hmmm... ok, so it can get addresses from seeds which means that there is at least some connectivity which is good. Go to Settings -> Options -> Network, un-tick everything and restart the wallet.

**Comment by Patrikas17** [comment]
Still no reaction. ( No block source available, 0 active connections, 7 days behind) But when I was launching wallet it asked me where I want to hold data, because wallet is lauching first time and I choosed "default". any other suggestions ? :disappointed:

**Comment by KosherTableSalt** [comment]
I had problem similar to this, but mine was related to the windows (DELL) update that messed something up, could never figure out what happened but kept getting a similar error something with the P2P connection. The fix may seem stupid and a little to simple but i just deleted and reinstalled the wallet and it worked. Hope it helps! Sorry for the trouble mate, Cheers

**Comment by Patrikas17** [comment]
Sorry for making so much problems and questions to you guys, but it still doesn't work for me, I checked my windows latest update, everything is clear, uninstalled the "Dashcore" and deleted data from "appdata", then again donwloaded and installed wallet, but it still shows "Connecting to peers.." and no reaction.
![capture png111](https://user-images.githubusercontent.com/33431850/32704812-3f57128c-c814-11e7-8c46-cdcd1e509ae8.PNG)

**Comment by nmarley** [comment]
Hi @Patrikas17 , is this still an issue for you?

If yes, have you tried (or are you able to) installing on a brand-new system? This would be my current recommendation.

If you have, and it still doesn't have connectivity, I'd suggest starting from another physical location such as a café, to debug network connectivity issues.

**Comment by nmarley** [comment]
Closing as needs more info from OP
