### ISSUE TITLE
error: ‘masternodeSync’ was not declared in this scope

### ISSUE THREAD

**Issue by perwpqwe** [dashpay/dash#1722]
Linux ubuntu 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)

./configure --disable-wallet
make
-------------
  CXX      rpc/libbitcoin_server_a-mining.o
rpc/mining.cpp: In function ‘UniValue getblocktemplate(const UniValue&, bool)’:
rpc/mining.cpp:501:10: error: ‘masternodeSync’ was not declared in this scope
     if (!masternodeSync.IsSynced())
          ^
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-implicit-fallthrough’
cc1plus: warning: unrecognized command line option ‘-Wno-self-assign’
Makefile:5993: recipe for target 'rpc/libbitcoin_server_a-mining.o' failed

**Comment by cuddleup** [comment]
same probmlem

**Comment by dKrishtal** [comment]
same problem

**Comment by UdjinM6** [comment]
Should be fixed by #1733.
