### ISSUE TITLE
Can`t build Windows wallet on ubuntu 16.04

### ISSUE THREAD

**Issue by maxifom** [dashpay/dash#1724]
I installed the toolchain:
`sudo apt-get install g++-mingw-w64-i686 mingw-w64-i686-dev g++-mingw-w64-x86-64 mingw-w64-x86-64-dev`
After that, i have successfully completed these steps: 
`cd depends
make HOST=i686-w64-mingw32 -j4
cd ..`,
but i can`t find ./configure anywhere in the folders. How to finish building the wallet (I got no .exe or .tar files)?

**Comment by schinzelh** [comment]
I'd strongly suggest to look into using gitian for Windows platform cross compilation, as correctly setting up the toolchain is a tedious task.

--> https://github.com/dashpay/dash/blob/master/doc/gitian-building.md

**Comment by chaeplin** [comment]
```
cd depends
make HOST=i686-w64-mingw32
cd ..
./autogen.sh
./configure ~~
```

I think you need `./autogen.sh`
