### ISSUE TITLE
hdd crashed, only have seed phrase

### ISSUE THREAD

**Issue by Master244** [dashpay/dash#1744]
I have looked everywhere but I couldn't find the right answer to this question.

My HDD crashed and I had my 12 word phrase backed up on a USB but when I restore the wallet it doesn't show the correct balance. I tried restoring through Exodus and get keys from there but still nothing there. I can see the block in the explorer saying not redeemed though. My question is, is there some way to update or regenerate the blockchain or generate the private key with the help of the public adress in the explorer and the seed?

I am really lost, hard to find info about this. And if I can't get it back it's just frozen there :/ would suck to see that it's mine but I can't do anything with it.

**Comment by chaeplin** [comment]
start your dashd/Qt with `-rescan`.

```
  -rescan
       Rescan the block chain for missing wallet transactions on startup
```

https://github.com/dashpay/dash/blob/v0.12.2.0/doc/release-notes.md#experimental-hd-wallet

```
Experimental HD wallet

This release includes experimental implementation of BIP39/BIP44 compatible HD wallet. Wallet type (HD or non-HD) is selected when wallet is created via usehd command-line option, default is 0 which means that a regular non-deterministic wallet is going to be used. If you decide to use HD wallet, you can also specify BIP39 mnemonic and mnemonic passphrase (see mnemonic and mnemonicpassphrase command-line options) but you can do so only on initial wallet creation and can't change these afterwards. If you don't specify them, mnemonic is going to be generated randomly and mnemonic passphrase is going to be just a blank string.

WARNING: The way it's currently implemented is NOT safe and is NOT recommended to use on mainnet. Wallet is created unencrypted with mnemonic stored inside, so even if you encrypt it later there will be a short period of time when mnemonic is stored in plain text. This issue will be addressed in future releases.

```
```
  -usehd
       Use hierarchical deterministic key generation (HD) after bip39/bip44.
       Only has effect during wallet creation/first start (default: 0)

  -mnemonic
       User defined mnemonic for HD wallet (bip39). Only has effect during
       wallet creation/first start (default: randomly generated)

  -mnemonicpassphrase
       User defined mnemonic passphrase for HD wallet (bip39). Only has effect
       during wallet creation/first start (default: empty string)

  -hdseed
       User defined seed for HD wallet (should be in hex). Only has effect
       during wallet creation/first start (default: randomly generated)

```

**Comment by Master244** [comment]
I did that, but the weird thing is it didn't show up. I used Jaxx and learned the hard way to only use the core team software. But I had my balance in Jaxx ran the update ofcourse I had a backup of my 12 word phrase, but I read things about a changing server adress I can't seem to figure out. 

https://chainz.cryptoid.info/dash/tx.dws?4697821.htm

it shows it's just sitting there but I cant seem to import it. Trying to import in electrum-dash was not possible it uses a different 12 word encryption so I'm really at a loss here :')

**Comment by chaeplin** [comment]
If you know exact address, use https://iancoleman.io/bip39/ (offline version is https://github.com/iancoleman/bip39 ). 

Import private key to a wallet.

**Comment by Master244** [comment]
Ye I found that, but then do you mean based on the Account Extended Private Key? Because now I was generating and trying to CTRL+F the public key and see if it was there yet but no luck so far. What wallet would allow import for that Account Extended Private Key?

**Comment by chaeplin** [comment]
@Master244 
BIP39 Mnemonic --> 12 word Mnemonic
Coin --> Dash
Derived Addresses --> will show you Dash address

**Comment by Master244** [comment]
I dont get it sorry for my slow understanding :/

I filled in the 12 word, selected the Dash to but in the derived addresses I dont find the public adress from here: https://chainz.cryptoid.info/dash/address.dws?Xb9TApN5mv8iy9bTha7ZriMYapnZVsCoKp.htm and I don't see where I have to put this key in to generate the private key? Or is that not possible? Thanks a million by the way for helping me out :)

**Comment by chaeplin** [comment]
@Master244 
If your `12 word Mnemonic` is correct, https://iancoleman.io/bip39/ should show you the Dash address. 

1) At `Derived Addresses` increase number labeled `show` from `20` to like `100`
2) At `Derivation Path` change `External / Internal` from `0` to `1` to check if the Dash address is in change path.


DashCore currently supports only `m/44'/5'/0'/0` and` m/44'/5'/0'/1` now(means no account yet)


The following shows `how to recover mnemonic with DashCore`.
You have 12 word `BIP39 Mnemonic`(looks like not from DashCore/QT, cause DashCore/QT uses 24 word as default).
And you want to use the mnemonic with DashCore/QT.

As I linked https://github.com/dashpay/dash/blob/v0.12.2.0/doc/release-notes.md#experimental-hd-wallet , DashCore/QT will generated/use HD wallet if the following conditions are true
1) no wallet.dat in Dash data Directory
2) DashCore stat with `-usehd` or  `usehd=1` is in dash.conf

Once HD wallet created, you can't change  mnemonic or hdseed at all.

To import/create HD wallet with Dashcore/QT,
1) no wallet.dat in Dash data Directory
2) start DashCore/QT with `-usehd` and `mnemonic` --> With dash.conf is more easy.
- stop DashCore/QT
- backup wallet.dat, move wallet.dat
- add following to dash.conf
```
usehd=1
mnemonic= xx xxx xxx xxx
```
- start wallet
- use `dumphdinfo` to check hdseed and mnemonic
- encrypt wallet
- remove `mnemonic` from dash.conf

**Comment by Master244** [comment]
Wow! Thanks for the detailed response. 

My browser crashes when I create 2000 or more, but is it not possible to also enter the public adress I already have? Now I just generate them and ctrl+f to try and see if it's there. 

Also their support says they use: m/44'/60'/0'/0 shouldn't I then use BIP32 with custom path? But then I read on Git they use:

m / purpose' / coin_type' / account' / change / address_index
But some wallets (e.g Ledger) chose an HD path of m/44'/60/0' which is almost BIP44, except the change path is not used. 

I just can't find what they use for Dash only for Bitcoins..

My idea now was to port the functionality into a node.js app with a db and api connected to it. Then I can just run the function and check afterwards if it matches on the public address and breaks or continues to create the matching public address? And should I be doing this for the external and internal ones or is there a smarter way?

What does internat and external mean anyway for HD wallets?

But I feel it should be simpeler, I have the public address I posted before and the 12 word phrase or seed why is it so hard to claim the Dash I have sitting there :') .

Thanks again for your responses I learn a lot by them! I will update here when I tried your steps.

**Comment by chaeplin** [comment]
@Master244 
1) m/44'/60'/0'/0 --> 60' is path for Ether
2) Exodus uses only m/44'/5'/0'/0/x as I last checked(external only)
3) https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#change 
```
Change

Constant 0 is used for external chain and constant 1 for internal chain (also known as change addresses). External chain is used for addresses that are meant to be visible outside of the wallet (e.g. for receiving payments). Internal chain is used for addresses which are not meant to be visible outside of the wallet and is used for return transaction change.

Public derivation is used at this level.
```

**Comment by Master244** [comment]
I then believe my Dash Coins are stuck at a external address. The one I linked before. I followed your steps to restore the wallet. It gave me a message to confirm binding the mnemonic in the config. 

I still don't see any balance. Do I need to follow some other step within Dash-Core to claim the sitting Dash at the public address?

**Comment by chaeplin** [comment]
@Master244 use
`dash-cli validateaddress your_dash_addr` to check 
```
 dash-cli validateaddress yTgapoCdZQuKxBBzJ1Zr7bQRfczypDeEhL
{
  "isvalid": true,
  "address": "yTgapoCdZQuKxBBzJ1Zr7bQRfczypDeEhL",
  "scriptPubKey": "76a91450c846052fe46a4f8b6b01ebdd10746498e8dd5d88ac",
  "ismine": true,
  "iswatchonly": false,
  "isscript": false,
  "pubkey": "0296151909bf075002447934c3e604c0af5ce1dbc1084e791745111e66a65b2472",
  "iscompressed": true,
  "account": "",
  "hdkeypath": "m/44'/1'/0'/0/0",
  "hdchainid": "20b5c3a36caed9f43f5312d64beb3c938e5167d2932af9b8c2f8f81f31933ebe"
}
```

if `ismine` is true, and balance is off, then use `-rescan` when starting dashd/qt

```
  -rescan
       Rescan the block chain for missing wallet transactions on startup
```

And you can increase keypool size and check again with validateaddress.
```
dash-cli help keypoolrefill
keypoolrefill ( newsize )

Fills the keypool.

Arguments
1. newsize     (numeric, optional, default=1000) The new keypool size

Examples:
> dash-cli keypoolrefill 
> curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "keypoolrefill", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:9998/
```
