### ISSUE TITLE
DashSpanish-NewsSite proposal reports 3000 votes!

### ISSUE THREAD

**Issue by demodun** [dashpay/dash#1754]
You can see my script here
https://www.dash.org/forum/threads/which-masternodes-voted-and-what-exactly-voted-on-various-proposals.18172/#post-149684

And if you see the results (upload.zip) it says that DashSpanish-NewsSite has almost 3000 votes!
the hash of the proposal is
4a0599c4dbf7c5697f3a9610bc5e8856066bfd3490c77dcf218d1a2411e3978e

most of the YES votes are reported as :YES:DELETE

Whats happening there?

**Comment by chaeplin** [comment]
Proposal is old(date passed), so Sentinel do vote to delete the proposal. 

Proposal Time-Span | 7/20/2017 11:27:50 AM | 8/19/2017 6:52:30 AM



  "4a0599c4dbf7c5697f3a9610bc5e8856066bfd3490c77dcf218d1a2411e3978e": {
    "DataHex": "5b5b2270726f706f73616c222c7b22656e645f65706f6368223a2231353033303933313530222c226e616d65223a22446173685370616e6973682d4e65777353697465222c227061796d656e745f61646472657373223a2258776e507769726d34615337735452386f784134744c4b4a707a5a6a64776b384d74222c227061796d656e745f616d6f756e74223a223537222c2273746172745f65706f6368223a2231353030353137363730222c2274797065223a312c2275726c223a2268747470733a2f2f7777772e6461736863656e7472616c2e6f72672f702f446173685370616e6973682d4e65777353697465227d5d5d",
    "DataString": "[[\"proposal\",{\"end_epoch\":\"1503093150\",\"name\":\"DashSpanish-NewsSite\",\"payment_address\":\"XwnPwirm4aS7sTR8oxA4tLKJpzZjdwk8Mt\",\"payment_amount\":\"57\",\"start_epoch\":\"1500517670\",\"type\":1,\"url\":\"https://www.dashcentral.org/p/DashSpanish-NewsSite\"}]]",
    "Hash": "4a0599c4dbf7c5697f3a9610bc5e8856066bfd3490c77dcf218d1a2411e3978e",
    "CollateralHash": "5a64ba702e244207fb50777e79fa175e938ae507af5ea77054ed01d5ba7d9857",
    "ObjectType": 1,
    "CreationTime": 1500040425,
    "AbsoluteYesCount": 430,
    "YesCount": 498,
    "NoCount": 68,
    "AbstainCount": 40,
    "fBlockchainValidity": true,
    "IsValidReason": "",
    "fCachedValid": true,
    "fCachedFunding": true,
    "fCachedDelete": true,
    "fCachedEndorsed": false
  },



https://www.dashninja.pl/proposaldetails.html?proposalhash=4a0599c4dbf7c5697f3a9610bc5e8856066bfd3490c77dcf218d1a2411e3978e

**Comment by demodun** [comment]
The same appeared with the proposal 
connectDashwithEUdecisionmakers
585106dc3f05092aae66abd00549edb229c7e3f235706025b21bca1c83bcf5da

almost 3000 vote there too, having the same status YES:DELETE

**Comment by chaeplin** [comment]
also expired https://www.dashninja.pl/proposaldetails.html?proposalhash=585106dc3f05092aae66abd00549edb229c7e3f235706025b21bca1c83bcf5da


Proposal Time-Span | 8/19/2017 6:26:09 PM | 9/18/2017 1:50:49 PM
-- | -- | --

**Comment by UdjinM6** [comment]
Not an issue, works as designed. Closing.
