### ISSUE TITLE
"Start Mixing" shouldn't react to space bar

### ISSUE THREAD

**Issue by codablock** [dashpay/dash#1766]
When Dash Core is freshly started, the "Start Mixing" button has focus and thus pressing space by mistake immediately tries to start mixing. This happened to me when I was starting Dash and then started typing somewhere else while it was loading. When Dash Core got to the foreground, I pressed space (as I was in the middle of typing a sentence).

I'd suggest to make "Start Mixing" not react on space or at least not get focus on startup.

**Comment by UdjinM6** [comment]
fixed by #2154
