### ISSUE TITLE
Include p2pk into addressindex

### ISSUE THREAD

**Issue by UdjinM6** [dashpay/dash#1767]
See https://github.com/bitpay/bitcoin/issues/17

Example:
https://insight.dash.org/insight/tx/f770f05d2b1c63b71b2650227252da06ef226661982c4ee9b136b64f77bbbd0c
vs
https://insight.dash.org/insight/address/XoLTipv6ryWECYu94vbkmDjntAXqNgouTW

**Comment by nmarley** [comment]
I believe this has been added to the `develop` branch now. Ok to close this @UdjinM6 @codablock ?

**Comment by UdjinM6** [comment]
Yep, #1839 fixed this I believe. Closing.
