### ISSUE TITLE
Dash-qt lag problem: When I try to importwallet from the gui console , Dash-qt lags

### ISSUE THREAD

**Issue by demodun** [dashpay/dash#1785]
I issued to the gui->tools->console the command : 
importwallet filename
An "importing wallet" frame appears, and the Gui lags until the import is finished (in my case it was about 2 minutes). This is yet another GUI lag problem.

Dash core version 12.2.1 (32 bit)
QT version 5.5.0

**Comment by nmarley** [comment]
This is expected.
