### ISSUE TITLE
Are Russian translation updates wanted?

### ISSUE THREAD

**Issue by jet24** [dashpay/dash#1792]
I looked through /dash/src/qt/locale/dash_ru.ts and can offer some fixes. For example wallet is inconsistently translated as кошелёк or Бумажник. Peer is sometimes участник and sometimes пир. Node is sometimes узел and sometimes нод. A few endings on masternode are incorrect depending on sentence structure. Dash is mostly in English alphabet but sometimes in Russian, and there are some other minor typos or literal word translations which have a better alternative.

I am not a programmer and don't know what I'm doing in github. Do I just do a pull request? Edit the file and upload? I don't want to edit 5000 lines to then be told to jump through some other hoops like make a fork and build a patch or whatever. I don't know any of that stuff, just want the edits to make it in and not be ignored.

**Comment by UdjinM6** [comment]
Thanks for pointing out! Translations are not edited directly on GitHub, instead we accept translations via https://www.transifex.com/dash/dash/

**Comment by jet24** [comment]
Thanks. I will look into it, and go from there.
