### ISSUE TITLE
Implement X11 benchmark

### ISSUE THREAD

**Issue by codablock** [dashpay/dash#1806]
As suggested in [#1804](https://github.com/dashpay/dash/pull/1804/files/640bee1814ff0722f60572a0b0bb9bc9eaf63266..9bf69879330869a79efdc69fec2c8fa5686b04c2#discussion_r158414690)

**Comment by nmarley** [comment]
Looks like 0f4d963baf0d7d8c0d3780b8920cc2eb1b3a3fcb added X11 benchmarks, possible to close this? @codablock @UdjinM6

**Comment by codablock** [comment]
Yepp, can be closed (will do so now). Thanks for pointing this out.
