### ISSUE TITLE
make check failure on Debian stretch

### ISSUE THREAD

**Issue by possientis** [dashpay/dash#1814]
I am getting test failures for `v0.12.2.2` on Debian stretch:
 
    $ uname -a
     Linux right 4.8.0-1-amd64 #1 SMP Debian 4.8.5-1 (2016-10-28) x86_64 GNU/Linux

    $ git checkout v0.12.2.2
    $ ./autogen.sh
     ...
     $ ./configure ...
     ....
     $ make
     ....    
     $ make check
     ...

    make[4]: Entering directory '/home/john/Libs/dash/src/secp256k1'
      CC       src/tests-tests.o
    src/tests.c: In function ‘test_ecdsa_der_parse’:
    src/tests.c:3561:52: error: dereferencing pointer to incomplete type ‘ECDSA_SIG {aka struct  ECDSA_SIG_st}’
             valid_openssl = !BN_is_negative(sig_openssl->r) && !BN_is_negative(sig_openssl->s) && BN_num_bits(sig_openssl->r) > 0 && BN_num_bits(sig_openssl->r) <= 256 && BN_num_bits(sig_openssl->s) > 0 && BN_num_bits(sig_openssl->s) <= 256;
                                                    ^~
    Makefile:931: recipe for target 'src/tests-tests.o' failed

I am guessing this issue is relating to the OpenSSL 1.1API change. A similar issue was [highlighted for bitcoin](https://github.com/bitcoin-core/secp256k1/issues/429) and a fix was provided [here](https://github.com/bitcoin/bitcoin/pull/9326)

**Comment by codablock** [comment]
Can't check this as I'm not at my laptop atm. Are you using the depends prefix and did you do a make inside the depends dir?

**Comment by possientis** [comment]
Hi, very sorry not sure I understand the question. I simply cloned the github repo, then `cd dash` then `checkout v0.12.2.2` then 'autogen.sh` and `configure` and `make` (being understood that `configure` had the correct `LDFLAGS` and `CPPFLAGS` pointing to my build of Berkeley DB). So build was successful but `make check` failed. All this was done inside `dash` directory.

**Comment by codablock** [comment]
The depends dir contains all dependencies you need to build Dash. You can build the dependencies by calling make inside the depends dir. After that you'll have to use './configure - -prefix=$(pwd)/depends/<host>' to let the build system use these. Can't give you the exact command line atm as I'm on my mobile atm.
I'll later check why it doesn't work with the openssl version of stretch.

**Comment by possientis** [comment]
The openssl version of stretch is 1.1 which is known to have non-backward compatible API changes

**Comment by codablock** [comment]
https://github.com/dashpay/dash/pull/1816 should fix this

**Comment by possientis** [comment]
Thanks v much, will be happy to test it when new commit available
