### ISSUE TITLE
Dash POW or POS?

### ISSUE THREAD

**Issue by senzacionale** [dashpay/dash#1825]
I am not sure if DASH is POS or POW?
I know it is not a truly POS but its masternodes work kind off in a POS way and keeping DASH coins there is very profitable. This means that is POW?

I checked your code and you set it as POW.
https://github.com/dashpay/dash/blob/master/src/chainparams.cpp

**Comment by andyfreer** [comment]
Block production in Dash is achieved by proof of work.  That is to say miners need to produce valid blocks at the required difficulty to add the next block to the chain.

Within each block, the miner need to include a coinbase tx splitting 45% of the reward to the next winning Masternode from the Masternode list and this is where some people misunderstand Dash as proof of service consensus.

Whilst it's true that part of gaining entry into the Masternode list is proving ownership of 1000 Dash in a UTXO, the Masternode also needs to be providing *service* to the network on a running fullnode referencing that collateral to be enabled in the MN list.

Therefore, proving a stake alone will not enable any node to receive rewards as in a proof of stake coin, and neither does proving that stake give you any ability to produce a block or decide the contents of a block.

So no, I don't think stating Dash as a POS coin is in anyway a good definition of what is inherently a mined proof of work cryptocurrency.,

**Comment by senzacionale** [comment]
thank you
