### ISSUE TITLE
Spelling error in Get Dash -> OTC section 

### ISSUE THREAD

**Issue by Candidculture** [dashpay/dash#1831]
Not directly code related, but there appears to be an error on the [Get Dash](https://www.dash.org/get-dash/) page. Spillage.t?

<img width="461" alt="screen shot 2018-01-03 at 4 30 31 pm" src="https://user-images.githubusercontent.com/25105397/34542904-252debc0-f0a4-11e7-9d10-a41f9a9a6484.png">

**Comment by UdjinM6** [comment]
Please create an issue at https://github.com/dashpay/dash-website/issues
Thank you.
