### ISSUE TITLE
Announcing several MN with identical IP/port

### ISSUE THREAD

**Issue by landergate** [dashpay/dash#1832]
Is there anything that prevents MN owners from announcing several MN on only one identical IP/port?
What could prevent them to become ENABLED, receive payments and not provide services? Considering that only one daemon would be published for incoming connections and actually reachable on that IP:port.

**Comment by thephez** [comment]
Yes, there is - you can see [CMasternodeMan::CheckSameAddr()](https://github.com/dashpay/dash/blob/master/src/masternodeman.cpp#L1015-#L1024) for the details.

**Comment by landergate** [comment]
@thephez Great, thanks!
Do non-MN nodes actually executing this check?
