### ISSUE TITLE
Tiny fonts on Windows 10 (next to unreadable) - Dash Core Version v0.12.2.2 (64-Bit)

### ISSUE THREAD

**Issue by JVerstry** [dashpay/dash#1837]
Hi, I know a similar issue has been opened (https://github.com/dashpay/dash/issues/1339), but it has been closed without a solution. None of its suggestions fixes the reported issue. 

NetBeans faced the same issue and there are some workarounds:
- https://stackoverflow.com/a/24209191/520957
- https://netbeans.org/bugzilla/show_bug.cgi?id=254512#c6 

Is there any similar command-line or configuration workaround available for the Dash Wallet? Else, I think we should implement some.

**Comment by UdjinM6** [comment]
Try selecting `DASH-light-hires` theme in settings (requires wallet restart to take effect).

**Comment by JVerstry** [comment]
Suggestion works !!!
