### ISSUE TITLE
[feature-request] Masterblocks: Scaling Blockchain by summarizing balances

### ISSUE THREAD

**Issue by Technologov** [dashpay/dash#1838]
This is a follow up on previous idea, with some improvements:
Old idea: Discussion of a wild idea: Multiple Genesis Blocks, Archival Node
https://github.com/dashpay/dash/issues/1380

Here is the new idea:
https://docs.google.com/document/d/1usnNigTJw6cpone_xrcIMmzxF7U1MFrjb3y7aTsbDx0/edit

**Comment by nmarley** [comment]
Thanks for the suggestion! We've chosen a different route for scaling Dash. This is a good forum topic discussion, but not feasible as a Github issue to be solved. Closing here, please open a thread at dash.org/forum for further discussion.
