### ISSUE TITLE
Orphan streaks are back

### ISSUE THREAD

**Issue by oliverw** [dashpay/dash#1850]
Once again smaller pools are getting crazy orphan streaks killing them off if this goes on. Just have a look at our pool's block list: https://poolmining.org/pool/dash. The possibility of this happening naturally is astronomically low.

**Comment by nmarley** [comment]
@UdjinM6 @codablock @schinzelh I don't believe this is an issue anymore, correct? Are we able to close this?

**Comment by oliverw** [comment]
Hasn't happened for a quite a while.
