### ISSUE TITLE
Makefile.am:78: error: CPPFLAGS_FOR_BUILD must be set with '=' before using '+=' Makefile.am:79: error: CFLAGS_FOR_BUILD must be set with '=' before using '+='

### ISSUE THREAD

**Issue by mrmetech** [dashpay/dash#1855]
`libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'

libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build-aux/m4'.
libtoolize: copying file 'build-aux/m4/libtool.m4'
libtoolize: copying file 'build-aux/m4/ltoptions.m4'
libtoolize: copying file 'build-aux/m4/ltsugar.m4'
libtoolize: copying file 'build-aux/m4/ltversion.m4'
libtoolize: copying file 'build-aux/m4/lt~obsolete.m4'
configure.ac:45: installing 'build-aux/compile'
configure.ac:45: installing 'build-aux/config.guess'
configure.ac:45: installing 'build-aux/config.sub'
configure.ac:28: installing 'build-aux/install-sh'
configure.ac:28: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
aclocal: warning: couldn't open directory 'build-aux/m4': No such file or directory
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build-aux/m4'.
libtoolize: copying file 'build-aux/m4/libtool.m4'
libtoolize: copying file 'build-aux/m4/ltoptions.m4'
libtoolize: copying file 'build-aux/m4/ltsugar.m4'
libtoolize: copying file 'build-aux/m4/ltversion.m4'
libtoolize: copying file 'build-aux/m4/lt~obsolete.m4'
configure.ac:10: installing 'build-aux/compile'
configure.ac:5: installing 'build-aux/config.guess'
configure.ac:5: installing 'build-aux/config.sub'
configure.ac:9: installing 'build-aux/install-sh'
configure.ac:9: installing 'build-aux/missing'
Makefile.am:78: error: CPPFLAGS_FOR_BUILD must be set with '=' before using '+='
Makefile.am:79: error: CFLAGS_FOR_BUILD must be set with '=' before using '+='
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
autoreconf: automake failed with exit status: 1
`

Hi i get this error when trying to compile the wallet and i have no idea why any help

**Comment by codablock** [comment]
Which OS are you building on? Also, can you give us the "./configure" flags you use?

**Comment by mrmetech** [comment]
Ubuntu 16 and it can use ./configure i get stock on that autogen

**Comment by charlesrocket** [comment]
same on 14.04
also have the same error on 16.04. but i unzip the file and build - it works

builds on lates macos

**Comment by josemejiasji** [comment]
Same here debian 8, following the gitian build process. Works on Mac OSX 10.13.2

**Comment by codablock** [comment]
On which branch are you? master or develop? If on master, can you try develop as well? If it's happening on develop, I'll have to take a closer look.

**Comment by mrmetech** [comment]
The problem was when i uploaded it to github i guess some of the files changed. It works fine if i don't do that so problem solved i guess

**Comment by charlesrocket** [comment]
@mrmetech this might be the .gitignore situation (?)

**Comment by Big-Brother** [comment]
I get this issue too on Ubuntu Server 16.04.3. You can patch this error by editing /src/secp256k1/Makefile.am and adding:

CPPFLAGS_FOR_BUILD =
CFLAGS_FOR_BUILD =

like so (line 78)

CPPFLAGS_FOR_BUILD =
CPPFLAGS_FOR_BUILD +=-I$(top_srcdir)
CFLAGS_FOR_BUILD =
CFLAGS_FOR_BUILD += -Wall -Wextra -Wno-unused-function

But.... this doesn't solve the problem. The problem is actually something else altogether. For me it says something related to secp256k1

**Comment by Lesther993** [comment]
I have the same issue when uploaded it to github and then did pull

**Comment by mrmetech** [comment]
I found the fix

**Comment by Lesther993** [comment]
What did you do?

**Comment by mrmetech** [comment]
some files were missing

**Comment by nmarley** [comment]
Closing as this is no longer an issue for OP. If you have a separate issue (such as problems with `secp256k1`), please feel free to open a new issue on Github with that specific information. Thanks.

**Comment by Bitcoinera** [comment]
Big-Brother solution worked for me
