### ISSUE TITLE
PrivKey

### ISSUE THREAD

**Issue by 1990606129** [dashpay/dash#1860]
When generating genesis block while testing an enclosed chain, a genesis ID is generated, sporkpubkey etc.

How do I actually create the privatekeypair to the public key? Is there something I'm missing?

I'm trying to create the privkey used to sign spork messages however I'm not sure exactly what this refers to or how to generate it.

**Comment by nmarley** [comment]
Hi, if you need a spork key for your own testing, you'll need to generate an ECDSA keypair and hard-code the public key into the code. Public keys are derived from private keys, but not the other way 'round. You won't be able to generate a private key for a public key.

> I'm trying to create the privkey used to sign spork messages however I'm not sure exactly what this refers to or how to generate it.

You will need to generate a new keypair (using any of several libraries available, or `masternode genkey` for example) and start your Dash-Qt client using the `-sporkkey` option and passing it the private key in WIF format. You'll have to hard-code the corresponding public key into `chainparams.cpp`, replacing the existing public key.
