### ISSUE TITLE
Unable to use addressindex RPC calls 

### ISSUE THREAD

**Issue by mrwillis** [dashpay/dash#1862]
Hi all,

I'm running on the testnet trying to using the following very useful commands:

== Addressindex ==
getaddressbalance                          Returns the balance for an address(es) (requires addressindex to be enabled).
getaddressdeltas                           Returns all changes for an address (requires addressindex to be enabled).
getaddressmempool                          Returns all mempool deltas for an address (requires addressindex to be enabled).
getaddresstxids                            Returns the txids for an address(es) (requires addressindex to be enabled).
getaddressutxos                            Returns all unspent outputs for an address (requires addressindex to be enabled).

I am making a block explorer of sorts and these would be a god-send! In my dash.conf I have the following information:

rpcuser=good_username
rpcpassword=good_password
rpcport=9998
rpcallowip=interesting_ip
rpcallowip=interesting_ip
rpcclienttimeout=30
testnet=1
listen=1
server=1
daemon=1
maxconnections=64
txindex=1
addressindex=1
timestampindex=1
spentindex=1

Unfortunately, when I call it, I get this error for the testnet address yaEjcAUVJUoVnPC5DMU5Au2EFDXETHPmsm

{"result":null,"error":{"code":-5,"message":"No information available for address"},"id":"curltest"}

But I know there are transactions for that address:

https://testnet-insight.dashevo.org/insight/address/yaEjcAUVJUoVnPC5DMU5Au2EFDXETHPmsm

Any ideas?

Thanks

**Comment by UdjinM6** [comment]
Make sure you reindexed (run daemon with "-reindex" option once) after adding these additional indexes into config file.

**Comment by nmarley** [comment]
Hi @mrwillis , were you able to fix this per @UdjinM6 's instructions above?

**Comment by ebiboy2** [comment]
I get same exact error, however after i reindexed, i get a new error code -28 Loading wallet...

**Comment by 7h3v01c3** [comment]
Error -28 - is an error that is human readable. One of the few :)

"Loading wallet" just meant you need to wait a little before making those calls. The wallet is re-indexing and setting everything up for you.
