### ISSUE TITLE
Block Height + Masternodes

### ISSUE THREAD

**Issue by 1990606129** [dashpay/dash#1865]
Individual X has a masternode and decides to mine to the same node as the mn. The masternode confirms the coin immediately and therefore has the highest block height.

How do you stop that masternode from forking your chain when you want the blocks to be confirmed by miners with the most hashing power, not a masternode.

Technically a miner could use this to fork the chain whenever he wants and cause multiple micro chains.

**Comment by codablock** [comment]
The block would be propagated the same way all the other blocks are propagated. And also the same rules as always apply, the chain with the most work wins. A single miner won't have enough hash power to do any damage, the masternode doesn't change anything here.

**Comment by nmarley** [comment]
Hi,

As @codablock wrote, nodes converge on most work chain, masternode does not give an advantage in this scenario.
