### ISSUE TITLE
create a tarball for the 10.9 SDK

### ISSUE THREAD

**Issue by broros** [dashpay/dash#1881]
cannot create a tarball for the 10.9 SDK

```
10.9 SDK is not supported on macos 10.13, I get an error when trying to compile tarball 10.9 sdk.
```

```
tar -C /Volumes/Xcode/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/ -czf MacOSX10.9.sdk.tar.gz MacOSX10.9.sdk
```

**Comment by NarubyRiverlione** [comment]
I've used this script successfully to extract any SDK I needed so far : https://github.com/devernay/xcodelegacy

Or I your comfortable in trusting  a 3th party you can download them from https://github.com/phracker/MacOSX-SDKs/releases

**Comment by schinzelh** [comment]
Answered - please note that the repo above may violate Apples distribution terms
