### ISSUE TITLE
Dash-qt wallet gets laggy

### ISSUE THREAD

**Issue by oti-dev** [dashpay/dash#1886]
Hello guys,

We've got an issue - the wallet gets laggy at times - both GUI and RPC interface react with significant latency. The wallet is pretty big and it's used alot. At the moment it consists of about 18k transactions, there's 400 transactions daily on average. 

Applicaton is run with:
`
spentindex=1
addressindex=1
timestampindex=1
server=1
txindex=1
`

I'm not sure if the issue is caused by the number of transactions, it's just my guess, but is it possible to make the wallet not maintain data about all 18k transactions and only keep some of the most recent?
Any ideas what's the actualy reason for this and what's the solution?

**Comment by nmarley** [comment]
Hi, I'm not sure if the number is the reason for this, b/c I've never had a wallet w/so many transactions. But a simple fix would be to transfer the balance to another wallet.

Is this still an issue for you?

**Comment by PastaPastaPasta** [comment]
Closing due to no response. please feel free to open if you still have an issue you'd like to investigate
