### ISSUE TITLE
Nomp

### ISSUE THREAD

**Issue by raskazlt** [dashpay/dash#1901]
Good afternoon.
I have a problem in the work of the pool on DASH that all works well for p2pool. On nomp does not work, there are no problems in the logs, 2000% and there are no blocks. What can I see?

**Comment by Stouse49** [comment]
You will need to provide more information.

**Comment by nmarley** [comment]
I'm not sure how we can help w/this, as the previous commenter stated, there's not enough information here to be able to help.

Feel free to add more info and we can re-open this if necessary.
