### ISSUE TITLE
QT Wallet Build Bombs on Make

### ISSUE THREAD

**Issue by buddilla** [dashpay/dash#1953]
Following instructions here:
https://github.com/dashpay/dash/blob/master/doc/build-osx.md#use-qt-creator-as-ide

I have tried:
./autogen.sh
./configure --with-gui=qt5 --enable-debug

and just:
./configure --with-gui=qt5 --enable-debug

I tried to build at least 9 times using different clangs and debuggers

I am able to build the daemon and the gui executable, not to be confused with dash.app, in the terminal. (Before someone asks why don't you use the executable instead? It is not acceptable for deployment.)

Qt errors on build:

Starting: "/usr/bin/make" all
make: *** No rule to make target `all'. Stop.
23:48:14: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project dash-qt (kit: Desktop Qt 5.10.0 clang 64bit)

Machine specs:
OS: macOS 10.13
CPU: 2.6 GHz Intel Core i7
RAM: 16 GB 1600 MHz DDR3
Disk size: 1TB
Disk Type HD/SDD Hybrid

**Comment by Stouse49** [comment]
./autogen.sh
./configure --with-gui=qt5 --enable-debug

After doing the above:

In QT Creator, go to Projects / Build Settings, then Build Steps, Then find the **Make:** make, click Details.  Uncheck "all".

Then you can build within QT Creator.

I reproduced your issue on a Mac and Linux (Ubuntu).

**Comment by buddilla** [comment]
Thank you
