### ISSUE TITLE
nObjectType will never equal GOVERNANCE_OBJECT_TRIGGER ?

### ISSUE THREAD

**Issue by mycamphortree** [dashpay/dash#1957]
When I look at the voting part of the code, I am wondering how a goverance's nObjectType is assigned to GOVERNANCE_OBJECT_TRIGGER, it's always default to GOVERNANCE_OBJECT_UNKNOWN?
Then, what the time call for AddNewTrigger in governance-calsses.cpp ?

**Comment by nmarley** [comment]
Hi,

Trigger objects are submitted by masternodes via Sentinel, using the `gobject submit` command. You can find this in `rpc/governance.cpp`.

Does that answer your question?

**Comment by mycamphortree** [comment]
I know thank you
