### ISSUE TITLE
libtool for -rpath problems

### ISSUE THREAD

**Issue by 26rahulsingh** [dashpay/dash#1986]
./autogen.sh
----------------
configure.ac:63: installing 'build-aux/compile'
configure.ac:15: installing 'build-aux/config.guess'
configure.ac:15: installing 'build-aux/config.sub'
configure.ac:25: installing 'build-aux/install-sh'
configure.ac:25: installing 'build-aux/missing'
Makefile.am:5: warning: user variable 'GZIP_ENV' defined here ...
/usr/share/automake-1.15/am/distdir.am: ... overrides Automake variable 'GZIP_ENV' defined here
Makefile.am:58: warning: user target 'distcleancheck' defined here ...
/usr/share/automake-1.15/am/distdir.am: ... overrides Automake target 'distcleancheck' defined here
src/Makefile.am: installing 'build-aux/depcomp'
src/Makefile.am:542: warning: user target '.mm.o' defined here ...
/usr/share/automake-1.15/am/depend2.am: ... overrides Automake target '.mm.o' defined here
parallel-tests: installing 'build-aux/test-driver'

./configure
--------------
checking how to run the C preprocessor... gcc -E
checking for gcc option to accept ISO C89... (cached) none needed
checking if gcc supports -std=c89 -pedantic -Wall -Wextra -Wcast-align -Wnested-externs -Wshadow -Wstrict-prototypes -Wno-unused-function -Wno-long-long -Wno-overlength-strings... yes
checking if gcc supports -fvisibility=hidden... yes
checking for __int128... yes
checking for __builtin_expect... yes
checking for x86_64 assembly availability... yes
checking for CRYPTO... yes
checking for main in -lcrypto... yes
checking for EC functions in libcrypto... yes
checking whether byte ordering is bigendian... no
configure: Using assembly optimizations: x86_64
configure: Using field implementation: 64bit
configure: Using bignum implementation: no
configure: Using scalar implementation: 64bit
configure: Using endomorphism optimizations: no
configure: Building ECDH module: no
configure: Building Schnorr signatures module: no
configure: Building ECDSA pubkey recovery module: yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libsecp256k1.pc
config.status: creating src/libsecp256k1-config.h
config.status: executing depfiles commands
config.status: executing libtool commands
Fixing libtool for -rpath problems.

i'm using ubuntu 16.04 and also tried with Debian 9.3 getting same error.

**Comment by nmarley** [comment]
I [don't think this is an error](https://bitcoin.stackexchange.com/questions/37816/fixing-libtool-for-rpath-problems)... what happens if you `make` the project?

**Comment by 26rahulsingh** [comment]
When I try to compile the code after running ./autogen.sh I got this issue I also try with Debian and Mac got the same issue. I follow the documentation properly, I also configured Berkeley DB but I don’t know why I’m getting this issue. I tried everything I can if you can help me with this that will be great for me.
Looking forward to hearing from you.

Regards
Rahul Singh

Sent from my iPhone

On 13-Mar-2018, at 12:29 PM, Nathan Marley <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't think this is an error<https://bitcoin.stackexchange.com/questions/37816/fixing-libtool-for-rpath-problems>... what happens if you make the project?

**Comment by 26rahulsingh** [comment]
If I make the project then I got different error
“make: *** [all-recursive] Error 1”.

Regards
Rahul Singh

Sent from my iPhone

On 13-Mar-2018, at 12:29 PM, Nathan Marley <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't think this is an error<https://bitcoin.stackexchange.com/questions/37816/fixing-libtool-for-rpath-problems>... what happens if you make the project?

**Comment by nmarley** [comment]
Hi Rahul,

What is the full output from `make`? This error doesn't give enough context to be able to know what's happening. The configure output is expected and does not indicate any errors.

**Comment by 26rahulsingh** [comment]
Hi Nathan

This is the error I got

'libbitcoin_server_a-rpcmining.o' failed
make[2]: *** [libbitcoin_server_a-rpcmining.o] Error 1
make[2]: Leaving directory '/home/d/src3/dash/src'
Makefile:9045: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/d/src3/dash/src'
Makefile:652: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

Regards
Rahul Singh

Sent from my iPhone

On 13-Mar-2018, at 10:43 PM, Nathan Marley <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Rahul,

What is the full output from make? This error doesn't give enough context to be able to know what's happening. The configure output is expected and does not indicate any errors.

**Comment by nmarley** [comment]
Hmm... ok, still not seeing enough output. Which branch are you building on, and have you made any local changes to the code?

**Comment by 26rahulsingh** [comment]
I’m building with master branch and did not made any changes to code.

On 13-Mar-2018, at 11:11 PM, Nathan Marley <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmm... ok, still not seeing enough output. Which branch are you building on, and have you made any local changes to the code?

**Comment by nmarley** [comment]
Can you try again completely using the `develop` branch? (Probably requires another `autogen.sh` and `configure` before building).

**Comment by 26rahulsingh** [comment]
Hi, Nmarley

i'm trying to create a genesis block, I have changed the CScript and pszTimestamp but not able to create my own genesis block. I googled a lot but did not get any help related to new bitcoin core version 0.16.0. If you can help me with this that will be really helpful for me.

Thanks

**Comment by nmarley** [comment]
I'm sorry, I don't think I will be able to help with that. Were you able to build the `develop` branch?

**Comment by nmarley** [comment]
Closing as the original issue reported isn't an error message, just the output of `configure` script.
