### ISSUE TITLE
Encrypted twice

### ISSUE THREAD

**Issue by plutomm16** [dashpay/dash#2013]
Although this should be impossible, I think I encrypted the same wallet twice. I updated to a new wallet version. While waiting for my coins to show up, I encrypted. Then my coins (that were already encrypted) showed up. (I assume at the same exact time that I was encrypting)  Therefore, it was encrypted twice and I am subsequently locked out. My original encryption no longer works since this "double encryption" happened. 

Info: I used the same encryption password the whole time. I did not choose a new one. Just simply encrypted again. 

Is there something in place that makes the system change the password entirely when this happens? Or the system doesn't know how to respond when this happens? Any suggestions on what may unlock the wallet at this point?

**Comment by nmarley** [comment]
Hi,

I don't believe that's how it works -- the entire wallet is encrypted, not individual "coins". If you updated to a new software version, the software should have still recognized that your wallet was already encrypted and not allowed you to encrypt again.

Can you confirm you were using the Dash-Qt wallet, or was it another wallet?

**Comment by plutomm16** [comment]
I think that is the problem. Because it did let me even though it probably
shouldn’t have. I must have entered an encryption (even though it was the
same one) while it was syncing and before the coins showed up. Then once
they appeared, it was “double” encrypted. It was all in a matter for a
minute or less I’d say.

**Comment by nmarley** [comment]
> I must have entered an encryption (even though it was the same one) while it was syncing and before the coins showed up
I'm not sure if that's possible but can't rule it out, as I'm not as familiar with the Qt wallet portion of the software.

My recommendation at this point is to locate your previous backups of `wallet.dat` and restore using that. Make sure you have everything backed up so that at any step you're not over-writing something that you can't get back.

**Comment by plutomm16** [comment]
It is the qt wallet. And unfortunately, I am new to this one so, so far I
only had one backup. It shows zero coins. That’s why I want to ask the
techs if they can help with this.

**Comment by nmarley** [comment]
Do you have any auto-generated backups in your "backup" folder?

**Comment by plutomm16** [comment]
I do, however, when i open them they either show a balance of zero coins
(the first backups before the encryption) or they are encrypted and I can
not open them.

**Comment by PaulieD** [comment]
I would verify that the coins were not moved from the addresses you think they should have been in. Possible an attacker gained access to your wallet.dat

**Comment by PastaPastaPasta** [comment]
At this point, I think we should close this issue, since it's been two years w/o response
