### ISSUE TITLE
Multiwallet support

### ISSUE THREAD

**Issue by kryvel** [dashpay/dash#2015]
Hello,
Does have Dashcoin support of multiwallet feature, that allows running with multiple -wallet options to load more than one wallet?
Same as in Bitcoin. [#8694](https://github.com/bitcoin/bitcoin/pull/8694)
Thanks in advance

**Comment by nmarley** [comment]
Hi,

As this is a Bitcoin 0.15 feature, I believe this is a backport slated for the next maintenance release, but @codablock would know better than me.

**Comment by kryvel** [comment]
Hi, I reopening this, because this is really needed feature. I hope not only for me
@codablock Could you please comment on this ? 
TIA

**Comment by kryvel** [comment]
Hi, @codablock
Could you please comment on this ?
Is this possible to backport multiwallet support to dashpay ?

**Comment by codablock** [comment]
It is possible, yes, but has no priority atm. We're all drowning in Evo related stuff ;)

**Comment by thephez** [comment]
@kryvel bitcoin/bitcoin#8694 was backported into the develop branch a few weeks ago by https://github.com/dashpay/dash/pull/3022 for release in the 14.1 release

**Comment by PastaPastaPasta** [comment]
The specific PR to be backported requested by @kryvel was released in v0.15.0.0 As such this issue is resolved
