### ISSUE TITLE
Is the code risky or not comprehensive enough?

### ISSUE THREAD

**Issue by luomijie** [dashpay/dash#2019]
In the GetNextMasternodeInQueueForPayment method, the Hash value of the first 100 blocks of the current block is Height, so that I can easily know the next winning Masternode object. Is it not enough for me to understand?
if(!GetBlockHash(blockHash, nBlockHeight - 101)) {}
Why do write like this?

**Comment by nmarley** [comment]
Hi, I'm not sure I fully understand your question. Can you please elaborate a bit more? What part of the code is confusing you?

**Comment by nmarley** [comment]
Closing as the question wasn't clear to me and I haven't gotten clarification since a few months ago.
