### ISSUE TITLE
error when mining and I seem to be stuck at a certain block

### ISSUE THREAD

**Issue by msc82** [dashpay/dash#2024]
Working with a Dash Fork, I’ve received the following error when mining and I seem to be stuck at a certain block.
When I pull info I’m getting an extremely high diff, but more concerning is the negative hashrate. 
Only chainparams have been modified – has anyone ever experienced an issue like this before?

getblocktemplate
error: {"code":-10,"message":"xxx is downloading blocks..."}
getmininginfo
{
    "blocks" : 88760,
    "currentblocksize" : 0,
    "currentblocktx" : 0,
    "difficulty" : 2246627940917608376140868048638038491047607210810940943340685754368.00000000,
    "errors" : "",
    "genproclimit" : -1,
    "networkhashps" : -9223372036854775808,
    "pooledtx" : 0,
    "testnet" : false,
    "chain" : "main",
    "generate" : false,
    "hashespersec" : 0
}
I can't mine past this point.

Thank you!

**Comment by nmarley** [comment]
Hi there,

Without more info I'm not sure how we can help, esp. since this is a fork and unsure of what code you've changed. Closing for now. If you have more info, please paste it in here and we can re-open if necessary.
