### ISSUE TITLE
regtest mode for macOS doesn't work as expected. 

### ISSUE THREAD

**Issue by thenakulchawla** [dashpay/dash#2053]
I have been trying to generate blocks using the regtest mode, 

`dashd -regtest -daemon`
`dash-cli -regtest generate 1`

I keep getting the error:

`error code: -12
error message:
Error: Keypool ran out, please call keypoolrefill first`

Unable to resolve this. All documentation online talks about -testnet, nothing to look for -regtest.
Please help.

**Comment by UdjinM6** [comment]
You probably use encrypted wallet.dat and used all addresses from keypool already. Either unlock your wallet via `walletpassphrase` rpc to let wallet generate new address for you or use `generatetoaddress` rpc to mine to a specific address.

**Comment by nakulchawla09** [comment]
Nothing that I do works, even in linux. Here is a screenshot.
<img width="825" alt="screen shot 2018-05-02 at 7 42 12 pm" src="https://user-images.githubusercontent.com/9155403/39558124-fc229604-4e40-11e8-975e-a7e09b22ea0a.png">

**Comment by thephez** [comment]
@nakulchawla09 I know this is a basic question, but is your dashd running with the `disablewallet` option? That would disable any wallet-related RPC calls. Also, when I do that, I get the exact error code you do (-32601).

FYI - `walletinfo` is not a valid RPC - try `getwalletinfo`. You can see the full list [here](https://dash-docs.github.io/en/developer-reference#rpc-summary-table).
