### ISSUE TITLE
consider increasing default privatesend rounds to 4

### ISSUE THREAD

**Issue by taw00** [dashpay/dash#2055]
This is more of a question and if I am correct in my assumptions, it then becomes a request.

2 rounds of PrivateSend is a bit light. Granted, it's still pretty darn solid, but I was thinking that perhaps bumping the default to something like 4 rounds might encourage better practice and quell concerns about certain attack vectors. Granted the user experience for mixing is not the greatest as is, but given the trajectory of evolution, it looks like there will be more participants adding to the PS entropy pool. Even MyDashWallet.org is mixing now.

Also, should 1 round be even available outside of testnet?

And if strophy is paying attention, we need to make sure that PrivateSend Best Practice documentation stays current. This is pretty good... Keep up the good work.
https://docs.dash.org/en/latest/wallets/dashcore/privatesend-instantsend.html#dashcore-privatesend-instantsend

**Comment by PaulieD** [comment]
Commit https://github.com/dashpay/dash/commit/5f4e0ba86e70c1e4b256a074cfde03bb7b682748 does this if we want to merge it.

**Comment by strophy** [comment]
Documentation updated - thanks @taw00

**Comment by UdjinM6** [comment]
fixed by 2128
