### ISSUE TITLE
[Bug] Mixed Inputs only show round count up to the current round limiter

### ISSUE THREAD

**Issue by PaulieD** [dashpay/dash#2068]
Even if an input has 10 rounds of mixing, if your PrivateSend config has the max at 8, it will show up as 8 rounds not 10 rounds. However, this appears to be a display bug, since if you change your max to 4, it will say that input has 4 rounds, then if you change the max back to 8 rounds, it will show 8 rounds again.

**Comment by UdjinM6** [comment]
fixed by 2137
