### ISSUE TITLE
 Make Deploy Cross Compile Not finding Frameworks/Plugins

### ISSUE THREAD

**Issue by 2a5A1Ghu1** [dashpay/dash#2076]
make deploy during cross compile for darwin in ubuntu 14 can not find frameworks or plugins to package in Dash-Qt.app

Error:

+ Removing old dist folder +
+ Copying source bundle +
+ Deploying frameworks +
Warning: Could not find any external frameworks to deploy in dist/Dash-Qt.app.
Warning: Could not detect Qt's path, skipping plugin deployment!
+ Installing qt.conf +
+ Adding Qt translations +
+ Done +

**Comment by PastaPastaPasta** [comment]
Closing as this has seen no updates in 2 years. Please reopen this issue if it's still a problem
