### ISSUE TITLE
'estimatefee 2' testnet returning -1

### ISSUE THREAD

**Issue by knoxcard** [dashpay/dash#2077]
`estimatefee 2 `

testnet returning -1
block count on dev: 125589

My live node works fine.

**Comment by thephez** [comment]
Was your testnet node recently started? Per the help description:
>A negative value is returned if not enough transactions and blocks
have been observed to make an estimate.

**Comment by knoxcard** [comment]
Yup Blockchain download finished just yesterday.  
This is what I figure as I provided my block count tally on dev: 125589

Thanks for your input, I a going to close this isse
