### ISSUE TITLE
help instantsendtoaddress. "btc" mentioned

### ISSUE THREAD

**Issue by Antti-Kaikkonen** [dashpay/dash#2117]
the output of `help instantsendtoaddress` contains the following text:

> Arguments:
> 1. "dashaddress"  (string, required) The dash address to send to.
> 2. "amount"      (numeric, required) The amount in **btc** to send. eg 0.1

btc should be changed to Dash or DASH.

**Comment by UdjinM6** [comment]
This was already fixed in `develop`: https://github.com/dashpay/dash/blob/develop/src/wallet/rpcwallet.cpp#L459
