### ISSUE TITLE
[Bug] Testnet - Windows 10 - Not updating confirmations

### ISSUE THREAD

**Issue by knoxcard** [dashpay/dash#2119]
- [x] Operating System: Windows 10
- [x] Dash Core Version: v0.12.2.3 (64-bit)

For some reason when I execute gettransaction from the testnet command line console, I keep getting confirmations as 0.  This is wrong as I can verify the number of successful confirmations on sites such as chain.so.  This data needs to be updated and fed to my app in real time. On production I use the Linux version, so testnet is off.  I am hoping it works there, but I am launching my app so I am not sure, need Testnet to work exactly the same to build perfect software.  

**[Chain.so]**
https://chain.so/tx/DASHTEST/6da645c5561539488e4a61743346d3b30847c7fb0f24916328eb6cb29f8280e3
confirmations: 43 (confirmed)

**[My Windows Dash Wallet - Console Window]**
gettransaction 6da645c5561539488e4a61743346d3b30847c7fb0f24916328eb6cb29f8280e3
confirmations: 0

**[Dash.conf File]**
testnet=1
server=1
reindex=1
walletnotify=curl http://www.****.io/transactions/add/dash/%s
rpcuser=****
rpcpassword=****
rpcport=8050

**Comment by thephez** [comment]
Dash Core v0.12.3 is being tested on Testnet currently so I would suggest updating to it for maximum compatibility ([RC3 here](https://github.com/dashpay/dash/releases)).  Is your client fully synced up to the current block?  There are quite a few older clients on Testnet which are not up to date so if you are connected to one of them, you will be out of sync with the longest chain.

**Comment by knoxcard** [comment]
I am fully synced and on the latest RC3.  How do I only connect to clients who have the latest clients?

**Comment by thephez** [comment]
If `gettransaction` still does not work, what block number does `getinfo` report and does `getchaintips` report any invalid blocks?  Also, you may want to try jumping on the [Dash Discord](https://discord.gg/9z8zX5j) #development-lab or #testnet-lab channels for assistance/info.

Re: client connections:
If you're using the GUI, go to the [Peers tab](https://docs.dash.org/en/latest/wallets/dashcore/interface.html#peers-tab) of the Tools window. You can right-click on a node to disconnect from it or ban it for a period of time. Alternately, you can use [`disconnectnode <ip:port>`](https://dash-docs.github.io/en/developer-reference#disconnectnode) from the CLI or the GUI console.

The first peer in the list is the one that it tries to sync with on startup, so make sure it is a 12.3 one for best results.

**Comment by knoxcard** [comment]
Is there a major difference between the Windows and Linux version.  I am installing the Linux version on my Windows machine using bash.  I have a feeling that Linux is considerably more developed than Windows.  Am I correct with this assumption?

**Comment by Antti-Kaikkonen** [comment]
I tested using testnet with the linux version and the number of confirmations is displayed correctly for me.

I think the same code is build to all of the platforms. But maybe most of the testing is done in Linux so windows errors might be harder to catch. I recommend trying getinfo and the other commands suggested by thepez to verify that your client is synced with the correct chain.

**Comment by knoxcard** [comment]
I can tell you right now the Linux version is much faster at downloading the blockchain!  Also, on the Windows version I was forced to use reindex=1 just to complete the download of the chain.  I also have Bitcoin Cash and Litecoin cores running in my Windows environment.  Dash was the only one not updating confirmations correctly using Windows.

Porting over Bitcoin Cash to my bash Linux setup, then Litecoin.  I will test Dash after Bitcoin cash has synced up and let you know how it goes.

**Comment by UdjinM6** [comment]
@knoxcard There are a lot of old nodes currently that stuck on some older blocks, you might have connected to them. What block are you on? What `getchaintips 3` rpc shows you?

**Comment by knoxcard** [comment]
Everything is working with the Linux version running under Windows 10 Bash Developer Console.  This is wonderful.  I converted my other Windows full nodes Litecoin and Bitcoin Cash as well.  Everything is working much better!

**Comment by knoxcard** [comment]
Any closing comments in regards to this?  I am about to close the ticket at the end of the day.

**Comment by knoxcard** [comment]
I want to expound more on this issue...

II failed to mention that on my Testnet local environment, I am sending DASH to myself.
Test tokens never leave my wallet.
Maybe that's why confirmations show a zero count?

Even with the Linux version, I previousy stated that everything was okay.
Recently, I've noticed that isn't necessarily the case.
DASH testnet block explorers show the correct confirmation count on these internal transfers.  Strange...

My workaround was to simply create a failsafe patch in my DEV branch.
Here is the code as it might eventually help someone else.

(NodeJS)
