### ISSUE TITLE
Failed Dash Transactions still show up in the transaction list.

### ISSUE THREAD

**Issue by PastaPastaPasta** [dashpay/dash#2123]
During testing, on main-net, on 12.2.3, sending a transaction every ~30 seconds, a few transactions failed but still showed up in the transaction list in Dash-QT. The tx says it "has not been successfully broadcast yet". Below is a picture of such and the debug.log region which is relevant.
![failed tx](https://user-images.githubusercontent.com/6443210/41494975-6c18acbe-70e2-11e8-9ecd-f9d8ba817df9.PNG)
[debug.txt](https://github.com/dashpay/dash/files/2107812/debug.txt)

**Comment by PaulieD** [comment]
It appears that these transactions broadcast after a wallet restart.

**Comment by PaulieD** [comment]
Hmm, some of these transactions did not broadcast, but show as in mempool... They go through when I manually broadcast the raw tx

**Comment by PaulieD** [comment]
Sending txs as fast as possible through rpc, everything was perfect until 35 txs in, then fine till 50 in, where 3 txs failed close to each other. Then everything was fine until around 80 txs in, at that point all (next 15 or so) of the transactions errored out. I stopped the test at this point.

It might be important to realize that no blocks have happened during this test, so they were all unconfirmed through the test.

**Comment by thephez** [comment]
>It appears to me that this happens once there are a large amount of txs which are unconfirmed... Looking more into that realm of it now

Not sure if what you seeing could be related, but it reminded me a little of this issue that occurs when there are too many chained txs:
[https://www.dash.org/forum/threads/tech-issue-with-wallet-doing-1500-transactions-per-day.26172/#post-177229](https://www.dash.org/forum/threads/tech-issue-with-wallet-doing-1500-transactions-per-day.26172/#post-177229)
