### ISSUE TITLE
Dash-CLI sendtoaddress command implementation has bug(s) in edge case.

### ISSUE THREAD

**Issue by PastaPastaPasta** [dashpay/dash#2127]
The transaction that shows the bug is [here.](https://live.blockcypher.com/dash/tx/8a0945afdb6ac550d2ec6a94341c27db701f1e231075cb7b85d5c38aaad043fa/) This transaction was generated using the command `sendtoaddress XbRJQrYCv9ef8HRL93s2iksGtdMFeTjU7F 0.0001 "" "" true false false` 

As you can see, the 546 duff input and output are not necessary and only result in a higher size and therefor fee. An important factor to recognize here is that 546 duffs is the dust threshold. Although I have been unable to look at the code to see what may be causing this, it seems to me that on the input side, dash core finds a set of inputs which are greater than or equal to the send amount. It then has a change output (which has to be at least 546 duffs (since that's the duff threshold) ) and the remaining as the send part.

**Comment by PaulieD** [comment]
Another odd edge case: 
https://live.blockcypher.com/dash/tx/6835c177eac776b5eea48aa91c3bc17fdebbee497953529fcc42421dd55f9b2e/
Command: `sendtoaddress XbRJQrYCv9ef8HRL93s2iksGtdMFeTjU7F 0.0001 "" "" false false false`

It seems to combine all those inputs, but there is no reason for it to do so, and resulted in a huge tx, and larger than expected fee.
