### ISSUE TITLE
test network local node synchronization to 151216 suddenly stopped, but the test network is now 160127	

### ISSUE THREAD

**Issue by guchenglin111** [dashpay/dash#2172]
test network local node synchronization to 151216 suddenly stopped, but the test network is now 160127

**Comment by strophy** [comment]
Please make sure you are running the latest version of Dash. Dash 0.12.2 cannot sync past a certain blockheight because the changed consensus rules brought in with the network upgrade in Dash 0.12.3 do not appear valid to it.

**Comment by guchenglin111** [comment]
Thank you. Your answer is very helpful

**Comment by PaulieD** [comment]
@guchenglin111 does that mean your problem is resolved? If that is the case, you can close this issue :)
