### ISSUE TITLE
Request that signed releases have published gpg key

### ISSUE THREAD

**Issue by kleetus** [dashpay/dash#2186]
I am attempting to import Alexander's (UdjinM6) gpg key in order to check the signature of the latest release. I have the fingerprint, of course, but I don't see the key published anywhere (such as PGP Global Directory, SKS Keyservers, MIT PGP server, etc.). I see there was a question on #809 pointing to where Holger has his keys, but I don't see one for Alexander. It would be great to publish this key in one of the key servers. When and if I meet up with you guys, I am happy to sign it.

**Comment by thephez** [comment]
You can find it on Keybase.io - https://keybase.io/udjinm6. Most, if not all, of the developers should be able to be found there.

**Comment by nmarley** [comment]
Also -- I'd like to note that UdjinM6 and Alex are different people, it seems like that might be a point of confusion from the wording of your issue description.

**Comment by nmarley** [comment]
To expound further, keys for Dash Core developers are actually in the repo here: https://github.com/dashpay/dash/tree/master/contrib/gitian-keys

Those filenames can also be used to search the identities on keybase.io as @thephez has suggested. I'm not sure if there's an actual need or requirement for having keys uploaded to a PGP server, but it looks like about 1/2 the development team has keys published with (e.g.) pgp.mit.edu or keys.gnupg.net.

@kleetus Does this help with your concern?

**Comment by schinzelh** [comment]
What thephez writes: All our members have their gpg keys published on keybase.io and linked from https://www.dash.org/team/

e.g. Alexander (aka codablock) --> https://keybase.io/codablock

**Comment by kleetus** [comment]
thanks, I forgot about checking keybase.io. I also got a bit confused over codablock's signature and UdjinM6 actual release.
