### ISSUE TITLE
testnet address inst valid

### ISSUE THREAD

**Issue by kiahmed** [dashpay/dash#2187]
tried to get some testcoin to the following address which I got from the api call getaccountaddress default
but all faucets errors saying invalid address ..what can I do?
yedNNmaWuUqRHdwW1f6fbm5ADJbwoc57cy

**Comment by UdjinM6** [comment]
Looks completely legit to me:
```
validateaddress yedNNmaWuUqRHdwW1f6fbm5ADJbwoc57cy
{
  "isvalid": true,
  "address": "yedNNmaWuUqRHdwW1f6fbm5ADJbwoc57cy",
  "scriptPubKey": "76a914c8d6047e56f7283dbe57bc80fafcbfb30d27d04288ac",
  "ismine": false,
  "iswatchonly": false,
  "isscript": false
}
```
Also explorers recognise it just fine: https://test.insight.dash.siampm.com/address/yedNNmaWuUqRHdwW1f6fbm5ADJbwoc57cy
(this address has 1K+ tDASH in it btw)

**Comment by kiahmed** [comment]
hmm..that tells me even tho the faucet sent it still threw error saying invalid address. Anyway, but then for following request why it balance shows null?
{
  "jsonrpc": "2.0",
  "method": "getaccountaddress",
  "params": ["default"],
  "id": 1
}

{
    "result": "yedNNmaWuUqRHdwW1f6fbm5ADJbwoc57cy",
    "error": null,
    "id": 1
}

**Comment by UdjinM6** [comment]
Not sure what you mean tbh... This method only returns you the address, it has nothing to do with the balance.

**Comment by kiahmed** [comment]
oh sorry..I had posted the wrong json. i ran this still the same result
{
  "jsonrpc": "2.0",
  "method": "getbalance",
  "params": ["default"],
  "id": 1
}
{
    "result": 0,
    "error": null,
    "id": 1
}

**Comment by UdjinM6** [comment]
Hmmm... Are you using the latest version (from 0.12.3.x or develop branch)? Is you node fully synced?

**Comment by kiahmed** [comment]
hmm.it used to be fully synced..i restarted other day now see stuck at 151223. If I upgrade would it reindex or can continue from there?

{
    "result": {
        "version": 120203,
        "protocolversion": 70208,
        "walletversion": 61000,
        "balance": 0,
        "privatesend_balance": 0,
        "blocks": 151223,
        "timeoffset": 0,
        "connections": 8,
        "proxy": "",
        "difficulty": 3.438605567000294,
        "testnet": true,
        "keypoololdest": 1521362416,
        "keypoolsize": 999,
        "paytxfee": 0,
        "relayfee": 0.00001,
        "errors": ""
    },
    "error": null,
    "id": 1
}

**Comment by kiahmed** [comment]
where do i run the command ? Now I am in even bigger trouble I get this even without adding the reconsiderblock option , hope I dont have resync everything 
 exec user process caused "exec format error"

**Comment by thephez** [comment]
You would run that command via `dash-cli` (or the Tools->Console window in Dash-QT if you are using the GUI) the same way you ran `getbalance`.

**Comment by kiahmed** [comment]
well, its in a container . my docker run command didnt change...all I did just upgraded to newer dash image and it starts dashd on run here is the run command 
docker run -it -d \
    --name dash-test-node \
    --restart always \
    -p 19999:19999 \
    -p 19998:19998 \
    -v $PWD/dash:/root/.dashcore \
    dash-testnet \
    -testnet \
    -server \
    -rpcallowip=::/0 \
    -rpcuser=xxxxx \
    -rpcpassword=xxxxxxx \
    -externalip=xxxxxxxxxxxx:19999 \
    -printtoconsole \
    -masternode=0

**Comment by thephez** [comment]
Do any of the RPC commands work? `getinfo` for instance? If any one of them works, they all should - unless the upgrade did not work (`reconsiderblock` was just added in 12.3).

**Comment by kiahmed** [comment]
finally got it to work..without reconsiderblock just ran clearbanned also deleted mncache.dat
