### ISSUE TITLE
v0.11.2.x Release announcement note

### ISSUE THREAD

**Issue by UdjinM6** [dashpay/dash#220]
Just had a though looking at all different test wallets I have and their names....
We need to make BIG RED LETTER NOTE:
IF YOU HAVE WALLET NAMED MASTERNODES.DAT RENAME IT BEFORE UPGRADING TO V0.11.2.x OR YOU WILL LOSE YOUR COINS

**Comment by vertoe** [comment]
+ plus detailled explaination why.

**Comment by UdjinM6** [comment]
Sure, but I think not too much detailed, smth like "Wallet will now save additional information about known masternodes to masternode.dat file" should be enough.

**Comment by vertoe** [comment]
this is an important ticket.

i'd like to add:
+ release notes and explainations about bip66 (miner votes)

bitcoin is currently going through a soft fork on bip66. darkcoin introduces this feature in v0.11.2.0, too.
here is a bitcoin graphic: http://bitcoin.sipa.be/ver-ever.png
discussion on bct: https://bitcointalk.org/index.php?topic=958036.0

**Comment by UdjinM6** [comment]
masternodes.dat issue should be solved by https://github.com/darkcoin/darkcoin/pull/225 now

**Comment by vertoe** [comment]
@UdjinM6 #230
