### ISSUE TITLE
estimatesmartfee return -1

### ISSUE THREAD

**Issue by crossle** [dashpay/dash#2207]
1. run ./dashd, already sync all blocks
2.  
$ ./dash-cli estimatesmartfee 2

{
  "feerate": -1,
  "blocks": 25
}

feerate return -1

**Comment by PastaPastaPasta** [comment]
Yeah, GUI too looks like smartfee implementation is flawed or purposefully held back. Electrum has it, no reason why the core wallet shouldn't, even though it will always be the minimum fee basically or a duff or 2 higher then that

**Comment by crossle** [comment]
Any other RPC function can get the fee?

**Comment by UdjinM6** [comment]
You have to keep node running 20-ish blocks to fill stats first before using fee estimation commands. In reality, you can simply use hardcoded fee instead - Dash's blocks have plenty of space (for now) and estimation isn't really needed.

**Comment by crossle** [comment]
Keep it run few days, worked now
