### ISSUE TITLE
question

### ISSUE THREAD

**Issue by eMosbat** [dashpay/dash#2222]
what is sporkaddress?

> strSporkAddress = "Xgtyuk76vhuFW2iT7UAiHgNdWXCf3J34wh";

and how can I generate sporkaddresses to use with `-sporkaddr=` ?

**Comment by PastaPastaPasta** [comment]
The sporkaddress is currently held by core. A message signed by the spork address can change a spork, sporks control a few non-critical things designed to prevent unintentional network forks. You can look at the current sporks [here](http://178.254.23.111/~pub/Dash/Dash_Info.html). If you have any questions about what each spork does I can try and clarify.

There are plans in the future to decentralize the control of sporks, however that has not been implemented yet.

**Comment by strophy** [comment]
Sporks are described in the docs:

- https://docs.dash.org/en/latest/introduction/features.html#sporks
- https://docs.dash.org/en/latest/developers/index.html#understanding-sporks

**Comment by nmarley** [comment]
Hi, I'll go ahead and close this since I believe it's been answered adequately.
