### ISSUE TITLE
Spork deactivation inconsistency

### ISSUE THREAD

**Issue by AngeGallego** [dashpay/dash#2263]
#### If so, please list the steps to reproduce below:
1. Activate a Spork
2. Deactivate it
3. List active sporks

### Expected behaviour
`spork show` should display a spork value of `-1`
`spork active` should display `false`

### Actual behaviour
`spork show` displays a spork value of `-1`
`spork active` displays `true`

### What version of Dash Core are you using?
`dash-0.12.3.2`

### Machine specs:
- OS: ubuntu17
- CPU: intel i7
- RAM: 16gb
- Disk size: 500gb
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
The problem seems to be that `mapSporksActive` will still have the spork into it even if deactivated, causing the check `mapSporksActive.count(nSporkID)` to return true and then `return r < GetAdjustedTime()` will return `true` even with the value `-1`

**Comment by UdjinM6** [comment]
`spork active` only makes sense for a time-based sporks by design. If you want to deactivate such a spork you must set its value to some timestamp in the future e.g. 3000000000.
