### ISSUE TITLE
Let's rename masternode privkey to pairingkey

### ISSUE THREAD

**Issue by Technologov** [dashpay/dash#2265]
hi all !

One of Dash forks (Dynamic, DYN), uses the term dynode pairingkey, which reflects it's purpose much better than privkey.

privkey term is ambiguous, because it can refer to masternode privkey (pairing key) or to callateral private key (1000 DASH).

dynamic.conf:
dynode=1
dynodepairingkey=5...

Not functional change.

**Comment by nmarley** [comment]
Thanks for the idea! This old term is going away in 12.4 with the split into Operator and Voting keys. See [DIP 3](https://github.com/dashpay/dips/blob/master/dip-0003.md#registering-a-masternode-proregtx) for more info.

**Comment by nmarley** [comment]
The new key names were actually implemented in this PR from a few days ago: https://github.com/dashpay/dash/pull/2248

I'll go ahead and close this, and feel free to add more info if your concern wasn't addressed.
