### ISSUE TITLE
How Budgeting System Technically Works?

### ISSUE THREAD

**Issue by aigon1989** [dashpay/dash#2269]
Hello,

This is not really an issue but a request of information about how Dash budgeting system works.

I am studying the code and reading the documentation but I think I don't really get it.

I don't see any place on the rewards generation where it reserves a 10% of the block value each block or how it rewards the proposals each month.

I guess that it validates if a proposal could be applied and voted in case the monthly reward asked by the proposal submitter is less than a 10% of the block value for each guessed payment and then for each generated block it checks which proposals has more than a 10% yes and also are scheduled to have a reward and then checks which proposals can be paid with the 10% block value of the current generated block and if not, it reeschedules the least popular proposals that can't be rewarded on the current block to be rewarded on the next closest one but that implies that alive proposals are limited by block value.

Also, where the rewards are paid from? 
I mean, I can't see in any place that a 10% of each block value paid to a masternode is being reserved to pay the proposals monthly and also I don't see from whom the budget rewards are substracted from. 

Is it substracted by the generation of each block rewarding a 90% to MN (45%) and Miners (45%) and considering that the sum of the remaining 10% is paid monthly to the proposals?

And what if the proposals payment ammount is less than the 10% of the monthly reward, does it accumulate somewhere or those new Dash are not minted?

Thank you all.

**Comment by thephez** [comment]
The 10% is [withheld from the block reward](https://github.com/dashpay/dash/blob/master/src/validation.cpp#L1328). Proposals are paid out in "superblocks" ([example](https://explorer.dash.org/block/000000000014702a849cddf3145c495086ef5235b8e1a08fbea8e9c17c7d149b) - note the amount in the coinbase tx) based on proposal voting. The 10% withheld for proposals does not accumulate anywhere and simply does not get created if there are not enough passing proposals to use it.

Hope this helps. For other questions like this I would recommend going to the [forum](https://www.dash.org/forum/) or [discord](https://discord.gg/9z8zX5j).
