### ISSUE TITLE
Unable to complete IBD

### ISSUE THREAD

**Issue by rex4539** [dashpay/dash#2273]
Steps:
Start app.

What happened:
IBD gets stuck and never resumes.

[debug.log.zip](https://github.com/dashpay/dash/files/2363570/debug.log.zip)

Expected result:
IBD completes.

**Comment by UdjinM6** [comment]
Thanks for reporting! I was able to reproduce the issue, pls see #2276 for a possible fix.

**Comment by rex4539** [comment]
Verified as fixed.
