### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by tchaton** [dashpay/dash#2282]
Hello here,

I have been using Dash to create my website, and I have found some ways to improve the user dev.
One outputs, several inputs -> We lose track of which one triggers the callback.
It will be great to have the ID of the triggered element.

I was also thinking it is a huge drawback to have only one outputs possible.
In JAVA,
def f(a)
and
def f(a, b) can both exists without issues because of the arguments inside.

It should be possible to have separated function with different inputs toward one output using arguments inputs as identifiers to know which function to trigger.

Best,
Thomas Chaton

**Comment by nmarley** [comment]
Hi Thomas,

Can you clarify a bit more what you're trying to do? From your description, I'm not certain this is the right project. Dash is a payments-focused cryptocurrency. Dash really can't create websites. Are you trying to do something with the currency or Dash network?

**Comment by tchaton** [comment]
ahahah sorry wrong dash project ahahah.
I was meaning the one from ploty. My bad.

**Comment by nmarley** [comment]
:) Thanks for the clarification!
