### ISSUE TITLE
question

### ISSUE THREAD

**Issue by crowdcoinChain** [dashpay/dash#2284]
how have the 
strSporkPubKey being converted to strSporkAddress
in chianparams?

**Comment by UdjinM6** [comment]
These are just regular pubkey/address, simply follow the process described there https://en.bitcoin.it/wiki/Technical_background_of_version_1_Bitcoin_addresses#How_to_create_Bitcoin_Address. There is also a tool that already has this process automated http://gobittest.appspot.com/Address (make sure to provide correct network bytes on step 4). Or you can apply the patch from #2054 and use `pubkeytoaddress` rpc instead.

**Comment by PastaPastaPasta** [comment]
Closable, question answered w/ no further discussion @UdjinM6

**Comment by Jetro-Costa** [comment]
Hello, what the variable strSporkAddress [At this line](https://github.com/dashpay/dash/blob/43d2973a0e89ac9435142d6379e664c0ec20b2a2/src/chainparams.cpp#L429)
