### ISSUE TITLE
darkcoind crashes when using non-standard ports

### ISSUE THREAD

**Issue by JanuaryLavender** [dashpay/dash#23]
To keep it short:

When you try to start a local masternode on a port different from [1]9999 darkcoind reports "CDarkSendPool::RegisterAsMasterNode() - Invalid port" in the debug log, but crashes right after.
When you try to start a remote masternode by running the "masternode start" command on your local darkcoind, the local darkcoind or darkcoin-qt show the same behavior. "CDarkSendPool::RegisterAsMasterNode() - Invalid port" is logged, but darkcoind crashes.

**Comment by jonathancross** [comment]
Has anyone confirmed if this is still an issue with `dashd` in 2016?
