### ISSUE TITLE
Possible wrong payee amounts

### ISSUE THREAD

**Issue by globaltoken** [dashpay/dash#2310]
Hello,

I noticed a small issue in the rewarding system of Masternodes.
The CAmount value is not rounded correctly, it is not much difference, but there is.

Let me show you an example:
https://insight.dash.org/insight/tx/2dcbfcbfa230b98804e4230dc72f6a77c2ce69bf639331f13a6844262f1b012a

This is the genesis tx, which have an output of 3.34606391 DASH.
Expected Masternode payee value is 50%: 1.673031955 DASH
actual paid value: 1.67303189 DASH

As i said, it is not a big difference, but this is not really the half of the blockreward.
I think this occurs, because there will be in some cases a floating value, that is not correctly converted into an uint64.

Cheers,
Pawel

**Comment by UdjinM6** [comment]
To reiterate: there is no overflow or anything, it just the way it's calculated. Closing.
