### ISSUE TITLE
windows installer is not signed

### ISSUE THREAD

**Issue by wallaceturner** [dashpay/dash#2322]
using dash 0.12.3.3
results in these images being displayed when installing, not a great experience for first timers
![image](https://user-images.githubusercontent.com/2849980/46048865-2c5a4480-c15e-11e8-8b20-d58fb15b4860.png)

![image](https://user-images.githubusercontent.com/2849980/46048854-1f3d5580-c15e-11e8-9bc6-c0c0acb7d636.png)

**Comment by strophy** [comment]
Same goes for macOS I believe - need to go to the settings and allow installation. This is documented ([Windows](https://docs.dash.org/en/latest/wallets/dashcore/installation-windows.html#running-the-dash-core-installer), [macOS](https://docs.dash.org/en/latest/wallets/dashcore/installation-macos.html#running-dash-core-for-the-first-time)) but it would be great to just sign the binary.

**Comment by PastaPastaPasta** [comment]
This might have been resolved in recent released as spearheaded by @nmarley

**Comment by strophy** [comment]
This was resolved in #3027

**Comment by nmarley** [comment]
Good catch, this can be closed.
