### ISSUE TITLE
travis ci multi architecture 

### ISSUE THREAD

**Issue by LucaPaterlini** [dashpay/dash#2337]
hello,
can you please share the Travis file used for the creation and upload 
of the mutli arc releases?

The actual travis only do the build and then discards it.
tk in advance

**Comment by nmarley** [comment]
Hi, the [.travis.yml](https://github.com/dashpay/dash/blob/develop/.travis.yml) file is included in the repo, but this is not used to build releases. This is done via Gitian, using the [process described here](https://github.com/dashpay/dash/blob/develop/doc/gitian-building.md).
