### ISSUE TITLE
failed build

### ISSUE THREAD

**Issue by LucaPaterlini** [dashpay/dash#2338]
hello,
I have tried to create a build with Travis of the Dash

https://travis-ci.org/LucaPaterlini/dash

It doesn't work, what does it mean?

**Comment by thephez** [comment]
It looks like your most [recent build](https://travis-ci.org/LucaPaterlini/dash/builds/442015495) was successful. Can this issue be closed?

**Comment by crowdcoinChain** [comment]
Yes it can be

**Comment by LucaPaterlini** [comment]
hello,
I have been able to compile it but now once I am opening it on windows after following the instructions for cross compiling(the only option available) then once I place it on windows and click on it do not starts.

**Comment by LucaPaterlini** [comment]
I have compiled and than copied the dash-qt file. What is the right
procedure instead?

**Comment by gladcow** [comment]
All windows dependencies should be installed before this dash-qt can be started. I think the simplest way to do this is to start windows setup exe (from this link,  for example: https://github.com/dashpay/dash/releases) before and copy new exe from travis over installed dash-qt.

**Comment by LucaPaterlini** [comment]
hello, 
what I am trying to do is to compile the wallet, I have installed all the dependencies mentioned in the guide.
if you have a chance to do so, please try to compile the win wallets and let me know if you get the same strange effect, as well is there any difference in the final result if you compile with qt4 or qt5 ? 

https://github.com/LucaPaterlini/dash/releases/tag/0.0.0.1

**Comment by gladcow** [comment]
I haven't Windows right now,  will test it in several hours

**Comment by crowdcoinChain** [comment]
Issue still not solved and I am curios why there is a lack of interest so far, no one else compile and everyone goes with the pre compiled version? (making useless the best open source feature)

**Comment by LucaPaterlini** [comment]
Issue still not solved and I am curios why there is a lack of interest so far, no one else compile and everyone goes with the pre compiled version? (making useless the best open source feature)

**Comment by LucaPaterlini** [comment]
from the master branch and I have followed those commands to reach the shown result
https://github.com/dashpay/dash/blob/develop/doc/build-cross.md
for win64

**Comment by LucaPaterlini** [comment]
I have just found out that I have not executed this line in the previous attempt,
$ sudo apt-get install nsis wine wine64 bc 
and now I am facing the fact that from what I have understood wine64 is no more available on public repo

https://askubuntu.com/questions/880832/wine-and-wine64

**Comment by gladcow** [comment]
Yes,  your file is not starting, I can't understand why (not dll dependencies,  I've checked it). It can be some QT incompatibility, your exe is 48 MB,  official is 34 MB,  so your one was built with other options. I have checked cross-build on my PC it gives the same exe like in official packet. I need some more time to debug this case.

**Comment by gladcow** [comment]
Try to build with this instructions (build depends first, then configure dashcore with path to depends folder) for develop branch. Is it working?

**Comment by LucaPaterlini** [comment]
sudo apt-get install nsis wine wine64 bcReading package lists... Done
Building dependency tree       
Reading state information... Done
Package wine64 is a virtual package provided by:
  winehq-staging 3.18.0~xenial
  winehq-stable 3.0.3~xenial
  winehq-devel 3.18.0~xenial
You should explicitly select one to install.

E: Package 'wine64' has no installation candidate

https://www.tecmint.com/install-wine-on-ubuntu-and-linux-mint/
this is what I have done following the ubuntu but still I get the mentioned error

**Comment by LucaPaterlini** [comment]
libtool: warning: remember to run 'libtool --finish /home/pater92/Desktop/dash/depends/x86_64-w64-mingw32/lib'
I have tried to continue avoiding to install the win64 package and during the depends make I got a wizard from wine asking to dowload itslef and a package fo coingeko or something like that.
then I got a warning
libtool: warning: remember to run 'libtool --finish /home/pater92/Desktop/dash/depends/x86_64-w64-mingw32/lib'

**Comment by gladcow** [comment]
So,  now you can't compile the sources?

**Comment by LucaPaterlini** [comment]
Still can't decently still having the intro slide transparent instead of white. And I have changes for 18.04 ubuntu OS. I have stopped Tring on 16.04

**Comment by oti-dev** [comment]
Hello, have you managed to solve the issue? I think I have the same one - dash-qt.exe process closes after 3 seconds without generating any logs, while dashd starts correctly.

**Comment by gladcow** [comment]
@oti-dev , is it self-built dash-qt? If yes, does dash-qt from [here](https://github.com/dashpay/dash/releases) is working?

**Comment by oti-dev** [comment]
Yes it is self-built, and yes, the downloaded version works. 

Actually I managed to get this to work with this configure invocation:
./configure "CXXFLAGS=-Og -g" "CFLAGS=-Og -g" --disable-hardening --disable-gcc-hardening --disable-linker-hardening --prefix=$HOME/build/win64/dash/depends/x86_64-w64-mingw32/

The obvious drawback is that the dash-qt file is 400MB. But after stripping the debug symbols it's back to 31MB, so I guess I'll work with it for now.

**Comment by nmarley** [comment]
Closing as this seems resolved now. Please be sure and use the depends system to build and re-open a new issue if necessary.
