### ISSUE TITLE
Doesn't this require 2 arguments

### ISSUE THREAD

**Issue by Duality-CDOO** [dashpay/dash#2340]
https://github.com/dashpay/dash/blob/eaef9020256400171ac7521df8819b0c832a0b73/src/wallet/wallet.cpp#L1519

nRounds is missing?

**Comment by UdjinM6** [comment]
The second one is optional https://github.com/dashpay/dash/blob/eaef9020256400171ac7521df8819b0c832a0b73/src/wallet/wallet.h#L824
