### ISSUE TITLE
[Develop] GetStatuses call in Overviewpage is a bit overloaded with information.

### ISSUE THREAD

**Issue by Duality-CDOO** [dashpay/dash#2345]
This, atm, is very overloaded in the UI and is far from user friendly - 
https://github.com/dashpay/dash/blob/develop/src/qt/overviewpage.cpp#L567

1. Build develop branch
2. Start mixing with PS
3. Watch the strings flow.

Maybe std::string.clear() or similar between each case in the GetStatuses() function in privatesend-client.cpp?

### Machine specs:
- OS: Ubuntu 18/OSX High Sierra
- CPU: i9 7980XE/i7 7 series
- RAM:128GB/16GB
- Disk size: 2TB/2TB
- Disk Type (HD/SDD): M.2/M.2

**Comment by UdjinM6** [comment]
It's meant for debugging/advanced users mostly. If don't want to see them just disable "Advanced PS UI" checkbox in Options.

**Comment by Duality-CDOO** [comment]
Fair enough, maybe a new line for each message instead of the ";" ?
