### ISSUE TITLE
Masternodes for voting IS are elected by the last blockhash ,isn't it? 

### ISSUE THREAD

**Issue by tkblack** [dashpay/dash#2355]
Masternodes for voting IS are elected by the last blockhash ,isn't it? If it means before next block be mined ,these masternodes is changeless? But ,the old versions were elected  when an IX be created. And why did u make this change?

**Comment by thephez** [comment]
The IS quorum masternodes are selected by several things including the transaction's inputs (every input of an IS tx uses a different quorum). I would recommend watching the video in the [InstantSend section](https://dash-docs.github.io/en/developer-guide#instantsend) of dash-docs.github.io.

**Comment by UdjinM6** [comment]
No further discussion happened, so I guess docs/video explained it clearly enough. Closing.
