### ISSUE TITLE
chain size through rpc

### ISSUE THREAD

**Issue by roccomuso** [dashpay/dash#2391]
Is it possible to get chain size on disk through rpc?
The equivalent of bitcoind `size_on_disk` property from the `getblockchaininfo` rpc method.

**Comment by thephez** [comment]
Not currently. This was added by bitcoin/bitcoin#11367 which has not been backported at this point.

**Comment by PastaPastaPasta** [comment]
this was backported in https://github.com/dashpay/dash/pull/3284

Will be released in 0.16.0.0
