### ISSUE TITLE
sever vulnerability

### ISSUE THREAD

**Issue by LucaPaterlini** [dashpay/dash#2453]
hello,
I think I have found a vulnerability for which I currently don't have a fix.
The grade is severe because create the probability for the pool to not pay the master node reward.
Is there any bug reward program or procedure to follow in this case. and have responsible disclosure.

Waiting for a kind reply from a core team leader,
cheers,
LP

**Comment by codablock** [comment]
You can contact me through alexander.block@dash.org
We have a bug bounty program and if the vulnerability can be confirmed, I'll get you in contact with the one who manages the bounties.

**Comment by codablock** [comment]
After some email exchanges with Luca, it turned out that chainparams were not correctly setup and thus payments were never enforced. This does not apply to Dash.

**Comment by attritionorg** [comment]
@codablock can you name the fork?
