### ISSUE TITLE
 error: undefined reference to `leveldb

### ISSUE THREAD

**Issue by VtpVlan-oo7** [dashpay/dash#2476]
here is a screenshot of that error's screenshot, i'm stuck with  that levedb problem before 1 week, so please if anyone knows then help me asap !!

![image](https://user-images.githubusercontent.com/31241756/48882563-d279a200-edcf-11e8-9346-389fa0fffdb8.png)

**Comment by PastaPastaPasta** [comment]
Can you provide more detail? What are you trying to do? If you are trying to build Dash, please follow the steps [here](https://github.com/dashpay/dash/blob/develop/doc/build-generic.md)

**Comment by VtpVlan-oo7** [comment]
@PastaPastaPasta  Thanks for your fast reply , I am new at Cryptocurrency development .

here i am stuck with to make a window wallet, like i try to  build that for windows and want to find .exe .
please help me it's really took 2 weeks and still i didn't got solution !!

**Comment by PastaPastaPasta** [comment]
You'll want to read [build-windows](https://github.com/dashpay/dash/blob/develop/doc/build-windows.md)

**Comment by VtpVlan-oo7** [comment]
@PastaPastaPasta  Thank you so much for your fast reply .if i'll stuck in it then i'll call you latter !!

**Comment by nmarley** [comment]
Thanks for your interest in Dash! I'm closing this now as it's generic support request and you should have info on how to proceed. Please feel free to use our [support forum](https://www.dash.org/forum/categories/dash-support.61/) if you have an issue that's not specific to this exact repo / issue building this codebase.
