### ISSUE TITLE
Invalid spork address specified

### ISSUE THREAD

**Issue by sharifzadesina** [dashpay/dash#2488]
I am trying to frok Dash,
But after I change the address prefix, `dash-qt` shows this message to me.
How can I generate new customized spork addresses?

**Comment by nmarley** [comment]
Hi,

You need to generate a new keypair (masternode genkey), and replace the spork address in `chainparams.cpp`. Or you could re-serialize the current spork address with your new address prefix, but you wouldn't have the corresponding spork private key if you did that.

Good luck!

**Comment by sharifzadesina** [comment]
Hi @nmarley, thank you
1- The `masternode genkey` is not available in my fork cause I don't have valid spork address,
2- when I use it with dash itself (not my fork) it gives me a private key, how can I get address from private key?

**Comment by sharifzadesina** [comment]
OK my problem sloved,
I disabled spork address checking at `init.cpp` then from `dash-qt` Debug Console I created key-pairs using `masternode genkey`, `importprivkey THEKEY "name", `getaddressesbyaccount "name"`.

**Comment by auscash** [comment]
> You need to generate a new keypair (masternode genkey), and replace the spork address in `chainparams.cpp`. 

How is this done?  And how many spork addresses need to be created, just for main net, test net, reg net?  Does this depend on address prefixes as well, or will it work by generating keys with openssl and somehow getting a private key in WIF and spork address from them?

Thanks!

**Comment by auscash** [comment]
> OK my problem sloved,
> I disabled spork address checking at `init.cpp` then from `dash-qt` Debug Console I created key-pairs using `masternode genkey`, `importprivkey THEKEY "name"`, `getaddressesbyaccount "name"`.

This worked for me too, thank you!
