### ISSUE TITLE
BIP32 standard for DASH

### ISSUE THREAD

**Issue by eabz** [dashpay/dash#2495]
I am creating an HD wallets app. But I don't seem to find the standard to Dash HD wallets. Should we use xpub default or drkp

**Comment by UdjinM6** [comment]
Pls use xpub https://github.com/dashpay/dash/blob/master/src/chainparams.cpp#L213

**Comment by eabz** [comment]
Great! Thanks!

**Comment by UdjinM6** [comment]
You are welcome 🙂
