### ISSUE TITLE
Synchronous test environment data stuck

### ISSUE THREAD

**Issue by ye21st** [dashpay/dash#2504]
When I synchronize the test environment data, the time reaches 2018-11-14 03:31:31, the sync data is stuck, and I can't continue syncing. I have already synchronized the data three times. I tried it on Win7 and Win10. It won't work. Can you help me?

![image](https://user-images.githubusercontent.com/17704719/49069786-1b64a700-f265-11e8-9204-58daa9ac7c6b.png)

**Comment by strophy** [comment]
Please confirm you are using v0.13.0.0-rc4 or higher.

**Comment by ye21st** [comment]
I downloaded the official wallet v0.12.3.3.
