### ISSUE TITLE
Segmentation fault while syncing testnet on rc5

### ISSUE THREAD

**Issue by mozgoo** [dashpay/dash#2507]
This issue tracker is only for technical issues related to Dash Core.

General Dash questions and/or support requests and are best directed to the [Dashpay Reddit](https://www.reddit.com/r/dashpay/).

To report critical security issues, email infosec@dash.org instead of creating Github issues.

#### If so, please list the steps to reproduce below:
1. get binary dash v0.13.0.0-rc5
2. start sync testnet from scratch

### Expected behaviour

sync all dash-testnet blockchain

### Actual behaviour

Segmentation fault (core dumped) at block 263999

### What version of Dash Core are you using?

v0.13.0.0-rc5

### Machine specs:
- OS: ubuntu linux 18.04
- RAM: 2GB
- Disk size: 30 GB 
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.

start command
```
dashd -datadir=/home/ubuntu/.dash -conf=/home/ubuntu/dash.conf
```

last three blocks in log (debug=1) [here](https://pastebin.com/HqDTCiS0)

dash.conf
```
dbcache=2048
disablewallet=1
listen=1
maxconnections=25
printtoconsole=1
rpcallowip=127.0.0.1
rpcallowip=172.16.0.0/12
rpcallowip=10.0.0.0/8
rpcauth=bcnode:<hash>
rpcport=19998
server=1
testnet=1
txindex=1
rpcthreads=4
rpcworkqueue=32
```

After downgrade to v0.13.0.0-rc4 sync continue without errors

**Comment by codablock** [comment]
Do you have the IP:port of the peer that you were connected to?

**Comment by codablock** [comment]
https://github.com/dashpay/dash/pull/2508 should fix this
