### ISSUE TITLE
Remove "About QT" from the help menu (GUI client)

### ISSUE THREAD

**Issue by taw00** [dashpay/dash#2514]
I always found it odd that the GUI client had an "About QT" in the help menu. What wallet user needs fluff about the GUI toolkit used by developers to implement the wallet? Do folks agree that we should just comment that out?

Not a critical bit, but.. it is just odd legacy crap for when only developers were using crypto. Granted the folks using the GUI client are still predominantly the more technically savvy users, but even then it is still really odd.

-t0dd

**Comment by UdjinM6** [comment]
I can be wrong but it's smth about licensing qt as a community edition to compile the wallet i.e. you have to include/display the note/license.

**Comment by PastaPastaPasta** [comment]
As Udjin said, this is a licensing requirement to use QT

**Comment by taw00** [comment]
The licensing claim is incorrect, but I am not going to lose sleep over it.
QT community version is LGPL same as GTK+ and a thousand other open source libraries.
