### ISSUE TITLE
Rpc: Introduce call for per-block fee statistics

### ISSUE THREAD

**Issue by salisbury-espinosa** [dashpay/dash#2519]
original: https://github.com/ElementsProject/elements/pull/185
related:
RPC: Introduce getblockstats to plot things https://github.com/bitcoin/bitcoin/pull/10757 
Qt: Show transaction size in transaction details window https://github.com/bitcoin/bitcoin/pull/8672

**Comment by ega-forever** [comment]
Are there any updates on "getblockstats" API?, I need it as well

**Comment by PastaPastaPasta** [comment]
bitcoin#10757 backported by https://github.com/dashpay/dash/pull/3058 and bitcoin#8672 was backported by https://github.com/dashpay/dash/pull/1615
