### ISSUE TITLE
downgraded testnet wallet with re-orged blockchain showing bizarre PS stats

### ISSUE THREAD

**Issue by taw00** [dashpay/dash#2561]
1. I had a testnet 0.13 wallet that had a 1400+ tDash 100% mixed (6 rounds)
2. testnet was re-orged at block 4000
3. I downgraded my wallet to 0.12.3.4 without nuking the existing wallet
4. I loaded up with a couple thousand tDash
5. PS info on the Overview tab shows... 77% PS ... I did not mix any tDash after that batch in step 1.

See attached screenshot. Probably ... minor, but... smells like a UI bug.

![screenshot from 2018-12-17 11-12-54](https://user-images.githubusercontent.com/6908872/50100221-ed341080-01ed-11e9-834d-dd936c82b80c.png)

**Comment by UdjinM6** [comment]
Hmmm.. can you screenshot Transactions tab with some (old) Privatesend Denominate transactions in the list?

**Comment by UdjinM6** [comment]
Actually, nvm, I found a backuped wallet and I think I can reproduce the same issue here on my machine.

**Comment by taw00** [comment]
Thought maybe because my wallet ran down the wrong chain for a bit. But no, I re-reindexed and am on the right chain and... it's still present.

**Comment by taw00** [comment]
In case you still want it, here's the transaction tab...
(the confirmed stuff is new tdash after block 4000 on the current chain).
![screenshot from 2018-12-17 16-04-40](https://user-images.githubusercontent.com/6908872/50115502-92aeaa80-0215-11e9-8106-87605ead5f19.png)

**Comment by UdjinM6** [comment]
Ah, no, that's not what I thought. This is basically because your wallet shows txes that are "still unconfirmed". You should just repair your wallet via Tools -> Repair -> Recover txes (`-zapwallettxes=1`) and it will fix itself. But I think I found another small issue thanks to switching back and forth from one testnet to another :)
