### ISSUE TITLE
Dash 12.3.14 does not receive funds in testnet

### ISSUE THREAD

**Issue by Gillian217** [dashpay/dash#2574]
Hi, I'm starting to use dash core wallet and set it to testnet. I've generated an address and load it on the dash testnet faucet that was provided. but checking the wallet it did not received the dash that what sent. Hope someone can help me.
Dash core wallet
wallet:
![screenshot from 2018-12-20 07-48-14](https://user-images.githubusercontent.com/37716672/50255275-370a3a00-042c-11e9-8474-ce9beb62db99.png)
Address:
![screenshot from 2018-12-20 07-48-42](https://user-images.githubusercontent.com/37716672/50255287-3ffb0b80-042c-11e9-8702-514145a9cb93.png)
Faucet:
![screenshot from 2018-12-20 07-51-52](https://user-images.githubusercontent.com/37716672/50255416-bd268080-042c-11e9-9a7b-164e9ee17c8f.png)
Loaded:
![screenshot from 2018-12-20 07-52-05](https://user-images.githubusercontent.com/37716672/50255455-ef37e280-042c-11e9-9427-0124fe7414f4.png)
checking the wallet:
![screenshot from 2018-12-20 07-54-26](https://user-images.githubusercontent.com/37716672/50255372-8badb500-042c-11e9-84ff-10e56d47143f.png)

Does not received any transactions.

**Comment by strophy** [comment]
Dash testnet was recently reset, so you are probably on the wrong chain. Please ensure you are using [v0.13.0.0-rc9](https://github.com/dashpay/dash/releases/tag/v0.13.0.0-rc9) and start dash with the "-reindex-chainstate" argument. You may need to also invoke "addnode 18.202.52.170:19999 add" in the debug console. You should end up on a chain around 8600 blocks high (check [here](https://testnet-insight.dashevo.org/insight/)).

Alternatively, you can just delete your datadir and start again, if you are using rc9 it should end up on the right chain. More details [here](https://www.dash.org/forum/threads/v13-0-testing.41945/page-4#post-204046).

**Comment by AllenYaoya** [comment]
have the same issue... I have upgraded dash core to v0.13.0.0-rc9 and sync update to date. But when I called the faucet and it did return ''Success! You have been awarded with XXX DASH!". 
Actually, I can't find any transactions related to my receive address.

**Comment by AllenYaoya** [comment]
> https://testnet-insight.dashevo.org/insight/

Hi ,
getblockcount return 9239 for now , is identical to what shown at https://testnet-insight.dashevo.org/insight/ .

**Comment by strophy** [comment]
Maybe the faucet is on the wrong chain, which one were you using. Send me your address and how much tDash you need and I'll send you some. I think we can close this issue soon if @Gillian217 doesn't respond again.

**Comment by AllenYaoya** [comment]
> Maybe the faucet is on the wrong chain, which one were you using. Send me your address and how much tDash you need and I'll send you some. I think we can close this issue soon if @Gillian217 doesn't respond again.

myaddress: yM6P4RvVNhUCVqAT2hMHWx9N9jG7x3oPU7
amount: 100

Thanks so much!

**Comment by AllenYaoya** [comment]
> Maybe the faucet is on the wrong chain, which one were you using. Send me your address and how much tDash you need and I'll send you some. I think we can close this issue soon if @Gillian217 doesn't respond again.

received! thanks!

**Comment by strophy** [comment]
It will probably work, but you may run into errors. Using unreleased versions with real Dash is at your own risk.
