### ISSUE TITLE
How to enable ipv6 mn support in the source code?

### ISSUE THREAD

**Issue by YellowFeveRs** [dashpay/dash#2580]
I am working on a fork of dash and I was wondering how to reenable the ipv6 node support as it used to be enabled in older versions of the dash code is there anyone who knows which file I have to change to reenable this feature again?

**Comment by nmarley** [comment]
Hi,

PR #1065 is the one which removed support for IPv6 MNs. You should be able to see what changed there and even revert that commit in your own code base.

Good luck!
