### ISSUE TITLE
[Private Testnet] Dash fails to sync

### ISSUE THREAD

**Issue by 0xA01** [dashpay/dash#2623]
Hi there. I did Dash private testnet.

I did everything as it described in manuals, checked many times, including seed nodes in `chainparamsseeds.h` etc.

I started `dashd` on one server and `dash-qt` on another machine (visible from outer network through ports forwarding). Both machines are in `chainparamssseeds.h` and daemons connects to each other, using `-printtoconsole` I can see their User Agent string etc.

![peers are connected](https://i.imgur.com/bReW8MX.png)

There is few blocks on one machine I generated with `generate n` and they never are synced to another machine. The source code on both machines is the same.

I did left them open for 12+ hours but in logs are only connect/reconnect records and no information about sync.

![dashd logs](https://i.imgur.com/uy4kJ7E.jpg)
![no sync info](https://i.imgur.com/1Rfs01E.png)

`dash-qt` is still in "Connecting to peers" status and the same progress % as yesterday.

![Connecting to peers](https://i.imgur.com/W49Yu99.png)
![Progress is stale](https://i.imgur.com/D9euV4h.png)

Moreover, when I see another peer in peers list from `dash-qt` there is label: `Whitelisted: no` I am worrying this may be the reason or not?

![Not whitelisted](https://i.imgur.com/fD95avY.png)

It never trying to send any blocks from one machine to another. May be two machines are not enough? Maybe I am missing something?

Maybe I should try to reproduce this using vanilla `dash` source w/o changing genesis or something. What I am missing? I see lot of messages over internet about same issue. Even if I use `litemode=1` to disable all Dash-specific functionality it still do not syncing. Why?

Thanks in advance.
Best regards.

**Comment by thephez** [comment]
Have you considered using a devnet instead? They are similar to a testnet, but you can easily start one up without modifying source code or anything (requires Dash Core 12.3 or newer). You can find some info here - https://blog.dash.org/dash-devnets-bc27ecbf0085 (NOTE: the example devnet used in that post was a temporary one that is no longer online).

**Comment by thephez** [comment]
@salmanfarisk There is nothing in Dash Core to prevent modifying it and there are quite a few projects that have (10s if not 100s of them actually, e.g. PIVX). I'd suggest starting by looking into `debug.log` and troubleshooting from there.

Also, since this is not actually a bug in Dash Core, the issue will probably be closed. It is probably better to discuss on the forum or discord.

**Comment by 0xA01** [comment]
Launching private testnet with new generated genesis keep in mind: there is check for masternodes count int daemon. If there is 0 masternodes currently in network sync will reset and start from beginning.

**Comment by CryptoTeller** [comment]
@salmanfarisk 0xA01 said if you have zero masternodes you wont sync, try adding at least one if not 2 masternodes to your private testnet...

**Comment by salmanfarisk** [comment]
@CryptoTeller  Tanks for responding. Can possible to set a masternodes in local machine( without using VPS ) for testing my private testnet...??
