### ISSUE TITLE
Build 0.13 failed - chiabls/bls.hpp

### ISSUE THREAD

**Issue by M8BWNN** [dashpay/dash#2635]
build on ubuntu fails:
( in docker, standard libdb4.8 image which fits most coins )
```
git clone https://github.com/dashpay/dash
cd dash
apt-get -y install curl cmake
cd depends
make -j8
cd ..
./autogen.sh
./configure --with-gui=no --prefix=$(pwd)/depends/ax86_64-pc-linux-gnu
make -j8
```

```
  CXX      libdash_server_a-addrdb.o
gcc gen_context.o -o gen_context
./gen_context
  CC       src/libsecp256k1_la-secp256k1.lo
In file included from evo/deterministicmns.h:9:0,
                 from activemasternode.h:14,
                 from activemasternode.cpp:5:
./bls/bls.h:14:27: fatal error: chiabls/bls.hpp: No such file or directory
compilation terminated.
Makefile:6435: recipe for target 'libdash_server_a-activemasternode.o' failed
make[2]: *** [libdash_server_a-activemasternode.o] Error 1
```

followed this documentation
https://github.com/dashpay/dash/blob/develop/doc/build-generic.md

might be related to: #2562 #2354

**Comment by UdjinM6** [comment]
There is probably a typo in your commands. This
```
./configure --with-gui=no --prefix=$(pwd)/depends/ax86_64-pc-linux-gnu
```
should be 
```
./configure --with-gui=no --prefix=$(pwd)/depends/x86_64-pc-linux-gnu
```

**Comment by M8BWNN** [comment]
you are right. but i get the same result with the corrected typo.

**Comment by UdjinM6** [comment]
Make sure that you have all build dependencies installed https://github.com/dashpay/dash/blob/develop/doc/build-unix.md#base-build-dependencies and that `make` in `depends` actually succeeds.

Full script in your case would be smth like this (assuming you are running under sudo/root):
```
apt-get update
apt-get install -y curl build-essential libtool autotools-dev automake pkg-config python3 bsdmainutils cmake
git clone https://github.com/dashpay/dash
cd dash/depends
make -j8 NO_QT=1
cd ..
./autogen.sh
./configure --prefix=$(pwd)/depends/x86_64-pc-linux-gnu
make -j8
```

**Comment by nasa8x** [comment]
I also have a problem with missing this library and how to fix it:
Download: https://github.com/codablock/bls-signatures/archive/v20181101.zip
unzip and cmd:

`git submodule update --init --recursive
mkdir build
cd build
cmake ../
cmake --build . -- -j 6
sudo make install`

**Comment by M8BWNN** [comment]
@UdjinM6 yes i have all those dependencies installed and they succeed.
@nasa8x yes thank you, that helped. 

so here is my working script:
```
sudo -s
apt-get update
apt-get install -y curl build-essential libtool autotools-dev automake pkg-config python3 bsdmainutils cmake
wget https://github.com/codablock/bls-signatures/archive/v20181101.zip
unzip v20181101.zip
cd bls-signatures-20181101
cmake .
make install
cd ..
git clone https://github.com/dashpay/dash
cd dash/depends
make -j8
cd ..
./autogen.sh
./configure --with-gui=no --prefix=$(pwd)/depends/x86_64-pc-linux-gnu
make -j8
```

**Comment by auscash** [comment]
Having the same issue.  Is the bls-signatures current for Dash?  I'm trying to compile the 0.13.x release.

**Comment by auscash** [comment]
Oh right, if bls signatures is a library for a signature scheme, why isn't that included with Dash then?

**Comment by auscash** [comment]
By the way, --with-gui=no doesn't seem to work.  --without-gui instead

**Comment by ksemaev** [comment]
same with 0.14.x release

**Comment by flound1129** [comment]
This is not the correct use of --prefix

**Comment by bedri** [comment]
Thanks @nasa8x . These libraries should be included in the source code. It is a must!

**Comment by bittylicious** [comment]
Confirmed this affects the 0.14.x release

**Comment by AllanDoensen** [comment]
I get this issue when compiling latest code (0.14.x) on ubuntu 19.10. I am using the non-portable DB, but other then that it is just a generic build directly from github. I have not used any gui flags...problem is still there.

**Comment by BenCryptoKing** [comment]
Guys, I think the most stable version of DASH is 0.12.3.4

**Comment by thephez** [comment]
@BenCryptoKing That is quite an old version and not supported. Current version is 0.15 (see the releases page of this repository).
