### ISSUE TITLE
AcceptBlock FAILED: bad-txns-vin-empty

### ISSUE THREAD

**Issue by DinoStray** [dashpay/dash#2659]
Node: 0.13.0.0 testnet
While I submit new block, I always got the same error: 

ERROR: ProcessNewBlock: AcceptBlock FAILED: bad-txns-vin-empty, Transaction check failed (tx hash d668682214aa0e8827974155a7c76562205c046ebaeb41e163457d03e9f02822)  (code 16)

I have set all the transaction type as below:
tx.nType = TRANSACTION_NORMAL;

**Comment by DinoStray** [comment]
another error:

ERROR: ProcessNewBlock: AcceptBlock FAILED: bad-txns-type (code 16)

**Comment by codablock** [comment]
I assume you're working on a mining pool implementation?

On testnet, DIP3 has activated already, which requires you to include the "coinbase_payload" which is found in the result of `getblocktemplate` into the coinbase special transaction (nType=5).

Here is an example of a pool (UNOMP) where we implemented support for the new coinbase transaction: https://github.com/UNOMP/node-merged-pool/pull/17/commits/8134bbb3d954724b0437758042a0c8d4bf92e1bc

If you provide us with code (you can also do this in private), we might be able to assist you further.

**Comment by DinoStray** [comment]
> I assume you're working on a mining pool implementation?
> 
> On testnet, DIP3 has activated already, which requires you to include the "coinbase_payload" which is found in the result of `getblocktemplate` into the coinbase special transaction (nType=5).
> 
> Here is an example of a pool (UNOMP) where we implemented support for the new coinbase transaction: [UNOMP/node-merged-pool@8134bbb](https://github.com/UNOMP/node-merged-pool/commit/8134bbb3d954724b0437758042a0c8d4bf92e1bc)
> 
> If you provide us with code (you can also do this in private), we might be able to assist you further.

OK, I got it. 3Q very much.
Another question, if I change coinbase trasaction type to TRANSACTION_COINBASE(5) and version 3, the found block can also be submit to mainnet, right?

**Comment by DinoStray** [comment]
New error:

2019-01-29 10:42:07 IsBlockPayeeValid -- ERROR: Invalid masternode payment detected at height 33774: CTransaction(hash=323192e610, ver=3, type=5, vin.size=1, vout.size=1, nLockTime=0, vExtraPayload.size=38)
    CTxIn(COutPoint(0000000000000000000000000000000000000000000000000000000000000000, 4294967295), coinbase 03ee830004ef2d505c2f2fc20000002403000000000000)
    CTxOut(nValue=18.90000000, scriptPubKey=76a9141f5bf1158daa4ecc3d773699)
2019-01-29 10:42:07 ERROR: ConnectBlock(DASH): couldn't find masternode or superblock payments

**Comment by codablock** [comment]
No, such a block would currently not be accepted on mainnet. Only after DIP3 activation, mainnet will accept such blocks. You will have to check for presence of a non-empty `coinbase_payload` field in the block template and only then change the transaction type to 5 and version to 3.

For the last error, something like https://github.com/UNOMP/node-merged-pool/pull/17/commits/5a70b799f8a049ff04bd19355e99583d73d8fa25 must be implemented. Dash Core will now return an array of payments in the `masternode` field of `getblocktemplate` instead of a single payment.

In general, I'd advise to look into all commits of https://github.com/UNOMP/node-merged-pool/pull/17 and check what needs to be ported to your own pool.

**Comment by DinoStray** [comment]
> No, such a block would currently not be accepted on mainnet. Only after DIP3 activation, mainnet will accept such blocks. You will have to check for presence of a non-empty `coinbase_payload` field in the block template and only then change the transaction type to 5 and version to 3.
> 
> For the last error, something like [UNOMP/node-merged-pool@5a70b79](https://github.com/UNOMP/node-merged-pool/commit/5a70b799f8a049ff04bd19355e99583d73d8fa25) must be implemented. Dash Core will now return an array of payments in the `masternode` field of `getblocktemplate` instead of a single payment.
> 
> In general, I'd advise to look into all commits of [UNOMP/node-merged-pool#17](https://github.com/UNOMP/node-merged-pool/pull/17) and check what needs to be ported to your own pool.

I check it out, and finally submit block success.
Thank you so much.

**Comment by codablock** [comment]
@DinoStray I assume this issue can be closed then?
