### ISSUE TITLE
ConnectBlock(): ProcessSpecialTxsInBlock for block <hash> failed with bad-tx-type

### ISSUE THREAD

**Issue by valar999** [dashpay/dash#2661]
I try to submit block with cb transaction according to DIP0003(4).
DIP0003 is not activated on mainnet for now, too few this kind of blocks.
But why my node v0.13.0.0 is not accept dip0003 block?

I get this error:
`ConnectBlock(): ProcessSpecialTxsInBlock for block <hash> failed with bad-tx-type`

**Comment by codablock** [comment]
Please note that DIP3/DIP4 blocks are only allowed AFTER DIP3 has activated, which is not the case yet.

For miners, this especially means that the coinbase transaction MUST be in the old style until DIP3 activates. It must only be a DIP4 special coinbase transaction when `getblocktemplate` returns a non-empty value in `coinbase_payload`.

Please also read https://github.com/dashpay/dash/issues/2659 as it contains a few hints on implementing support in mining pool software.
