### ISSUE TITLE
How can i perform transaction between peers using dash coin

### ISSUE THREAD

**Issue by pravya191** [dashpay/dash#2664]
Hi,
    I just set up the dash coin running on private network . and able to load the dash wallet . and also connect another peer by editing dash.conf 
added addnode = my peer IP
just close the already running server and restart ./dash-qt
the peers are visble in peer tab
and do a send coin from one wallet to another
from the sending user wallet dash balance get deducted but its not confirmed. and this transaction is not visible in other wallet

OS : ubuntu 16.04

**Comment by PastaPastaPasta** [comment]
you would run `sendtoaddress address amount` followed by `generate x` where x is the number of blocks you want to generate

**Comment by CryptoTeller** [comment]
You might need to wait for IsSynced = True before you can see the full blockchain on recieving node.

**Comment by UdjinM6** [comment]
You can force sync to switch to the next step by using `mnsync next` rpc.

**Comment by pravya191** [comment]
@UdjinM6 @CryptoTeller thank you
I just run " mnsync next " the out put will added in screenshot
![screenshot from 2019-02-04 18-21-41](https://user-images.githubusercontent.com/45413215/52209752-db482300-28aa-11e9-9bda-62e98389bb44.png)

![screenshot from 2019-02-04 18-21-28](https://user-images.githubusercontent.com/45413215/52209713-bf448180-28aa-11e9-9d56-1ceb11ff6c2a.png)

The screenshot of addnode
![screenshot from 2019-02-04 18-22-04](https://user-images.githubusercontent.com/45413215/52209800-09c5fe00-28ab-11e9-9557-881742d7e0ea.png)

**Comment by PastaPastaPasta** [comment]
it appears this issue is solved... Feel free to reopen if you feel it is not solved
