### ISSUE TITLE
Altcoin peers do not sync with each other

### ISSUE THREAD

**Issue by salmanfarisk** [dashpay/dash#2665]
I am new in blockchain technologies. I working in dash core 0.13.x. I just do some changes in chainparam.cpp and make the new private dash network with own genesis block. My network is do the mining successfully. I just setup the same network in another local machine. I connect both with 

    addnode=<local ip>
on dash.conf file in home directory. Then I do some steps in console that

step:1

On local machine one
    
              getaccountaddress ""
              result: yT7Bksf2UJM7bvSNpssGEmjiiejLMEcmso
Step:2

On local machine two 
               
              getaccountaddress ""
              result: ydBH74omTAMaWgcJujKTKzBmQdkRGu7Ygx
Step:3

On local machine one 

             generate 10
             result: Some dash balance is credited in to my dash coin wallet by mining

Step:4

I just send 23 dash yT7Bksf2UJM7bvSNpssGEmjiiejLMEcmso (local machine one address) to ydBH74omTAMaWgcJujKTKzBmQdkRGu7Ygx (local machine two address).

Step:5

I just do the mining process by
       
        generate 10
        result:Successfully mine  blocks

Step:6

I already decrease the coin maturity to 3 in dash-master/src/consensus/consensus.h

Step: 7

Now I check the transaction status on machine one. It is 9 confirmed. 

Step :8

Checked on the local machine two. **But not reflected the balance**
I continue the mining process. But balance is not reflected in second node.

Please give any suggestion or solution for my case. I thing the issue due to sync problem between two peers.

**Comment by codablock** [comment]
We unfortunately can't support development of forked coins, simply because we don't have the necessary time and resources to do so. You can still give it a try in the forums or Discord and hope for community support, but don't expect too much there as well.
