### ISSUE TITLE
[Dash 0.13.0.0] getblocktemplate issue

### ISSUE THREAD

**Issue by NaN-git** [dashpay/dash#2667]
I'm using getblocktemplate and I want to signal DIP0003 on mainnet. Therefore I'm sending the following request to the node: `{"id":"0","method":"getblocktemplate","params":[{"rules":["dip0003"]}]}`

### Describe the issue
Sometimes I receive in the version field 0x20000000 and sometimes 0x20000008

### Can you reliably reproduce the issue?
I have found no way so far to reproduce the issue reliably.

### Expected behaviour
I expect at least consistent behaviour. According to BIP9 the node should indicate it's preference, which would be 0x20000008.

**Comment by codablock** [comment]
@NaN-git the behavior you see is currently expected. `getblocktemplate` will first check if the masternode that's being paid in the new block is upgraded to the latest protocol version. Only if this is true, it will add the necessary bits to the version.

This is to ensure that such deployments don't get activated before enough masternode support is available. We might reconsider this style of deployment in future versions, so not sure if it will stay this way.

**Comment by NaN-git** [comment]
Ok, thank you. So it might not be an good idea to always set this flag. But people started complaining that miners do not indicate DIP3 yet.
Shall I rely on the default behaviour?

**Comment by codablock** [comment]
Well, it's the safest option to rely on the default behavior. But at the same time, no one can stop you from setting that bit all the time.

Masternodes are currently at around 62% upgrades and we can assume that we have 80% in a few days, so it should be safe to already signal with the bit.

**Comment by codablock** [comment]
@NaN-git Not sure you if you already heard about 0.13.1.0, but it basically does what you asked in this issue. It will now return the version bit for every block in `getblocktemplate`, no matter if the paid MN is upgraded or not.
