### ISSUE TITLE
litemode causes a chain split in v13.0.0

### ISSUE THREAD

**Issue by andcoisqu** [dashpay/dash#2693]
Running v13.0.0. Wiped the `testnet3` directory, syncing with `testnet=1`, `txindex=1`, `litemode=1`. Node connects to peers showing the right number of blocks, but block 7378, `0000002cac5ff3267d7b5daa1b164ada35e39f02cadc360a1523c539eeef08e5` is marked invalid. Retried several times, always marked invalid.

**Comment by codablock** [comment]
Fixed by #2694 and will be released as part of v13.2.
