### ISSUE TITLE
compilation issue v0.14

### ISSUE THREAD

**Issue by MrDefacto** [dashpay/dash#2720]
Hi,

It looks that someone assumed that on the world exist only Windows, Linux and MacOS... but the truth is different...

`stacktraces.cpp:30:10: fatal error: 'linux/limits.h' file not found
#include <linux/limits.h> // for PATH_MAX
         ^~~~~~~~~~~~~~~~
1 error generated.`

Writing code in such way eliminates for example whole *BSD systems family... and probably few others.

Regards,
D

**Comment by MrDefacto** [comment]
Even with:

Options used to compile and link:
  with wallet   = no
  with gui / qt = no
  with zmq      = yes
  with test     = no
  with bench    = no
  with upnp     = no
  debug enabled = yes
  **stacktraces enabled = no**
  werror        = no

it doesn't compile.

**Comment by UdjinM6** [comment]
Pls try #2721

**Comment by MrDefacto** [comment]
it looks that problem is bigger...

  CXX      libdash_util_a-stacktraces.o
stacktraces.cpp:39:10: fatal error: 'backtrace.h' file not found
#include <backtrace.h>
         ^~~~~~~~~~~~~
1 error generated.

**Comment by UdjinM6** [comment]
Make sure to run `make` in `depends/` after you pulled latest `develop`.

**Comment by MrDefacto** [comment]
good point 👍  thank You.

I'm including updated build script for FreeBSD.


[dash_build.zip](https://github.com/dashpay/dash/files/2896718/dash_build.zip)

**Comment by bedri** [comment]
make in depends folder result the following errors:

```
bedri@desktop:~/XFSdepo/coin-projects/dash/depends> make
Invalid configuration `desktop': machine `desktop' not recognized
sha256sum: hosts/.mk: No such file or directory
sha256sum: hosts/.mk: No such file or directory
sha256sum: hosts/.mk: No such file or directory
sha256sum: hosts/.mk: No such file or directory
sha256sum: hosts/.mk: No such file or directory
sha256sum: hosts/.mk: No such file or directory
sha256sum: hosts/.mk: No such file or directory
sha256sum: hosts/.mk: No such file or directory
sha256sum: hosts/.mk: No such file or directory
sha256sum: hosts/.mk: No such file or directory
sha256sum: hosts/.mk: No such file or directory
sha256sum: hosts/.mk: No such file or directory
sha256sum: hosts/.mk: No such file or directory
Makefile:70: hosts/.mk: No such file or directory
make: *** No rule to make target 'hosts/.mk'.  Stop.
```

**Comment by 10xcryptodev** [comment]
@bedri your CPU was not detected, there is a new version of config.sub file that you can use, until is backported for the codebase: https://github.com/bitcoin/bitcoin/blob/master/depends/config.sub

**Comment by bedri** [comment]
@10xcryptodev unfortunately it still does not work with the linked config.sub :(
```
bedri@desktop:~/XFSdepo/coin-projects/dash/depends> make
Invalid configuration `desktop': machine `desktop-unknown' not recognized
sha256sum: hosts/.mk: No such file or directory
sha256sum: hosts/.mk: No such file or directory
sha256sum: hosts/.mk: No such file or directory
sha256sum: hosts/.mk: No such file or directory
sha256sum: hosts/.mk: No such file or directory
sha256sum: hosts/.mk: No such file or directory
sha256sum: hosts/.mk: No such file or directory
sha256sum: hosts/.mk: No such file or directory
sha256sum: hosts/.mk: No such file or directory
sha256sum: hosts/.mk: No such file or directory
sha256sum: hosts/.mk: No such file or directory
sha256sum: hosts/.mk: No such file or directory
sha256sum: hosts/.mk: No such file or directory
Makefile:70: hosts/.mk: No such file or directory
make: *** No rule to make target 'hosts/.mk'.  Stop.
```

**Comment by bedri** [comment]
Somehow it sees machine as desktop-unknown with the new config.sub.
Shouldn't it recognize Ryzen 5 & OpenSuSE Tumbleweed?

**Comment by 10xcryptodev** [comment]
@bedri are you running on VM? Maybe the VM Software is not setting the CPU info the right way

**Comment by bedri** [comment]
@10xcryptodev no I am running on real machine.

**Comment by PastaPastaPasta** [comment]
Have you followed the build instructions? installed all dependancies, ran ./autogen.sh and ran ./configure as described https://github.com/dashpay/dash/blob/master/doc/build-generic.md ?

**Comment by bedri** [comment]
@PastaPastaPasta I had compiled and am running several coin wallets already on this system. Dashcore release binaries are working without problem as well. All required libraries are installed and of course I ran autogen.sh and configure. I even tried ./configure --disable-stacktraces and it still gives backtrace.h not found error
```
stacktraces.cpp:48:10: fatal error: backtrace.h: No such file or directory
   48 | #include <backtrace.h>
      |          ^~~~~~~~~~~~~
```

**Comment by bedri** [comment]
Shouldn't these kind of header files included into Dash source code for consistency? Earlier we had similar problem with some other library header file but it's fixed now I guess. I forgot the name of the library.

**Comment by bedri** [comment]
I installed libbacktrace0 and libbacktrace-devel packages from https://software.opensuse.org/package/libbacktrace0 and it solved the compile error however building dependency error is still there. I hope we can figure out the reason and it will be fixed.
