### ISSUE TITLE
Do not corrupt DB on sudden power cutoff

### ISSUE THREAD

**Issue by rex4539** [dashpay/dash#2738]
git @ develop HEAD

Reproducibility: always

Steps:
1. Run a node.
2. Pull the power plug to emulate a sudden power cutoff.

What happened:
DB is corrupt and you have to reindex from scratch.

Expected result:
DB is written in a safe way so in case of sudden cutoff, it continues from where you left off.

Notes:
I had this issue occur so many times, I'm quite close to give up running a Dash node. Bitcoin Core, Bitcoin Unlimited and Zcash do not have this issue. The DB never gets corrupted on sudden power cutoff and continues from where you left off.

**Comment by oti-dev** [comment]
Actually I'm not sure if it happens always. I had incidents where the node was killed and the DB was fine afterwards. But mostly it was trashed.

**Comment by codablock** [comment]
@rex4539 @oti-dev Did you only observe this on `develop` or also on v0.12.x/v0.13.x releases?

https://github.com/dashpay/dash/pull/2744 should fix such issues introduced in v0.13.x and thus also present in `develop`.

**Comment by oti-dev** [comment]
I've had this ever since 0.12.x.

**Comment by rex4539** [comment]
Same here.

**Comment by UdjinM6** [comment]
Should be fixed by #2744 in `develop` and by #2746 in `master` (v0.13.2).
