### ISSUE TITLE
RPC - masternode current kills Core

### ISSUE THREAD

**Issue by thephez** [dashpay/dash#2788]
### Describe the issue
`masternode current` causes Dash Qt to close immediately

#### If so, please list the steps to reproduce below:
1. Run `masternode current`

### Actual behaviour
Qt closes immediately

### What version of Dash Core are you using?
Current develop branch: https://github.com/dashpay/dash/commit/591b0185c5f576b3bb2d7a04b16d7914729e57a6

### Any extra information that might be useful in the debugging process.
Nothing in `debug.log`, but I think we're going out of bounds here on the index (1 minus 9 :scream: ) https://github.com/dashpay/dash/blob/develop/src/rpc/masternode.cpp#L252. `masternode winner` passes through that same function and it works fine.

**Comment by UdjinM6** [comment]
Fixed by #2789
