### ISSUE TITLE
How to tell if transaction was sent with InstantSend after confirm?

### ISSUE THREAD

**Issue by Crypto2** [dashpay/dash#2876]
I may be wrong here but it seems like after a transaction sent with InstantSend confirms 'instantlock' in listsinceblock/listtransactions starts returning false according to a few test TXes I sent? Since most places won't confirm a TX unless it has X number of confirms if it doesn't see the TX before the 1st confirm it won't instantly confirm it while it waits for X blockchain confirms?

**Comment by Crypto2** [comment]
Any information on this?

**Comment by MrDefacto** [comment]
You can execute 'getrawtransaction' command through RPC to get informations about tx status. 
Example:
getrawtransaction 34831a8bb1b03c522456aa3a2cd3bf5132cb03e904048be8d8bcaba08223ab9f 1

and it returns special flag 'instantlock' set to 'true'.

**Comment by Crypto2** [comment]
On a large site it would be pretty big overhead to have to use listsinceblock + getrawtransaction on every TX. I would think listsinceblock/listtransactions should have instantlock = true for at least the 6 confirms until they are ready for inclusion in future IS sends?

**Comment by antouhou** [comment]
The instalock isn't saved on the blockchain. It can be retrieved only as a p2p message. The reason is that after some confirmations InstantSend transaction is the same transaction as any other transaction

**Comment by Crypto2** [comment]
Yep that's what I mean, I see in the code there is a temp storage with InstantSend TXes in it: https://github.com/dashpay/dash/blob/master/src/wallet/rpcwallet.cpp#L62
`bool fLocked = instantsend.IsLockedInstantSendTransaction(wtx.GetHash());`

Looking around not digging too deep it looks like that flag should stay in the DB for Params().GetConsensus().nInstantSendKeepLock blocks (mainnet == 24) but it doesn't seem to do so since even on the 1st confirm instantlock reverts to false.

**Comment by PastaPastaPasta** [comment]
This should be mostly irrelevant now since ChainLocks are enabled, and the tx should show chainlock true if it's block does have a clsig

**Comment by PastaPastaPasta** [comment]
Closing, see comment above. Please open a new issue / reopen if you have a concern
