### ISSUE TITLE
Typo in german translation, "L" missing in Warteschlange (queue)

### ISSUE THREAD

**Issue by Sleekesst** [dashpay/dash#288]
It reads "Warteschange", it should say "Warteschlange" (queue). Occurs 3 times:

./src/qt/locale/dash_de.ts:

    <message>
        <location filename="../overviewpage.cpp" line="414"/>
        <source>Submitted to masternode, waiting in queue .</source>
        <translation>An Masternode übermittelt, wartet in Warteschange .</translation>
    </message>
    <message>
        <location filename="../overviewpage.cpp" line="415"/>
        <source>Submitted to masternode, waiting in queue ..</source>
        <translation>An Masternode übermittelt, wartet in Warteschange ..</translation>
    </message>
    <message>
        <location filename="../overviewpage.cpp" line="416"/>
        <source>Submitted to masternode, waiting in queue ...</source>
        <translation>An Masternode übermittelt, wartet in Warteschange ...</translation>
    </message>

**Comment by crowning-** [comment]
Good find, thanks a lot :thumbsup:

@schinzelh , I've already fixed it over at Transifex.
