### ISSUE TITLE
Dash 0.13 windows build

### ISSUE THREAD

**Issue by Hser2bio** [dashpay/dash#2895]
Hi there!

trying to cross compiling deps in windows subsystem shoot this error:

In file included from /home/xxxxx/dash/depends/work/build/x86_64-w64-mingw32/chia_bls/v20181101-167abe8206b/contrib/relic/include/relic_arch.h:38:0,
                 from /home/xxxxx/dash/depends/work/build/x86_64-w64-mingw32/chia_bls/v20181101-167abe8206b/contrib/relic/include/relic_util.h:38,
                 from /home/xxxxx/dash/depends/work/build/x86_64-w64-mingw32/chia_bls/v20181101-167abe8206b/contrib/relic/src/arch/relic_arch_none.c:31:
/home/xxxxx/dash/depends/work/build/x86_64-w64-mingw32/chia_bls/v20181101-167abe8206b/contrib/relic/include/relic_types.h:39:10: fatal error: gmp.h: No such file or directory
 #include <gmp.h>
          ^~~~~~~
compilation terminated.
contrib/relic/src/CMakeFiles/relic_s.dir/build.make:188: recipe for target 'contrib/relic/src/CMakeFiles/relic_s.dir/arch/relic_arch_none.c.obj' failed
make[3]: *** [contrib/relic/src/CMakeFiles/relic_s.dir/arch/relic_arch_none.c.obj] Error 1
make[3]: *** Waiting for unfinished jobs....

**Comment by vereten** [comment]
Same error:
.../depends$ make chia_bls
.../depends/sources/download-stamps/.stamp_fetched-gmp-gmp-6.1.2.tar.bz2.hash' failed

**Comment by Hser2bio** [comment]
FIXED
