### ISSUE TITLE
"FATAL ERROR in relic_ep_util.c:298"

### ISSUE THREAD

**Issue by L3P3** [dashpay/dash#2900]
### Describe the issue
I unpacked the tar.gz file to /usr, like I did with earlier versions. Then, I ran `dash-qt` and it works like it always did: Pretty well. But after a few minutes, I discovered that it wrote to the terminal:
```
FATAL ERROR in relic_ep_util.c:298
FATAL ERROR in relic_ep_util.c:298
```
As I said, the app works flawlessly so far, I am just a bit worried about the "fatal" error message.

### Expected behaviour
I expect no error messages in release builds.

### Actual behaviour
An "FATAL ERROR" message is printed twice.

### What version of Dash Core are you using?
Dash Core version v0.13.3.0 (64-bit)
Just downloaded from `dash.org`.

### Machine specs:
- OS: Debian Linux `buster`
- CPU: amd64, 6 cores
- RAM: 8 GiB, more than enough
- Disk size: huge, more than enough
- Disk Type (HD/SDD): Data directory is on an huge hdd.

### Any extra information that might be useful in the debugging process.
The debug console in the GUI does not show any additional message. Just the default header.
After closing dash-qt, the same message appeared twice again.

**Comment by codablock** [comment]
These FATAL_ERROR messages come from deep inside a library that we use internally. They are not as fatal as they sound like, because the code surrounding that library is catching and handling the error pretty well.

**Comment by nmarley** [comment]
As stated above, not actually an issue.
