### ISSUE TITLE
Building without Qt4 

### ISSUE THREAD

**Issue by shaygover** [dashpay/dash#2916]
Hi,

Does Qt4 still required?
I'm trying to remove qt4 from my system (Arch) and it seems that dashcore requires it. But searching for old issues, might suggest that it no longer the issue? Yes/No?

Thanks

**Comment by UdjinM6** [comment]
No, qt4 shouldn't be required. Make sure you follow build instructions - prepare `depends` and then specify correct `--prefix=...` in `./configure` command https://github.com/dashpay/dash/blob/develop/doc/build-generic.md
