### ISSUE TITLE
How to Build dash in CLion(Linux)

### ISSUE THREAD

**Issue by hzxGoForward** [dashpay/dash#2921]
Is there any one can tell me how to import the source code into CLion to Build it ?
I have obey the building tutorial of dash in this website, and I am sure I do it correctly. 
But there are still some problems in building it in CLion, I thought the problem cames from makelists.txt, but I don't know how to alert the file. 

So,If there is some helpful materials or can someone hospital can tell me how and what to do? thx!

**Comment by codablock** [comment]
I'm using CLion for all my development activities, but I do NOT use it to build the source. The `CMakeLists.txt` found in the project is NOT meant to be buildable (see the disclaimer on top of that file), which means that you will face millions of errors when you try to use it for building. The `CMakeLists.txt` is only existing to allow opening the project in CLian, which then gives all kinds of advanced IDE features for which it has to know the project structure.

**Comment by hzxGoForward** [comment]
@codablock thanks! I understand.

**Comment by codablock** [comment]
Happy to help. Closing this issue then.
