### ISSUE TITLE
dashd crashes after updating pruned node from 0.13 to 0.14.0.1

### ISSUE THREAD

**Issue by NaN-git** [dashpay/dash#2961]
### Describe the issue
I tried to upgrade a pruned node with `prune=1024` from version 0.13.2.0 to version 0.14.0.1.
dashd crashes during startup with the following message:
`dashd: llmq/quorums_blockprocessor.cpp:276: void llmq::CQuorumBlockProcessor::UpgradeDB(): Assertion 'r' failed.`

The reason seems to be that `DIP0003EnforcementHeight` is less than `pruneheight` and therefore `llmq::CQuorumBlockProcessor::UpgradeDB()` tries to access a pruned block.

### Can you reliably reproduce the issue?
yes

### What version of Dash Core are you using?
v0.14.0.1

**Comment by PastaPastaPasta** [comment]
resolved by 2962
