### ISSUE TITLE
The dash 0.14.0.0 & 0.14.0.1 has small memory leak

### ISSUE THREAD

**Issue by lcgogo** [dashpay/dash#2969]
### Describe the issue
I runs dash 0.14.0.0 masternode for several days. I find out the masternode memory usage slowly increases from about 500MB up to 800MB in about 10 days. Then I check the 0.14.0.1 release note mentions : Fixed a rare memory/db leak in LLMQ based InstantSend.
So I upgrade to 0.14.0.1, however the new version consumes more memory than 0.14.0.0 and increases quicker than 0.14.0.0 .

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.
<img width="1494" alt="屏幕快照 2019-06-08 上午10 32 22" src="https://user-images.githubusercontent.com/8175573/59141080-6c561480-89d9-11e9-9efb-78204e576459.png">

The first orange line is dash-0.13.2.0 memory usage. The 2nd purple line is dash-0.14.0.0 and the 3rd red line is dash-0.14.0.1

### What version of Dash Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

Now i use dash-0.14.0.1

**Comment by codablock** [comment]
What happens when you restart dashd? Does it start at 500MB again and then climb back to 800MB or does it start with 800MB immediately?

**Comment by lcgogo** [comment]
> What happens when you restart dashd? Does it start at 500MB again and then climb back to 800MB or does it start with 800MB immediately?

I run dash in alpine based docker. I restart it by docker stop/start.

**Comment by UdjinM6** [comment]
@lcgogo can you confirm the issue with mem usage always growing or is it a bit higher but not growing any further for you now?

**Comment by qwizzie** [comment]
I was worried a bit about a possible memory leak as well, so i'm monitered my masternodes RAM usage for these last twee weeks 

10-06-2019 : 27,6%
14-06-2019 : 28,3%
16-06-2019 : 28,9%
17-06-2019 : 32,4%
18-06-2019 : 32,0%
19-06-2019 : 30,3%
20-06-2019 : 28,8%
21-06-2019 : 28,4%
23-06-2019 : 27,0%
24-06-2019 : 26,4%

Maybe this helps..

**Comment by PastaPastaPasta** [comment]
Based on what @qwizzie provides this isn't an issue. Please reopen if you have any more information pointing to a memory leak. 

Thansk
