### ISSUE TITLE
Api Question (Method getaddressesbylabel and getaddressesbyaccount )

### ISSUE THREAD

**Issue by akarimovbytewerk** [dashpay/dash#2977]
Good day. Can you help me with deprecated method analog?
After update Dash Core to version 0.14.0.1 method "getaddressesbyaccount" is deprecated and cannot be used anymore, in bitcoin documents there is alternative to it "getaddressesbylabel", but there is no such method in your documentation.
So the question is how can i get addresses for specific label (account)?

**Comment by UdjinM6** [comment]
Hi. I believe `getaddressesbyaccount` is deprecated since ages, it's not smth we introduced in 0.14.x. In any case, it should be fully functional, you can use it just like before.

**Comment by akarimovbytewerk** [comment]
Is there an additional parameter to server config or command request to use deprecated methods? Because i'm getting `{"code":-32601,"message":"Method not found"}` response

**Comment by UdjinM6** [comment]
Hmmm.... not that I'm aware of. Make sure there is no typo and you have wallet support compiled in if you use self-compiled binaries.

**Comment by thephez** [comment]
Yes, I confirmed `getaddressesbyaccount` is still functional also. You can see info on it [here](https://dash-docs.github.io/en/developer-reference#getaddressesbyaccount).

Example usage: `getaddressesbyaccount ""` (shows addresses for default account)

**Comment by akarimovbytewerk** [comment]
Wallet support is disabled by default in Docker image, that was the cause of problem...
Thanks for answer.
