### ISSUE TITLE
dash-cli listunspent: Method not found

### ISSUE THREAD

**Issue by cipig** [dashpay/dash#2993]
After updating dash to latest, `dash-cli listunspent` returns
```
error code: -32601
error message:
Method not found
```

**Comment by PastaPastaPasta** [comment]
Unable to reproduce, `listunspent` in debug console is working for me on 0.14.0 build

**Comment by nmarley** [comment]
@cipig What binary are you using? Are you building yourself or using one of the pre-built binaries? (If you built it, are you using any flags like `--no-wallet`?) Which architecture are you using?

It will be easier to help if we have a bit more info.

**Comment by cipig** [comment]
i am always building it myself... from master branch... it worked in the past, but seems some changes in the last 1-2 weeks broke it... i am on Debian Linux and this is my config:
```
server=1
txindex=1
litemode=1
listen=0
listenonion=0
onion=127.0.0.1:9050
rpcuser=bla
rpcpassword=bla
```

**Comment by nmarley** [comment]
Thanks for the info. It's working for me and others, and without answers to the other questions I asked, I'm not sure how much we will be able to help you.

We need to know _exactly_ how you build it in order to reproduce your issue.

**Comment by cipig** [comment]
```git clone https://github.com/dashpay/dash
cd dash
cd depends
make NO_QT=1 NO_UPNP=1 -j4
cd ..
./autogen.sh
./configure --prefix `pwd`/depends/x86_64-pc-linux-gnu --with-incompatible-bdb --with-gui=no --disable-tests --disable-bench --without-miniupnpc --disable-zmq
make -j4
sudo cp src/dash-cli src/dashd /usr/local/bin/
sudo strip /usr/local/bin/dash*```

**Comment by UdjinM6** [comment]
@cipig What's the output of `dash-cli --version` is for you?

**Comment by cipig** [comment]
`Dash Core RPC client version v0.14.0.1`

**Comment by UdjinM6** [comment]
I used your exact script and config to build and run on Debian 4.9 and `listunspent` works just fine for me. Make sure there was no typo or anything like that.

**Comment by cipig** [comment]
damn, i found the error... i compiled dash wrong the last time... used the same compile options as on the electrum servers, instead of the compile options for a normal daemon...
i am very sorry that i wasted your time

**Comment by UdjinM6** [comment]
Heh, things happen :)
