### ISSUE TITLE
Core Dumped when starting 0.14.0.1

### ISSUE THREAD

**Issue by mempooled** [dashpay/dash#2994]
### Describe the issue
dashd core dumps when trying to start for the second time after a successful syncronization to the tip of mainnet.

#### If so, please list the steps to reproduce below:
1. install and sync dashd
2. start dashd after it's synced to the tip of the chain
3. during start-up core dumps with following message:
dashd: evo/evodb.cpp:33: bool CEvoDB::VerifyBestBlock(const uint256&): Assertion `hashBestBlock == hashBlockIndex' failed.
Aborted (core dumped)
### Expected behaviour
This node already has a valid copy of the blockchain but won't get passed this failed assertion.

### Actual behaviour
Daemon dumps and kills itself.

### What version of Dash Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS: Ubuntu 16.04 LTS
- CPU: 1 CPU Core
- RAM: 2 GB Ram
- Disk size: 25GB space (15gb's free)
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
From debug.log
2019-06-23 09:03:45 LoadBlockIndexDB: last block file = 73
2019-06-23 09:03:45 LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=3343, size=71668146, heights=1088115...1091458, time=2019-06-16...2019-06-22)
2019-06-23 09:03:45 Checking all blk files are present...
2019-06-23 09:03:45 LoadBlockIndexDB: transaction index enabled
2019-06-23 09:03:45 LoadBlockIndexDB: address index disabled
2019-06-23 09:03:45 LoadBlockIndexDB: timestamp index disabled
2019-06-23 09:03:45 LoadBlockIndexDB: spent index disabled
2019-06-23 09:03:45 LoadBlockIndexDB: hashBestChain=0000000000000012122870e9505f1bd0f46a029b09daac2305d6d1ec2970d81e height=1091458 date=2019-06-22 15:17:04 progress=0.999576
2019-06-23 09:03:45 init message: Verifying blocks...
2019-06-23 09:03:45 Verifying last 6 blocks at level 3
2019-06-23 09:03:45 [0%]...

**Comment by UdjinM6** [comment]
Looks like evodb is corrupted, pls try reindexing.

**Comment by mempooled** [comment]
Starting the node using reindex will work and it will successfully get to the tip of the chain. When you give it the dash-cli stop command it exits leaving this in the debug.log

> 2019-06-23 15:02:20 Dumped mempool: 0.000141s to copy, 0.002848s to dump
> 2019-06-23 15:02:41 Error: Out of memory. Terminating.
> 2019-06-23 15:02:41 #### std::terminate() called, aborting ####
> #### UNKNOWN REASON ####

To note the vps does have 2GB of ram and 1GB of swap. Upon starting the daemon you receive the original assertion error and the core dumps. I have increased swap to 2GB and will try another reindex seems like something is getting corrupted on exit but I figured 2GB of ram and 1GB of swap would have been sufficient for a full node's original sync up with the network.

**Comment by mempooled** [comment]
After increasing the swap space to 2GB the node is able to perform the re-index as well as stop successfully. Upon stop it trys to dump the mempool and baloon's to 1.7ish GB of swap usage. This was failing in the 1GB of ram instance and corrupting the evo db it seems.

I guess the absolute minimum specs for a fullnode is now 2GB of ram and 2GB of swap. We can close this issues.

**Comment by UdjinM6** [comment]
>I guess the absolute minimum specs for a fullnode is now 2GB of ram and 2GB of swap.

Yes, mem usage is higher with 14.0 and 2gb ram + 2gb swap is the lowest spec you can run it on. I would recommend to use 4gb swap though to be on a safe side.

Anyway, thanks for reporting back and posting your solution 👍
