### ISSUE TITLE
Wallet node stop syncing

### ISSUE THREAD

**Issue by bitfex** [dashpay/dash#2996]
Hello,

After 22.06.2019 wallet node stop syncing.

Dashd version: v0.14.0.1 (from releases binary)

### Machine specs:
- OS: Ubuntu 18.04.2 LTS (Bionic Beaver)
- CPU: Intel(R) Celeron(R) CPU J3355 @ 2.00GHz
- RAM: 8Gb
- Disk size: 500Gb
- Disk Type (HD/SDD): HDD

debug.log attached: [debug.log](https://github.com/dashpay/dash/files/3318599/start.log)

**Comment by UdjinM6** [comment]
Possible duplicate of #2995 , pls try the solution mentioned there i.e. `reconsiderblock 00000000000000112e41e4b3afda8b233b8cc07c532d2eac5de097b68358c43e`

**Comment by bitfex** [comment]
Thank you, seems that helped (I was need to wait about a 15-60 minutes to node started syncing)
