### ISSUE TITLE
Regtest mode can't mine

### ISSUE THREAD

**Issue by sipsorcery** [dashpay/dash#2998]
From what I can tell after #2778 the intent is that the mining related RPC commands have been removed from the daemon.

Doesn't this result in `regtest` mode being unusable in the official binaries? Without the `generate` commands the `regtest` node will be stuck at block 0.

I have integration tests that run checks on transaction processing logic directly against the official executables. Without `regtest` mode these tests can no longer be run.

**Comment by UdjinM6** [comment]
The miner was removed from win and mac os binaries only (which never had any integration tests anyway), linux binaries should work in regtest mode just like before. If however you need a functioning regtest mode in win and mac os binaries too, you can always build it yourself with `--disable-miner` flag removed.
