### ISSUE TITLE
Doc - Mac OS X Homebrew

### ISSUE THREAD

**Issue by themsay** [dashpay/dash#30]
The command should be "git clone git@github.com:darkcoinproject/darkcoin.git darkcoin"
not this "git clone git@github.com:darkcoin-project/darkcoin.git darkcoin".

**Comment by mkinney** [comment]
Neither are applicable anymore. Should be okay to close this issue.

File: shows this line
build-osx.md:        git clone https://github.com/darkcoin/darkcoin.git

Tested it on mac and the current command works:
mkinneymbp:tmp mikekinney$ git clone https://github.com/darkcoin/darkcoin.git
Cloning into 'darkcoin'...
remote: Counting objects: 54195, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 54195 (delta 0), reused 0 (delta 0), pack-reused 54189
Receiving objects: 100% (54195/54195), 63.18 MiB | 2.11 MiB/s, done.
Resolving deltas: 100% (38832/38832), done.
Checking connectivity... done.
mkinneymbp:tmp mikekinney$ cd darkcoin/
mkinneymbp:darkcoin mikekinney$ ls
COPYING		Makefile.am	autogen.sh	contrib		doc		qa		src
INSTALL		README.md	configure.ac	depends		pkg.m4		share
mkinneymbp:darkcoin mikekinney$
