### ISSUE TITLE
mke failed

### ISSUE THREAD

**Issue by Kosteloos** [dashpay/dash#3010]
make HOST=x86_64-w64-mingw32 -j4

[100%] Linking CXX executable runtest.exe
CMakeFiles/runtest.dir/objects.a(test.cpp.obj):test.cpp:(.text+0x14d3) : référence indéfinie vers « std::thread::_State::~_State() »
CMakeFiles/runtest.dir/objects.a(test.cpp.obj):test.cpp:(.text+0x2e317) : référence indéfinie vers « std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) »
CMakeFiles/runtest.dir/objects.a(test.cpp.obj):test.cpp:(.text+0x2e332) : référence indéfinie vers « std::thread::join() »
CMakeFiles/runtest.dir/objects.a(test.cpp.obj):test.cpp:(.text+0x14bb) : référence indéfinie vers « std::thread::_State::~_State() »
collect2: error: ld returned 1 exit status
src/CMakeFiles/runtest.dir/build.make:100: recipe for target 'src/runtest.exe' failed
make[3]: *** [src/runtest.exe] Error 1
make[3] : on quitte le répertoire « /home/thor/kosteloos/depends/work/build/x86_64-w64-mingw32/chia_bls/v20181101-9b349cf8507/build »
CMakeFiles/Makefile2:306: recipe for target 'src/CMakeFiles/runtest.dir/all' failed
make[2]: *** [src/CMakeFiles/runtest.dir/all] Error 2
make[2] : on quitte le répertoire « /home/thor/kosteloos/depends/work/build/x86_64-w64-mingw32/chia_bls/v20181101-9b349cf8507/build »
Makefile:129: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1] : on quitte le répertoire « /home/thor/kosteloos/depends/work/build/x86_64-w64-mingw32/chia_bls/v20181101-9b349cf8507/build »
funcs.mk:242: recipe for target '/home/thor/kosteloos/depends/work/build/x86_64-w64-mingw32/chia_bls/v20181101-9b349cf8507/./.stamp_built' failed
make: *** [/home/thor/kosteloos/depends/work/build/x86_64-w64-mingw32/chia_bls/v20181101-9b349cf8507/./.stamp_built] Error 2

help me please

**Comment by PastaPastaPasta** [comment]
did you follow the build instructions? what OS are you building on? more information would help

**Comment by barrystyle** [comment]
Able to replicate on Debian 10 (buster); steps required are:

git clone https://github.com/dashpay/dash
git checkout v0.14.0.x
cd depends
make HOST=x86_64-w64-mingw32 -j4

**Comment by barrystyle** [comment]
Disregard; issue is a symptom of not setting the posix compliance for both gcc & g++:

```
$ sudo apt-get install g++-mingw-w64-x86-64
$ # Required to enable C++ threading libraries (e.g. std::thread)
$ sudo update-alternatives --set x86_64-w64-mingw32-g++  /usr/bin/x86_64-w64-mingw32-g++-posix
$ sudo update-alternatives --set x86_64-w64-mingw32-gcc  /usr/bin/x86_64-w64-mingw32-gcc-posix
```

**Comment by nmarley** [comment]
Hey @Kosteloos , did you try installing the suggested package above and running the `update-alternatives` commands as mentioned here https://github.com/dashpay/dash/issues/3010#issuecomment-511160950 ?

**Comment by PastaPastaPasta** [comment]
closing as the fix was given.
