### ISSUE TITLE
rescanblockchain isn't implemented in rpc

### ISSUE THREAD

**Issue by krtschmr** [dashpay/dash#3042]
`rescanblockchain` is working on LTC and BTC but no on dash.

do we need it, to capture past transactions for a view-only address that we added right now?

**Comment by PastaPastaPasta** [comment]
try to use `rescan` https://docs.dash.org/en/stable/wallets/dashcore/cmd-rpc.html?highlight=rescan#wallet-options

**Comment by nmarley** [comment]
Ok, glad you found a solution that's working for you! 😄
