### ISSUE TITLE
Error -28 Loading Wallet

### ISSUE THREAD

**Issue by ebiboy2** [dashpay/dash#3073]
I am trying to make an explorer of some sort and i need the `addressdeltas` functionality. I added `txindex=1` and `addressindex=1` in the config and started the deamon with the `-reindex` option.
After like forever, I still get `error code: -28 and error message: Loading wallet...` 
Where do i go from here?

**Comment by UdjinM6** [comment]
What version are you using and on what OS? Also pls check debug.log file - what are 20-30-ish last lines there?

**Comment by ebiboy2** [comment]
> 
> 
> What version are you using and on what OS? Also pls check debug.log file - what are 20-30-ish last lines there?
> 
> EDIT: and what about resource usage - is dashd busy with smth or is it sitting at 0% cpu?

I am using Ubuntu and i'm running the latest version. debug.log does not show any errors.

**Comment by ebiboy2** [comment]
Solved the problem by rebooting server
