### ISSUE TITLE
not synced with network. Awaiting full sync before running Sentinel.

### ISSUE THREAD

**Issue by phyuphyu84** [dashpay/dash#3185]
I've forked dashcore and when installing sentinel. dashd not synced with network. Awaiting full sync before running Sentinel. I stop this state and fail in creating masternode. Please help me.

**Comment by nmarley** [comment]
We don't have the capacity to support forks at this time.

Please ensure that DashCore (or whatever your fork is called) is running and fully synced before running Sentinel. If you have some issue with DashCore (not the fork), feel free to report it here. It will take a few hours to sync from scratch, depending on your network connection.

You can check the status via any/all of the following, which all give different information related to syncing status:

- `dash-cli getblockchaininfo`
- `dash-cli getblockcount`
- `dash-cli mnsync status`
