### ISSUE TITLE
0.15.0.0-rc1 UI/UX Send tab move Privatesend checkbox

### ISSUE THREAD

**Issue by tortugaverde98** [dashpay/dash#3241]
### Describe the issue
v15 has a much cleaner look, but the privatesend checkbox is still easily overlooked, and can result in a user sending regular funds by accident.

On the Send tab, move PrivateSend checkbox and Balance to the left side, just above the Send button and below "Note: Not enough data for fee estimation..."

When the user goes to press send, they have a better chance of seeing the privatesend box, and remembering to check it before sending. Privacy mistakes are easy to make and the consequences can be severe in some countries.. This will help reduce mistakes.

**Comment by PastaPastaPasta** [comment]
Superseded by #3442, solves the issue you were describing.
