### ISSUE TITLE
0.15.0.0-rc1 UI/UX Dark Mode console text

### ISSUE THREAD

**Issue by tortugaverde98** [dashpay/dash#3242]
### Describe the issue
Dark mode console text is difficult to read. It is black on dark background.

#### If so, please list the steps to reproduce below:
1. Set to dark mode, open console.

### Expected behaviour
Text should be light grey as it is on other tabs.

### Actual behaviour
Text is black.

### What version of Dash Core are you using?
v0.15.0.0-rc1

### Machine specs:
- OS: Linux

**Comment by PastaPastaPasta** [comment]
![darkmode-console](https://user-images.githubusercontent.com/6443210/81631807-3ba40980-93f8-11ea-97af-f8c3a9cc50ec.png)
Looks good now
I think this was fixed by https://github.com/dashpay/dash/pull/3315

Thanks for opening the issue!
