### ISSUE TITLE
0.15.0.0-rc1 UI/UX Recent Transaction Arrows

### ISSUE THREAD

**Issue by tortugaverde98** [dashpay/dash#3243]
### Describe the issue
Recent Transactions should be easily understood at a glance. The arrow directions are confusing.

### Expected behaviour
Replace the incoming arrow with a big fat green plus sign.
Replace the outgoing arrow with a big fat red minus sign.

### Actual behaviour
Blue left and right arrows are confusing. Must then look at the amount to determine which arrow is which.

### What version of Dash Core are you using?
0.15.0.0-rc1

**Comment by PastaPastaPasta** [comment]
This has been resolved by just removing these arrows in v16, and instead using green/red coloring (not in rc3, but will be in .0 release)
