### ISSUE TITLE
0.15.0.0-rc1 Traditional theme could use a smidge more contrast (branding)

### ISSUE THREAD

**Issue by taw00** [dashpay/dash#3248]
Attached is a screenshot of the GUI wallet using the Traditional theme. The branding is almost invisible the contrast is so minimal. It could probably use a bit more oomph. Personally, I don't care for the Traditional theme, but, if we are going to have it, maybe improve it in this regard.

![Screenshot from 2019-12-20 10-00-09](https://user-images.githubusercontent.com/6908872/71268651-698a9380-231b-11ea-9739-76a905dc1a9c.png)

**Comment by PastaPastaPasta** [comment]
fixed by https://github.com/dashpay/dash/pull/3441
