### ISSUE TITLE
0.15.0.0-rc2 still has minor GUI issues on Windows HiDPI

### ISSUE THREAD

**Issue by strophy** [dashpay/dash#3311]
A few remaining GUI issues with Dash Core 0.15.0.0-rc2 under Windows 10 18363.592 x64 with 2880x1620 panel @ 150% scaling.

1. Splash screen appears blurry/scaled regardless of which theme is selected:
<img width="480" alt="startup" src="https://user-images.githubusercontent.com/32928115/73391601-206c1e80-428d-11ea-8aa5-aba8c710dea3.PNG">

2. Contrast issues also raised in #3248 in the traditional theme. Note that font size is correct here:
<img width="1440" alt="traditional" src="https://user-images.githubusercontent.com/32928115/73391870-a12b1a80-428d-11ea-87a0-4a1a5c7f8ddb.PNG">

3. Light theme finally looks good under Windows default settings without any scaling overrides applied! Tiny text problem (#2565) and truncated text is gone, but the GUI text is now scaled to 200% while system is set to 150%, so it looks comically large in contrast to system text, which can be seen in the menu. System scaling should be applied to all text, like in the traditional theme. Logo in top right corner also remains blurry/scaled.
<img width="1440" alt="light" src="https://user-images.githubusercontent.com/32928115/73392204-33cbb980-428e-11ea-9491-5eec78f718cb.PNG">

4. Dark theme has some issues with dark text on dark background, text size and tab colours, similar to #3242 :
<img width="577" alt="dark" src="https://user-images.githubusercontent.com/32928115/73392523-dc7a1900-428e-11ea-9f57-b30e987206eb.PNG">

**Comment by PastaPastaPasta** [comment]
@strophy Have these been fully resolved? I believe so, but please reopen if I'm wrong
