### ISSUE TITLE
Non-deterministic test failure is happening.

### ISSUE THREAD

**Issue by sarawut11** [dashpay/dash#3331]
### Describe the issue
When I run the functional test in local, non-deterministic test failure is happening.
Sometimes pass, sometimes fails and when it fails, the failed test case is different every time.
### Can you reliably reproduce the issue?
Yes, I can reproduce it in local.
#### If so, please list the steps to reproduce below:
1. Compile dash in ubuntu
2. sudo ./test/functional/test_runner.py --extended --exclude dbcrash,pruning

### Expected behaviour
All tests should be passed.

### Actual behaviour
Non-deterministic failure is happening.

### What version of Dash Core are you using?
v0.15 branch if Github Repo

### Machine specs:
- OS: ubuntu
- CPU: 4
- RAM: 8G
- Disk size: 100G
- Disk Type (HD/SDD): HD

### Extra Infos(logs)
TEST                           | STATUS    | DURATION
abandonconflict.py             | ✓ Passed  | 9 s
addressindex.py                | ✓ Passed  | 11 s
assumevalid.py                 | ✓ Passed  | 5 s
bip65-cltv-p2p.py              | ✓ Passed  | 4 s
bip68-112-113-p2p.py           | ✓ Passed  | 18 s
bip68-sequence.py              | ✓ Passed  | 14 s
bip9-softforks.py              | ✓ Passed  | 76 s
bipdersig-p2p.py               | ✓ Passed  | 4 s
bitcoin_cli.py                 | ✓ Passed  | 1 s
blockchain.py                  | ✓ Passed  | 5 s
decodescript.py                | ✓ Passed  | 1 s
dip3-deterministicmns.py       | ✓ Passed  | 42 s
dip4-coinbasemerkleroots.py    | ✓ Passed  | 39 s
disablewallet.py               | ✓ Passed  | 2 s
disconnect_ban.py              | ✓ Passed  | 2 s
example_test.py                | ✓ Passed  | 1 s
feature_shutdown.py            | ✓ Passed  | 2 s
forknotify.py                  | ✓ Passed  | 1 s
fundrawtransaction-hd.py       | ✓ Passed  | 35 s
fundrawtransaction.py          | ✓ Passed  | 26 s
getblocktemplate_longpoll.py   | ✓ Passed  | 66 s
getchaintips.py                | ✓ Passed  | 1 s
httpbasics.py                  | ✓ Passed  | 1 s
import-rescan.py               | ✓ Passed  | 4 s
importmulti.py                 | ✓ Passed  | 3 s
importprunedfunds.py           | ✓ Passed  | 1 s
invalidateblock.py             | ✓ Passed  | 6 s
invalidblockrequest.py         | ✓ Passed  | 1 s
invalidtxrequest.py            | ✓ Passed  | 2 s
keypool-hd.py                  | ✓ Passed  | 3 s
keypool-topup.py               | ✓ Passed  | 4 s
keypool.py                     | ✓ Passed  | 3 s
listsinceblock.py              | ✓ Passed  | 2 s
listtransactions.py            | ✓ Passed  | 7 s
llmq-chainlocks.py             | ✖ Failed  | 43 s
llmq-dkgerrors.py              | ✓ Passed  | 44 s
llmq-is-cl-conflicts.py        | ✓ Passed  | 27 s
llmq-is-retroactive.py         | ✓ Passed  | 119 s
llmq-signing.py                | ✓ Passed  | 36 s
llmq-simplepose.py             | ✓ Passed  | 37 s
maxuploadtarget.py             | ✓ Passed  | 37 s
mempool_limit.py               | ✓ Passed  | 4 s
mempool_packages.py            | ✓ Passed  | 8 s
mempool_persist.py             | ✓ Passed  | 8 s
mempool_reorg.py               | ✓ Passed  | 2 s
mempool_resurrect_test.py      | ✓ Passed  | 1 s
mempool_spendcoinbase.py       | ✓ Passed  | 1 s
merkle_blocks.py               | ✓ Passed  | 2 s
minchainwork.py                | ✓ Passed  | 4 s
mining.py                      | ✓ Passed  | 1 s
multi_rpc.py                   | ✓ Passed  | 3 s
multikeysporks.py              | ✓ Passed  | 14 s
multiwallet.py                 | ✓ Passed  | 3 s
net.py                         | ✓ Passed  | 1 s
nulldummy.py                   | ✓ Passed  | 2 s
p2p-acceptblock.py             | ✓ Passed  | 3 s
p2p-compactblocks.py           | ✓ Passed  | 16 s
p2p-fingerprint.py             | ✓ Passed  | 8 s
p2p-fullblocktest.py           | ✓ Passed  | 80 s
p2p-instantsend.py             | ✓ Passed  | 36 s
p2p-leaktests.py               | ✓ Passed  | 6 s
p2p-mempool.py                 | ✓ Passed  | 1 s
p2p-timeouts.py                | ✓ Passed  | 63 s
p2p-versionbits-warning.py     | ✓ Passed  | 8 s
preciousblock.py               | ✓ Passed  | 1 s
prioritise_transaction.py      | ✓ Passed  | 3 s
proxy_test.py                  | ✓ Passed  | 1 s
rawtransactions.py             | ✓ Passed  | 13 s
receivedby.py                  | ✓ Passed  | 10 s
reindex.py                     | ✓ Passed  | 3 s
resendwallettransactions.py    | ✓ Passed  | 1 s
rest.py                        | ✓ Passed  | 8 s
rpc_getblockstats.py           | ✓ Passed  | 1 s
rpcbind_test.py                | ✓ Passed  | 35 s
rpcnamedargs.py                | ✓ Passed  | 1 s
sendheaders.py                 | ✓ Passed  | 23 s
signmessages.py                | ✓ Passed  | 1 s
signrawtransactions.py         | ✓ Passed  | 1 s
smartfees.py                   | ✓ Passed  | 167 s
spentindex.py                  | ✓ Passed  | 8 s
sporks.py                      | ✓ Passed  | 8 s
timestampindex.py              | ✓ Passed  | 4 s
txindex.py                     | ✓ Passed  | 4 s
txn_clone.py                   | ✓ Passed  | 2 s
txn_clone.py --mineblock       | ✓ Passed  | 1 s
txn_doublespend.py             | ✓ Passed  | 2 s
txn_doublespend.py --mineblock | ✓ Passed  | 2 s
uptime.py                      | ✓ Passed  | 1 s
wallet-accounts.py             | ✓ Passed  | 3 s
wallet-dump.py                 | ✓ Passed  | 19 s
wallet-encryption.py           | ✓ Passed  | 7 s
wallet-hd.py                   | ✓ Passed  | 22 s
wallet.py                      | ✓ Passed  | 25 s
walletbackup.py                | ✓ Passed  | 125 s
zapwallettxes.py               | ✓ Passed  | 3 s
zmq_test.py                    | ✓ Passed  | 3 s
ALL                            | ✖ Failed  | 1528 s (accumulated) 
Runtime: 392 s
(python-virtualenv) me@me:~/Documents/dash$

**Comment by 10xcryptodev** [comment]
Tests are passing
steps to reproduce below:

sudo ./test/functional/test_runner.py --extended --exclude dbcrash,pruning

What version of Dash Core are you using?
commit: 087d984

Extra Infos(logs)
TEST | STATUS | DURATION
abandonconflict.py             | ✓ Passed  | 5 s
addressindex.py                | ✓ Passed  | 7 s
assumevalid.py                 | ✓ Passed  | 6 s
bip65-cltv-p2p.py              | ✓ Passed  | 10 s
bip68-112-113-p2p.py           | ✓ Passed  | 10 s
bip68-sequence.py              | ✓ Passed  | 10 s
bipdersig-p2p.py               | ✓ Passed  | 9 s
bitcoin_cli.py                 | ✓ Passed  | 2 s
blockchain.py                  | ✓ Passed  | 8 s
conf_args.py                   | ✓ Passed  | 3 s
decodescript.py                | ✓ Passed  | 1 s
deprecated_rpc.py              | ✓ Passed  | 1 s
dip3-deterministicmns.py       | ✓ Passed  | 26 s
dip4-coinbasemerkleroots.py    | ✓ Passed  | 24 s
disablewallet.py               | ✓ Passed  | 1 s
disconnect_ban.py              | ✓ Passed  | 2 s
example_test.py                | ✓ Passed  | 1 s
feature_help.py                | ✓ Passed  | 0 s
feature_logging.py             | ✓ Passed  | 4 s
feature_shutdown.py            | ✓ Passed  | 1 s
fundrawtransaction-hd.py       | ✓ Passed  | 10 s
fundrawtransaction.py          | ✓ Passed  | 8 s
getblocktemplate_longpoll.py   | ✓ Passed  | 66 s
getchaintips.py                | ✓ Passed  | 2 s
httpbasics.py                  | ✓ Passed  | 1 s
import-rescan.py               | ✓ Passed  | 3 s
importmulti.py                 | ✓ Passed  | 4 s
importprunedfunds.py           | ✓ Passed  | 2 s
invalidateblock.py             | ✓ Passed  | 6 s
invalidblockrequest.py         | ✓ Passed  | 1 s
invalidtxrequest.py            | ✓ Passed  | 6 s
keypool-hd.py                  | ✓ Passed  | 4 s
keypool-topup.py               | ✓ Passed  | 4 s
keypool.py                     | ✓ Passed  | 4 s
listsinceblock.py              | ✓ Passed  | 4 s
listtransactions.py            | ✓ Passed  | 2 s
llmq-chainlocks.py             | ✓ Passed  | 38 s
llmq-connections.py            | ✓ Passed  | 28 s
llmq-dkgerrors.py              | ✓ Passed  | 29 s
llmq-is-cl-conflicts.py        | ✓ Passed  | 18 s
llmq-is-retroactive.py         | ✓ Passed  | 107 s
llmq-signing.py                | ✓ Passed  | 24 s
llmq-signing.py --spork21      | ✓ Passed  | 33 s
llmq-simplepose.py             | ✓ Passed  | 74 s
maxuploadtarget.py             | ✓ Passed  | 27 s
mempool_limit.py               | ✓ Passed  | 7 s
mempool_packages.py            | ✓ Passed  | 4 s
mempool_persist.py             | ✓ Passed  | 7 s
mempool_reorg.py               | ✓ Passed  | 2 s
mempool_resurrect_test.py      | ✓ Passed  | 2 s
mempool_spendcoinbase.py       | ✓ Passed  | 1 s
merkle_blocks.py               | ✓ Passed  | 5 s
minchainwork.py                | ✓ Passed  | 5 s
mining.py                      | ✓ Passed  | 1 s
multi_rpc.py                   | ✓ Passed  | 2 s
multikeysporks.py              | ✓ Passed  | 16 s
multiwallet.py                 | ✓ Passed  | 7 s
multiwallet.py --usecli        | ✓ Passed  | 154 s
net.py                         | ✓ Passed  | 2 s
node_network_limited.py        | ✓ Passed  | 12 s
notifications.py               | ✓ Passed  | 3 s
nulldummy.py                   | ✓ Passed  | 3 s
p2p-acceptblock.py             | ✓ Passed  | 5 s
p2p-compactblocks.py           | ✓ Passed  | 14 s
p2p-fingerprint.py             | ✓ Passed  | 7 s
p2p-fullblocktest.py           | ✓ Passed  | 117 s
p2p-instantsend.py             | ✓ Passed  | 12 s
p2p-leaktests.py               | ✓ Passed  | 6 s
p2p-mempool.py                 | ✓ Passed  | 2 s
p2p-timeouts.py                | ✓ Passed  | 63 s
p2p-versionbits-warning.py     | ✓ Passed  | 10 s
preciousblock.py               | ✓ Passed  | 1 s
prioritise_transaction.py      | ✓ Passed  | 9 s
privatesend.py                 | ✓ Passed  | 1 s
proxy_test.py                  | ✓ Passed  | 3 s
rawtransactions.py             | ✓ Passed  | 3 s
receivedby.py                  | ✓ Passed  | 2 s
reindex.py                     | ✓ Passed  | 3 s
resendwallettransactions.py    | ✓ Passed  | 1 s
rest.py                        | ✓ Passed  | 2 s
rpc_getblockstats.py           | ✓ Passed  | 1 s
rpcbind_test.py                | ✓ Passed  | 36 s
rpcnamedargs.py                | ✓ Passed  | 1 s
sendheaders.py                 | ✓ Passed  | 20 s
signmessages.py                | ✓ Passed  | 1 s
signrawtransactions.py         | ✓ Passed  | 1 s
smartfees.py                   | ✓ Passed  | 45 s
spentindex.py                  | ✓ Passed  | 5 s
sporks.py                      | ✓ Passed  | 8 s
timestampindex.py              | ✓ Passed  | 4 s
txindex.py                     | ✓ Passed  | 5 s
txn_clone.py                   | ✓ Passed  | 2 s
txn_clone.py --mineblock       | ✓ Passed  | 2 s
txn_doublespend.py             | ✓ Passed  | 2 s
txn_doublespend.py --mineblock | ✓ Passed  | 2 s
uacomment.py                   | ✓ Passed  | 3 s
uptime.py                      | ✓ Passed  | 1 s
wallet-accounts.py             | ✓ Passed  | 3 s
wallet-dump.py                 | ✓ Passed  | 11 s
wallet-encryption.py           | ✓ Passed  | 7 s
wallet-hd.py                   | ✓ Passed  | 20 s
wallet.py                      | ✓ Passed  | 16 s
walletbackup.py                | ✓ Passed  | 13 s
zapwallettxes.py               | ✓ Passed  | 4 s
zmq_test.py                    | ✓ Passed  | 2 s

ALL                            | ✓ Passed  | 1345 s (accumulated)

**Comment by PastaPastaPasta** [comment]
Ran tests three times on develop (087d98477bc86209cb0d1e426580dbd0ab3561ef) and seeing no failures. Recent test fixes has resolved this issue

**Comment by PastaPastaPasta** [comment]
These test failures were likely fixed by https://github.com/dashpay/dash/pull/3410 and https://github.com/dashpay/dash/pull/3422 or potentially other PRs.

As noted by myself a few weeks ago and 10xcryptodev, the extended test suite, besides pruning.py (see https://github.com/dashpay/dash/issues/3440) seem to be passing. 

Please reopen this issue, or another issue if you are still getting test failures.

Thanks for reporting this issue!
