### ISSUE TITLE
0.15.0.0 Privatesend multi-session not enabled by default

### ISSUE THREAD

**Issue by forro68** [dashpay/dash#3339]
### Describe the issue
Privatesend multi-session is not enabled by default.

#### If so, please list the steps to reproduce below:
1. Launch Dash application.
2. Look in Settings/Options/Wallet.
3. Checkbox  enable privatesend multisession is not checked.

### Expected behaviour
It should be checked by default.

### Actual behaviour
It is not checked.

### What version of Dash Core are you using?
0.15.0.0

**Comment by nmarley** [comment]
This one seems pretty simple to implement, just switch the default to "on".

@UdjinM6 Any reason (e.g. privacy concerns or something) why we shouldn't change the default for this setting?

**Comment by PastaPastaPasta** [comment]
I believe at one point there was a concern regarding going through keys too rapidly.

**Comment by forro68** [comment]
> I believe at one point there was a concern regarding going through keys too rapidly.

Would it be possible to have it automatically create a new backup after replenishing the keys? For the user's sake, privatesend must be fast and 'grandma proof'.

**Comment by forro68** [comment]
See PR [3343](https://github.com/dashpay/dash/pull/3343)

No idea how to trigger an automatic backup when low on keys.

**Comment by thephez** [comment]
@PastaPastaPasta This will become a non-issue if we switch to HD wallets at some point, correct? I think Bitcoin Core did that in 0.16 (new wallets default to HD). Of course that would require checking if the wallet was HD or not since older wallets do not auto-upgrade to HD.

**Comment by forro68** [comment]
Closing for now, will reopen when bitcoin backports catch up and we have HD wallets.
