### ISSUE TITLE
0.15 Lite mode downloads full blockchain.

### ISSUE THREAD

**Issue by forro68** [dashpay/dash#3341]
Dash lite mode downloads the full blockchain. To a non-technical user, Lite mode implies that the blockchain will not be downloaded.

#### If so, please list the steps to reproduce below:
1. Launch dash: ./dashcore-0.15.0/bin/dash-qt --litemode --enableprivatesend
2. Received popup warning: You are starting in lite mode, most Dash-specific functionality is disabled.
3. Allow dashcore to sync until it hit 1gb. Close dash. Submit github issue.

### Expected behaviour
Blockchain is not downloaded.

### Actual behaviour
Blockchain is downloaded.

### What version of Dash Core are you using?
0.15

**Comment by UdjinM6** [comment]
I think there is a confusion of what `litemode` actually means, pls see `--help`: `Disable all Dash specific functionality (Masternodes, PrivateSend, InstantSend, Governance)`. It's NOT an SPV mode.

**Comment by forro68** [comment]
Yes, I assumed it was an SPV or dapi type light wallet. Hopefully in the future this can be made real.

**Comment by forro68** [comment]
There is hope:
[Litemode changes #3488](https://github.com/dashpay/dash/pull/3488)

**Comment by PastaPastaPasta** [comment]
please follow https://github.com/dashpay/dash/issues/3485 and the PR you mentioned.

Closing as this issue is a duplicate/already resolved.
