### ISSUE TITLE
Cant compile windows 64 bit depends - gmp

### ISSUE THREAD

**Issue by akshaynexus** [dashpay/dash#3351]
### Describe the issue
The windows 64 bit depends wont compile and fail at compiling the gmp dependency
#### If so, please list the steps to reproduce below:
1.try to build windows64 bit depends
2.Wait until it fails at gmp with error 
`checking for build system executable suffix... configure: error: Cannot determine executable suffix`

### Expected behaviour
It should build depends successfully.
### Actual behaviour
Fails at compiling dmp dependency with error 
`checking for build system executable suffix... configure: error: Cannot determine executable suffix`
### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Dash Core are you using?
latest commit from develop branch 9d5c3d12ebebc63870bd0e748a94f67410e7b065

### Machine specs:
OS: Ubuntu 19.10 eoan
Kernel: x86_64 Linux 5.3.0-40-generic
Uptime: 18h 42m
Packages: 2126
Shell: bash 5.0.3
CPU: AMD Ryzen Threadripper 2950X 16-Core @ 32x 3.5GHz [49.2°C]
GPU: GeForce RTX 2060, GeForce RTX 2070 SUPER
RAM: 2977MiB / 32024MiB

### Any extra information that might be useful in the debugging process.
https://gist.github.com/akshaynexus/5b9f8f98f8f8d12196bc6df12e51d185

**Comment by UdjinM6** [comment]
I can't reproduce this... Make sure to follow steps in https://github.com/dashpay/dash/blob/master/doc/build-cross.md#windows-64bit32bit-cross-compilation
