### ISSUE TITLE
Reliably Corrupt Wallet

### ISSUE THREAD

**Issue by PastaPastaPasta** [dashpay/dash#3356]
#### If so, please list the steps to reproduce below:
1. Have two wallets, wallet.dat and corrupt_wallet.dat
2. `./dash-qt` 
	opens wallet with wallet.dat
3. while initial dash-qt is open, `./dash-qt -wallet="corrupt_wallet.dat"`
	pop up will come up about not being able to lock onto the directory
4. close popup and let second dash-qt close
5. close initial dash-qt
6. `./dash-qt -wallet="corrupt_wallet.dat"` the wallet will be corrupted

### Expected behaviour
Wallet is not corrupted

### Actual behaviour
Wallet is corrupted

### What version of Dash Core are you using?
0.15.0.0

### Machine specs:
- OS: Windows 10

**Comment by xdustinface** [comment]
Hmm couldn't reproduce this. Tried macOS and Win10 with `0.15` and current `develop`,  all with clean wallets. But i didn't get a corrupted wallet. Are you sure there wasn't something else going on with the wallet or so when you run into this?

**Comment by PastaPastaPasta** [comment]
Hmmm, I can't reproduce it now... This is weird...

**Comment by PastaPastaPasta** [comment]
I'm gonna go ahead and close this, because I am not longer able to reproduce
