### ISSUE TITLE
Feat. request for Dash Platform: `quorum sign` rpc command with additional quorumHash

### ISSUE THREAD

**Issue by Cofresi** [dashpay/dash#3424]
The platform validators (which are congruent with an LLMQ) need to be able to sign a platform block. We plan to use the existing internal api Sign method described here:
https://github.com/dashpay/dips/blob/master/dip-0007.md#void-signuint256-quorumhash-uint256-id-uint256-msghash

and implemented here:
https://github.com/dashpay/dash/blob/master/src/llmq/quorums_signing_shares.cpp#L1394

Currently it is not possible to specify a particular quorum that needs to sign. The quorum is selected by a random internal mechanism. We suggest adding an additional optional parameter `quorumHash` to the rpc method to be able for an external process which makes use of LLMQs to specify which quorum should sign.

**Comment by PastaPastaPasta** [comment]
Implemented in https://github.com/dashpay/dash/pull/3446
