### ISSUE TITLE
Feat. request for Dash Platform: change `protx diff` rpc cmd output to include member bitmap and complete qc fields

### ISSUE THREAD

**Issue by Cofresi** [dashpay/dash#3425]
For the platform light client to be able to completely verify the quorum list with additional member information (needed for LLMQ health metrics in platform validator rotation process) the output of the `protx diff` command needs to include all quorum commitment fields plus the signature.

**Comment by PastaPastaPasta** [comment]
fixed by https://github.com/dashpay/dash/pull/3468
