### ISSUE TITLE
SporkAddress

### ISSUE THREAD

**Issue by MonkeyD-Core** [dashpay/dash#3455]
Can someone tell me how can i get the sporkaddress ?
i cant go to debug console becouse the wallet cannof start.
Thanks

**Comment by thephez** [comment]
Not sure this is what you are asking for, but you can see the spork addresses in chainparams.cpp (e.g. for [mainnet](https://github.com/dashpay/dash/blob/master/src/chainparams.cpp#L364)).

**Comment by MonkeyD-Core** [comment]
Yup sir, im asking about that.. how can i get the sporkaddress to fill in the chainparams.cpp ?

Thanks you for the respond

**Comment by thephez** [comment]
Oh, you are trying to modify it. I guess you could probably run [getnewaddress](https://dashcore.readme.io/docs/core-api-ref-remote-procedure-calls-wallet#section-get-new-address) via dash-cli (assuming dashd is working and it is only dash-qt that you cannot start).

**Comment by MonkeyD-Core** [comment]
i got massage on telegram say the dash developer not supporting fork again

"I'm not supporting forks and as far as I know Dash core group also stopped supporting fork developers due to limited resources"

i want to learn about forking dash, i learn it on google but doesnt not get the solution for the sporkaddress.. im so sad for this one.

Thanks for your respond.

**Comment by MonkeyD-Core** [comment]
![Screenshot_2020-04-25-15-44-16-22](https://user-images.githubusercontent.com/62377315/80282162-7c3a2c80-8742-11ea-9cac-c54aac846f92.png)
The wallet & daemon doesnt not work

**Comment by 10xcryptodev** [comment]
You you already have a address generated in your new chain you can change the spork address on in chainparams.cpp
If you never generated a new address on your chain, you need to remove this spork address validation, generate the new address as @thephez described, change the in chainparams.cpp and add back the spork address validation to make sure the address you generated is valid

**Comment by MonkeyD-Core** [comment]
i trying to remove the spork address before, set the verification as false and minimum spork as 0

i cant generate the new address becouse the daemon still giving invalid spork address when i start the daemon

now i try to set up back
the minspork to 1 , verification to true
but changin on letter on the dash spork address with my preffix

**Comment by MonkeyD-Core** [comment]
I dont know where is the sporkaddress verification.
Thanks for the respond.

**Comment by MonkeyD-Core** [comment]
![Screenshot_2020-04-25-22-36-07-77](https://user-images.githubusercontent.com/62377315/80282646-30d54d80-8745-11ea-8717-db6313917bbe.png)

**Comment by nmarley** [comment]
You need to change the network to regtest or make your own devnet, otherwise the incoming sporks won't match your new address. Verification logic should all be in spork.cpp. It syncs sporks via getsporks message in the masternode sync process.

I think you're probably biting off a bit too much all at once. I'd recommend starting by using a devnet (read up in the docs on how to do this) or using regtest to start out, otherwise things will fail b/c you're having to coordinate too many moving parts at once (e.g. network magic, port numbers, etc.).

**Comment by MonkeyD-Core** [comment]
Yup, i got the spork address 😚😚😚
But my peer cannot connected now 😆
Very interesting !

**Comment by PastaPastaPasta** [comment]
@MonkeyD-Core Have you figured this out? Is this issue resolved/able to be closed?
