### ISSUE TITLE
[Improvement] Parse URI when pasted into address field

### ISSUE THREAD

**Issue by PastaPastaPasta** [dashpay/dash#3474]
When pasting a URI into the address field, all information should auto fill, address, amount, etc.

I was unable to find a patch upstream which does this

Please see video: https://www.youtube.com/watch?v=1lIPihP1S_E for the UX electrum dash has and the current UX that Dash Core has.

**Comment by xdustinface** [comment]
There is also the "File -> Open URI..." action in the menu to paste URI's in a more convenient way compared to how he is doing it in the video. 

<img width="304" alt="Bildschirmfoto 2020-05-11 um 11 48 46" src="https://user-images.githubusercontent.com/35775977/81548488-acf2a680-937d-11ea-9956-9673290798b6.png">
<img width="676" alt="Bildschirmfoto 2020-05-11 um 11 48 53" src="https://user-images.githubusercontent.com/35775977/81548501-b0862d80-937d-11ea-93d4-926f98cab73b.png">



If we still want to have the "Paste an URI into the address field" thing i can add this for sure. Other opinions?

**Comment by UdjinM6** [comment]
Yep, "Open URI" does exactly this - parses URI and fills all the fields. But I agree, parsing an URI pasted into "Pay To" would make user experience a bit (much?) better.
