### ISSUE TITLE
Paying to a BIP70 invoice shouldn't throw an error

### ISSUE THREAD

**Issue by PastaPastaPasta** [dashpay/dash#3481]
Please see the video: https://youtu.be/dmRXdt_F81I

There error thrown is: "Error communicating with ... [URL] Error transferring [URL]... - server replied: Unsupported Media Type."

None of the other apps are throwing any errors, it is possible this is an anypay side problem and I have sent them this issue so they can respond about their server setup.

**Comment by 10xcryptodev** [comment]
BIP70 is not supported after bitcoin#17165 is valid fix this error?

**Comment by PastaPastaPasta** [comment]
The reason that bitcoin devs had for #17165 we don't really agree with. BIP70 has it place, and as such I believe we are going to continue to support it and bypass that PR

**Comment by PastaPastaPasta** [comment]
Bip70 has been removed

**Comment by riongull** [comment]
Why was BIP70 support removed from Dash?  

I'm not necessarily opposed to this decision, but this seems important enough to explain.

**Comment by riongull** [comment]
Related:

https://github.com/dashpay/dash/pull/4023

**Comment by PastaPastaPasta** [comment]
That should've answered those questions. Feel free to ask any follow up questions you may have

**Comment by riongull** [comment]
@PastaPastaPasta I was hoping for a narrative description. It appears you wanted to drop the OpenSSL dependency, but how are we justifying removing the BIP70 feature?  Was it not used, not secure, something else?
