### ISSUE TITLE
Privatesend mixing - randomize rounds

### ISSUE THREAD

**Issue by forro68** [dashpay/dash#3525]
Set a minimum and maximum range of mixing rounds, default perhaps 8 to 16 rounds. Coins are then mixed anywhere between 8 to 16 rounds. When sending from privatesend, any coin that meets the lower bound is eligible to send. Increases difficulty of analysis?

**Comment by PastaPastaPasta** [comment]
Imo this has mostly been done by 3661. Go ahead an reopen if there is more you'd like to see done
