### ISSUE TITLE
long living quorum question

### ISSUE THREAD

**Issue by sidhujag** [dashpay/dash#3544]
Hey guys,

Great work on the LLQM stuff! I just wanted some clarification on how the PoSe works. There is a LLQM that is mined every 24 blocks (https://github.com/dashpay/dash/blob/master/src/chainparams.cpp#L163) 

Is this the one responsible for PoSe not taking into account IS/DS/chainlocks? Or is there an inherent assumption that a service like chainlocks will circulate through masternodes by association because it consumes the LLQM? I guess I'm wondering if the 50_60 LLQM is self-sufficient in finding inactive MN's or does it require services to use them. That will help me better understand how it works exactly from a high-level.

If it does require 50 masternodes to sign off every hour I can see it will circulate through 5000 masternodes in ~100 hours, a payment cycle being ~208 hours so you get 2 checks on average every round which is consistent to your documentation.

**Comment by UdjinM6** [comment]
The most of current PoSe logic is basically in these two function https://github.com/dashpay/dash/blob/master/src/evo/deterministicmns.cpp#L845-L880 which works for every quorum commitment mined for all quorums - for every quorum member see if it is included into the valid members list for that quorum in a commitment that was mined and if not apply some score to it. Then you just reduce this score by 1 every next block to let it "heal" itself unless the the score is above "max" in which case the node is PoSe-banned and must be revived manually.

**Comment by sidhujag** [comment]
@UdjinM6 is the one created every hour exercising this code or does it need chainlock for example to leverage the quorum to get here?

**Comment by UdjinM6** [comment]
Every quorum is created via DKG which results in a single "final" mined commitments (or a "null" commitment of DKG failed for some reason). The "punish" code is executed for every commitment that was mined, the "decrease" code is executed on every block.

**Comment by sidhujag** [comment]
Thanks I can see how it makes uptime provability more efficient I hated the mnping bandwidth bloat.  I guess each service (chainlock, instant send inputs) need to do a DKG based on params of the LLQM for a tx coinbase commitment.

I also wonder why you removed the height in the coinbase and use it in ccbtx.. is this just semantics deduplicating the height or something more?

**Comment by UdjinM6** [comment]
Every new/revived masternode goes to the end of the queue, it will only be paid after everyone else i.e. after `mn count` blocks (well, more or less - this is only true if you are ignoring the fact that some of currently online MNs might be pose-banned or disbanded, but you get the idea).

re height in coinbase tx: https://github.com/dashpay/dips/blob/master/dip-0004.md#height-in-cbtx-and-deprecation-of-bip34
