### ISSUE TITLE
typo in CSigningManager::VerifyRecoveredSig

### ISSUE THREAD

**Issue by sidhujag** [dashpay/dash#3545]
https://github.com/dashpay/dash/blob/master/src/llmq/quorums_signing.cpp#L922 passes in llmqTypeChainLocks when I think you meant to pass in llmqType, actually this variable is not needed as type is the only thing used you can pass in llmqType directly.

Was initially put in by @codablock here https://github.com/dashpay/dash/commit/4026ea203

**Comment by PastaPastaPasta** [comment]
fixed by #3546
