### ISSUE TITLE
Masternode Tab should work with nowallet

### ISSUE THREAD

**Issue by PastaPastaPasta** [dashpay/dash#3576]
`./dash-qt --nowallet` and see that the Masternode tab isn't accessible. I don't see any reason why it shouldn't work.

**Comment by linuxsh2** [comment]
@PastaPastaPasta I'd like to grab this issue if no one is working on it.

**Comment by PastaPastaPasta** [comment]
Sounds good, consider it yours :)

**Comment by linuxsh2** [comment]
@PastaPastaPasta This was done/merged in https://github.com/dashpay/dash/pull/4318
