### ISSUE TITLE
cli masternode status fail for node behind firewall

### ISSUE THREAD

**Issue by mrobinton** [dashpay/dash#3586]

**Comment by mrobinton** [comment]
node behind firewall example
rpcbind=127.0.0.1
rpcport=9998
bind=192.168.1.123
port=9999
masternodeaddr=44.55.66.77:9999
externalIP=44.55.66.77

masternode is behind firewall with inbound port redirected
44.55.66.77:9999 => 192.168.1.123:9999

Other cli commands work normally, this one fails
cli masternode status

{
  "outpoint": "0000000000000000000000000000000000000000000000000000000000000000-4294967295",
  "service": "44.55.66.77:9999",
  "state": "ERROR",
  "status": "Error. Could not connect to 44.55.66.77:9999"
}

error string from activemasternode.cpp
            strError = "Could not connect to " + activeMasternodeInfo.service.ToString();
            LogPrintf("CActiveDeterministicMasternodeManager::Init -- ERROR: %s\n", strError);

This should not be called for mn behind firewall, it is guaranteed to fail.

**Comment by mrobinton** [comment]
This breaks sentinel which requires the ability to check the masternode status

**Comment by PastaPastaPasta** [comment]
I presume you have `-masternodeblsprivkey` set correct? It sounds like it because you say that the MN is working and getting paid

**Comment by PastaPastaPasta** [comment]
Closing due to no response
