### ISSUE TITLE
[0.16.0.0-rc2] Mixing TXes of type Payment to yourself show up in the Overview tab

### ISSUE THREAD

**Issue by kxcd** [dashpay/dash#3597]
### Describe the issue
Mixing TXes of type Payment to yourself show up in the Overview tab.
### Can you reliably reproduce the issue?
yes, just mix a bunch for a while on testnet
#### If so, please list the steps to reproduce below:
1.mix 
2.mix
3.wait

### Expected behaviour
They should be filtered from the Overview tab since there are automatic TXes and not actually user created as such.

### Actual behaviour
They get displayed.

### Screenshots.
![image](https://user-images.githubusercontent.com/20513885/87016365-f5a9cd00-c211-11ea-8be9-8ca8549adf27.png)

also, https://www.dash.org/forum/threads/v0-16-testing.50294/page-2#post-222595

### What version of Dash Core are you using?
[0.16.0.0-rc2]

### Machine specs:
N/A

### Any extra information that might be useful in the debugging process.
N/A

**Comment by xdustinface** [comment]
Fixed by #3657
