### ISSUE TITLE
How can I use Redis DB instead of level DB

### ISSUE THREAD

**Issue by ValeryKrapiv1130** [dashpay/dash#3608]
I'd like to store indexes not in **level DB** but in **Redis** (in memory). 
The goal is to create code that as less as it is possible to changes existing codebase (replacing/changing only needed parts of code for easy portability to future versions).
I need help if it is possible to code only in **dbwrapper.h** and **dbwrapper.cpp**.
Thanks.

**Comment by PastaPastaPasta** [comment]
I'm sorry @ValeryKrapiv1130, we don't support Redis, however, checkout https://github.com/Flenst/DASH-Tools, I think he parsed the chain using both MongoDB and Redis.

**Comment by ValeryKrapiv1130** [comment]
Hi @PastaPastaPasta!
Thanks for your replay.
I have just use Resid for storing chain indices. Is it possible?

**Comment by PastaPastaPasta** [comment]
Not sure. The link that I gave you is the best advise I know of
