### ISSUE TITLE
InstantX transaction status after restart wallet

### ISSUE THREAD

**Issue by poiuty** [dashpay/dash#371]
If we send coins with InsnatX and restart wallet - all this transactions display as normal.
So we need check status after restart wallet.

**Comment by evan82** [comment]
It's on the todo list, there's actually a lot of changes I would like to make to instantX. It should save the transaction list locally on disk, then load on startup. It also should hold transactions until they confirm six times, at which point they are safe to remove. This way even if it takes a week to get them into a block, the inputs are safe from double spends. Also, it should have a floating fee -- I was thinking 2x the average fee to get a transaction into a block. All of those changes should make it much, much more robust. Maybe 12.1 :+1:
