### ISSUE TITLE
Unchecked signhash in ProcessMessageSigSesAnn

### ISSUE THREAD

**Issue by sidhujag** [dashpay/dash#3757]
Hey guys,

There is an unchecked variable here, was it intended to be verified against quorum pubkey?

https://github.com/dashpay/dash/blob/develop/src/llmq/quorums_signing_shares.cpp#L338

**Comment by UdjinM6** [comment]
No, it was only meant to be used as an id here I think. Can/should be dropped because `GetOrCreateSessionFromAnn` takes care of it already and this one is just a leftover from previous refactoring/commit split I guess.

**Comment by sidhujag** [comment]
this call you mean https://github.com/dashpay/dash/blob/develop/src/llmq/quorums_signing_shares.cpp#L130?

I don't see where it verified it there?

**Comment by UdjinM6** [comment]
I mean, there is no signature to verify at this point. We use it simply as a unique (yet deterministic) session id, there is nothing to check here.

**Comment by sidhujag** [comment]
ok thanks
