### ISSUE TITLE
Unused invType for CDKGSessionHandler

### ISSUE THREAD

**Issue by sidhujag** [dashpay/dash#3758]
https://github.com/dashpay/dash/blob/master/src/llmq/quorums_dkgsessionhandler.cpp#L93

Creates CDKGSessionHandler with an invType but this invType is never checked. Is this OK? remove?

**Comment by UdjinM6** [comment]
We use it here https://github.com/dashpay/dash/blob/master/src/llmq/quorums_dkgsessionhandler.cpp#L54

**Comment by sidhujag** [comment]
Ahh makes sense should have checked that, in my code as per latest Bitcoin invtype's are removed from cinv and so I just use the hash to remove from network related buffers and so I didn't need the invtype, 

see: https://github.com/syscoin/syscoin/blob/dev-4.x/src/llmq/quorums_dkgsessionhandler.cpp#L54

And EraseOtherRequest is here: https://github.com/syscoin/syscoin/blob/dev-4.x/src/net_processing.cpp#L898

You may end up solving it the same way.
