### ISSUE TITLE
polymorphic classes not using a virtual destructor

### ISSUE THREAD

**Issue by sidhujag** [dashpay/dash#3759]
I get a bunch of warnings on these classes for not having a virtual destructor for BLSWrapper:

https://github.com/dashpay/dash/blob/master/src/bls/bls.h#L34

You should consider adding virtual dtors for CBLSWrapper, it may mean derived classes aren't deleted if base class pointer is deleted.

**Comment by PastaPastaPasta** [comment]
Hey @sidhujag, sounds reasonable, feel free to open a PR and we can evaluate it
