### ISSUE TITLE
rpc call to create a wallet?

### ISSUE THREAD

**Issue by thestick613** [dashpay/dash#3760]
What is the RPC call to create a new wallet? Can a dash node manage multiple wallets?

**Comment by PastaPastaPasta** [comment]
The PR that introduces `createwallet` rpc was bitcoin#13058. This is not included in Dash v0.16, however, likely will be included in v0.17

**Comment by thestick613** [comment]
It seems dash core can't handle multiple wallets easily enough ... yet.

**Comment by PastaPastaPasta** [comment]
This is a duplicate of https://github.com/dashpay/dash/issues/2657, so I'm gonna close this one. Feel free to open a new issue if you have any other problems (or comment on that issue)
