### ISSUE TITLE
[qt] Abnormal non-deterministic scaling of Settings text

### ISSUE THREAD

**Issue by PastaPastaPasta** [dashpay/dash#3767]
This was happening on 34a146c5c8e5e5242c92b297f70ac9fbe82fc842, a commit in https://github.com/dashpay/dash/pull/3682, however I have no reason to believe that it is related to that PR.

See the video showing these weird scaling stuff. Happening on Ubuntu 18.04
https://youtu.be/_i7BNwukRU4

**Comment by qwizzie** [comment]
Does your balances part of the screen also move to the right (below Send) if you maximize your window ? 
See : https://www.dash.org/forum/threads/dash-core-v0-16-has-been-released.50752/#post-223598

**Comment by PastaPastaPasta** [comment]
> Maybe unrelated to this specific issue, but i have noticed that under Windows 10 the Balances and PrivateSend part of the screen move to the right (below Send), if you maximize your wallet window.
> 
> See : https://www.dash.org/forum/threads/dash-core-v0-16-has-been-released.50752/#post-223598
> 
> I am wondering if that is also the case with Ubuntu 18.04 (qt) ?
See my response in the forum.

**Comment by UdjinM6** [comment]
Reproduced the issue on develop, Ubuntu 20.04. Wasn't able to reproduce this on mac or windows, seems to work fine on these OSes for me.

**Comment by UdjinM6** [comment]
@PastaPastaPasta Pls try https://github.com/UdjinM6/dash/commit/ba01e4c4589497247e12cac49feadc4508b523df. If I'm right and the root of the issue is dead pointers in maps then it's not just Options dialog which is broken...
