### ISSUE TITLE
EraseObjectRequest missing from CSigningManager::ProcessMessageRecoveredSig

### ISSUE THREAD

**Issue by sidhujag** [dashpay/dash#3779]
Is there a reason for no EraseObjectRequest in this function? https://github.com/dashpay/dash/blob/develop/src/llmq/quorums_signing.cpp#L482

I do see it in the other function which receives an CInv https://github.com/dashpay/dash/blob/develop/src/llmq/quorums_signing.cpp#L680 its just missing from ProcessMessageRecoveredSig.

**Comment by PastaPastaPasta** [comment]
Thanks for reporting the issue! It's now been fixed
