### ISSUE TITLE
potential deadlock in spork.cpp

### ISSUE THREAD

**Issue by sidhujag** [dashpay/dash#3814]
https://github.com/dashpay/dash/blob/master/src/spork.cpp#L189

has a potential lock-order-inversion issue.

This is the fix: https://github.com/syscoin/syscoin/commit/08477e15a484099aaa37ec4610438c1b6477c1da#diff-0d7c5dba4239c4b6d3be8e7ba142a255b1301fde8c54cb5e0f4979f3d5cc25aeL202

This is the TSAN: https://cirrus-ci.com/task/5590017022099456?command=ci#L3366

You should probably also review other places where inventory is sent from governance classes, it cannot be using local class CS locks there likely I found a couple other places it was affecting too.

**Comment by PastaPastaPasta** [comment]
fixed by 3829
