### ISSUE TITLE
WSL Cross-compile not working

### ISSUE THREAD

**Issue by Nugetzrul3** [dashpay/dash#3819]
### Describe the issue
When building for Windows through Linux cross-compile, I encounter this error multiple times:
`g++: error: unrecognized command line option ‘-mthreads’; did you mean ‘-pthread’?`
#### If so, please list the steps to reproduce below:
1. Clone repository
2. `cd depends`
3. `make HOST=x86_64-w64-mingw32 -j2`

### Expected behaviour
It should have compiled fine

### Actual behaviour
Make errored out

### What version of Dash Core are you using?
I cloned from `master` branch to self-compile

### Machine specs:
- OS: Windows, using WSL Ubuntu 1804
- CPU: Intel i5-7600k
- RAM: 16 GB
- Disk size: 1 TB
- Disk Type (HD/SDD): HDD

### Any extra information that might be useful in the debugging process.
```
    "g++"  -ftemplate-depth-128 -std=c++11 -fvisibility=hidden     -I/mnt/e/NachoCoinWidnows/depends/x86_64-w64-mingw32/include     -O3 -finline-functions -Wno-inline -Wall -pedantic -mthreads -m64 -Wextra -Wno-long-long -Wno-unused-parameter -Wunused-function -pedantic -DBOOST_ALL_NO_LIB=1 -DBOOST_CHRONO_STATIC_LINK=1 -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_SYSTEM_STATIC_LINK=1 -DBOOST_THREAD_BUILD_LIB=1 -DBOOST_THREAD_USES_CHRONO -DBOOST_USE_WINDOWS_H -DNDEBUG -DWIN32_LEAN_AND_MEAN  -I"." -c -o "bin.v2/libs/thread/build/gcc-7/release/binary-format-pe/link-static/runtime-link-static/target-os-windows/threadapi-win32/threading-multi/win32/tss_pe.o" "libs/thread/src/win32/tss_pe.cpp"

g++: error: unrecognized command line option ‘-mthreads’; did you mean ‘-pthread’?
```
This is just one of the times it says it is unrecognised

**Comment by Nugetzrul3** [comment]
I have also tried doing `make HOST=x86_64-w64-mingw32` where the directory is in the native Linux directory, not `/mnt/e`. It still fails with the same error

**Comment by strophy** [comment]
This works fine for me with Ubuntu 20.04 under WSL2. Can you please confirm you installed all [dependencies](https://github.com/dashpay/dash/blob/master/doc/build-cross.md#windows-64bit-cross-compilation) and changed to the POSIX version of g++ as described here https://github.com/dashpay/dash/blob/master/doc/build-cross.md#building-for-64-bit-windows

**Comment by Nugetzrul3** [comment]
> This works fine for me with Ubuntu 20.04 under WSL2. Can you please confirm you installed all [dependencies](https://github.com/dashpay/dash/blob/master/doc/build-cross.md#windows-64bit-cross-compilation) and changed to the POSIX version of g++ as described here https://github.com/dashpay/dash/blob/master/doc/build-cross.md#building-for-64-bit-windows

`sudo update-alternatives --config x86_64-w64-mingw32-g++`
```
  Selection    Path                                   Priority   Status
------------------------------------------------------------
  0            /usr/bin/x86_64-w64-mingw32-g++-win32   60        auto mode
* 1            /usr/bin/x86_64-w64-mingw32-g++-posix   30        manual mode
  2            /usr/bin/x86_64-w64-mingw32-g++-win32   60        manual mode
```
Already selected.
`sudo apt install build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git python3 cmake`
```
automake is already the newest version (1:1.15.1-3ubuntu2).
autotools-dev is already the newest version (20180224.1).
bsdmainutils is already the newest version (11.1.2ubuntu1).
build-essential is already the newest version (12.4ubuntu1).
libtool is already the newest version (2.4.6-2).
pkg-config is already the newest version (0.29.1-0ubuntu2).
cmake is already the newest version (3.10.2-1ubuntu2.18.04.1).
curl is already the newest version (7.58.0-2ubuntu3.10).
curl set to manually installed.
git is already the newest version (1:2.17.1-1ubuntu0.7).
git set to manually installed.
python3 is already the newest version (3.6.7-1~18.04).
python3 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 82 not upgraded.
```
All dependencies installed.

I am also using WSL2, but 1804 version. Should that be an issue though?

**Comment by Nugetzrul3** [comment]
I think I have found the issue:
```
root@IAMYOURFATHER:/home/salmaan1234# g++ -mthreads
g++: error: unrecognized command line option ‘-mthreads’; did you mean ‘-pthread’?
g++: fatal error: no input files
```
On the other hand
```
root@IAMYOURFATHER:/home/salmaan1234# x86_64-w64-mingw32-g++-posix -mthreads
x86_64-w64-mingw32-g++-posix: fatal error: no input files
compilation terminated.
```

**Comment by strophy** [comment]
Yes, that looks like the problem. This works fine with Dash Core, or can you reproduce it there too? Otherwise you'll need to look at what is different for your `NachoCoinWidnows` fork...

**Comment by Nugetzrul3** [comment]
Yes seems to be that. Just tried building for Dash:
```
 "x86_64-w64-mingw32-g++"  -ftemplate-depth-128 -std=c++11 -fvisibility=hidden     -I/mnt/e/dashcore/depends/x86_64-w64-mingw32/include     -O3 -finline-functions -Wno-inline -Wall -pedantic -mthreads -m64 -Wextra -Wno-long-long -Wno-unused-parameter -Wunused-function -pedantic -DBOOST_ALL_NO_LIB=1 -DBOOST_CHRONO_STATIC_LINK=1 -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_SYSTEM_STATIC_LINK=1 -DBOOST_THREAD_BUILD_LIB=1 -DBOOST_THREAD_USES_CHRONO -DBOOST_USE_WINDOWS_H -DNDEBUG -DWIN32_LEAN_AND_MEAN  -I"." -c -o "bin.v2/libs/thread/build/gcc-mingw-7.3/release/binary-format-pe/link-static/runtime-link-static/target-os-windows/threadapi-win32/threading-multi/win32/thread.o" "libs/thread/src/win32/thread.cpp"
```
It is using `x86_64-w64-mingw32-g++` instead of `g++`. Do you know by any chance where I can find the file to change it so that it uses `x86_64-w64-mingw32-g++` instead of `g++`?

**Comment by strophy** [comment]
Sorry, I don't know where to do that. Maybe one of the devs can help out...

**Comment by Nugetzrul3** [comment]
Okay thanks. No worries, someone else compiled it and sent. Thanks for the help anyways @strophy
