### ISSUE TITLE
getwalletinfo error,GetOldestKeyInPool: read oldest key in keypool failed

### ISSUE THREAD

**Issue by Alteryy** [dashpay/dash#3838]
Dash Core Daemon version v0.16.1.1

./dash-cli getwalletinfo
error code: -1
error message:
GetOldestKeyInPool: read oldest key in keypool failed

What does this mean and how to solve it

**Comment by UdjinM6** [comment]
Smth isn't quite right with your wallet it seems. Save `wallet.dat` file (and `<datadir>/wallets/` folder if you have one) in some safe place. Check `<datadir>/backups/` folder if it has some older versions of the wallet saved. If it does, copy this folder in some safe place too. Next, try to send all your funds to some another wallet. If this fails, try picking the most recent wallet.dat from "backups" folder you saved earlier and place it in <datadir> overriding the original one (double check you have the original one saved somewhere just in case). Try moving funds again. If this also fails, try using the next file from your (saved somewhere) "backups" folder and so on. There should be 10 most recent backups (by default) which _should_ be enough to restore old keys in most cases, try as many as you can even if a couple of the most recent ones would fail. Hope it helps.

**Comment by PastaPastaPasta** [comment]
Closing as no comment in 6+ months. Please reopen if you have additional isseus
