### ISSUE TITLE
Block sync stopped at 1379127

### ISSUE THREAD

**Issue by mtb-pro** [dashpay/dash#3840]
how to fix it?

Dash Core RPC client version v0.15.0.0
### watch dash-cli getblockchaininfo

{
  "chain": "main",
  "blocks": 1379127,
  "headers": 1379127,
  "bestblockhash": "000000000000000ccfb26e157e87776cd053fbecf730d74fbb5f50a3acda30a5",
  "difficulty": 193699454.3116622,
  "mediantime": 1606554605,
  "verificationprogress": 0.9993560104103038,
  "chainwork": "0000000000000000000000000000000000000000000047ddec41faf2f9679b81",
  "pruned": false,
  "softforks": [
    {
      "id": "bip34",
      "version": 2,
      "reject": {
        "status": true
      }
    },
    {
      "id": "bip66",
      "version": 3,
      "reject": {
        "status": true
      }
    },
    {
      "id": "bip65",
      "version": 4,
      "reject": {
        "status": true
      }
    }
  ],
  "bip9_softforks": {
    "csv": {
      "status": "active",
      "startTime": 1486252800,
      "timeout": 1517788800,
      "since": 622944
    },
    "dip0001": {
      "status": "active",
      "startTime": 1508025600,
      "timeout": 1539561600,
      "since": 782208
    },
    "bip147": {
      "status": "active",
      "startTime": 1524477600,
      "timeout": 1556013600,
      "since": 939456
    },
    "dip0003": {
      "status": "active",
      "startTime": 1546300800,
      "timeout": 1577836800,
      "since": 1028160
    },
    "dip0008": {
      "status": "active",
      "startTime": 1557878400,
      "timeout": 1589500800,
      "since": 1088640
    }
  }
}

**Comment by UdjinM6** [comment]
Pls update to [v0.16.1.1](https://github.com/dashpay/dash/releases/tag/v0.16.1.1) and then [reconsider the fork block](https://github.com/dashpay/dash/issues/3836#issuecomment-735226848).
