### ISSUE TITLE
Wallet won't stay open Linux

### ISSUE THREAD

**Issue by PalmTreeVI** [dashpay/dash#3848]
I upgraded wallet from Linux 15 to dashcore-0.16.1.1-x86_64-linux-gnu.tar.gz wallet.  Running ./dash-qt attempts to start and immediately closes.

To reproduce:
1. Open wallet and try again, not working.
2. Backup and delete ~/.dashcore and ~/.config/Dash folders
3. Retry, same thing
The create or restore wallet windows opens, I select new wallet, then the splash screen is visible, after a short while the wallet closes (and not running in the background)

The terminal output when this happens is:

```[user@pc bin]$ ./dash-qt
Assertion failure:
  assertion: false
  file: qt/guiutil.cpp, line: 1771
  function: int GUIUtil::supportedWeightToIndex(QFont::Weight)
   0#: (0x55ACC53C4BA6) <unknown-file> - ???
   1#: (0x55ACC4C4775E) <unknown-file> - ???
   2#: (0x55ACC4C6D025) <unknown-file> - ???
   3#: (0x55ACC58AAD30) <unknown-file> - ???
   4#: (0x55ACC58CB8B3) <unknown-file> - ???
   5#: (0x55ACC58CC2FF) <unknown-file> - ???
   6#: (0x55ACC58CC40D) <unknown-file> - ???
   7#: (0x55ACC4C4C703) <unknown-file> - ???
   8#: (0x55ACC4C09C3C) <unknown-file> - ???
   9#: (0x55ACC4C0A2AC) <unknown-file> - ???
  10#: (0x55ACC5FE5382) <unknown-file> - ???
  11#: (0x55ACC59F1CD4) <unknown-file> - ???
  12#: (0x55ACC56956EF) <unknown-file> - ???
  13#: (0x55ACC568FE3C) <unknown-file> - ???
dash-qt: qt/guiutil.cpp:1771: int GUIUtil::supportedWeightToIndex(QFont::Weight): Assertion `false' failed.
Aborted (core dumped)
[user@pc bin]$ ```

I have also tried the following commands after deleting the same folders above (clean install) which were recommended via help from Discord:  

`dash-qt -resetguisettings`
`dash-qt -font-weight-normal=0 -font-weight-bold=8`
`dash-qt -font-weight-normal=0 -font-weight-bold=0`

All of these produce the same result

### Machine specs:

- OS: Linux (Manjaro/Arch) with XFCE
- CPU: Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
- RAM: 32g
- Disk size: 10tb
- Disk Type (HD/SDD): hdd

### Extra Information

Debug log show same message.

**Comment by UdjinM6** [comment]
So I downloaded and installed Manjaro 20.2 in VM and the first time I tried to run Dash Core 0.16.1.1 it didn't crash but it hanged in some limbo state, had to kill it with `-9`. I checked debug.log and found this:
```
2020-12-04 01:34:57 GUI: QXcbWindow: Unhandled client message: "WM_S0"
2020-12-04 01:34:58 GUI: QXcbWindow: Unhandled client message: "_NET_WM_CM_S0"
2020-12-04 01:34:58 GUI: QXcbWindow: Unhandled client message: "COMPOSITING_MANAGER"
2020-12-04 01:34:58 GUI: QXcbWindow: Unhandled client message: "XFWM4_COMPOSITING_MANAGER"
```

However, when I tried to run it again it simply started as it should and I was not able to reproduce any issues since then.
<img width="1023" alt="Screenshot 2020-12-04 at 05 07 13" src="https://user-images.githubusercontent.com/1935069/101112835-3e15bd00-35ef-11eb-9d64-8eeb7665d248.png">

**Comment by kxcd** [comment]
Specifically the user had issue when using XFCE window manager. Can you confirm you were using that WM, udinM6?

**Comment by UdjinM6** [comment]
@kxcd 
<img width="1024" alt="Screenshot 2020-12-04 at 11 47 35" src="https://user-images.githubusercontent.com/1935069/101142355-8a302400-3626-11eb-8ce6-834f9b36a077.png">

**Comment by xdustinface** [comment]
@PalmTreeVI Besides what @UdjinM6 asked you to do, can you do some more things :) 

1.  Run with `-debug=qt` and post the `debug.log` for that
2. There *should* be at least one working `x` value in the range 0-8 for `dash-qt -font-weight-normal=x -font-weight-bold=x` so can you try **all** x values like: 

- `x=0` => `dash-qt -font-weight-normal=0 -font-weight-bold=0`
- ....
- ....
- `x=8` => `dash-qt -font-weight-normal=8 -font-weight-bold=8`
3. Try to run with `-font-family=Montserrat`, this could also work just fine

**Comment by PalmTreeVI** [comment]
I tried all of the above in same command and the wallet is now syncing!!!

`[user@pc bin]$ ./dash-qt -debug=qt -font-weight-normal=0 -font-weight-bold=0 -font-family=Montserrat`

On opening, after splash screen there was a panel to set fonts which I adjusted slightly and hit OK,I had tried the font-weight commands initially so I think the font-family command is the trick that made it work.

**Comment by UdjinM6** [comment]
@PalmTreeVI Glad it worked and thanks for reporting back with your findings! 👍
