### ISSUE TITLE
PrivateSend settings dialog GUI display bug

### ISSUE THREAD

**Issue by strophy** [dashpay/dash#3850]
The Settings > Options > PrivateSend dialog is drawing the up/down arrows incorrectly here. Notice how they are all pointing up instead of up/down, and the bold border around the field is pushing the arrows out of alignment with the field below:
![image](https://user-images.githubusercontent.com/32928115/101198386-42fa6f80-36c8-11eb-967f-e8805694bc0a.png)

Hovering over the arrows causes them to switch to up/down, but both arrows are pointing inwards instead of outwards:
![image](https://user-images.githubusercontent.com/32928115/101198421-50175e80-36c8-11eb-88ac-9f9c0e565898.png)

### Expected behaviour
Arrows should stay in alignment and point in the right direction.

### Actual behaviour
Arrows point in weird directions as described above

### Screenshots.
See above

### What version of Dash Core are you using?
0.16.1.1

### Machine specs:
- OS: Windows 10 20H2
- CPU: i7 4810MQ
- RAM: 16GB
- Disk size: 500GB
- Disk Type (HD/SDD): SSD

**Comment by xdustinface** [comment]
@strophy Fixed the arrow directions in #3851. Im aware of the slightly wrong alignment of the arrows in the hover/selected states but couldn't find a solution in reasonable time when i digged into so i decided to not waste a lot more time with it at that point because its imo just a nit. But lets see, maybe someone else will come up with an idea/solution there.

**Comment by UdjinM6** [comment]
Oh, wow! Is this a Windows only issue? Cause I don't see anything like that here on mac.

**Comment by xdustinface** [comment]
> I don't see anything like that here on mac.
It's a light mode only issue 😄

**Comment by UdjinM6** [comment]
WAT? There is a Light mode in our wallet? :trollface: 

I see now, thanks :)

**Comment by strophy** [comment]
Thanks for the quick work guys! Fixing the direction is good enough for me, can close unless you want to keep open to deal with the alignment issue another day :+1:
