### ISSUE TITLE
subgroup attack on BLS12-381 DKG

### ISSUE THREAD

**Issue by sidhujag** [dashpay/dash#3898]
It came to my attention that there is a new discovered attack on DKG using BLS12-381 which Dash uses. The severity depends on your expertise but from my analysis it is not totally critical from my understanding of chainlocks/pose, it may be to instantsend/privatesend because I never looked at that code. Anyways here is a document outlining the attack pls see if it is relevant and to what extent. If you wish to chat with the researcher I will create a private room in the Syscoin discord for us to chat about it and steps to take to fix.

https://docs.google.com/document/d/1fjuc_JLPgSg3yy1cQOopbjroMhePaNel7pi8uZbUduk/edit

The research was an attempt to attack distributed key generation (DKG), key resharing and threshold BLS signing on DKG but it applies on any cryptographic setups on that curve on other systems as well.

**Comment by omershlo** [comment]
Hi everyone, I am the author of the above doc. 
I want to chip in if I may - here is my main question: can someone who is familiar with the code confirm that EC points sent between nodes are checked to be in the subgroup of prime order of bls12-381? 

If the answer is "yes" - I would love to get a pointer to the relevant part in the code to double check. 
The attack described above is new and undermine security of the protocol unless mitigated.

**Comment by sidhujag** [comment]
will work with developers on discord and resolve this there thanks :)
