### ISSUE TITLE
feeHash TX meaning

### ISSUE THREAD

**Issue by yussefsoudan** [dashpay/dash#3991]
Hi there! 

This is a technical question - not an issue - as I was unable to get any replies on the [subreddit here.](https://www.reddit.com/r/dashpay/comments/l4wo67/what_is_ncollateralhash_in_governanceobjectcpp/). 

I'm trying to figure out how are proposals ranked if there's a tie in the number of votes they received. I am particularly asking about the initial ranking of passed proposals, not when allocating funds. I was unable to find this documented anywhere, so I started looking into the code.

In line 537 in governance.cpp, it says 'Sort by votes, if there's a tie sort by their feeHash TX'.
The 'feeHash TX' is the nCollateralHash variable of the CGovernanceObject, and I am wondering what exactly is it?

Thanks!

**Comment by UdjinM6** [comment]
[The answer by Antti-Kaikkonen](https://www.reddit.com/r/dashpay/comments/l4wo67/what_is_ncollateralhash_in_governanceobjectcpp/gkrrdfb/) is the correct one - it's `the txid of the 5 dash proposal fee transaction`.

**Comment by yussefsoudan** [comment]
So, does that mean if there's a tie then the first project proposed is prioritized? Or would it be random?

**Comment by UdjinM6** [comment]
It means that if there is a tie then proposals are compared by txids (transaction hashes) of their proposal fee txes. There is no way to have two identical txids in two different proposals, so you can be pretty sure that it's always deterministic.

**Comment by yussefsoudan** [comment]
Thanks for your quick response! I basically meant to ask if the hash of the proposal fee takes the timestamp of submission into consideration at all? And if that's the case, does a larger feeHashTx value indicate anything about the time it was submitted?

**Comment by UdjinM6** [comment]
No, there is no timestamp or block height or anything like that. It's a pure tx hash you can see in block explorers etc., just a huge randomly looking (yet deterministic) number.

**Comment by yussefsoudan** [comment]
Got it - thanks so much!
