### ISSUE TITLE
Labeling on the addresses does not work.

### ISSUE THREAD

**Issue by splawik21** [dashpay/dash#3992]
I was testing the MNs on testnet when realized that the rewards which arrive and are seen on the tx history tab are the alfanumeric addresses even though on the moment of requesting the label has been given.
![BC018695-79FA-4D42-AB8B-7E0E229F4C95](https://user-images.githubusercontent.com/14001049/107157539-df6d1680-6984-11eb-9fbd-53631ecdf86b.png)
![EFCFD7F7-3EA7-490A-9CEA-28246AAA8B63](https://user-images.githubusercontent.com/14001049/107157541-e09e4380-6984-11eb-823a-0c469d3bf3c1.png)

**Comment by PastaPastaPasta** [comment]
Has been fixed
