### ISSUE TITLE
Code issue : 

### ISSUE THREAD

**Issue by BlockMechanic** [dashpay/dash#3999]
Browsing in the code i found this :- https://github.com/dashpay/dash/blob/43d2973a0e89ac9435142d6379e664c0ec20b2a2/src/rpc/rawtransaction.cpp#L929

ProduceSignature is boolean, shouldn't we check if it's true/false here accordingly ? 

https://github.com/dashpay/dash/blob/43d2973a0e89ac9435142d6379e664c0ec20b2a2/src/script/sign.h#L70

**Comment by PastaPastaPasta** [comment]
I don't think this is a problem. Especially now that signrawtransaction is deprecated
