### ISSUE TITLE
Support blocksdir and walletdir

### ISSUE THREAD

**Issue by bohdanyurov-gl** [dashpay/dash#4011]
Looks like there is no support for overriding blocks and wallets directories. Can we add those as options?

Relevant bitcoin issue:
bitcoin/bitcoin#14595

**Comment by thephez** [comment]
You can use `-wallet` or `-walletdir` to set wallet location. See [here](https://dashcore.readme.io/v0.17.0/docs/dash-core-wallet-arguments-and-commands-dashd#wallet-options) for all options (this is the same info as you get from running `-help`).

0.17 (currently on testnet) [adds `-blocksdir`](https://dashcore.readme.io/v0.17.0/docs/dash-core-wallet-arguments-and-commands-dashd#options).

**Comment by bohdanyurov-gl** [comment]
Thanks, I will wait for  0.17.

**Comment by thephez** [comment]
The current RC is available here if you want to check it out: https://github.com/dashpay/dash/releases/tag/v0.17.0.0-rc3

**Comment by PastaPastaPasta** [comment]
Resolved with 0.17 release
