### ISSUE TITLE
Build Error on Ubuntu 20.04 With Release 0.17.0.2

### ISSUE THREAD

**Issue by breadsax** [dashpay/dash#4168]
I cloned the repo and was able to build the depends directory successfully. 

I then cd .. to the dash directory and ran ./autogen.sh and ./configure --prefix=`pwd`/depends/x86_64-pc-linux-gnu --with-incompatible-bdb

I get to this point and receive the following error:

  CXXLD    libdashconsensus.la
/usr/bin/ld: /home/alt/dash/depends/x86_64-pc-linux-gnu/share/../lib/libbls-dash.a(libsodium_la-randombytes.o): relocation R_X86_64_PC32 against symbol `randombytes_sysrandom_implementation' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status

**Comment by UdjinM6** [comment]
Pls try patching it like that
```
diff --git a/depends/packages/bls-dash.mk b/depends/packages/bls-dash.mk
index 4f19da6bc..cc2a9f53e 100644
--- a/depends/packages/bls-dash.mk
+++ b/depends/packages/bls-dash.mk
@@ -61,6 +61,7 @@ define $(package)_config_cmds
   export CFLAGS="$($(package)_cflags) $($(package)_cppflags)" && \
   export CXXFLAGS="$($(package)_cxxflags) $($(package)_cppflags)" && \
   export LDFLAGS="$($(package)_ldflags)" && \
+  export CIBUILDWHEEL=1 && \
   $(host_prefix)/bin/cmake ../ $($(package)_config_opts)
 endef
 
```
and see if it helps. 

(make sure to run `make clean` in `dash/` before running `make` again)

**Comment by breadsax** [comment]
I did not have luck with this patch, unfortunately.

The code compiled successfully with master branch before pushing the code for release.

The only change above you suggested was to add export CIBUILDWHEEL=1 && \    in the location above, is that correct? 

I'm certain it is more difficult to compile since we are doing deterministic builds by default and I don't see other instructions for local builds.

Any other ideas from you @UdjinM6 or the community? Thank you!

**Comment by BlockGardener** [comment]
I receive the same error message on Ubuntu 18.04.

I tried the suggested fix with the same result.

Compiling with -fPIC results in the same error message.

**Comment by UdjinM6** [comment]
Pls note that you need to rebuild depends and clean/rebuild src after the patch i.e. `make -C depends/ && make clean && ./autogen.sh && make`

**Comment by breadsax** [comment]
@UdjinM6 I did actually rebuild the depends and tried again ./autogen.sh and ./configure --prefix=pwd/depends/x86_64-pc-linux-gnu --with-incompatible-bdb and make -j4

Still same error

**Comment by gituser** [comment]
Having same issue as @breadsax on Ubuntu 18.04.

This https://github.com/dashpay/dash/issues/4168#issuecomment-845309340 doesn't help.

**Comment by UdjinM6** [comment]
Pls try #4174

**Comment by gituser** [comment]
@UdjinM6 https://github.com/dashpay/dash/pull/4174 fixed this issue for me.

**Comment by breadsax** [comment]
Confirmed, this is fixed with that patch above.

**Comment by PastaPastaPasta** [comment]
Thanks for reporting this issue :)

**Comment by xdustinface** [comment]
Hmm i don't think #4174 is the best way to fix this. Even though it works, `libsodium` shouldn't be required here as dependency because we set custom allocators/deallocators here https://github.com/dashpay/dash/blob/79a1b1aa47459c3c14f675c65822e9d3709a47e8/src/bls/bls.cpp#L393

I assume the issue here is that @breadsax and @gituser have `libsodium-dev` installed locally which is a shared lib and can't be used for static linking. Can you both check that and maybe try a clean depends/core build with #4176 to confirm its working (or not)?

**Comment by gituser** [comment]
@xdustinface your patch works.

I've got indeed `libsodium-dev` installed on my local machine where I build dash.
