### ISSUE TITLE
Possible privacy leakage due to ordered transaction inputs

### ISSUE THREAD

**Issue by yixiao5428** [dashpay/dash#4269]
This is a security vulnerability.

The wallet uses ordered inputs of transactions (`src/wallet/wallet.cpp`, [line 3730 - 3737](https://github.com/dashpay/dash/blob/master/src/wallet/wallet.cpp#L3730-L3737)), which may incur privacy risks like fingerprinting the wallet to observers.

A possible solution is to not only clear the original order, but also shuffle it, then push back the new order before signing the transaction.

Similar fix from Bitcoin: https://github.com/bitcoin/bitcoin/commit/2fb9c1e6681370478e24a19172ed6d78d95d50d3.

Reported by `6004ed5feaa31ae9df36b5dbc60f0fa53255a5fb734334082c6d202405fc738c`.

**Comment by PastaPastaPasta** [comment]
Thanks for your issue

I believe this is not an issue as we sort inputs / outputs based on BIP69. See https://github.com/dashpay/dash/pull/3527#discussion_r439844759 and https://github.com/dashpay/dash/blob/master/src/wallet/wallet.cpp#L3868
