### ISSUE TITLE
backport namespace changes in support of newer bind and boost libraries

### ISSUE THREAD

**Issue by taw00** [dashpay/dash#4340]
I have had to patch dash core for a while now for [my builds](https://github.com/taw00/dashcore-rpm) in order to successfully build with newer boost and bind. Specifically, this patch:
https://github.com/taw00/dashcore-rpm/blob/master/SOURCES/dash-0.17.0.3-patch02-bind-namespace-errors.patch

Now, bitcoin upstream fixed this some time ago, but they also shifted to std::bind or some such. I.e., their fix is different than my fix, and therefore, I was not going to commit a PR to the dashcore codebase. This really needs someone more intimate with the code to do it right. It alters a bunch of method calls so ... I leave it in y'all's good hands. :)

Here's an example of what bitcoin upstream did to address some of the namespacing issues. I don't know if this was the only change.
https://github.com/bitcoin/bitcoin/commit/cb53b825c26af6e628ba88d72b2000e75bedbbc6

It would be really nice if for the next major release we addressed this.

Thanks! -t

**Comment by dzutte-cpp** [comment]
Fixed by #4343.
