### ISSUE TITLE
Start-many issue

### ISSUE THREAD

**Issue by scratchy** [dashpay/dash#436]
Hey,

Start-many is broken, or at least not that stable as the 'normal' start.
Theres currently no check that the the node which should be started is realy online.
So currently the behavour is: even if theres no node running on the given IP "sucessfull" ist responded.
Thats somehow only a issue for user-experience but this information is published to the Masternode-List.
S.o. whos deeper in the code should dig into it if this is an security issue (maybe its possible to spam the masternode list) ? Even those entrys which are not real show ENABLED on the masternode full list, that also looks not that good.

Following code-snipped should be modified and placed in activemasternode.cpp arround line 195 (im talking about v12)

if(!ConnectNode((CAddress)service, service.ToString().c_str())){
            notCapableReason = "Could not connect to " + service.ToString();
            LogPrintf("CActiveMasternode::ManageStatus() - not capable: %s\n", notCapableReason);
            return;
}

**Comment by evan82** [comment]
You're right, however it's just a local check, it will definitely help for debugging and keeping your masternode online, but it's not really going to stop anyone from spamming the masternode list (that still requires 1000DASH to sign inorder to propagate the message, so it shouldn't be an issue). Thanks for reporting this, we'll fix it before v12 goes live.

**Comment by scratchy** [comment]
Awesome this fix went fast.
Thank you ! :)

**Comment by scratchy** [comment]
Sorry:
Time for reopen it.

It seems the check is not working correctly.
If the port is closed it still says: "result" : "successful", with the normal start it says 'Not capable masternode: Could not connect to..'
