### ISSUE TITLE
Linking problem related to libzmq.so and libsodium.so

### ISSUE THREAD

**Issue by lano1106** [dashpay/dash#4363]
I get the following output when compiling the project: v0.17.0.3

`
  CXXLD    dashd
/usr/bin/ld: /usr/lib64/libzmq.so: undefined reference to symbol 'sodium_free'
/usr/bin/ld: /usr/lib/libsodium.so.23: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:4886: dashd] Error 1
`

Does anyone has seen this before?
I'll try to compile myself libsodium. I suspect that maybe some optional C++ support is missing from the official package.

Worse-case scenario.
What ZeroMQ is used for inside dashcore?
Is this coming from bitcoin?
ie: A different comm channel to essentially send requests that are ordinarily sent through the JSON-RPC interface?

I suspect that if I'm not sure what ZeroMQ is for, there is a good chance that I can disable it with no undesirable side-effect...

### What version of Dash Core are you using?
self-compiled

### Machine specs:
- OS: Linux kernel 5.12.19. ArchLinux
- CPU: Sandybridge
- RAM: 32 GB

**Comment by PastaPastaPasta** [comment]
I don't think any of us here use arch, so it's possible there are issues with building on arch, and we would support getting patches to fix those. Disabling ZMQ won't cause any issues, unless you plan to use ZMQ (zmq is useful for getting a 'notification' whenever an 'event' happens, we use it for blocks and transactions and the like. (See https://github.com/dashpay/dash/blob/master/doc/zmq.md for more info about zmq)

**Comment by PastaPastaPasta** [comment]
We no longer use libsodium; closing for now, feel free to re-open if you still experience these issues! Thanks
