### ISSUE TITLE
Masternode payed even if the daemon is Offline

### ISSUE THREAD

**Issue by scratchy** [dashpay/dash#442]
Hey,

Related to #436 it looks like registered nodes were payed even if their daemon _never_ run.
Only the fact they published their vin to the network looks like they were choosen for a payment.
Is this situation possible or did i made a mistake?

**Comment by evan82** [comment]
When you register a node online, you're added to the list as enabled, then added to the payment queue at the end of the line. If you leave the cold node online for example, it will continue to ping the network and it's possible for a masternode to be unreachable, but still get payment when it's time comes. This was going to be solved by proof-of-service, which would check that the port was open and the daemon was responding to it's assigned tasks. So this is a known issue and not a very serious one -- something that will be tackled in a future version of the software.
