### ISSUE TITLE
 fatal error: bls-dash/bls.hpp: No such file or directory

### ISSUE THREAD

**Issue by thedecentralized** [dashpay/dash#4444]
Hi, how are you? i have an error when trying to compile a trace to run a node, can you help me please?

![image](https://user-images.githubusercontent.com/83592440/133943583-f79beff6-7003-493b-9705-6f68ec87674a.png)

**Comment by PastaPastaPasta** [comment]
What process are you following building? Please follow the build guides found in the doc folder including building depends

**Comment by thedecentralized** [comment]
yes, i followed and even redid again but nothing came of it

one note is that the missing file "libdash_server_a-bloom.o" is not available on github

![image](https://user-images.githubusercontent.com/83592440/133947443-bebba9a6-dfd8-4784-89cc-d97ee0a67a1b.png)

**Comment by PastaPastaPasta** [comment]
What's your environment, OS, etc

What exactly were all the commands you ran?

**Comment by thedecentralized** [comment]
I use Zorin OS

I gave the following commands

./autogen

./configure --enable-debug --with-incompatible-bdb --with-gui=qt5

make -j4

**Comment by PastaPastaPasta** [comment]
Sooo... You didn't build depends?

```
cd depends
make
./configure --prefix depends/host as described in docs
```

**Comment by thedecentralized** [comment]
no, i will try now, thanks
