### ISSUE TITLE
Spork Address

### ISSUE THREAD

**Issue by thedecentralized** [dashpay/dash#4445]
Hello, how is everything? I'm doing a fork to further study the dash and generate blocks for my network, how could I generate a spork address?

**Comment by PastaPastaPasta** [comment]
We don't spend much (if any) effort supporting forks. Spork addresses are just like any other address and are generated as such. 
see: https://docs.dash.org/en/stable/developers/index.html#sporks, https://dashcore.readme.io/docs/core-api-ref-remote-procedure-calls-dash#spork

**Comment by thedecentralized** [comment]
thank you :)
