### ISSUE TITLE
mnbudget prepare problem

### ISSUE THREAD

**Issue by TanteStefana** [dashpay/dash#449]
When I try to prepare a proposal, it says the result is a string and it expected a bool.

I enter:
mnbudget prepare TScherryfarm http://www.dashpay.io/ts.json 15 88000 yL7WTtehXs7w5wsyqGMpkdESM9W1ejHRvi 500 yes

And I get:
value is type str, expected bool (code -1)

Also, I don't know how to say I want to use ix or not, I've tried the following but none of them work.  They always give me this:
Correct usage is 'mnbudget prepare proposal-name url payment_count block_start dash_address monthly_payment_dash [use_ix(true|false)]' (code -1)

This is what I've tried:
mnbudget prepare TScherryfarm http://www.dashpay.io/ts.json 15 88000 yL7WTtehXs7w5wsyqGMpkdESM9W1ejHRvi 500 yes false

mnbudget prepare TScherryfarm http://www.dashpay.io/ts.json 15 88000 yL7WTtehXs7w5wsyqGMpkdESM9W1ejHRvi 500 yes use_ix false

mnbudget prepare TScherryfarm http://www.dashpay.io/ts.json 15 88000 yL7WTtehXs7w5wsyqGMpkdESM9W1ejHRvi 500 yes [use_ix(false)]

Nothing seems to work.

**Comment by elbereth** [comment]
Why the "yes" at the end of your prepare statement?
mnbudget prepare TScherryfarm http://www.dashpay.io/ts.json 15 88000 yL7WTtehXs7w5wsyqGMpkdESM9W1ejHRvi 500 **yes**

mnbudget prepare TScherryfarm http://www.dashpay.io/ts.json 15 88000 yL7WTtehXs7w5wsyqGMpkdESM9W1ejHRvi 500 **yes** false

mnbudget prepare TScherryfarm http://www.dashpay.io/ts.json 15 88000 yL7WTtehXs7w5wsyqGMpkdESM9W1ejHRvi 500 **yes** use_ix false

mnbudget prepare TScherryfarm http://www.dashpay.io/ts.json 15 88000 yL7WTtehXs7w5wsyqGMpkdESM9W1ejHRvi 500 **yes** [use_ix(false)]

**Comment by TanteStefana** [comment]
I was on the phone with daughter when I saw this.  I guess I'll try blaming senility again??  too much cut and pasting!  Still, I can't choose true or false regarding IX  I just tried:
false
use_ix false
[use_ix(false)]

But I was able to not use that argument and submit a proposal (I believe the default is true)
