### ISSUE TITLE
Missing transaction type for spendings of watch-only addresses

### ISSUE THREAD

**Issue by crowning-** [dashpay/dash#466]
- I added Masternode yEeSSUjQKPVJKZYeMRtaRiSoUqYuid3Wuv as "watch-only" address
- When this Masternode gets paid I can see it as type "Mined" in the "Transactions" tab
- When this Masternode spends some DASH (e.g. transaction de0721f68246864a9c475517240c5c67d777b11a92eb4aca366f3a391733eb4d) I see the sum of the payments from that transaction as one outgoing payment listed, but without any transaction type

Would be nice to have a transaction type there to make use of the type-filter.

**Comment by schinzelh** [comment]
Deprecated by Evolution GUI
