### ISSUE TITLE
Exit daemon dashcore

### ISSUE THREAD

**Issue by marcel1974** [dashpay/dash#4673]
How to exit dashd properly without killing the process with kill. I dont want to corrupt the database
Most cli wallet daemons have an exit switch why not dashcore dashd.
Perhaps it was omitted for a reason, I would like to know.

letheand exit
ryod exit
monerod exit

Why not dashd exit

And yes I did google it for some time..
Best Regards

**Comment by thelazier** [comment]
@marcel1974 , please try to stop dashd by issue the command 
`dash-cli stop`
