### ISSUE TITLE
New Spork for QR Activation for SPV clients

### ISSUE THREAD

**Issue by HashEngineering** [dashpay/dash#4847]
### Expected behavior
When DIP0024 is activated, mobile and SPV clients won't know.  Even after activation, there is a certain number of blocks required  to be added to the blockchain before `getqrinfo` can return information.

We would like a spork to be created and then activated after `getqrinfo` will be able to return valid data.  

Suggested name and number:
```c++
SPORK_24_DIP24_SPV                                   = 10023,
```

**Comment by PastaPastaPasta** [comment]
Assigning to @knst

**Comment by HashEngineering** [comment]
This issue is resolved because we don't need a spork.
