### ISSUE TITLE
Testnet stuck on 769865

### ISSUE THREAD

**Issue by dpc** [dashpay/dash#4943]
It seems both https://sochain.com/testnet/dash and https://blockexplorer.one/dash/testnet are stuck at the same height, mined 15 hours ago. We see the same on our own testnet node. Is this expected?

**Comment by dpc** [comment]
I guess upgrade to rc11 is necessary.

**Comment by thephez** [comment]
@dpc There's also one known bug (fixed in https://github.com/dashpay/dash/pull/4942) which requires you to enable `debug=lllmq` to get unstuck. The subsequent RC will resolve that.
