### ISSUE TITLE
Ensure that sentinel is not affected by any changes, and no changes to sentinel are required.

### ISSUE THREAD

**Issue by PastaPastaPasta** [dashpay/dash#4948]

**Comment by PastaPastaPasta** [comment]
@nmarley Can you provide an update here as to the status of sentinel? Is it ready?

**Comment by nmarley** [comment]
It should be ready in general, but to make sure we don't miss anything:

1. We need to test the most recent `develop` on testnet for a while (couple days?)
2. I think @strophy and I still need to work together to ensure the current version is working w/dashmate, and
3. to possibly update the docker `run.sh` script, and
4. to review and/or update the README to make sure it's current.

... at a minimum.

**Comment by PastaPastaPasta** [comment]
> It should be ready in general, but to make sure we don't miss anything:
> 
> 1. We need to test the most recent `develop` on testnet for a while (couple days?)
> 2. I think @strophy and I still need to work together to ensure the current version is working w/dashmate, and
> 3. to possibly update the docker `run.sh` script, and
> 4. to review and/or update the README to make sure it's current.
> 
> ... at a minimum.

hey @nmarley thanks for the response.. 

Why would we test develop, instead of 18.0.0-rc12 which is the thing being released? 18.0.0-rc12 has been on testnet for a few weeks now.

What needs to be updated in run.sh and why?

Would you be able to look at the README and ensure it's up to date? 

Thanks

**Comment by nmarley** [comment]
I mean the develop branch of Sentinel, not referring to DashCore.

If you mean rc12 has been on testnet for a few days (not weeks), then yes,
I agree with that statement. I have not had the capacity to work on
Sentinel for a few weeks now.

The latest env changes in Sentinel make a lot of the run.sh script obsolete.

Sure, I'll make sure the README is up to date. I wrote this in list format
more as a checklist of things that we need to do to make sure Sentinel is
ready for release.

**Comment by thephez** [comment]
Fwiw I ran the `develop` branch (non-dockerized) on a testnet MN for a couple weeks and didn't notice issues. Although issues may not have been evident since most of the network was DCG hosted and using docker.

**Comment by PastaPastaPasta** [comment]
@nmarley Can you please confirm that `master` of sentinel is ready for the imminent release of v18.0.0?

**Comment by nmarley** [comment]
@PastaPastaPasta Unfortunately I am on holiday and don't have the capacity for that right now, I might have some this week or next, but can't guarantee it. If this is a problem please contact @strophy for help w/resources.

Feel free to do a PR in the Sentinel repo to bump the version on develop, then another PR to merge develop into master if you want Sentinel `master` branch to be ready.
