### ISSUE TITLE
-usehd does not store CoinJoin funds in HD wallet

### ISSUE THREAD

**Issue by gfkdjgmn** [dashpay/dash#4985]
How to replicate:
1) Create a new wallet using -usehd=1
2) Receive and mix a bunch of dash
3) Try to restore the wallet using the mnemonic. The result is that you will only see some collateral payment and make collateral input transactions, but your coinjoin funds are not there. 

This has the potential to lose a lot of dash. I was lucky that my hard drive didn't break as I didn't have any other backup than the mnemonic.

**Comment by UdjinM6** [comment]
Pls try running the node with the wallet you restored via `-mnemonic` with `-rescan=2` option in cmd-line (or try using `Rescan blockchain files 2` button on Wallet Repair tab if you prefer using GUI).

NOTE: probably related - #3796

**Comment by gfkdjgmn** [comment]
Using the `Rescan blockchain files 2` GUI option did not help but I'm not starting to suspect that this is an issue with the address gap limit which is 20 by default. The reason is that when loading the original then this line appears in debug.log:
```
Keys: 0 plaintext, 0 encrypted, 0 total; Watch scripts: 0; HD PubKeys: 31245; Metadata: 31245; Unknown wallet records: 2
```
and I can actually see old mixing transactions in the wallet restored from mnemonic.

Is there any way to increase the address gap without creating a custom build?

**Comment by UdjinM6** [comment]
> I'm now starting to suspect that this is an issue with the address gap limit which is 20 by default.
> Is there any way to increase the address gap without creating a custom build?

It's a mixed HD/keypool wallet in our case so the gap limit is keypool size actually (`-keypool`) and it's 1000 by default. But yeah, this could be it - I can reproduce the issue by setting `-keypool=10` via cmd line and restoring from mnemonic via `upgradetohd` rpc. Try using a larger keypool e.g. `-keypool=10000` (or `keypoolrefill 10000` in console) and then rescan the wallet again. Btw, you can use `rescanblockchain` rpc to save some time if you know which blocks you want to scan exactly (ideally, it should be blocks in which the first/last (missing) transaction was mined).

**Comment by gfkdjgmn** [comment]
Thank you @UdjinM6, I will try with a larger keypool. I imagine that so many addresses being unused might have something to do with this issue https://github.com/dashpay/dash/issues/4986

**Comment by gfkdjgmn** [comment]
I manged to recover the wallet from seed using a larger keypool.

First I tried with a keypool size of 10000, which wasn't enough. But I tried again with 100000 and it worked!
