### ISSUE TITLE
InvalidChainFound - block 1738697

### ISSUE THREAD

**Issue by jerrybb** [dashpay/dash#5014]
Hi, dash has stopped syncing at block 1738697. Same issue is with some other online services like cryptoid - see attached screenshot. Sync stopped at same block. 
<img width="635" alt="image" src="https://user-images.githubusercontent.com/44587704/190413258-1b217609-b076-4d48-8f1c-c5d185bbb9d4.png">

Log events: 2022-09-15T13:05:47Z InvalidChainFound:  current best=00000000000000362d528545b40976af8a9b5380def57d63943a30a9379a5385  height=1738697  log2_work=78.91219653  date=2022-09-15T12:39:02Z

CheckForkWarningConditions: Warning: Found invalid chain at least ~6 blocks longer than our best chain.

Any idea what is going on?

**Comment by thephez** [comment]
Yes, Dash's [previously announced](https://www.dash.org/news/dash-core-v-018/) hard fork happened at block after they are stuck. This could happen if Dash Core was not updated to v18 prior to activation.

[This support article](https://support.dash.org/en/support/solutions/articles/26000050175-dashcore-wallet-v17-stuck-on-block-1737792) describes how to get back on track.

**Comment by jerrybb** [comment]
Thank you, this solved the issue indeed. Confirmed.
