### ISSUE TITLE
[Question] reconsiderblock throws an error

### ISSUE THREAD

**Issue by message** [dashpay/dash#5016]
### Describe the issue
My Dash Core daemon is not syncing new blocks. On a restart I have a message in `debug.log` about invalid block reconsideration.

```
2022-09-17T13:01:02Z ResetBlockFailureFlags: the best known invalid block (000000000000001aa25181e4c466e593992c98f9eb21c69ee757b8bb0af50244) is ahead of our tip, reconsidering
```

But while reconsidering it fails with
```
2022-09-17T13:02:56Z ERROR: ConnectBlock(DASH): ProcessSpecialTxsInBlock for block 000000000000001aa25181e4c466e593992c98f9eb21c69ee757b8bb0af50244 failed with bad-qc-invalid (code 16)
2022-09-17T13:02:56Z InvalidChainFound: invalid block=000000000000001aa25181e4c466e593992c98f9eb21c69ee757b8bb0af50244  height=1738698  log2_work=78.91219724  date=2022-09-15T12:41:21Z
2022-09-17T13:02:56Z InvalidChainFound:  current best=00000000000000362d528545b40976af8a9b5380def57d63943a30a9379a5385  height=1738697  log2_work=78.91219653  date=2022-09-15T12:39:02Z
2022-09-17T13:02:56Z ERROR: ConnectTip: ConnectBlock 000000000000001aa25181e4c466e593992c98f9eb21c69ee757b8bb0af50244 failed, bad-qc-invalid (code 16)
2022-09-17T13:02:56Z InvalidChainFound: invalid block=000000000000001aa25181e4c466e593992c98f9eb21c69ee757b8bb0af50244  height=1738698  log2_work=78.91219724  date=2022-09-15T12:41:21Z
2022-09-17T13:02:56Z InvalidChainFound:  current best=00000000000000362d528545b40976af8a9b5380def57d63943a30a9379a5385  height=1738697  log2_work=78.91219653  date=2022-09-15T12:39:02Z
```
I tried to run manually `reconsiderblock 000000000000001aa25181e4c466e593992c98f9eb21c69ee757b8bb0af50244` but I still get same error. Any suggestions on what should I do?

### What version of Dash Core are you using?
v18.0.1

### Machine specs:
- OS: Debian

**Comment by PastaPastaPasta** [comment]
Hi, 

I'm not able to reproduce this at the moment. Would you be able to do the following for me? 

shutdown dashd
delete debug.log
restart dashd with debug all. IE `dashd --debug=1` or my putting `debug=1`
please send that debug.log to me, there shouldn't be much sensitive info in there, but you may want to email it to me pasta@dash.org instead of posting it publicly. 

Thanks, that should provide us more info as to why it's being marked a bad-qc-invalid

**Comment by message** [comment]
I'm sorry. I was pushed into deleting blockchain and re-downloading it again, because I didn't knew how fast I would receive a reply. I still sent you an email, but it's without `--debug`.

**Comment by kxcd** [comment]
`dashd -debug` for the record.

**Comment by PastaPastaPasta** [comment]
> `dashd -debug` for the record.

This is the same as -debug=1 btw

**Comment by M03G** [comment]
@message  I have a similar problem on the same block.

**Comment by M03G** [comment]
`2022-09-19T14:55:36Z ThreadSocketHandler -- removing node: peer=0 nRefCount=1 fInbound=0 m_masternode_connection=0 m_masternode_iqr_connection=0    │
│2022-09-19T14:55:37Z New outbound peer connected: version: 70223, blocks=1740931, peer=1                                                            │
│2022-09-19T14:55:37Z ERROR: AcceptBlockHeader: block 000000000000001aa25181e4c466e593992c98f9eb21c69ee757b8bb0af50244 is marked invalid             │
│2022-09-19T14:55:37Z ThreadSocketHandler -- removing node: peer=1 nRefCount=1 fInbound=0 m_masternode_connection=0 m_masternode_iqr_connection=0    │
│2022-09-19T14:55:37Z New outbound peer connected: version: 70223, blocks=1740931, peer=2                                                            │
│2022-09-19T14:55:37Z ERROR: AcceptBlockHeader: block 000000000000001aa25181e4c466e593992c98f9eb21c69ee757b8bb0af50244 is marked invalid             │
│2022-09-19T14:55:38Z ThreadSocketHandler -- removing node: peer=2 nRefCount=1 fInbound=0 m_masternode_connection=0 m_masternode_iqr_connection=0    │
│2022-09-19T14:55:38Z New outbound peer connected: version: 70223, blocks=1740931, peer=3                                                            │
│2022-09-19T14:55:39Z ERROR: AcceptBlockHeader: block 000000000000001aa25181e4c466e593992c98f9eb21c69ee757b8bb0af50244 is marked invalid             │
│2022-09-19T14:55:39Z New outbound peer connected: version: 70219, blocks=1737833, peer=4                                                            │
│2022-09-19T14:55:39Z ThreadSocketHandler -- removing node: peer=3 nRefCount=1 fInbound=0 m_masternode_connection=0 m_masternode_iqr_connection=0    │
│2022-09-19T14:55:39Z Synchronizing blockheaders, height: 1737833 (~99.81%)                                                                          │
│2022-09-19T14:55:40Z New outbound peer connected: version: 70223, blocks=1740931, peer=5                                                            │
│2022-09-19T14:55:40Z New outbound peer connected: version: 70219, blocks=1737833, peer=6                                                            │
│2022-09-19T14:55:45Z P2P peers available. Skipped DNS seeding.                                                                                      │
│2022-09-19T14:55:45Z dnsseed thread exit                                                                                                            │
│2022-09-19T14:55:46Z New outbound peer connected: version: 70223, blocks=1740931, peer=7                                                            │
│2022-09-19T14:55:52Z New outbound peer connected: version: 70219, blocks=1737833, peer=8                                                            │
│2022-09-19T14:55:52Z New outbound peer connected: version: 70223, blocks=1740931, peer=9                                                            │
│2022-09-19T14:55:54Z New outbound peer connected: version: 70223, blocks=1740931, peer=10                                                           │
│2022-09-19T14:55:54Z New outbound peer connected: version: 70223, blocks=1740931, peer=11                                                           │
│2022-09-19T14:57:19Z ThreadSocketHandler -- removing node: peer=12 nRefCount=1 fInbound=0 m_masternode_connection=0 m_masternode_iqr_connection=0   │
│2022-09-19T14:57:57Z ThreadSocketHandler -- removing node: peer=13 nRefCount=1 fInbound=0 m_masternode_connection=0 m_masternode_iqr_connection=0   │
│2022-09-19T14:58:53Z InvalidChainFound: invalid block=000000000000001aa25181e4c466e593992c98f9eb21c69ee757b8bb0af50244  height=1738698  log2_work=78│
│2022-09-19T14:58:53Z InvalidChainFound:  current best=00000000000000362d528545b40976af8a9b5380def57d63943a30a9379a5385  height=1738697  log2_work=78│
│2022-09-19T14:58:58Z ERROR: ConnectBlock(DASH): ProcessSpecialTxsInBlock for block 000000000000001aa25181e4c466e593992c98f9eb21c69ee757b8bb0af50244 │
│2022-09-19T14:58:58Z InvalidChainFound: invalid block=000000000000001aa25181e4c466e593992c98f9eb21c69ee757b8bb0af50244  height=1738698  log2_work=78│
│2022-09-19T14:58:58Z InvalidChainFound:  current best=00000000000000362d528545b40976af8a9b5380def57d63943a30a9379a5385  height=1738697  log2_work=78│
│2022-09-19T14:58:58Z ERROR: ConnectTip: ConnectBlock 000000000000001aa25181e4c466e593992c98f9eb21c69ee757b8bb0af50244 failed, bad-qc-invalid (code 1├
│2022-09-19T14:58:58Z InvalidChainFound: invalid block=00000000000000038eb4daa0b1a66b6aa233395014733f1675e7afa1358702a8  height=1738729  log2_work=78│
│2022-09-19T14:58:58Z InvalidChainFound:  current best=00000000000000362d528545b40976af8a9b5380def57d63943a30a9379a5385  height=1738697  log2_work=78`

**Comment by PastaPastaPasta** [comment]
Hi. If you updated after the hard fork, it is likely you'll have to reindex.

**Comment by M03G** [comment]
> Hi. If you updated after the hard fork, it is likely you'll have to reindex.

The error appeared about 6-7 days ago.
After that, the version was updated.
Unfortunately, I do not remember when the update was last installed.
What hard fork are you talking about? When it was?

**Comment by M03G** [comment]
rescan did not help. reindex helped. Thanks
