### ISSUE TITLE
The node is stuck at height 1738697 having block hash of 00000000000000362d528545b40976af8a9b5380def57d63943a30a9379a5385. Next block 1738698 should be hash 000000000000001aa25181e4c466e593992c98f9eb21c69ee757b8bb0af50244 (as per all explorers) but it is not working as expected. We have even tried reconsiderblock command.

### ISSUE THREAD

**Issue by mpdev123** [dashpay/dash#5018]
Problem:

The node is stuck at height 1738697 having block hash of 00000000000000362d528545b40976af8a9b5380def57d63943a30a9379a5385. Next block 1738698 should be hash 000000000000001aa25181e4c466e593992c98f9eb21c69ee757b8bb0af50244 (as per all explorers) but it is not working as expected. We have even tried reconsiderblock command.

InvalidChainFound:  current best=00000000000000362d528545b40976af8a9b5380def57d63943a30a9379a5385  height=1738697  log2_work=78.91219653  date=2022-09-15T12:39:02Z
this block 1738698:
2022-09-19T09:14:59Z ERROR: ConnectTip: ConnectBlock 000000000000001aa25181e4c466e593992c98f9eb21c69ee757b8bb0af50244 failed, bad-qc-invalid (code 16)

Node info:

$ ./dash-cli getblockchaininfo
{
  "chain": "main",
  "blocks": 1738697,
  "headers": 1738697,
  "bestblockhash": "00000000000000362d528545b40976af8a9b5380def57d63943a30a9379a5385",
  "difficulty": 73244017.95390324,
  "mediantime": 1663244460,
  "verificationprogress": 0.9986797140566226,
  "initialblockdownload": true,
  "chainwork": "000000000000000000000000000000000000000000007871309887ec28a6e90a",
  "size_on_disk": 31209153982,
  "pruned": false,
...

$: ./dash-cli getnetworkinfo
{
  "version": 180001,
  "buildversion": "v18.0.1",
  "subversion": "/Dash Core:18.0.1/",
  "protocolversion": 70223,
...

**Comment by thephez** [comment]
Please try the instructions list in https://github.com/dashpay/dash/issues/5014#issuecomment-1248127313 if you haven't already. Due to the nature of this upgrade, you can encounter this depending on exactly when you upgraded to v18.

**Comment by PastaPastaPasta** [comment]
If @thephez's suggestion doesn't work, you likely will need to reindex
