### ISSUE TITLE
sync stopped at 1737833

### ISSUE THREAD

**Issue by mtb-pro** [dashpay/dash#5031]
how to fix it?

Dash Core RPC client version v0.17.0.3
dash-cli getblockchaininfo

{
  "chain": "main",
  "blocks": 1737833,
  "headers": 1737833,
  "bestblockhash": "0000000000000002e91bac9f95f96885a89de2c46846d197933c8c5f03cb806f",
  "difficulty": 75380794.81416096,
  "mediantime": 1663107922,
  "verificationprogress": 0.989364943128956,
  "initialblockdownload": true,
  "chainwork": "0000000000000000000000000000000000000000000078608c6e0b7e27c0dd3f",
  "size_on_disk": 31167033577,
  "pruned": false,
  "softforks": [
    {
      "id": "bip34",
      "version": 2,
      "reject": {
        "status": true
      }
    },
    {
      "id": "bip66",
      "version": 3,
      "reject": {
        "status": true
      }
    },
    {
      "id": "bip65",
      "version": 4,
      "reject": {
        "status": true
      }
    }
  ],
  "bip9_softforks": {
    "csv": {
      "status": "active",
      "startTime": 1486252800,
      "timeout": 1517788800,
      "since": 622944
    },
    "dip0001": {
      "status": "active",
      "startTime": 1508025600,
      "timeout": 1539561600,
      "since": 782208
    },
    "bip147": {
      "status": "active",
      "startTime": 1524477600,
      "timeout": 1556013600,
      "since": 939456
    },
    "dip0003": {
      "status": "active",
      "startTime": 1546300800,
      "timeout": 1577836800,
      "since": 1028160
    },
    "dip0008": {
      "status": "active",
      "startTime": 1557878400,
      "timeout": 1589500800,
      "since": 1088640
    },
    "realloc": {
      "status": "active",
      "startTime": 1601510400,
      "timeout": 1633046400,

**Comment by UdjinM6** [comment]
pls see https://github.com/dashpay/dash/issues/5014#issuecomment-1248127313

**Comment by mtb-pro** [comment]
I use the following functions and it is not possible to update to version 0.18 for me

getaccountaddress
getaddressesbyaccount
getbalance|getnewaddress
getreceivedbyaccount
listtransactions
move
sendfrom
sendmany

what do i can do now?

**Comment by thephez** [comment]
> I use the following functions and it is not possible to update to version 0.18 for me
> 
> getaccountaddress getaddressesbyaccount getbalance|getnewaddress getreceivedbyaccount listtransactions move sendfrom sendmany
> 
> what can i do now?

Some of these still exist (getbalance, getnewaddress, listtransactions, sendmany) and some of them represented by the new "labels" system that was introduced by Bitcoin before they dropped accounts (getaddressbylabel, getreceivedbylabel). I'm not sure what would be required to move from accounts to labels. Bitcoin made this change ~4 yrs ago so there may be some info available from people that encountered this situation with it.

**Comment by PastaPastaPasta** [comment]
solution was provided
