### ISSUE TITLE
Dash-Qt: Date in recent transactions is wrong

### ISSUE THREAD

**Issue by schinzelh** [dashpay/dash#507]
I've noticed that the dates of transactions in the QT are not correct during blockchain download

![image](https://cloud.githubusercontent.com/assets/636669/9191498/47f3c01c-4002-11e5-8f51-48e03eb381ba.png)

Although my blockchain is 21 weeks behind, the transactions wobble around the current date (2015-08-11).

May be caused by "headers first" approach.

**Comment by UdjinM6** [comment]
It's not "wrong" imo, it's just the whole list/wallet is "out of sync" as stated everywhere in the wallet :stuck_out_tongue: There is a bunch of stuff on sync process under the hood and wallet tries to keep off from updating GUI, reorganizing/beautifying things because it could bring a noticeable lag (updating GUI requires `cs_main` lock in many places for example).

**Comment by schinzelh** [comment]
I am not saying that the wallet should display the transactions in correct order, but at least showing the correct date from the block the tx occured. This wallet has 10000 incoming tx and all are displayed as being occured between 2015-08-09 and 2015-08-11, which changing times of day. I'll create a screen capture to show what i mean :)

**Comment by schinzelh** [comment]
Even after sucessful rescan the dates mismatch

![image](https://cloud.githubusercontent.com/assets/636669/9192360/b0e17968-400a-11e5-8343-aa6bd59b7219.png)

**Comment by UdjinM6** [comment]
ohhh....wow... does this persists after wallet restart?

**Comment by schinzelh** [comment]
Yep, it does. Maybe this is even related with "importprivkey", as all addresses have been imported into that wallet.

**Comment by schinzelh** [comment]
It seems i found a rare edge case in importprivkey/rescan functionality.

These are the steps to reproduce.

- create new wallet.dat
- let blockchain sync
- importprivkey cSPr4ikmBEsDJ6Rn1fGnU7FeJ767dLZxXm27udW8jwvQrPb3BqKg 0 false
- stop wallet
- restart walllet with --rescan

Result 1:

![image](https://cloud.githubusercontent.com/assets/636669/9193804/88c5e534-4016-11e5-9c15-95e508f9e199.png)

- importprivkey cVq6Vt9UqgqeDSuPb2qjvxrVfbt6pPQZPQNpmnHM1SUgdP3aoHQY 0 true

Result 2:

![image](https://cloud.githubusercontent.com/assets/636669/9193871/22b84042-4017-11e5-8743-0b09efbceba1.png)

http://test.explorer.dash.qa/tx/e33acc10454e57c19d5f2c8b866736bb7964a18d66b4b1e3952b983ea73d0365#o21

So it seems the date from the first tx is leaking into the second tx after the rescan.

**Comment by schinzelh** [comment]
Obsolete
