### ISSUE TITLE
Not sure how to start coinjoin process on dash daemon only with rpc calls

### ISSUE THREAD

**Issue by anycolo** [dashpay/dash#5078]
Is `coinjoin start` enough?
Where can i see the progress?
I can see the outputs in `listunspent` but where can i set the minimum mixed value?
These can be set up in the GUI, but there is little information on how to do it via console.

**Comment by Freigh** [comment]
I've been trying to get this to open a well.. I have the account from stellar.  Just can't seem to get the cash out
