### ISSUE TITLE
Incorrect values shown in Qt GUI for large, complex transaction

### ISSUE THREAD

**Issue by strophy** [dashpay/dash#5180]
### Describe the issue

I'm experiencing what I assume is a UI problem in Dash Core 18.2.1. I am trying to clean up a lot of mining outputs and consolidate it on the faucet, which requires sending a large transaction with a custom change address, in this case 4000 tDASH in an 80kb transaction. The values displayed in the confirmation dialog are completely incorrect if I select "Subtract fee from amount". It works fine if I don't select that checkbox.

#### If so, please list the steps to reproduce below:
1. Have the testnet mining target wallet loaded (contains a single address, so must pay change to custom address)
2. Attempt to send 4000 tDASH to an address with/without `Subtract fee from amount` checkout checked
3. Observe different values displayed in GUI, incorrect when `Subtract fee from amount` is checked

### Expected behaviour
The GUI should show the correct values

### Actual behaviour
The GUI shows incorrect values when `Subtract fee from amount` is checked

### Screenshots.
![image](https://user-images.githubusercontent.com/32928115/216866648-def81b84-584c-4260-a79e-b8593c20971c.png)
![image](https://user-images.githubusercontent.com/32928115/216866667-5cd64152-5026-41db-b303-f9a9a672faba.png)

### What version of Dash Core are you using?
v18.2.1 dash-qt

### Machine specs:
- OS: Fedora 37
- CPU: AMD Ryzen 7 PRO 6850H
- RAM: 32GB LPDDR5
- Disk size: 2TB
- Disk Type (HD/SDD): SSD

### For the GUI-related issue on Linux provide names and versions of a distro, a desktop environment and a graphical shell (if relevant).
Fedora 37
Kernel 6.1.9
Gnome 43.2 (Wayland)

**Comment by knst** [comment]
It may be some integer overflow or using `unsigned int` somewhere instead CAmount.

I read code around, but I can't spot a bug yet :disappointed: 

Btw, I'd like to see 2 things.
if the cause related to integer **signed** overflow, sanitizer can help.
Need to build code like that:
```
make clean && ./autogen.sh && ./configure --prefix=$(pwd)/depends/x86_64-pc-linux-gnu  --with-sanitizers=signed-integer-overflow  
```
After configure you should see this line:
```
sanitizers         = signed-integer-overflow
```
If the signed integer overflow will happen, sanitizer will spot an exact line in code where it happened.

-----
There are also some logs included in build, that can be useful to localize issue such as
```
    WalletLogPrintf("Fee Calculation: Fee:%d Bytes:%u Tgt:%d (requested %d) Reason:\"%s\" Decay %.5f: Estimation: (%g - %g) %.2f%% %.1f/(%.1f %d mem %.1f out) Fail: (%g - %g) %.2f%% %.1f/(%.1f %d mem %.1f out)\n",
```
May be there's something useful appears in logs? Can you attach to issue the related logs also?
