### ISSUE TITLE
Functional Test Failures on Mac arm with SQLite

### ISSUE THREAD

**Issue by PastaPastaPasta** [dashpay/dash#5187]
1. Build depends
2. `./configure --prefix=$(pwd)/depends/aarch64-apple-darwin22.2.0 --enable-werror --enable-suppress-external-warnings --enable-c++20 --with-sqlite --without-bdb`
3. `make clean && make -j8 check`
4. `./test/functional/test_runner.py -j 20 feature_filelock.py tool_wallet.py wallet_dump.py wallet_multiwallet.py`

All tests fail when they should succeed, see logs here: https://gist.github.com/PastaPastaPasta/fc6f3221b58a1fa65376753978c360f4

commit: 97d94520d03e3ba3a010476358bfc04d4544536d

**Comment by kittywhiskers** [comment]
Confirmed on Debian 11, tests are compiled support specific, not OS specific
