### ISSUE TITLE
Create wallet screen doesn't render properly

### ISSUE THREAD

**Issue by thephez** [dashpay/dash#5248]
### Describe the issue

On at least some Linux installations, the "Create Wallet" screen is malformed with text overlapped by other elements and/or cut off.

#### If so, please list the steps to reproduce below:
1. Open Core Qt v18 or v19-RC
2. Click "File" -> "Create Wallet"

### Expected behaviour
All elements should be visible

### Actual behaviour
Some elements overlap

### Screenshots.

![image](https://user-images.githubusercontent.com/8145677/224752588-48926bc1-19dc-49a1-9a80-4ae154004d4a.png)

### What version of Dash Core are you using?
This happens with at least 18.2.1 and 19.0-RC5

### For the GUI-related issue on Linux provide names and versions of a distro, a desktop environment and a graphical shell (if relevant).
Ubuntu 22.04 (X11)

**Comment by knst** [comment]
done and backported to 19.x https://github.com/dashpay/dash/pull/5266
