### ISSUE TITLE
Dash Core v19.0.0 RC6 (Testnet) : protx register_submit problem with 4000 tdash collateral

### ISSUE THREAD

**Issue by qwizzie** [dashpay/dash#5256]
I tried to do a protx register_submit of a 4000 tdash transaction (after Dash Core v19 activation) that i got from the protx register_prepare command , but i am getting a bad-protx-collateral (code 16) (code -1) error, after issuing that protx register_submit. Goal is to start a HPMN on Testnet.

Update 16-03-2023 : turns out that for 4K high performance masternodes a different protx register_prepare command needs to be used :

protx register_prepare_hpmn "collateralHash" collateralIndex "ipAndPort" "ownerAddress" "operatorPubKey_register" "votingAddress_register" "operatorReward" "payoutAddress_register" "platformNodeID" platformP2PPort platformHTTPPort ( "feeSourceAddress" )

platformP2PPort is 26656 (fixed for testnet i assume)
platformHTTPPort is 3000 (fixed for testnet i assume) 

No idea what my (unique ?) platformNodeID is. I asked pshenmic about this, as i am trying to setup a HPMN through Dashmate which he maintains.

If anyone else can tell me where or how i can find this platformNodeID, i would appreciate it. The one i thought it perhaps was in Dashmate's config.json (testnet - platform - tenderdash - Nodekey - id ), threw a 'platformNodeID must be hexadecimal string (code -8) on me.

**Comment by ogabrielides** [comment]
@qwizzie Until actual Platform release you can use any non-empty hash160 hex string as long as it is unique across the network.
You can use online tool such as https://md5calc.com/hash/ripemd160 to generate them.

**Comment by qwizzie** [comment]
Thank you, but i found it inside my Dashmate's config.json file. It was stored there under testnet - Platform - Nodekey --> id
I jkust had some trouble getting the protx register_prepare_hpmn correct as i did not put the feeSourceAddress at the end. So i got an error. But thats all fixed now and i got my masternode HPMN registered.

**Comment by ogabrielides** [comment]
@qwizzie Just keep in mind that the above is just a workaround for Testnet right now. With Core v19 rollout, the HPMN DIP will be released as well including a section describing steps to calculate `platformNodeID`

**Comment by qwizzie** [comment]
@ogabrielides Problem is that i can't really use Dashmate to setup a single masternode (registered through protx commands specific to hpmn as a HPMN) on Testnet and have it deploy and connect properly to Platform. It will then just keep showing status 'restarting' with regards Drive ABCI and Drive Tenderdash. 

Not untill pull request 794 has been merged --> https://github.com/dashpay/platform/pull/794

To be honest i kinda expected i could use Dashmate with the release of v19.0.0 on Testnet to just setup a single masternode as a HPMN and connect to Platform properly.
