### ISSUE TITLE
upgradewallet missing from help output

### ISSUE THREAD

**Issue by thephez** [dashpay/dash#5263]
### Describe the issue
`-upgradewallet` no longer appears in the help output for dashd/dash-cli

#### If so, please list the steps to reproduce below:
1. Run `dashd -help` or `dash-cli -help`

### Expected behaviour
Expect to see help output for `upgradewallet` (the RPC still exists)

### Actual behaviour
`upgradewallet` missing from help output

### What version of Dash Core are you using?
v19.0.0-RC.7

**Comment by UdjinM6** [comment]
`-upgradewallet` cmd-line option was removed in https://github.com/dashpay/dash/commit/5f10b3e5dc9744aedca5cb4b222c777389f86155#diff-f807f97d1de845ebccc36c08e68869abcfe37478871194d5d4beb9a29047145aL65
