### ISSUE TITLE
Mining error with Testnet v19 RC.7

### ISSUE THREAD

**Issue by thephez** [dashpay/dash#5264]
### Describe the issue
Get an error message like this when trying to mine:

```CalcCbTxMerkleRootMNList -- failed: RemoveMN: Can't delete a masternode a554045a49fb5e84a01af9e8bff2a3bf77846b27c36530a7552524f65164893a with a duplicate platformNodeID=0000000000000000000000000000000000000000```

#### If so, please list the steps to reproduce below:
1. Run 19-RC7 and try to mine

### What version of Dash Core are you using?
v19.0.0-rc.7

### Any extra information that might be useful in the debugging process.
Earlier today I registered a HPMN (TXID: `a554045a49fb5e84a01af9e8bff2a3bf77846b27c36530a7552524f65164893a`), then issued a `protx revoke`. Later I tried to register a new HPMN (TXID: `3979cfb79c4562e819aca69ffae2ea84b9b8f29bd89bdc68be67b88c6f31bf99`) re-using the same collateral, but changing the necessary parameters (platform node id, IP, owner key). That second tx appears stuck in the mempool.

**Comment by PastaPastaPasta** [comment]
Unable to reproduce so far...

**Comment by PastaPastaPasta** [comment]
This should fix it

**Comment by ogabrielides** [comment]
Fixed
