### ISSUE TITLE
Translation Problem ZH_HK

### ISSUE THREAD

**Issue by Naruto323** [dashpay/dash#529]
The ZH_HK Translation is outdated cos it is still using Darkcoin (暗黑幣) in Chinese.It can be removed since ZH_HK and ZH_TW is basically the same.There is no need to keep this outdated translation in the program.
![590967356_2015_08_1507 37 08_122_575lo](https://cloud.githubusercontent.com/assets/13805505/9287271/15854f52-433f-11e5-95f7-957b9ebe57fc.jpg)

**Comment by UdjinM6** [comment]
Yep, that's exactly what is planned https://dashtalk.org/threads/please-help-in-translations-for-v12-wallets.5523/page-3#post-63390 for next translations update

**Comment by UdjinM6** [comment]
Would also be nice to get Chinese more progress. Please help us to translate Dash https://www.transifex.com/dash/dash/dash_ents/ Thanks!
