### ISSUE TITLE
CPU/Memory Problem after two days, process shutdown

### ISSUE THREAD

**Issue by minersday** [dashpay/dash#535]
The CPU hogging dashd thread is, please fix it, if possible:
from top -H:
21921 xxxxx 22 2 908200 179908 36092 R 58.1 8.8 49:39.70 dash-msghand

getting messages like this, continious flood, like screen is scrolling as fast as it can..
strace -p 21921:
endto(39, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\373\257\264\272,\226\312<\375\35\242\304"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(31, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\373\257\264\272,\226\312<\375\35\242\304"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(35, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\373\257\264\272,\226\312<\375\35\242\304"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(36, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\373\257\264\272,\226\312<\375\35\242\304"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(37, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\373\257\264\272,\226\312<\375\35\242\304"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(33, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\373\257\264\272,\226\312<\375\35\242\304"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(20, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\356\247\370\"\16\274\242\260Q\r\220\336"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(26, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\356\247\370\"\16\274\242\260Q\r\220\336"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(24, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\356\247\370\"\16\274\242\260Q\r\220\336"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(28, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\356\247\370\"\16\274\242\260Q\r\220\336"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(30, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\356\247\370\"\16\274\242\260Q\r\220\336"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(32, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\356\247\370\"\16\274\242\260Q\r\220\336"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(21, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\356\247\370\"\16\274\242\260Q\r\220\336"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(23, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\356\247\370\"\16\274\242\260Q\r\220\336"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(29, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\356\247\370\"\16\274\242\260Q\r\220\336"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(27, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\356\247\370\"\16\274\242\260Q\r\220\336"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(39, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\356\247\370\"\16\274\242\260Q\r\220\336"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(31, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\356\247\370\"\16\274\242\260Q\r\220\336"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(35, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\356\247\370\"\16\274\242\260Q\r\220\336"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(36, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\356\247\370\"\16\274\242\260Q\r\220\336"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(37, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\356\247\370\"\16\274\242\260Q\r\220\336"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(33, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\356\247\370\"\16\274\242\260Q\r\220\336"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(20, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\373\257\264\272,\226\312<\375\35\242\304"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(26, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\373\257\264\272,\226\312<\375\35\242\304"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(24, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\373\257\264\272,\226\312<\375\35\242\304"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(28, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\373\257\264\272,\226\312<\375\35\242\304"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(30, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\373\257\264\272,\226\312<\375\35\242\304"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(32, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\373\257\264\272,\226\312<\375\35\242\304"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(21, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\373\257\264\272,\226\312<\375\35\242\304"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(23, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\373\257\264\272,\226\312<\375\35\242\304"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(29, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\373\257\264\272,\226\312<\375\35\242\304"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(27, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\373\257\264\272,\226\312<\375\35\242\304"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(39, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\373\257\264\272,\226\312<\375\35\242\304"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140
sendto(31, "\277\fk\275dseep\0\0\0\0\0\0\0t\0\0\0\373\257\264\272,\226\312<\375\35\242\304"..., 140, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 140

--- 
minimal hogging:
futex(0x7f615b513d68, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7f615b513d94, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 34140475, {1439662667, 560970182}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f615b513d68, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7f615b513d94, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 34140477, {1439662667, 562308164}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f615b513d68, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7f615b513d94, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 34140479, {1439662667, 563645382}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f615b513d68, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7f615b513d94, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 34140481, {1439662667, 565038070}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f615b513d68, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7f615b513d94, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 34140483, {1439662667, 566340425}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f615b513d68, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7f615b513d94, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 34140485, {1439662667, 567818400}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f615b513d68, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7f615b513d94, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 34140487, {1439662667, 569213288}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f615b513d68, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7f615b513d94, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 34140489, {1439662667, 570554175}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f615b513d68, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7f615b513d94, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 34140491, {1439662667, 571893022}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f615b513d68, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7f615b513d94, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 34140493, {1439662667, 573248748}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f615b513d68, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7f615b513d94, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 34140495, {1439662667, 574590053}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f615b513d68, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7f615b513d94, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 34140497, {1439662667, 575932126}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f615b513d68, FUTEX_WAKE_PRIVATE, 1) = 0

----

Don't know if it's from BOOST_FOREACH doing the dseep looping, maybe wait/sleep has to be in there?

**Comment by minersday** [comment]
Issue fixed with version ..45

**Comment by darkcoinproject** [comment]
Perfect thanks

**Comment by minersday** [comment]
There's something happening after two day's it seems. CPU / Memory goes up and down like a chainsaw..

spamming the same thing connection timed out.

**Comment by minersday** [comment]
![cpu-usage](https://cloud.githubusercontent.com/assets/7759283/9337090/ce9b3f80-45e5-11e5-871d-b61fddf9d8f7.png)
![memory-usage](https://cloud.githubusercontent.com/assets/7759283/9337091/cea3c150-45e5-11e5-93d8-178ffe097510.png)

**Comment by minersday** [comment]
Spamming the  (Connection timed out), in the process.

**Comment by evan82** [comment]
Do you have a "connect=" in your configuration?

**Comment by minersday** [comment]
Nope, in any of the dash.conf:s.

**Comment by minersday** [comment]
People having daemon shutdown, could be because of the memory/CPU erratic use after two days. Could trigger daemon shutdown in hosting services.

**Comment by minersday** [comment]
Could this be the problem?
http://stackoverflow.com/questions/28320969/futex-return-etimedout-quicker-than-the-parameter-timeout

all of masternodes are configured to keep the time with ntpd, and in VM-hosting enviroments, there could be clock cycle skips, because of the shared enviroment. And ntpd needs to adjust time.

**Comment by minersday** [comment]
Changed the clocksource in VM to acpi_pm:
echo acpi_pm > /sys/devices/system/clocksource/clocksource0/current_clocksource

now getting mostly spammed in strace with:
gettimeofday({1439921834, 663640}, NULL) = 0
gettimeofday({1439921834, 663765}, NULL) = 0
gettimeofday({1439921834, 663841}, NULL) = 0

**Comment by minersday** [comment]
With .046
CPU/MEM/Disk/Network usage, seems to gone back down to normal levels and not going up and down rapidly.
