### ISSUE TITLE
minimum size of CoinJoin denominations

### ISSUE THREAD

**Issue by p-m** [dashpay/dash#5374]
Hi,
It would be nice to have a configuration option for the minimum size of CoinJoin denominations.
(Perhaps another one for the maximum size could be nice too.)
TIA for any implementation, Peter

**Comment by PastaPastaPasta** [comment]
It's not clear what you mean. Please try to clarify what you're requesting

**Comment by p-m** [comment]
When I use CoinJoin, a lot of denominations with a size of 0.00100001 are made.
I don't need them.
I would like to specify the minimum size, for example 0.100001.

**Comment by p-m** [comment]
Hi,
Would it work, if I delete for example lines 395 and 396 in src/coinjoin/coinjoin.h and recompile?
I mean, as a workaround, before having a runtime option?
TIA for any help, Peter

**Comment by kxcd** [comment]
Check the commandline options, there are ways to target certain denomination sizes.

**Comment by p-m** [comment]
How please?

Example : There are 32.1 Dash in the wallet. How can I get 3 times 10.0001, 2 times 1.00001 and some change of a bit less than 0.1 Dash please?

**Comment by p-m** [comment]
I think, you can close this issue. Bridgewater on Discord help-desk has just sent a quite acceptable work-around.
