### ISSUE TITLE
Update mount instructions on docker hub

### ISSUE THREAD

**Issue by qrest** [dashpay/dash#5387]
The documentation on https://hub.docker.com/r/dashpay/dashd is suggesting to mount a volume to `/dash`, which is not correct since v18.1. Instead the volume should be mounted to `/home/dash`. 

Change

``
 docker volume create --name=dashd-data
 docker run -v dashd-data:/dash --name=dashd-node -d \
     -p 9999:9999 \
     -p 127.0.0.1:9998:9998 \
     dashpay/dashd
``

to

``
 docker volume create --name=dashd-data
 docker run -v dashd-data:/home/dash --name=dashd-node -d \
     -p 9999:9999 \
     -p 127.0.0.1:9998:9998 \
     dashpay/dashd
``

This change was introduced by this commit: https://github.com/dashpay/dash/commit/6699b0228f9fd5885ebe60d2e33e4f678ed77c18

**Comment by PanderMusubi** [comment]
Can you make a PR for this?

**Comment by qrest** [comment]
> Can you make a PR for this?

The repository (https://github.com/dashpay/docker-dashd) is archived so no I can not.

**Comment by PanderMusubi** [comment]
Ah, but the docker files live now here https://github.com/dashpay/dash/tree/master/contrib/containers

**Comment by qrest** [comment]
Right, but the image description is not fetched from there. So I guess the owner of the docker hub account has to change it directly.

**Comment by PanderMusubi** [comment]
Anybody knows who is that? @kwvg @PastaPastaPasta @strophy

**Comment by qrest** [comment]
Thanks, the docker image page is indeed correct now

**Comment by PanderMusubi** [comment]
Or is it the functionality that is offered for free isn't sufficient for what you talk about?
