### ISSUE TITLE
No block sources available

### ISSUE THREAD

**Issue by shaygover** [dashpay/dash#5396]
What I did:

1. Reset network
2. Manually added nodes from https://www.dashninja.pl/deterministic-masternodes.html#mnlistdetail
3. Checked that I can reach those nodes on port 9999. I can.

Ideas?

version: v0.12.0.56-7154cdf on Arch Linux.

**Comment by PastaPastaPasta** [comment]
Well, if you're actually using v0.12.0.56 of Dash Core then that'll be you're issue... You need to be using v19.1.0 https://github.com/dashpay/dash/releases/tag/v19.1.0; please reopen if you continue to have issues.

**Comment by shaygover** [comment]
That's strange, the package was installed via AUR. Source URL is https://github.com/dashpay/dash/releases/download/v19.1.0/dashcore-19.1.0-x86_64-linux-gnu.tar.gz 
but the about inside the gui reports v0.12.0.56-7154cdf.

**Comment by shaygover** [comment]
That was a local error on my system. Keep it close
