### ISSUE TITLE
(Dash Core wallet) mismatch between payment queue position for Masternodes/Evonodes and number of enabled Masternodes+Evonodes in Tools/Information

### ISSUE THREAD

**Issue by qwizzie** [dashpay/dash#5528]
Dash Core wallet v19.3.0
Windows 

Why is the masternode payment queue position for regular Masternodes and Evonodes higher, then the combined enabled number of regular masternodes and Evonodes operating on the Dash network ?

Some random just paid regular masternodes : 3594

![Knipsel](https://github.com/dashpay/dash/assets/6610543/fcc041ae-ea9c-4bb4-8fe7-7ef0a9813887)

Some random just paid HighPerformance / Evonodes : 3585-3587-3586-3581

![Knipsel1](https://github.com/dashpay/dash/assets/6610543/8dbdb8f6-3d5e-42ff-9f35-f7227a8b7858)

Number of regular Masternodes + HPMNs / Evonodes according Tools - Information : 3378+54=3432

![Knipsel2](https://github.com/dashpay/dash/assets/6610543/f8b6b008-b5a3-4e7b-94c3-9af58f79063a)

I asked rango of Dash Central to check his masternode queue position logic (note: his Nextpay is based on 3432), but now i am starting to think maybe there is something wrong with the Dash Core wallet in that regard and Dash Central is simply fetching an incorrect number from there. So I suspect this issue also affects Dash Central masternode payment queue position logic.

First created a forum post, but remembered devs don't really respond to forum posts that often so therefore also this Github issue. Forum post here : https://www.dash.org/forum/index.php?threads/v19-3-0-release-announcement.53942/#post-235636

**Comment by UdjinM6** [comment]
>Why is the masternode payment queue position for regular Masternodes and Evonodes higher, then the combined enabled number of regular masternodes and Evonodes operating on the Dash network ?

HPMNs/Evonodes are paid 4 times in a row so payment queue length in your example is 3378+54*4=3594

**Comment by qwizzie** [comment]
That makes sense. So it looks like Dash Central is not taking into account that Evonodes enabled count number needs to be multiplied with 4, in its masternode next payment logic (Nextpay). I will forward this to Dash Central / rango.
