### ISSUE TITLE
On behalf of Dash Central : determining correct masternode/evo node collateral address, in a situation of having same payout address

### ISSUE THREAD

**Issue by qwizzie** [dashpay/dash#5571]
rango from Dash Central asked me to forward his issue with having the same payout address for several masternodes/evonodes causing some issues for Dash Central, to the Dashcore Incident system. I just know the 'Issues' on Dashpay Github, so i made a Github issue for rango here.

It is related to having a same payout address for several masternodes/evonodes, causing issues for Dash Central (MN payments from MN1 end up with MN2, causing Last Pay to reset and causing a distortion of the masternode payments history on Dash Central).

His question is as follows 

> What is the recommended way to determine the masternode collateral address of the masternode, that has been paid for a given block hash? I have problems distinguishing the correct masternode that received a payment if two masternodes/evo nodes use the same payout address on Dash Central.

rango also reached out to Quantum Explorer on Slack.

**Comment by thephez** [comment]
From slack:

Use [`masternode payments`](https://docs.dash.org/projects/core/en/stable/docs/api/remote-procedure-calls-dash.html#masternode-payments)

```
ubuntu@hp-masternode-4:~$ dash-cli masternode payments
[
  {
    "height": 901406,
    "blockhash": "000000a084436f31b25315c351322fd54908e9c68e57ab697dc8e000ce60ade8",
    "amount": 1003679457,
    "masternodes": [
      {
        "proTxHash": "9427f6cbb0807d4783d74927eaf1a70e9c19339ac47ac7be1dd80b0ca4ec2835",
        "amount": 1003679457,
        "payees": [
          {
            "address": "",
            "script": "6a",
            "amount": 376379796
          },
          {
            "address": "yVXDAM73Tg6A44Bm3qduXsMCYxzuqBCT48",
            "script": "76a91464f2b2b84f62d68a2cd7f7f5fb2b5aa75ef716d788ac",
            "amount": 627299661
          }
        ]
      }
    ]
  }
]
```

>it defaults to current block, but you can give it a blockhash
from the protx hash given you should be able to figure out which MN it is

```
ubuntu@hp-masternode-4:~$ dash-cli masternode list | grep -A13 -B1 9427f6cbb0807d4783d74927eaf1a70e9c19339ac47ac7be1dd80b0ca4ec2835
  "4ee3ff5074723d995f4cb957a954587c6c637a42655ada8f4054037b28d1e7a8-67": {
    "proTxHash": "9427f6cbb0807d4783d74927eaf1a70e9c19339ac47ac7be1dd80b0ca4ec2835",
    "address": "34.209.238.228:19999",
    "payee": "yVXDAM73Tg6A44Bm3qduXsMCYxzuqBCT48",
    "status": "ENABLED",
    "type": "Regular",
    "pospenaltyscore": 0,
    "consecutivePayments": 0,
    "lastpaidtime": 1694073057,
    "lastpaidblock": 901406,
    "owneraddress": "ygaU7693ezDaVFxcgoixRYLAHHSq33xZSa",
    "votingaddress": "ygaU7693ezDaVFxcgoixRYLAHHSq33xZSa",
    "collateraladdress": "yZFzoi8rfXVhj1i5bDKCciPyCb7nVQT1YC",
    "pubkeyoperator": "959f6f2d48d283390b246a55b19a267f8ada326c8eb67f217839d5d1cc55377d8c1a2962cd5e80b892577454390c36b8"
  },```

**Comment by qwizzie** [comment]
I have forwarded this info to rango and i will close this issue once rango gives feedback to me that he fixed his issue.

**Comment by qwizzie** [comment]
Looks like rango got it fixed : 

> New masternode collateral payment detection has been activated. Payments for two masternodes with with two collaterals on one address are now correctly detected. It works for all new payments. 

I will close this issue here.
