### ISSUE TITLE
Tesnet nodes stuck at block 900699

### ISSUE THREAD

**Issue by the-smooth-operator** [dashpay/dash#5573]
Hello,
all our nodes (>3) running testnet got stuck today at block 900699.
Furthermore, we started a new node in testnet starting from 0 and it also got stuck at the same block.

We have tried making the block as invalid, and reconsidering it without success. We tried reindexing the chain too.
We are running the last stable version 19.3, and tried using the pre-release 20.0.0 but it did not fix the issue.

Here are the relevant logs:
```
2023-09-08T13:42:34Z ERROR: AcceptBlockHeader: block 00000046ef806654fcd0a92299325b6ec6f99c514b9ae82a64d7cc2f8f4fd798 is marked invalid
```

**Comment by thephez** [comment]
Did you reindex when running the latest (v20)? The v20 hard fork activated on testnet which is why 19.3 isn't syncing. But a reindex with v20 should have get things back on track.

**Comment by the-smooth-operator** [comment]
Reindexing with v20 made the trick. Thanks
