### ISSUE TITLE
meta: unfork on GitHub from bitcoin/bitcoin

### ISSUE THREAD

**Issue by coolaj86** [dashpay/dash#5643]
# The Solution

Click on the [GitHub Support: Detach Fork](https://support.github.com/contact?flow=detach_fork&subject=Detach%20Fork&tags=rr-forks) at:
- <https://support.github.com/contact?flow=detach_fork&subject=Detach%20Fork&tags=rr-forks>

# The Problem

This is being listed as a contributing soft fork (i.e. one that exists for the purpose of doing PRs upstream).

As such, GitHub is sending bot tags that tell search engines to prefer what we have mistakenly labeled as the "upstream".

(granted, there are enough links to this repo that it confuses search engines enough to list us despite the "canonical" meta tags and such - but make no mistake, we're fighting against them)

# Forked from BitCoin/Core/Pay

Anywhere you see `forked from` it means we are explicitly telling search engines to ignore our project and to refer people to the "upstream" instead.

<img width="191" alt="Screenshot 2023-10-23 at 11 11 25 AM" src="https://github.com/dashpay/dash/assets/122831/13c89bea-a5c2-48ca-a1f0-3ec555c71c8f">

# Documentation

<img width="564" alt="Screenshot 2023-10-23 at 11 02 09 AM" src="https://github.com/dashpay/tenderdash/assets/122831/17102d93-028a-4d26-b58f-7f198112409f">

Replaces #5419

**Comment by PastaPastaPasta** [comment]
Closing; please don't create new issues that duplicate your own issue.. Please update the old issue instead

**Comment by coolaj86** [comment]
@PastaPastaPasta That's silly. Then it stays at the bottom of the pile.

Squeaky wheel gets grease. Dusty wheel gets no grease.

If we ourselves don't take pride in Dash, how can we expect it to do anything but continue to fall.

This isn't a "we'll get around to it in another 3 years, once the important work gets done" type of issue.

This is a "no one will care about Dash so long as it doesn't put it's big boy pants on, or at least it's one name tag" issue. A "what happens when we reach the finish line, but never told anyone there was a race" issue.

**Comment by PastaPastaPasta** [comment]
If you're worried about an issue not getting attention; add comments to it, get others to add comments to it; ping me on discord about it. Creating duplicate issues is not the solution.

**Comment by coolaj86** [comment]
And yet you've taken more time to address the meta-ness of the issue, than to click the button. Eh?

**Comment by coolaj86** [comment]
(or maybe you did click the button?)
