### ISSUE TITLE
test: rework function tests to have asset unlock functionality activated via mn_rr

### ISSUE THREAD

**Issue by PastaPastaPasta** [dashpay/dash#5644]
see todo introduced here: https://github.com/dashpay/dash/pull/5642/commits/1d500f88b6277303b08ea0a581511035ba24a015#diff-e771a3dd26d84715d137f42a9d77361684707ebb905310fc678ada1e47d6112fR59

This should reword the functional test to work while the credit pool is increasing in the background due to mn_rr; then remove the conditional check in validation for regtest special case.

This should be updated before RC.2.

**Comment by UdjinM6** [comment]
still not fixed https://github.com/dashpay/dash/blob/v20.1.0/src/evo/specialtxman.cpp#L60, moving to v21

**Comment by knst** [comment]
done. see #6269
