### ISSUE TITLE
GLIBC_2.28 dependency in precompiled dashd in dashcore-20.0.0-x86_64-linux-gnu.tar.gz

### ISSUE THREAD

**Issue by fairglu** [dashpay/dash#5706]
Precompiled release binary in dashcore-20.0.0-x86_64-linux-gnu.tar.gz has a dynamic dependency to GLIBC_2.28, which when that particular version is not available results in the following error:

> ./dashd: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./dashd)

Expected behavior would be the precompiled binaries to be a static build, with limited dependencies, or if a specific Linux distribution requirement was added for 20.0, I did not see it mentioned in the release notes ?

**Comment by PastaPastaPasta** [comment]
This is correct; a minimum glibc of 2.28 is required now. You can see here https://github.com/dashpay/dash/pull/5448 for more information. 

This does drop support for ubuntu 18.04; however ubuntu 18.04 reached end of life on May 31, 2023

This probably should've been mentioned in the release notes; sorry about that.
