### ISSUE TITLE
'masternode status' returns wrong pubKey

### ISSUE THREAD

**Issue by schinzelh** [dashpay/dash#580]
As per

https://dashtalk.org/threads/v12-release.5888/page-25#post-64168

>Hmm, mine is showing a wrong address too. I smell a bug

>./dash-cli masternode status
{
"vin" : "CTxIn(COutPoint(0000000000000000000000000000000000000000000000000000000000000000, 4294967295), coinbase )",
"pubKeyMasternode" : "XtdEd9b3yw2iEEfgjyQbwp82viVrXXXXXX",
"status" : "Not capable masternode: Could not find suitable coins!"
}

**Comment by UdjinM6** [comment]
That's an address that corresponds to masternodeprivkey. I'm not sure what that command was meant to do so in https://github.com/dashpay/dash/pull/562 https://github.com/UdjinM6/dash/commit/b59f603539e5e3555189d9b8b44ccbb5c4a6cdea#diff-a4cdb81b821da1ed5387826be192a2a2R434 it's replaced by pubkey hash (which at least appears in logs when mn signature is wrong so it could be kind of helpful for debuging). But then I'm not sure why we show it to user at all... maybe we should show actaul 1000 DASH address there..

**Comment by schinzelh** [comment]
Ups, redacted the OP to save the privkey :)

My expectation was to get the funding vin address here, at least this is my understanding of "pubKeyMasternode"

**Comment by UdjinM6** [comment]
Moved it out of #562 to #581 
Now it should work like you described.

**Comment by schinzelh** [comment]
Tested successfully in b1d28c9
