### ISSUE TITLE
Unable to send transactions with `onlynet=onion` flag

### ISSUE THREAD

**Issue by kxcd** [dashpay/dash#5844]
The node must be connected to TOR with the proxy flag and has the `onlynet=onion` qualifier set also.  The node is connected to peers and at the chain tip when compared to known good explorers.  The user attempts to send a TX, either normal send or CoinJoin, or protx, it doesn't matter and the TX never gets ISD, nor mined.  It claims to be broadcast and in mempool. The TX cannot be abandoned and using the resend option does not push it through.  The only way to get the TX to confirm, is to restart the wallet without connection to TOR.  Then the TX will go through as expected.  This behavior started in v20 and affects all v20.x releases.  It has been reported by numerous community members myself included.  Tested with windows wallet.

**Comment by UdjinM6** [comment]
I can't reproduce this on macos 🤷‍♂️

**Comment by knst** [comment]
@kxcd does it work with 20.1 ?

**Comment by kxcd** [comment]
Sorry, I've been checked out.  I need to test this again with latest version of wallet and having made ONE other change the `dash.conf` file, you see previously I was setting the proxy as so `proxy=127.0.0.1:9050`, however, after talking to @PastaPastaPasta I learned this will try to send everything via the proxy, which is not correct for TOR, so now I am setting instead `onion=127.0.0.1:9050` and will report back if that solves the issue for me.

**Comment by kxcd** [comment]
OK, after testing using the onion param rather than the proxy param, the issue is not happening and the node is properly connected to TOR.
