### ISSUE TITLE
(Minor UI bug - Windows 10) Window width resizes after closing Settings>Options modal via "Close"/"OK"/"X" buttons

### ISSUE THREAD

**Issue by jmmon** [dashpay/dash#5886]
**Expected behavior**
Expected window width to NOT CHANGE when I close the Options modal

**Actual behavior**
When closing the settings window (even if no settings are changed, even if cancelling or clicking the X; did NOT test "Reset Options" button to see if it leads to the same effect.)
- Changing settings while modal is open as no effect on this bug

**To reproduce**
1. On Dash 20.0.4, change the window dimensions. 
2. Then open Options modal. 
3. Then close Options modal.

**System information**

Dash 20.0.4, from dash.org/downloads

Windows 10,
 i7-8th gen, 
 SSD M.2

Windows 10 Home os build: 19045.4046

I want to say this bug appeared somewhat recently, in latest or or one of the latest versions. Low priority.

**Comment by knst** [comment]
@jmmon,

I can't reproduce mentioned behaviour on my machine. can you provide your `dash.conf` please? Don't forget to remove rpcpassword from `dash.conf` if you have any.

What is your screen resolution and font scale if you do use any?

**Comment by jmmon** [comment]
So looks like my `dash.conf` is empty?? (`user/appdata/roaming/dashcore/dash.conf`)

To reiterate with more info, when I resize the dash window and then open & close SettingsModal, ONLY the WIDTH will reset back to original width, but the height does NOT reset.

**Some more tests:**
- I just tested and I am indeed still seeing this bug without any external monitors on my laptop. My laptop is 3000x2000 and scaled at 150%.
- My external is 3440x1440 scaled at 100%, it is my primary monitor. Disabling the laptop and using ONLY this monitor, and even closing and re-opening dashcore: still prone to this bug.
- I have my taskbar on the left side. Just in case, I moved it to the bottom, then just to be safe closed and reopened dashcore, then tried the test. Still is resetting the width of the window.

What other info can I get you?

**Comment by knst** [comment]
> To reiterate with more info, when I resize the dash window and then open & close SettingsModal, ONLY the WIDTH will reset back to original width, but the height does NOT reset.

that's strange, I guess it happens due to some certain minimal width that is supposed to be for Main window and which is reset after opening Settings window (even if no settings changed).  hm...

**Comment by jmmon** [comment]
I can't recall when it started occurring either. I feel like it is relatively recent (as in last few releases?). I know there were some UI changes in the last number of months, right? So maybe the bug crept in during that time.

Anyway, not a huge deal but it is annoying. So if it's easy to find/fix, hope it can be fixed in the next release!

**Comment by vampyren** [comment]
I have the issue on win11! 

I can confirm its just the width that resets, height stays at correct size! 
Simple to reproduce really.

**Comment by PastaPastaPasta** [comment]
This is probably a windows specific bug. @kwvg please investigate this and try to identify why :)
