### ISSUE TITLE
Inputs per denomination in GUI not honoured

### ISSUE THREAD

**Issue by p-m** [dashpay/dash#5975]
Hi,

When setting non default values for denoms_goal and denoms_hardcap in GUI, dash-qt still uses default values.

Steps to reproduce:
1.) Fresh installation of dashcore-20.1.1-x86_64-linux-gnu.tar.gz (no configuration files)
2.) Start dash-qt
3.) Set "Inputs per denomination" to Target = 10, Maximum = 16
4.) Check used values in console with getcoinjoininfo: 10/16, this is ok.
5.) Restart dash-qt
6.) Check values in GUI: 10/16, this is ok
7.) Check used values in console with getcoinjoininfo: 50/300, this is NOT ok.

Workaround: Set values in ~/.dashcore/dash.conf.

Cheers, Peter

**Comment by kxcd** [comment]
More than one user reporting this issue.  Can a dev have a look into it and see if you can reproduce and maybe suggest a fix?

**Comment by PastaPastaPasta** [comment]
> More than one user reporting this issue.

Can you cite the others?

**Comment by PastaPastaPasta** [comment]
Resolved in https://github.com/dashpay/dash/pull/6208; will be released in v22 / v21.2 / v21.1.1 whichever comes first :)
