### ISSUE TITLE
RPC Trouble?

### ISSUE THREAD

**Issue by scratchy** [dashpay/dash#617]
Hey,

Got trouble with RPC:

Heres the json what im posting (working):

{"jsonrpc":"1.0","method":"getbalance","params":["payment"]}

but if im posting this:

{"jsonrpc":"1.0","method":"getbalance","params":["payment","30"]}

it doesnt work:

Server returned HTTP response code: 500 for URL: http://127.0.0.1:9998

Any idears whats up there?

**Comment by UdjinM6** [comment]
```
curl --user darkcoind --data-binary '{"jsonrpc":"1.0","method":"getbalance","params":["payment","30"]}' -H 'content-type: text/plain;' http://127.0.0.1:9998/
Enter host password for user 'darkcoind':
{"result":null,"error":{"code":-1,"message":"value is type str, expected int"},"id":null}
```
Try sending second parameter as `int` and it should work
```
curl --user darkcoind --data-binary '{"jsonrpc":"1.0","method":"getbalance","params":["payment",30]}' -H 'content-type: text/plain;' http://127.0.0.1:9998/
Enter host password for user 'darkcoind':
{"result":0.00000000,"error":null,"id":null}
```

**Comment by scratchy** [comment]
Thank You!

Probem solved ~

**Comment by wuhuaping** [comment]
oot@iZ2zeeeup1v8x4tt6rzmr6Z:/var/www/html/mpos/cronjobs# ./findblock.php -f
PHP Fatal error: Uncaught Exception: RPC call did not return 200: HTTP error: 500 - JSON Response: [-8] Invalid blockhash in /var/www/html/mpos/include/lib/jsonRPCClient.php:120
Stack trace:
#0 /var/www/html/mpos/cronjobs/findblock.php(35): jsonRPCClient->__call('listsinceblock', Array)
#1 {main}
thrown in /var/www/html/mpos/include/lib/jsonRPCClient.php on line 120

root@iZ2zeeeup1v8x4tt6rzmr6Z:~# dash-cli getblockhash
error code: -1
error message:
getblockhash index

Returns hash of block in best-block-chain at index provided.

Arguments:

index (numeric, required) The block index
Result:
"hash" (string) The block hash

Examples:

dash-cli getblockhash 1000
curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getblockhash", "params": [1000] }' -H 'content-type: text/plain;' http://127.0.0.1:9998/
I used the old version of the wallet link, not wrong
But the new version of the wallet link is wrong
