### ISSUE TITLE
chainparams break on centos via pkgsrc.se

### ISSUE THREAD

**Issue by djadk84** [dashpay/dash#633]
Im currently trying to get dashcoin v0.12.0.55 to work on centos using pkgsrc.se from netbsd but it is breaking at the build fase. you can see the log output of de build process.
# cat /etc/redhat-release

CentOS Linux release 7.1.1503 (Core)
# gcc --version

gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# pkg_info -a|grep boos

boost-jam-1.58.0    Free, peer-reviewed portable C++ source libraries (Boost.Jam utility)
boost-headers-1.58.0 Free, peer-reviewed portable C++ source libraries (build-time headers)
boost-libs-1.58.0   Free, peer-reviewed portable C++ source libraries (binary libraries)

\ curl\ cut\ date\ diff\ digest\ dirname\ echo\ egrep\ env\ expr\ false\ find\ gmake\ grep\ gzcat\ head\ hostname\ id\ install\ libtoolize\ ln\ ls\ mkdir\ mv\ patch\ pkg-config\ printf\ pwd\ readelf\ rm\ rmdir\ sed\ sh\ sort\ tail\ tar\ test\ touch\ tr\ true\ uname\ wc\ xargs >> /usr/pkgsrc/wip/darkcoin/work/.build_makevars.mk.tmp
set -e;                  echo _WRAP_PATH"=  "/usr/pkgsrc/wip/darkcoin/work/.buildlink/bin:/usr/pkgsrc/wip/darkcoin/work/.gcc/bin:/usr/pkgsrc/wip/darkcoin/work/.tools/bin:/usr/pkg/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/pkg/sbin:/usr/pkg/bin:/root/bin >> /usr/pkgsrc/wip/darkcoin/work/.build_makevars.mk.tmp
set -e;                  if test -f /usr/pkgsrc/wip/darkcoin/work/.build_makevars.mk.tmp; then               ( echo ".if !defined(_MAKEVARS_MK)";            echo "_MAKEVARS_MK=    defined";        echo "";                        /bin/cat /usr/pkgsrc/wip/darkcoin/work/.build_makevars.mk.tmp;              echo "";                        echo ".endif # _MAKEVARS_MK"; ) > /usr/pkgsrc/wip/darkcoin/work/.build_makevars.mk;                         /bin/rm -f /usr/pkgsrc/wip/darkcoin/work/.build_makevars.mk.tmp;                fi
set -e;/bin/touch -f /usr/pkgsrc/wip/darkcoin/work/.build_makevars.mk
set -e;                      cd /usr/pkgsrc/wip/darkcoin/work/dash-0.12.0.55 && cd /usr/pkgsrc/wip/darkcoin/work/dash-0.12.0.55 &&       /usr/bin/env USETOOLS=no PTHREAD_CFLAGS=\ -pthread\  PTHREAD_LDFLAGS=\ -pthread PTHREAD_LIBS=-lpthread\ -lrt PTHREADBASE=/usr QTDIR=/usr/pkg/qt4 MOC="/usr/pkg/qt4/bin/moc" UIC="/usr/pkg/qt4/bin/uic" QMAKE="/usr/pkg/qt4/bin/qmake" QMAKESPEC=/usr/pkg/qt4/mkspecs/netbsd-g++ DL_CFLAGS= DL_LDFLAGS= DL_LIBS= CC=gcc CFLAGS=-O2\ -fPIC\ -march=native\ -mfpmath=sse\ -msse3\ -I/usr/pkg/include\ -I/usr/pkg/include/db4\ -I/usr/include\ -I/usr/pkg/qt4/include\ -I/usr/pkg/include/freetype2\ -I/usr/pkg/include/libdrm CPPFLAGS=-I/usr/pkg/include\ -I/usr/pkg/include/db4\ -I/usr/include\ -I/usr/pkg/qt4/include\ -I/usr/pkg/include/freetype2\ -I/usr/pkg/include/libdrm CXX=g++ CXXFLAGS=-O2\ -fPIC\ -march=native\ -mfpmath=sse\ -msse3\ -I/usr/pkg/include\ -I/usr/pkg/include/db4\ -I/usr/include\ -I/usr/pkg/qt4/include\ -I/usr/pkg/include/freetype2\ -I/usr/pkg/include/libdrm\ -std=c++0x\ -Wl,-R/usr/pkg/lib/darkcoin\ -L/usr/pkg/lib/darkcoin\ -I/usr/pkg/include/boost COMPILER_RPATH_FLAG=-Wl,-R F77=f77 FC=f77 FFLAGS=-O LANG=C LC_ALL=C LC_COLLATE=C LC_CTYPE=C LC_MESSAGES=C LC_MONETARY=C LC_NUMERIC=C LC_TIME=C LDFLAGS=-L/usr/pkg/lib\ -Wl,-R/usr/pkg/lib\ -L/usr/lib64\ -Wl,-R/usr/lib64\ -L/usr/pkg/qt4/lib\ -Wl,-R/usr/pkg/qt4/lib LINKER_RPATH_FLAG=-R PATH=/usr/pkgsrc/wip/darkcoin/work/.wrapper/bin:/usr/pkgsrc/wip/darkcoin/work/.buildlink/bin:/usr/pkgsrc/wip/darkcoin/work/.gcc/bin:/usr/pkgsrc/wip/darkcoin/work/.tools/bin:/usr/pkg/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/pkg/sbin:/usr/pkg/bin:/root/bin:/usr/pkg/bin:/usr/pkg/bin PREFIX=/usr/pkg MAKELEVEL=0 PKG_SYSCONFDIR=/usr/pkg/etc HOME=/usr/pkgsrc/wip/darkcoin/work/.home CPP=cpp LINK_ALL_LIBGCC_HACK= LOCALBASE=/usr/pkg NO_WHOLE_ARCHIVE_FLAG=-Wl,--no-whole-archive WHOLE_ARCHIVE_FLAG=-Wl,--whole-archive X11BASE=/usr/pkg X11PREFIX=/usr/pkg PKGMANDIR=man PKGINFODIR=info PKGGNUDIR=gnu/ MAKECONF=/dev/null OBJECT_FMT=ELF USETOOLS=no LIBTOOL="libtool " BSD_INSTALL_PROGRAM=/bin/install\ -c\ -s\ -o\ root\ -g\ root\ -m\ 755 BSD_INSTALL_SCRIPT=/bin/install\ -c\ -o\ root\ -g\ root\ -m\ 755 BSD_INSTALL_LIB=/bin/install\ -c\ -o\ root\ -g\ root\ -m\ 755 BSD_INSTALL_DATA=/bin/install\ -c\ -o\ root\ -g\ root\ -m\ 644 BSD_INSTALL_MAN=/bin/install\ -c\ -o\ root\ -g\ root\ -m\ 644 BSD_INSTALL=/bin/install BSD_INSTALL_PROGRAM_DIR=/bin/install\ -d\ -o\ root\ -g\ root\ -m\ 755 BSD_INSTALL_SCRIPT_DIR=/bin/install\ -d\ -o\ root\ -g\ root\ -m\ 755 BSD_INSTALL_LIB_DIR=/bin/install\ -d\ -o\ root\ -g\ root\ -m\ 755 BSD_INSTALL_DATA_DIR=/bin/install\ -d\ -o\ root\ -g\ root\ -m\ 755 BSD_INSTALL_MAN_DIR=/bin/install\ -d\ -o\ root\ -g\ root\ -m\ 755 BSD_INSTALL_GAME=/bin/install\ -c\ -s\ -o\ root\ -g\ root\ -m\ 2555 BSD_INSTALL_GAME_DATA=/bin/install\ -c\ -o\ root\ -g\ root\ -m\ 664 BSD_INSTALL_GAME_DIR=/bin/install\ -d\ -o\ root\ -g\ root\ -m\ 775 INSTALL_INFO= MAKEINFO=/usr/pkgsrc/wip/darkcoin/work/.tools/bin/makeinfo FLEX= BISON= PKG_CONFIG=/usr/pkgsrc/wip/darkcoin/work/.tools/bin/pkg-config PKG_CONFIG_LIBDIR=/usr/pkgsrc/wip/darkcoin/work/.buildlink/lib64/pkgconfig:/usr/pkgsrc/wip/darkcoin/work/.buildlink/lib/pkgconfig:/usr/pkgsrc/wip/darkcoin/work/.buildlink/share/pkgconfig PKG_CONFIG_LOG=/usr/pkgsrc/wip/darkcoin/work/.pkg-config.log PKG_CONFIG_PATH= WRAPPER_DEBUG=no WRAPPER_UPDATE_CACHE=yes WRAPPER_REORDER=yes                     /usr/bin/make -j8               -f Makefile all
Making all in src
make[1]: Entering directory `/usr/pkgsrc/wip/darkcoin/work/dash-0.12.0.55/src'
make[2]: Entering directory`/usr/pkgsrc/wip/darkcoin/work/dash-0.12.0.55/src'
  CXX      libbitcoinconsensus_la-allocators.lo
  CXX      libbitcoinconsensus_la-eccryptoverify.lo
  CXX      libbitcoinconsensus_la-ecwrapper.lo
  CXX      libbitcoinconsensus_la-hash.lo
  CXX      libbitcoinconsensus_la-pubkey.lo
  CXX      libbitcoinconsensus_la-uint256.lo
  CXX      libbitcoinconsensus_la-utilstrencodings.lo
  CXX      dashd-dashd.o
  CXX      libbitcoin_server_a-addrman.o
  CXX      libbitcoin_server_a-alert.o
  CXX      libbitcoin_server_a-bloom.o
  CXX      libbitcoin_server_a-chain.o
  CXX      libbitcoin_server_a-checkpoints.o
  CXX      libbitcoin_server_a-init.o
  CXX      libbitcoin_server_a-leveldbwrapper.o
  CXX      libbitcoin_server_a-main.o
  CXX      libbitcoin_server_a-merkleblock.o
  CXX      libbitcoin_server_a-miner.o
  CXX      libbitcoin_server_a-net.o
  CXX      libbitcoin_server_a-noui.o
  CXX      libbitcoin_server_a-pow.o
  CXX      libbitcoin_server_a-rest.o
miner.cpp: In function 'void BitcoinMiner(CWallet_)':
miner.cpp:490:53: warning: 'auto_ptr' is deprecated (declared at /usr/include/c++/4.8.2/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
             auto_ptr<CBlockTemplate> pblocktemplate(CreateNewBlockWithKey(reservekey));
                                                     ^
  CXX      libbitcoin_server_a-rpcblockchain.o
  CXX      libbitcoin_server_a-rpcmasternode.o
  CXX      libbitcoin_server_a-rpcmasternode-budget.o
  CXX      libbitcoin_server_a-rpcmining.o
  CXX      libbitcoin_server_a-rpcmisc.o
  CXX      libbitcoin_server_a-rpcnet.o
  CXX      libbitcoin_server_a-rpcrawtransaction.o
  CXX      libbitcoin_server_a-rpcserver.o
  CXX      script/libbitcoin_server_a-sigcache.o
  CXX      libbitcoin_server_a-timedata.o
  CXX      libbitcoin_server_a-txdb.o
  CXX      libbitcoin_server_a-txmempool.o
  CXX      libbitcoin_common_a-allocators.o
  CXX      libbitcoin_common_a-amount.o
  CXX      libbitcoin_common_a-base58.o
  CXX      libbitcoin_common_a-chainparams.o
  CXX      libbitcoin_common_a-coins.o
chainparams.cpp: In constructor 'CMainParams::CMainParams()':
chainparams.cpp:168:40: error: ambiguous overload for 'operator=' (operand types are 'std::vector<unsigned char>' and 'boost::assign_detail::generic_list<int>')
         base58Prefixes[PUBKEY_ADDRESS] = list_of( 76);                    // Dash addresses start with 'X'
                                        ^
chainparams.cpp:168:40: note: candidates are:
In file included from /usr/include/c++/4.8.2/vector:69:0,
                 from chainparamsbase.h:9,
                 from chainparams.h:9,
                 from chainparams.cpp:7:
/usr/include/c++/4.8.2/bits/vector.tcc:160:5: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
     vector<_Tp, _Alloc>::
     ^
In file included from /usr/include/c++/4.8.2/vector:64:0,
                 from chainparamsbase.h:9,
                 from chainparams.h:9,
                 from chainparams.cpp:7:
/usr/include/c++/4.8.2/bits/stl_vector.h:439:7: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::vector<_Tp, _Alloc>&&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
       operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
       ^
/usr/include/c++/4.8.2/bits/stl_vector.h:461:7: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::initializer_list<_Tp>) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
       operator=(initializer_list<value_type> __l)
       ^
chainparams.cpp:169:40: error: ambiguous overload for 'operator=' (operand types are 'std::vector<unsigned char>' and 'boost::assign_detail::generic_list<int>')
         base58Prefixes[SCRIPT_ADDRESS] = list_of( 16);                    // Dash script addresses start with '7'
                                        ^
chainparams.cpp:169:40: note: candidates are:
In file included from /usr/include/c++/4.8.2/vector:69:0,
                 from chainparamsbase.h:9,
                 from chainparams.h:9,
                 from chainparams.cpp:7:
/usr/include/c++/4.8.2/bits/vector.tcc:160:5: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
     vector<_Tp, _Alloc>::
     ^
In file included from /usr/include/c++/4.8.2/vector:64:0,
                 from chainparamsbase.h:9,
                 from chainparams.h:9,
                 from chainparams.cpp:7:
/usr/include/c++/4.8.2/bits/stl_vector.h:439:7: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::vector<_Tp, _Alloc>&&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
       operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
       ^
/usr/include/c++/4.8.2/bits/stl_vector.h:461:7: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::initializer_list<_Tp>) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
       operator=(initializer_list<value_type> __l)
       ^
chainparams.cpp:170:36: error: ambiguous overload for 'operator=' (operand types are 'std::vector<unsigned char>' and 'boost::assign_detail::generic_list<int>')
         base58Prefixes[SECRET_KEY] =     list_of(204);                    // Dash private keys start with '7' or 'X'
                                    ^
chainparams.cpp:170:36: note: candidates are:
In file included from /usr/include/c++/4.8.2/vector:69:0,
                 from chainparamsbase.h:9,
                 from chainparams.h:9,
                 from chainparams.cpp:7:
/usr/include/c++/4.8.2/bits/vector.tcc:160:5: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
     vector<_Tp, _Alloc>::
     ^
In file included from /usr/include/c++/4.8.2/vector:64:0,
                 from chainparamsbase.h:9,
                 from chainparams.h:9,
                 from chainparams.cpp:7:
/usr/include/c++/4.8.2/bits/stl_vector.h:439:7: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::vector<_Tp, _Alloc>&&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
       operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
       ^
/usr/include/c++/4.8.2/bits/stl_vector.h:461:7: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::initializer_list<_Tp>) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
       operator=(initializer_list<value_type> __l)
       ^
chainparams.cpp:171:40: error: ambiguous overload for 'operator=' (operand types are 'std::vector<unsigned char>' and 'boost::assign_detail::generic_list<int>')
         base58Prefixes[EXT_PUBLIC_KEY] = list_of(0x02)(0xFE)(0x52)(0xF8); // Dash BIP32 pubkeys start with 'drkv'
                                        ^
chainparams.cpp:171:40: note: candidates are:
In file included from /usr/include/c++/4.8.2/vector:69:0,
                 from chainparamsbase.h:9,
                 from chainparams.h:9,
                 from chainparams.cpp:7:
/usr/include/c++/4.8.2/bits/vector.tcc:160:5: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
     vector<_Tp, _Alloc>::
     ^
In file included from /usr/include/c++/4.8.2/vector:64:0,
                 from chainparamsbase.h:9,
                 from chainparams.h:9,
                 from chainparams.cpp:7:
/usr/include/c++/4.8.2/bits/stl_vector.h:439:7: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::vector<_Tp, _Alloc>&&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
       operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
       ^
/usr/include/c++/4.8.2/bits/stl_vector.h:461:7: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::initializer_list<_Tp>) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
       operator=(initializer_list<value_type> __l)
       ^
chainparams.cpp:172:40: error: ambiguous overload for 'operator=' (operand types are 'std::vector<unsigned char>' and 'boost::assign_detail::generic_list<int>')
         base58Prefixes[EXT_SECRET_KEY] = list_of(0x02)(0xFE)(0x52)(0xCC); // Dash BIP32 prvkeys start with 'drkp'
                                        ^
chainparams.cpp:172:40: note: candidates are:
In file included from /usr/include/c++/4.8.2/vector:69:0,
                 from chainparamsbase.h:9,
                 from chainparams.h:9,
                 from chainparams.cpp:7:
/usr/include/c++/4.8.2/bits/vector.tcc:160:5: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
     vector<_Tp, _Alloc>::
     ^
In file included from /usr/include/c++/4.8.2/vector:64:0,
                 from chainparamsbase.h:9,
                 from chainparams.h:9,
                 from chainparams.cpp:7:
/usr/include/c++/4.8.2/bits/stl_vector.h:439:7: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::vector<_Tp, _Alloc>&&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
       operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
       ^
/usr/include/c++/4.8.2/bits/stl_vector.h:461:7: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::initializer_list<_Tp>) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
       operator=(initializer_list<value_type> __l)
       ^
chainparams.cpp:173:40: error: ambiguous overload for 'operator=' (operand types are 'std::vector<unsigned char>' and 'boost::assign_detail::generic_list<unsigned int>')
         base58Prefixes[EXT_COIN_TYPE]  = list_of(0x80000005);             // Dash BIP44 coin type is '5'
                                        ^
chainparams.cpp:173:40: note: candidates are:
In file included from /usr/include/c++/4.8.2/vector:69:0,
                 from chainparamsbase.h:9,
                 from chainparams.h:9,
                 from chainparams.cpp:7:
/usr/include/c++/4.8.2/bits/vector.tcc:160:5: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
     vector<_Tp, _Alloc>::
     ^
In file included from /usr/include/c++/4.8.2/vector:64:0,
                 from chainparamsbase.h:9,
                 from chainparams.h:9,
                 from chainparams.cpp:7:
/usr/include/c++/4.8.2/bits/stl_vector.h:439:7: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::vector<_Tp, _Alloc>&&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
       operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
       ^
/usr/include/c++/4.8.2/bits/stl_vector.h:461:7: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::initializer_list<_Tp>) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
       operator=(initializer_list<value_type> __l)
       ^
chainparams.cpp: In constructor 'CTestNetParams::CTestNetParams()':
chainparams.cpp:237:40: error: ambiguous overload for 'operator=' (operand types are 'std::vector<unsigned char>' and 'boost::assign_detail::generic_list<int>')
         base58Prefixes[PUBKEY_ADDRESS] = list_of(139);                    // Testnet dash addresses start with 'x' or 'y'
                                        ^
chainparams.cpp:237:40: note: candidates are:
In file included from /usr/include/c++/4.8.2/vector:69:0,
                 from chainparamsbase.h:9,
                 from chainparams.h:9,
                 from chainparams.cpp:7:
/usr/include/c++/4.8.2/bits/vector.tcc:160:5: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
     vector<_Tp, _Alloc>::
     ^
In file included from /usr/include/c++/4.8.2/vector:64:0,
                 from chainparamsbase.h:9,
                 from chainparams.h:9,
                 from chainparams.cpp:7:
/usr/include/c++/4.8.2/bits/stl_vector.h:439:7: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::vector<_Tp, _Alloc>&&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
       operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
       ^
/usr/include/c++/4.8.2/bits/stl_vector.h:461:7: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::initializer_list<_Tp>) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
       operator=(initializer_list<value_type> __l)
       ^
chainparams.cpp:238:40: error: ambiguous overload for 'operator=' (operand types are 'std::vector<unsigned char>' and 'boost::assign_detail::generic_list<int>')
         base58Prefixes[SCRIPT_ADDRESS] = list_of( 19);                    // Testnet dash script addresses start with '8' or '9'
                                        ^
chainparams.cpp:238:40: note: candidates are:
In file included from /usr/include/c++/4.8.2/vector:69:0,
                 from chainparamsbase.h:9,
                 from chainparams.h:9,
                 from chainparams.cpp:7:
/usr/include/c++/4.8.2/bits/vector.tcc:160:5: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
     vector<_Tp, _Alloc>::
     ^
In file included from /usr/include/c++/4.8.2/vector:64:0,
                 from chainparamsbase.h:9,
                 from chainparams.h:9,
                 from chainparams.cpp:7:
/usr/include/c++/4.8.2/bits/stl_vector.h:439:7: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::vector<_Tp, _Alloc>&&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
       operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
       ^
/usr/include/c++/4.8.2/bits/stl_vector.h:461:7: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::initializer_list<_Tp>) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
       operator=(initializer_list<value_type> __l)
       ^
chainparams.cpp:239:40: error: ambiguous overload for 'operator=' (operand types are 'std::vector<unsigned char>' and 'boost::assign_detail::generic_list<int>')
         base58Prefixes[SECRET_KEY]     = list_of(239);                    // Testnet private keys start with '9' or 'c' (Bitcoin defaults)
                                        ^
chainparams.cpp:239:40: note: candidates are:
In file included from /usr/include/c++/4.8.2/vector:69:0,
                 from chainparamsbase.h:9,
                 from chainparams.h:9,
                 from chainparams.cpp:7:
/usr/include/c++/4.8.2/bits/vector.tcc:160:5: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
     vector<_Tp, _Alloc>::
     ^
In file included from /usr/include/c++/4.8.2/vector:64:0,
                 from chainparamsbase.h:9,
                 from chainparams.h:9,
                 from chainparams.cpp:7:
/usr/include/c++/4.8.2/bits/stl_vector.h:439:7: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::vector<_Tp, _Alloc>&&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
       operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
       ^
/usr/include/c++/4.8.2/bits/stl_vector.h:461:7: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::initializer_list<_Tp>) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
       operator=(initializer_list<value_type> __l)
       ^
chainparams.cpp:240:40: error: ambiguous overload for 'operator=' (operand types are 'std::vector<unsigned char>' and 'boost::assign_detail::generic_list<int>')
         base58Prefixes[EXT_PUBLIC_KEY] = list_of(0x3a)(0x80)(0x61)(0xa0); // Testnet dash BIP32 pubkeys start with 'DRKV'
                                        ^
chainparams.cpp:240:40: note: candidates are:
In file included from /usr/include/c++/4.8.2/vector:69:0,
                 from chainparamsbase.h:9,
                 from chainparams.h:9,
                 from chainparams.cpp:7:
/usr/include/c++/4.8.2/bits/vector.tcc:160:5: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
     vector<_Tp, _Alloc>::
     ^
In file included from /usr/include/c++/4.8.2/vector:64:0,
                 from chainparamsbase.h:9,
                 from chainparams.h:9,
                 from chainparams.cpp:7:
/usr/include/c++/4.8.2/bits/stl_vector.h:439:7: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::vector<_Tp, _Alloc>&&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
       operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
       ^
/usr/include/c++/4.8.2/bits/stl_vector.h:461:7: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::initializer_list<_Tp>) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
       operator=(initializer_list<value_type> __l)
       ^
chainparams.cpp:241:40: error: ambiguous overload for 'operator=' (operand types are 'std::vector<unsigned char>' and 'boost::assign_detail::generic_list<int>')
         base58Prefixes[EXT_SECRET_KEY] = list_of(0x3a)(0x80)(0x58)(0x37); // Testnet dash BIP32 prvkeys start with 'DRKP'
                                        ^
chainparams.cpp:241:40: note: candidates are:
In file included from /usr/include/c++/4.8.2/vector:69:0,
                 from chainparamsbase.h:9,
                 from chainparams.h:9,
                 from chainparams.cpp:7:
/usr/include/c++/4.8.2/bits/vector.tcc:160:5: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
     vector<_Tp, _Alloc>::
     ^
In file included from /usr/include/c++/4.8.2/vector:64:0,
                 from chainparamsbase.h:9,
                 from chainparams.h:9,
                 from chainparams.cpp:7:
/usr/include/c++/4.8.2/bits/stl_vector.h:439:7: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::vector<_Tp, _Alloc>&&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
       operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
       ^
/usr/include/c++/4.8.2/bits/stl_vector.h:461:7: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::initializer_list<_Tp>) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
       operator=(initializer_list<value_type> __l)
       ^
chainparams.cpp:242:40: error: ambiguous overload for 'operator=' (operand types are 'std::vector<unsigned char>' and 'boost::assign_detail::generic_list<unsigned int>')
         base58Prefixes[EXT_COIN_TYPE]  = list_of(0x80000001);             // Testnet dash BIP44 coin type is '5' (All coin's testnet default)
                                        ^
chainparams.cpp:242:40: note: candidates are:
In file included from /usr/include/c++/4.8.2/vector:69:0,
                 from chainparamsbase.h:9,
                 from chainparams.h:9,
                 from chainparams.cpp:7:
/usr/include/c++/4.8.2/bits/vector.tcc:160:5: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
     vector<_Tp, _Alloc>::
     ^
In file included from /usr/include/c++/4.8.2/vector:64:0,
                 from chainparamsbase.h:9,
                 from chainparams.h:9,
                 from chainparams.cpp:7:
/usr/include/c++/4.8.2/bits/stl_vector.h:439:7: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::vector<_Tp, _Alloc>&&) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
       operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
       ^
/usr/include/c++/4.8.2/bits/stl_vector.h:461:7: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::initializer_list<_Tp>) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]
       operator=(initializer_list<value_type> __l)
       ^
make[2]: *_\* [libbitcoin_common_a-chainparams.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
make[2]: Leaving directory `/usr/pkgsrc/wip/darkcoin/work/dash-0.12.0.55/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/usr/pkgsrc/wip/darkcoin/work/dash-0.12.0.55/src'
make: **\* [all-recursive] Error 1
**\* Error code 2

Stop.
bmake[1]: stopped in /usr/pkgsrc/wip/darkcoin
set -e;                  /bin/rm -f /usr/pkgsrc/wip/darkcoin/work/.warning/_.tmp;                    test -d /usr/pkgsrc/wip/darkcoin/work/.warning || exit 0;               cd /usr/pkgsrc/wip/darkcoin/work/.warning;                      for file in ./_; do                         test "$file" != "./_" || exit 0;            break;                      done;                               /bin/cat ./_ | /bin/sed -e "s|^|WARNING: |" 1>&2;                   /bin/mv -f ./\* /usr/pkgsrc/wip/darkcoin/work/.warning-done
set -e;                  /bin/rm -f /usr/pkgsrc/wip/darkcoin/work/.error/_.tmp;                  test -d /usr/pkgsrc/wip/darkcoin/work/.error || exit 0;                 cd /usr/pkgsrc/wip/darkcoin/work/.error;                        for file in ./_; do                         test "$file" != "./_" || exit 0;            break;                          done;                               /bin/cat \* | /bin/sed -e "s|^|ERROR: |" 1>&2;                   if /bin/awk 'END { exit (NR > 0) ? 0 : 1; }' ./_; then              /bin/mv -f ./\* /usr/pkgsrc/wip/darkcoin/work/.error-done;           exit 1;                             fi
**\* Error code 1

Stop.

**Comment by djadk84** [comment]
This was the fixed that bitcoin applied https://github.com/bitcoin/bitcoin/commit/a2b04ddfe6452e7d6274f4096bf3f2aee695a6d9

**Comment by schinzelh** [comment]
Should be fixed in the current version
