### ISSUE TITLE
Internal bug detected: 'MoneyRange(fee)'

### ISSUE THREAD

**Issue by bit0t** [dashpay/dash#6335]
My nodes started throwing errors, what's going on?

**Error message:**
      core_write.cpp:338 (TxToUniv)
      Internal bug detected: 'MoneyRange(fee)'
      You may report this issue here: https://github.com/dashpay/dash/issues

**Comment by jprudent** [comment]
same problem here

**Comment by knst** [comment]
> Is it supposed to be fixed by https://github.com/dashpay/dash/commit/b7d543061d6d33ee745b55aa566488e0aa869455 ?
It is an other issue.

I think we will have patch version 21.1.1 to avoid big release with any breaking changes in RPC, see #6336

**Comment by geastman3** [comment]
> > Is it supposed to be fixed by [b7d5430](https://github.com/dashpay/dash/commit/b7d543061d6d33ee745b55aa566488e0aa869455) ?
> > It is an other issue.
> 
> I think we will have patch version 21.1.1 to avoid big release with any breaking changes in RPC, see #6336

When? We had to do a emergency bypass to allow this code to be implemented when all of our nodes went down. We would like to get back to compliance.

**Comment by knst** [comment]
> > > Is it supposed to be fixed by [b7d5430](https://github.com/dashpay/dash/commit/b7d543061d6d33ee745b55aa566488e0aa869455) ?
> > > It is an other issue.
> > 
> > 
> > I think we will have patch version 21.1.1 to avoid big release with any breaking changes in RPC, see #6336
> 
> When? We had to do a emergency bypass to allow this code to be implemented when all of our nodes went down. We would like to get back to compliance.



Just now:
https://github.com/dashpay/dash/releases/tag/v21.1.1
