### ISSUE TITLE
[BUG] x86_64 Linux binaries v21.1.1 still show as v21.1.0 in terminal and in debug.log

### ISSUE THREAD

**Issue by qwizzie** [dashpay/dash#6342]
VirtualBox, Ubuntu 24.04 LTS, Windows 10 Pro machine.
dashcore-21.1.1-x86_64-linux-gnu.tar.gz binaries 
downloaded from : https://github.com/dashpay/dash/releases/tag/v21.1.1

![Knipsel](https://github.com/user-attachments/assets/de6b2818-df64-4990-af98-98594502b73b)

Maybe incorrectly packed ? please verify.

**Comment by knst** [comment]
I just downloaded files by link and tested:
```
$ grep 21.1.0 dashd
<nothing>
$ grep 21.1.1 dashd
grep: dashd: binary file matches
$ sha256sum dashd
802832379a5eca5312e58a89d633ea347ac7d3a04f4a7b64953df0bd3245b297  dashd
```

I believe you may still run old version @qwizzie

**Comment by qwizzie** [comment]
![euv6Kjz](https://github.com/user-attachments/assets/47b70a00-c043-46e6-bef3-f42b4a1e52e1)

**Comment by knst** [comment]
@qwizzie,
I believe, you run `dashd` from your PATH directly where it is installed.
Can you call `which dashd` and `sha256sum` for that full path?

Also, call `./dashd` if you want to enforce call from the _current directory_ instead of your PATH
