### ISSUE TITLE
FreeBSD compilation fails with ./configure: [[: not found

### ISSUE THREAD

**Issue by jTd7bPLFb** [dashpay/dash#6343]
Before, I could compile dash core (dashd, dash-cli) without issues on FreeBSD.
After latest git pull, it's not possible anymore.
fails with 
./configure: [[: not found

to compile as before

git clone https://github.com/dashpay/dash

export CXXFLAGS="-I/usr/local/include -pthread"
export CPPFLAGS="-I/usr/local/include -pthread"
export LDFLAGS="-L/usr/local/lib"

./configure --without-miniupnpc --enable-wallet --without-bdb \
--with-gui=no --disable-tests --disable-bench MAKE=gmake
gmake -j`nproc`

**System information**
FreeBSD 14.1
x86

**Comment by sergDash** [comment]
try this:

git checkout v21.1.1
cp src/dashbls/configure.ac ../
git checkout v22.0.0-rc.2
cp ../configure.ac src/dashbls/configure.ac

**Comment by jTd7bPLFb** [comment]
Yes, this made the compilation possible.

**Comment by sergDash** [comment]
I'm not a developer, but an ordinary fanatic :)

**Comment by jTd7bPLFb** [comment]
thanks.
devs don't seem to care though ..;-< ¯\_(ツ)_/¯ 
once again, thank you for the workaround, I can not run my mns in native freebsd jails instead of linuxulator jails.
