### ISSUE TITLE
Build issue with latest miniupnpc (Arch Linux)

### ISSUE THREAD

**Issue by chargr** [dashpay/dash#637]
After doing a system upgrade dash no longer launches because of changes to miniupnpc.

bitcoin addressed this in this pull request/commit.

https://github.com/bitcoin/bitcoin/commit/af9305a7e8a40014508fb66a22ae95e8afe142c6#diff-9a82240fe7dfe86564178691cc57f2f1

```
net.cpp: In function ‘void ThreadMapPort()’:
net.cpp:1056:74: error: invalid conversion from ‘int*’ to ‘unsigned char’ [-fpermissive]
     devlist = upnpDiscover(2000, multicastif, minissdpdpath, 0, 0, &error);
                                                                          ^
net.cpp:1056:74: error: too few arguments to function ‘UPNPDev* upnpDiscover(int, const char*, const char*, int, int, unsigned char, int*)’
```

workaround is to would be to `./configure --without-miniupnpc`

```
$ pacman -Q miniupnpc
miniupnpc 1.9.20150730-1

$ ls /var/cache/pacman/pkg/ | grep miniupnpc
miniupnpc-1.9.20150430-1-x86_64.pkg.tar.xz
miniupnpc-1.9.20150730-1-x86_64.pkg.tar.xz
```

**Comment by langesi** [comment]
I've had the same problem. I had to use the workaround to run ./configure successfully

**Comment by iPadGuy** [comment]
I have this issue on OS X, too -- trying the workaround...

**Comment by schinzelh** [comment]
This should be solved in  https://github.com/dashpay/dash/tree/v0.12.1.x branch - anyone wants to test?

**Comment by KristerV** [comment]
An old topic, but 0.12.1.5-1 is installed on my Arch just fine.

**Comment by schinzelh** [comment]
Thanks for testing, issue closed.
