### ISSUE TITLE
Masternode start command causes wallet to crash with underconfirmed output or invalid key/tx/ip

### ISSUE THREAD

**Issue by thesolarminer** [dashpay/dash#646]
When starting a masternode (start-alias) the windows x64 wallet with .55 version will hang indefinitely under any of these conditions:
1. Masternode output(deposit) is less than 25 confirmations.  (It should give a warning and not crash like previous versions did.  This failed at 15 and 19 confirmations so it isn't just 15 required confirms like others have indicated.)
2. If masternode.conf file has a different key than remove server.
3. If local wallet can't connect to remote server(blocked ip, bad ip config).
4. If 2 ips are set for the same outputs or same keys in masternode.conf, the first node will start, but the second will hang.
Logfile: No information is available from the debug.log.  The hang isn't logged.
Suggestions:
Check masternode.conf for repeat ips, keys, or outputs and give warning.
For outputs with less the 25 confirms give a warning and don't try to start.
For the other errors, allow a 2 second hang and then stop trying and give a warning.

**Comment by nmarley** [comment]
At this point this is obsolete, as 0.12.0.55 is ancient. If this is an issue with current software version, please feel free to report.
