### ISSUE TITLE
libboost_system version mismatch 1.55 vs 1.58

### ISSUE THREAD

**Issue by MintyFresh** [dashpay/dash#647]
After installing all dependencies and building the most recent release, running dashd returns:
dashd: error while loading shared libraries: libboost_system.so.1.55.0: cannot open shared object file: No such file or directory
I've checked and the current version is 1.58, located here /usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0
New to creating issues, sorry if this isn't appropriate use of this feature. Thanks in advance for any help

**Comment by UdjinM6** [comment]
Hello there,
I just tried to build from scratch on fresh vps  (ubuntu 14.04) and it works fine for me...
So I have few questions about your setup (and some suggestions):
- What OS (version) do you have?
- Are you trying to build in "old" folder or is it a new one (i.e. you cloned it and it's the first build)?

If it's an old folder:
- try to run "./autogen.sh && ./configure" before running "make"
- try to build via "make clean && make"
- try to configure with "--disable-shared"

And finally - make sure you are actually trying to run newly built binary and not an older one if you had one before.

**Comment by MintyFresh** [comment]
OS is ubuntu 15.10, perhaps that's where the issue is?
It's a new system. After installing, all that's been done is install dependencies for dash and bitcoin, compile dash and bitcoin, and run bitcoind (Bitcoind has been working without a hitch).
I believe I did run autogen.sh first, and I know I ran configure when I compiled this.

I'm working on ansible playbooks to automate the deployment of *coind's. I'll test to see if it's an issue specifically with 15.10 by building a new binary following your suggestion, and running the playbook to initialize dashd on both an installation of 15.10 and an installation of 14.04. Once I get a chance to test that out, I'll follow up here.

Thanks so much for your help!

**Comment by UdjinM6** [comment]
Well, I was curious so I spun up 15.10 and it compiled and ran successfully too...
Could there be smth in your setup that interfere with build process? I guess it could be helpful to see some actual commands you use to install dependencies/build binaries. For example I made this snippet for myself to have everything in one place to make install/build process on new machine nice and easy:
```
sudo add-apt-repository ppa:bitcoin/bitcoin
sudo apt-get update
sudo apt-get install build-essential libtool autotools-dev autoconf pkg-config libssl-dev libboost-all-dev libdb4.8-dev libdb4.8++-dev git htop vim
sudo fallocate -l 4G /swapfile
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile
# sudo vi /etc/fstab
# /swapfile   none    swap    sw    0   0
git clone https://github.com/dashpay/dash/
cd dash
./autogen && ./configure --disable-tests && make -j 2
```

**Comment by crowning-** [comment]
Did you run _"apt-get upgrade"_ between build and running dashd?

If you built dashd with 1.55.0 and the upgrade installed 1.58.0 in between you'll get this error message because dashd was dynamically linked.

**Comment by schinzelh** [comment]
I have created a Dash PPA for Ubuntu --> #880 - so no need to compile Dash by yourself anymore.

Just do  

```
sudo add-apt-repository ppa:dash.org/dash
sudo apt-get update
sudo apt-get install dashd dash-qt
```

and you should be set. Closing this ticket now.
