### ISSUE TITLE
dashd super slow over network

### ISSUE THREAD

**Issue by scratchy** [dashpay/dash#665]
Hello,

Im running Dashd for several reasons on a remote endpoint (NAS, 1gbit latency < 0.1ms).
Syncing the whole blockchain over SMB takes me almost 24 hours, even a resync take almost that long! And surely i doubled checked that the NAS/Network is not the bottleneck (it even has SSDs in it). Network / CPU / IO load is far less then 5%
If i run it on my local system it takes far less for that.

For example if i check the network usage for dashd while its reindexing, its speed is at ~20kb/sek.
I didnt checked the code, but maybe theres some 'low' buffers for read/write requests, maybe theres some way to optimize it easly with adjusting this buffers?

**Comment by crowning-** [comment]
Did you check the RAM usage? Maybe your NAS is swapping all the time.

**Comment by scratchy** [comment]
Hey,

For sure i did, 6GB free.

2016-01-06 12:50 GMT+01:00 crowning- <notifications@github.com>:

**Comment by deusstultus** [comment]
What is your NAS filesystem?  I'm presuming NTFS given SMB use.  ntfs-3g is notoriously slow, especially with operations of the nature of blockchain database read/writes.  This is likely your bottleneck.

**Comment by schinzelh** [comment]
Obsolete
