### ISSUE TITLE
[GUI] Dark theme mode

### ISSUE THREAD

**Issue by fcore117** [dashpay/dash#740]
Please add dark(not black) theme option to QT wallet in future.

**Comment by crowning-** [comment]
"Dark" is a bit imprecise...care to make/paint a mock-up or have examples from other currencies/wallets?

**Comment by crowning-** [comment]
"Dark" is a bit vague...care to make/paint a mock-up or have examples from other currencies/wallets?

**Comment by crowning-** [comment]
"Dark" is a bit vague...care to make/paint a mock-up or have examples from other currencies/wallets?

**Comment by crowning-** [comment]
"Dark" is a bit vague...care to make/paint a mock-up or have examples from other currencies/wallets?

**Comment by fcore117** [comment]
good examples of dark theme:
http://phandroid.s3.amazonaws.com/wp-content/uploads/2015/05/Android-M-dark-theme.jpg
or Firefox FT DeepDark theme or uTox dark theme.

**Comment by fcore117** [comment]
Any news of grey dark type of theme for Dash, there are no 0.12.1 binaries to test thats why i ask. At least i do not know any 0.12.1 binaries exists? It would be suitable to be 2 official color tones, current white and dark. White bleeds eyes out.

**Comment by schinzelh** [comment]
There are 12.1 binaries available on our CI system.

Depending on your OS try:

Linux --> https://dashpay.atlassian.net/builds/browse/DASHL-DEV/latestSuccessful/artifact/JOB1/gitian-linux-dash-dist
Windows --> https://dashpay.atlassian.net/builds/browse/DASHW-DEV/latestSuccessful/artifact/JOB1/gitian-win-dash-dist/
MacOS X --> https://dashpay.atlassian.net/builds/browse/DASHM-DEV/latestSuccessful/artifact/JOB1/gitian-osx-dash-dist/

**Comment by fcore117** [comment]
Thanks for binaries, DASH-dark theme is still missing and i truly hope it will be added before release.
![dark](https://cloud.githubusercontent.com/assets/1313813/18998357/0e106846-8741-11e6-9721-b6f88ac8d2d7.png)

Thanks for all development and i truly belive dash should be next bitcoin.

**Comment by fcore117** [comment]
What is state of dark theme mode in 0.12.2.x ? binaries link is dead.

**Comment by schinzelh** [comment]
Binary links changed to

Latest binaries:
- Windows : https://bamboo.dash.org/browse/DASHW-DEV/latestSuccessful/artifact/JOB1/gitian-win-dash-dist/
- MAC : https://bamboo.dash.org/browse/DASHM-DEV/latestSuccessful/artifact/JOB1/gitian-osx-dash-dist/
- Linux : https://bamboo.dash.org/browse/DASHL-DEV/latestSuccessful/artifact/JOB1/gitian-linux-dash-dist/
- Raspberry Pi : https://bamboo.dash.org/browse/DASHP-DEV/latestSuccessful/artifact/JOB1/gitian-RPi2-dash-dist/

**Comment by schinzelh** [comment]
Should be fixed.

**Comment by fcore117** [comment]
Hello, is that some upcoming commit? tested lastest binary but not yet there.
![th](https://user-images.githubusercontent.com/1313813/37460116-ecbad492-2852-11e8-8b51-85403e98d353.png)
