### ISSUE TITLE
[GUI] Transactions tab first left column

### ISSUE THREAD

**Issue by akijuh** [dashpay/dash#788]
v.12.1
Transactions tab first left column is too wide and therefore columns are misaligned.

![ac76d1dc-20e4-11e6-9054-9f8990e8395c](https://cloud.githubusercontent.com/assets/6022297/15469209/65c4b864-20f1-11e6-8c93-03c743b8625d.png)

**Comment by crowning-** [comment]
Tagged, will check later this week.

**Comment by akijuh** [comment]
Old Dash-blue theme column Address is now named Label.

As column top search box suggest, enter label or address, 
should this column text be named as "Address / Label" ?
And column text tool tip also to same.

Just my 2 duffs.
