### ISSUE TITLE
[GUI] Main window size

### ISSUE THREAD

**Issue by akijuh** [dashpay/dash#789]
Win7 64bit, Dash-qt v12.1.

Dash-qt main window position is remembered ok, but size is not.

Window size is not remembered correctly if you adjust window size to minimal and restart,
but if you adjust size to lager size, it is remembered ok.

**Comment by crowning-** [comment]
Tagged, will check later this week.

**Comment by akijuh** [comment]
I think this could be related to immature etc amount boxes which forces the window to bigger size when wallet start and initialize. Just a thought.

**Comment by akijuh** [comment]
BTW, this is **not** problem with v12.0.56 and Dash-blue theme.

**Comment by crowning-** [comment]
Not reproducible here. 

Would you please do a _"Settings -> Options -> Reset Options"_ and test if you can still reproduce the issue after that?

**Comment by akijuh** [comment]
Sure, no help.

Win7x64 test:
- Start your test wallet
- Drag with your mouse and window bottom right corner and resize main window to minimum size.
- Shut down wallet.
- Start wallet, now you see window in not same minimum size as you set earlier.
