### ISSUE TITLE
[GUI] Masternodes tab address column

### ISSUE THREAD

**Issue by akijuh** [dashpay/dash#790]
Win7 64bit - v.12.1

Masternodes tab -> address column is too narrow, ipv6 addresses are truncated.

Current default:
![currentdefault](https://cloud.githubusercontent.com/assets/6022297/15470684/8e54888c-20fa-11e6-8413-5ab1a23850cb.png)

I propose:
![propose](https://cloud.githubusercontent.com/assets/6022297/15470691/9b0773c8-20fa-11e6-8b9e-e77cffd4d4dd.png)

**Comment by UdjinM6** [comment]
ipv6 can be really huge and there are not so many of them so it might look weird.
![screen shot 2016-05-24 at 1 46 12](https://cloud.githubusercontent.com/assets/1935069/15486920/1b75b6aa-215a-11e6-8a8c-dd68b19ebfb1.png)


Also I'd rather truncate few ip addresses by default but leave all other fields non-truncated for minimum width. So smth like this maybe?
![screen shot 2016-05-24 at 1 47 00](https://cloud.githubusercontent.com/assets/1935069/15486933/3747eb96-215a-11e6-8366-45b4c9b6bd2d.png)

Thoughts? @schinzelh @crowning-

**Comment by crowning-** [comment]
I'd narrow everything as far as possible ("Last seen" has some wasted real estate) and if the width still does not fit the default wallet width I'd truncate the "Address" field and show the full value in a bubble help.
That's how I did it in the CoinControl dialog.

Oh, and once available double check the look in some of the longer locales (German, Finnish are the usual candidates).

**Comment by schinzelh** [comment]
Fixed with https://github.com/dashpay/dash/pull/799

**Comment by UdjinM6** [comment]
@crowning- good points! Might need to have another look at this later.
