### ISSUE TITLE
12.1. test version (mainnet) (WIN10 - 64bit)

### ISSUE THREAD

**Issue by Comodore125** [dashpay/dash#794]
Not starting with right setting of single MN. Bug message makes no sense. 

Testnet version does not start at all. 

What is bench_dash?

And I use dash-0.12.1.-win64 zip.

**Comment by schinzelh** [comment]
test_dash and bench_dash are test binaries and not for end user use.

If you want to connect to testnet, you need to add the parameter

`testnet=1`

to your dash.conf file and then start dash-qt as usual.

**Comment by Comodore125** [comment]
Thanks for answer. All is working.
