### ISSUE TITLE
[GUI] Masternodes tab active column text

### ISSUE THREAD

**Issue by akijuh** [dashpay/dash#795]
Win7 64bit - v0.12.1.0-1ceca7e

Masternodes tab -> active column text "Active (secs)", secs does not make sense.

![mnssecs](https://cloud.githubusercontent.com/assets/6022297/15481366/b7105098-2132-11e6-8505-40d65c2e5270.png)

**Comment by UdjinM6** [comment]
ooooops! :)

**Comment by schinzelh** [comment]
Fixed with https://github.com/dashpay/dash/pull/799
