### ISSUE TITLE
[GUI] Masternodes tab date format

### ISSUE THREAD

**Issue by akijuh** [dashpay/dash#796]
Win7 64bit - v0.12.1.0-1ceca7e

Masternodes tab -> date format is different than transactions tab date format.
I think it should follow transactions date format.

![mndate](https://cloud.githubusercontent.com/assets/6022297/15483423/447a050a-213d-11e6-8826-6404abebea7b.png)

![tadate](https://cloud.githubusercontent.com/assets/6022297/15483428/49ce1bf4-213d-11e6-8101-47f5f1951445.png)

**Comment by UdjinM6** [comment]
heh, good catch! 👍

**Comment by schinzelh** [comment]
Fixed with https://github.com/dashpay/dash/pull/799
