### ISSUE TITLE
Chinese Font Old/ New Wallet

### ISSUE THREAD

**Issue by tungfa** [dashpay/dash#802]
Alexy/ china is saying this:
Hey Tungfa, could you tell udjin that Mac wallet default fonts isn't working for some people, they have to update their fonts to download certain type Chinese font...

![image](https://cloud.githubusercontent.com/assets/636669/16516492/aab2b8e0-3f78-11e6-9959-7a7402f9c70e.png)

![image](https://cloud.githubusercontent.com/assets/636669/16516497/b60abc42-3f78-11e6-8561-084bc1b5dd00.png)

**Comment by tungfa** [comment]
is it possible the the default fonts Of Chinese  is not common ones? for example, we set Roman fonts for English, However if users don't have such font, they cannot see the characters, right? so maybe the simple solution is to change the default fonts for Chinese. （Microsoft YaHei，STHeiti Light）

**Comment by schinzelh** [comment]
@tungfa can you test this with the current version again?

**Comment by tungfa** [comment]
checked with raico (THE chinese)
and he said: "It’s ok and works smoothly"
tx guys

**Comment by UdjinM6** [comment]
Thanks! Closing.
