### ISSUE TITLE
Privatesend stuck

### ISSUE THREAD

**Issue by Comodore125** [dashpay/dash#803]
Private Send (23 May Gitian-win-dash-dist) is stuck for hours. 
![dashtest](https://cloud.githubusercontent.com/assets/6156234/15493154/4d87f54a-2182-11e6-8c6d-d39359826d95.JPG)
![dashtest2](https://cloud.githubusercontent.com/assets/6156234/15493157/5352f07e-2182-11e6-900c-fa04effe5bac.JPG)

**Comment by schinzelh** [comment]
This may be resolved by https://github.com/dashpay/dash/pull/797

**Comment by akijuh** [comment]
Maybe not enough masternodes and miners in the testnet?

**Comment by schinzelh** [comment]
Testnet masternodes need to update to latest protocolversion `70200` first, miners are enough.

**Comment by Comodore125** [comment]
As I now see 70200 protocol masternodes online. That privatesend transaction is indeed confirmed.
