### ISSUE TITLE
GPG signatures

### ISSUE THREAD

**Issue by SecTec** [dashpay/dash#809]
Hi,

1st: Holgers signing key isn't importable because of 2 missing chars in his pubkey.
I opened an issue 4 days ago in the dash-binary repo.

2nd: my gpg tells me that the dash-0.12.0.56-win64.zip signature is not valid.

**Comment by schinzelh** [comment]
Where did you retrieve the key from?

**Comment by UdjinM6** [comment]
https://raw.githubusercontent.com/dashpay/dash-binaries/master/pgp/holger-darkcoin-qa.asc works fine for me, no issues with signatures either.

**Comment by SecTec** [comment]
Oh, sorry. I retrieved the key first from the webpage and the formating was screwed up. Now from the keyservers.

The second thing wasn't a problem with the signature. I was verifying the signature first with an gui application. Today I verifyed it with gpg2 itself. It was fine.

Sorry for the false alert.

**Comment by schinzelh** [comment]
Good stuff, thanks for reporting anyway :)
