### ISSUE TITLE
Privatesend bad math

### ISSUE THREAD

**Issue by Comodore125** [dashpay/dash#815]
![2016-05-27](https://cloud.githubusercontent.com/assets/6156234/15605315/64a56570-2405-11e6-9acf-e6ad81b8eb02.png)

According to coin control all is right. Before, I had mixed for more rounds and changed it just for 2000/2

**Comment by UdjinM6** [comment]
I don't get it. Where it's "bad" exactly?

**Comment by Comodore125** [comment]
Denominated inputs have 2 of 2 round on average. But it says different things. I even checked coin control.

**Comment by UdjinM6** [comment]
hmm... I don't see how this could be possible... Pls sort coin control list by Rounds and see if there are any inputs with rounds less than 2 (but not `n/a`).

**Comment by Comodore125** [comment]
they are not. that is why I opened an issue.

**Comment by UdjinM6** [comment]
hmm.. maybe there are some stuck unconfirmed?

**Comment by Comodore125** [comment]
In the wallet, there are three conflicted PrivateSend Denominate. They are from the time before 70200 protocol. I just used recovery (n 1) and wallet is closing for many minutes while it does not uses CPU resources or HDD resources in that time. I am killing the process now.

**Comment by bertlebbert** [comment]
@Comodore125 I also had unconfirmed in a mixing wallet (70200 protocol) and had to 'kill process' after trying to use Repair options. When restarting the wallet, I added -zapwallettxes=1 to its shortcut and that worked (cleared those pesky 'unconfirmed').

**Comment by Comodore125** [comment]
I got this even when I start with that -zapwallettxes=1 in powershell

**Comment by thelazier** [comment]
Please try with the latest one for windows from https://dashpay.atlassian.net/builds/browse/DASHW-DEV-494/artifact
possibly add -reindex and -zapwallettxes=1 should help.

**Comment by Comodore125** [comment]
All is wel now. I just dont get why zapwallettxes=1 corrupted the wallet. Is it what was fixed by new build?
