### ISSUE TITLE
[GUI] Recent transactions digits

### ISSUE THREAD

**Issue by akijuh** [dashpay/dash#816]
Overview tab -> Recent transactions digits are now 8 digits, which is overkill.

I think recent transactions digits should follow "Options -> Decimal digits" setting,
as all other digits in the Overview tab do so.

In the transactions tab 8 digits is ok, as it is really the place where user inspect transactions.

What you think @schinzelh @UdjinM6 @crowning-

![rtdigits](https://cloud.githubusercontent.com/assets/6022297/15606589/d2d396ce-2415-11e6-882b-e02d7976a50e.png)

**Comment by akijuh** [comment]
Also there is room for one more row to add, total 6 rows.

**Comment by UdjinM6** [comment]
Not sure about decimals in recent txes group, might be a good idea though
> Also there is room for one more row to add, total 6 rows.

Actually, I have 7 in my local build since ages and it look a bit more consistent imo but always put it on "submit later" list... :)

**Comment by akijuh** [comment]
If recent tx's follows setting, its more cleaner look as all other amounts allready uses that,
and its up to user how many digits is used.

**Comment by crowning-** [comment]
I'll check whether it's possible to make the number of digits follow the "Visible digits" setting without changing the results of computations...

@UdjinM6 , I have 7 rows as well, if you don't mind I'll include it here.
