### ISSUE TITLE
Dash testnet wallet lattest release not closing after recovery - WIN10_64bit

### ISSUE THREAD

**Issue by Comodore125** [dashpay/dash#818]
I had three conflicted transaction so according to this [https://www.dash.org/forum/threads/conflicted-transactions.6132/](url) I made recovery. 

But client is not turning itself off. It says shutting down, but nothing is happening in the process manager for windows.

**Comment by Comodore125** [comment]
![bug](https://cloud.githubusercontent.com/assets/6156234/15626924/4ffae0b8-24d3-11e6-8c34-f7854f168280.JPG)
Now I can't even start that program.

**Comment by schinzelh** [comment]
Can you please test one of these builds?

Linux --> https://dashpay.atlassian.net/builds/browse/DASHL-DEV-559/artifact/JOB1/gitian-linux-dash-dist/
Windows --> https://dashpay.atlassian.net/builds/browse/DASHW-DEV-506/artifact/JOB1/gitian-win-dash-dist/
MacOS X --> https://dashpay.atlassian.net/builds/browse/DASHM-DEV-515/artifact/JOB1/gitian-osx-dash-dist/
Raspberry --> https://dashpay.atlassian.net/builds/browse/DASHP-DEV-511/artifact/JOB1/gitian-RPi2-dash-dist/

**Comment by Comodore125** [comment]
tried all options. not that everything works fine but everything is way faster. Great Job!
