### ISSUE TITLE
[GUI] Simplification for Newbs

### ISSUE THREAD

**Issue by TaoOfSatoshi** [dashpay/dash#827]
I feel that the current homepage configuration could use a bit of a simplification for non-tech people.

In the inspiration of Evan's sketch of Evolution, the appearance of a Public Dash Balance and a Private Dash Balance would be easy to understand for newcomers.

I propose the following changes to the GUI: 
- Underneath where it currently says "Available", provide the user with a bolded "Public Dash Balance", a "Private Dash Balance", the current "Pending", and a "Total Dash Balance". Underneath the bolded "Private Dash Balance" add a regular font explanation (to be used with PrivateSend).

So like this:

**AVAILABLE:**

**Public Dash Balance:**          2,994
**Private Dash Balance:**        456
(to be used with PrivateSend)
**Pending:**                             2
**TOTAL DASH BALANCE:**  3,452
- Underneath where it currently says "PrivateSend", keep the PrivateSend Balance field there, but replace it with the term "Private Dash Balance".
- And for the "Start Mixing" button, change it to "Create Private Dash". The average user won't care how they are getting Private Dash, they will just want to see that they are making it.

Sorry to post this here, but I thought it would be seen here before anywhere else.

Cheers,

Tao

**Comment by akijuh** [comment]
Maybe new "newbie" real simple theme would be the thing?

**Comment by crowning-** [comment]
I agree with @akijuh , it'll be much easier to just create a new CSS theme which hides all the complicated stuff from noobs.
Only problem might be changing the labels of the buttons because those are not part of the CSS and need translations.
If we keep the labels named as they are now it'll be trivial to add such a  theme.

**Comment by TaoOfSatoshi** [comment]
Sounds good. Anything to make it easier and less intimidating would be perfect.

**Comment by akijuh** [comment]
If this "noob" theme is coming to reality, it needs to default theme also.

**Comment by Comodore125** [comment]
why not to make a window on startup asking what theme each user want?

**Comment by TaoOfSatoshi** [comment]
Yes, when the user downloads the wallet for the first time, the options of "Basic (Most commonly used features)", Advanced, or Power User themes could be offered, with the according level of understanding and information displayed. Then, keep it as an option to change in settings. Good idea.

**Comment by TaoOfSatoshi** [comment]
Looks good. I like the streamlined approach, with the advanced theme being an option. Good work!

Re: Mixing Button and Public and Private Dash balances:
Is it possible to change the button to "Create Private Dash" and change the UI to reflect the Public and Private Dash balances? I think crowning said it was too much work, but I feel that this terminology would be easier for newbs to understand in the default easy UI.

**Comment by crowning-** [comment]
Since Udjin didn't use CSS it's an easy change.
But, IMO, _"Create Private Dash"_ is an unfortunate and misleading label. Sounds like mining, but there's no Dash created, just transferred/mixed into a different state.

I think the "Start Mixing" button as it is now is perfect, it explains what's done.
And the word/action "Mixing" is really easy to understand for newbs.

**Comment by UdjinM6** [comment]
I agree with @crowning- - "Create" is closer to mining/minting and could be confusing. It's more like "Transfer" of funds (to yourself but it's a transfer anyway) but then you'd have to answer to user's "Why the transfer is sooo slow? Wasn't it meant to be instant? Why not?" etc. ;) "Mixing" is easy to understand but it have to be explained first on the other hand ("Why do I need to mix anything? I just want my private dash"). So "Exchange" maybe? Or any other idea?

**Comment by TaoOfSatoshi** [comment]
Yes, I see your point @crowning, "Create" does sound like mining.

"Start Mixing" is brief and to the point, maybe it could just have a (?) bubble with a short explanation of what's happening when you press the button. Would that work?

**Comment by UdjinM6** [comment]
fixed by #867 #1129
