### ISSUE TITLE
[GUI] Masternodes Tab, sort using Address column

### ISSUE THREAD

**Issue by bertlebbert** [dashpay/dash#831]
Under the new Masternodes Tab, sorting rows '1rst to last' or 'last to 1rst' by clicking column headings works fine on all but the 'Address' column.

**Comment by akijuh** [comment]
You mean pubkey column, works for me, at least it is sorting, dunno what order though.

**Comment by crowning-** [comment]
Works perfectly on Win10 64bit and Ubuntu 16.04.
If you're on testnet, do you care to share your masternode.conf?

**Comment by bertlebbert** [comment]
Actually I noticed this problem under 'All Masternodes' tab,
not sure about 'My Masternodes' tab. I'm on Win7(64 bit):
![image 005](https://cloud.githubusercontent.com/assets/13893695/15843382/a80d9c7e-2c16-11e6-8ace-8aeed72e5a2c.png)

**Comment by bertlebbert** [comment]
Haha, that screenshot above is bad example, this screen is better example:
Appears to sort on first digit, such that 216.45.55.146:19999 is <  22.2.250:19999
(not so much of an issue really)

![image 006](https://cloud.githubusercontent.com/assets/13893695/15843923/d0df709c-2c1a-11e6-870b-882fac3465be.png)

**Comment by crowning-** [comment]
An IP-address, even when almost always called otherwise, is a string, NOT a number.

And a string (=alphabetical) sort means "216.45" < "23.22.".

Works as designed.

**Comment by bertlebbert** [comment]
As I say, really not much of an issue - just kinda looks odd...  I'll close this then?

**Comment by UdjinM6** [comment]
Ah, now I see what you meant by "wrong order :) yep, it's just a string and works the same as in Peers tab for example so even if it's a bit confusing it's still consistent :D

I guess it's ok to have it as it is. We can probably implement a more sophisticated sorting for `Address` column later if there would be many complaints. This however would require to replace current (naive and straightforward) implementation which uses standard widgets with custom model/view implementation and I'm not sure if it really worth it.

Same applies to `Active` column btw.
