### ISSUE TITLE
Dash-QT hangs on closing (Win10 - 32)

### ISSUE THREAD

**Issue by TaoOfSatoshi** [dashpay/dash#832]
I attempted to do a -zapwallettxes through the GUI, and the program hung upon exit. This is with the latest version posted by Flare on the Dash Chat Slack.

**Comment by schinzelh** [comment]
Related to https://github.com/dashpay/dash/pull/822

**Comment by Comodore125** [comment]
-reindex from wallet repair tab in tools window is doing the same. probably related (win10x64)

**Comment by Comodore125** [comment]
https://github.com/dashpay/dash/issues/818

**Comment by schinzelh** [comment]
Can you please test one of these builds?

Linux --> https://dashpay.atlassian.net/builds/browse/DASHL-DEV-559/artifact/JOB1/gitian-linux-dash-dist/
Windows --> https://dashpay.atlassian.net/builds/browse/DASHW-DEV-506/artifact/JOB1/gitian-win-dash-dist/
MacOS X --> https://dashpay.atlassian.net/builds/browse/DASHM-DEV-515/artifact/JOB1/gitian-osx-dash-dist/
Raspberry --> https://dashpay.atlassian.net/builds/browse/DASHP-DEV-511/artifact/JOB1/gitian-RPi2-dash-dist/

**Comment by Comodore125** [comment]
Should be alright, do you have client faster? https://github.com/dashpay/dash/issues/818#issuecomment-223799993
