### ISSUE TITLE
No block source available - stuck 6 hours behing

### ISSUE THREAD

**Issue by Comodore125** [dashpay/dash#838]
I have all required peers with latest build on testnet. (win10x64)

I already tried -reindex

**Comment by schinzelh** [comment]
Did you try to delete peers.dat before relaunching?

**Comment by Comodore125** [comment]
it did not help. :(

**Comment by schinzelh** [comment]
Please send your debug.log to holger@dash.org

**Comment by Comodore125** [comment]
done

**Comment by schinzelh** [comment]
Please update to 

https://dashpay.atlassian.net/builds/browse/DASHW-DEV-498/artifact/JOB1/gitian-win-dash-dist/

and add these nodes to your dash.conf

```
addnode=[2001:1608:10:25:10::101e:7241]:19999
addnode=[2001:1608:10:25:10::10d2:f4d1]:19999
addnode=[2001:1608:45:3::242:ac11:2]:19999
addnode=[2001:1608:45:3::242:ac11:3]:19999
addnode=[2001:1608:45:3::242:ac11:4]:19999
addnode=[2001:1608:45:3::242:ac11:5]:19999
addnode=[2001:1608:45:3::242:ac11:6]:19999
addnode=[2001:1608:45:3::242:ac11:7]:19999
addnode=[2001:19f0:9000:2042::2]:19999
addnode=[2001:19f0:9000:2049::2]:19999
```

**Comment by akijuh** [comment]
I had similar problem, i was forked, deleted all folders and files and restarted and let it sync, all good.

**Comment by Comodore125** [comment]
How many blocks are necessary to keep wallet stuck with wrong chain? 
This seems to be an issue with consensus protocol. Probably in bitcoin this issue persists as well.

**Comment by schinzelh** [comment]
This is not a issue with the consensus protocol, it only applies to Dash testnet where only 20 CPU cores are mining and you can fork the network by running a single rough GPU miner :)

Is your sync problem solved?

**Comment by Comodore125** [comment]
Yes, by deleting the blockchain, I already had last build.
