### ISSUE TITLE
Debug.log time sync (testnet latest win10x64)

### ISSUE THREAD

**Issue by Comodore125** [dashpay/dash#871]
debug.log is -2 hours compared to my local time and time in transaction tab. 

I would like to see local time that my PC uses. This is bug imho.

**Comment by schinzelh** [comment]
debug.log is not using local time, but UTC afaik

**Comment by UdjinM6** [comment]
@schinzelh is absolutely right, it's a feature. Otherwise it would be very hard to analyze problems using debug.log files grabbed from different nodes all around the world. Won't fix, closing.
