### ISSUE TITLE
[GUI] Transactions tab address/label column text colors

### ISSUE THREAD

**Issue by akijuh** [dashpay/dash#874]
Transactions tab -> Address / Label column, 'sent to' and 'received with' txs text colors, 
are they intentionally different color (grey)?

![txscolors](https://cloud.githubusercontent.com/assets/6022297/15913021/7d4c438e-2de0-11e6-8254-993597d4f564.png)

**Comment by akijuh** [comment]
Same issue in: Overview tab -> Recent transactions.

![txscolors2](https://cloud.githubusercontent.com/assets/6022297/15913351/275f53f6-2de2-11e6-89de-bf813a23748a.png)

**Comment by UdjinM6** [comment]
Note quite. Gray color was intended to make addresses without any label in address book less visible.
PrivateSend transaction/mixing txes however don't follow the same rule which is indeed a bug.
Will fix.

**Comment by akijuh** [comment]
Ok.
