### ISSUE TITLE
[GUI] Recent transactions icon size

### ISSUE THREAD

**Issue by akijuh** [dashpay/dash#876]
In my opinion 'Recent transactions' icon sizes are too big.

Is this possible do just with scaling down original icon pic, so no need to make new icons?
This is just suggestion,see mockup pic, icon size is 50% reduced.

Original:
![clipboard01](https://cloud.githubusercontent.com/assets/6022297/15926345/3c34b7fa-2e44-11e6-8abc-ad7afac30f67.png)

Mockup (-50%):
![clipboard02](https://cloud.githubusercontent.com/assets/6022297/15926350/42db4484-2e44-11e6-919e-2ec5a2326468.png)

**Comment by akijuh** [comment]
Bump, anyone :)

**Comment by PastaPastaPasta** [comment]
![smaller-icons](https://user-images.githubusercontent.com/6443210/81229215-f7bb9980-8fde-11ea-97b1-8a53202eac6b.PNG)
In recent versions, I think the icons are much more reasonable and more pleasing, please reopen if you feel this is still an active issue :)

Thanks

**Comment by akijuh** [comment]
> In recent versions, I think the icons are much more reasonable and more pleasing,
> please reopen if you feel this is still an active issue :)

Much better, thanks!
