### ISSUE TITLE
[GUI] Transactions date column filters

### ISSUE THREAD

**Issue by akijuh** [dashpay/dash#879]
Transactions tab -> date column filters.
Can we have 3 new options to list, ''Yesterday, 'last week' and 'last year' ?

So, the new complete filter list is then:
All
Today
Yesterday
This week
Last week
This month
Last month
This year
Last year
Range...

![clipboard01](https://cloud.githubusercontent.com/assets/6022297/15978951/ea8909a2-2f69-11e6-8603-44ee45a06da9.png)

**Comment by crowning-** [comment]
I could do this, but I wonder if it actually increases usability with THAT much options in one single dropdown box...

**Comment by UdjinM6** [comment]
Tbh I never switch from "All" at all so if we are just looking for more consistency I would shrink the list by dropping  "Last month" instead 😉  Everything else can by covered by "Range..." and this should be enough imo.

**Comment by akijuh** [comment]
Well, its simler and and faster just click with mouse than write whole range example 1.1.2015-31.12.2015.

**Comment by akijuh** [comment]
At least i use it, i have a habit to check last month masternode total payments,
but its up to you guys deside what that list should be.

**Comment by crowning-** [comment]
I could add my birthday...

Maybe we should persist what's currently selected for the range option, and that the range column was used last time.

**Comment by UdjinM6** [comment]
@akijuh well, that makes sense, I guess we'd have to leave Last month then ;)
@crowning- this could be useful I guess 👍 (I mean saving range option, not your birthday 😛 )

**Comment by akijuh** [comment]
Maybe 3 range options which user can modify and save?
So whole list can look like:

All
Today
This week
This month
Last month
Range...

and when range is selected, also 3 saved range options appears next to range selection, right side.

BTW. Current range selection combos does not follow wallet date format, 
example now its 10/06/16, but in the transactions list it is 10.6.2016.
