### ISSUE TITLE
Add PPA for Dash?

### ISSUE THREAD

**Issue by jonathancross** [dashpay/dash#880]
Seems this was discussed here: https://www.dash.org/forum/threads/ubuntu-repository.1670/

Would make installation / upgrades much easier for users on Linux.

**Comment by schinzelh** [comment]
Thanks, working on it. Will you be able to test?

**Comment by schinzelh** [comment]
I have sucessfully tested the PPAs installs on precise and trusty

![image](https://cloud.githubusercontent.com/assets/636669/16516292/9fad0e92-3f77-11e6-93bb-138595d11a4a.png)

![image](https://cloud.githubusercontent.com/assets/636669/16516344/e146a868-3f77-11e6-9e91-c3ebf4d10d2a.png)

I will push the PPAs later the day

**Comment by UdjinM6** [comment]
Awesome!

**Comment by schinzelh** [comment]
Vivid

![image](https://cloud.githubusercontent.com/assets/636669/16518357/a10f447a-3f82-11e6-87b2-c615bdbb4525.png)


Wily

![image](https://cloud.githubusercontent.com/assets/636669/16518360/a5043d74-3f82-11e6-888f-f02ef38c319d.png)



Xenial


![image](https://cloud.githubusercontent.com/assets/636669/16518361/a946b330-3f82-11e6-99b8-4c7aebc9ae37.png)


tested successfully as well.

**Comment by schinzelh** [comment]
Pushed to launchpad

![image](https://cloud.githubusercontent.com/assets/636669/16518593/f287d3f2-3f83-11e6-9448-9c8f97123787.png)

**Comment by UdjinM6** [comment]
hmm...ok, so I added ppa but `apt` refuses to recognize any new dash-* packages even after `apt-get update`... what am I doing wrong?

**Comment by schinzelh** [comment]
Simple answer: compilation/publication is not finished yet :)

**Comment by schinzelh** [comment]
PPA creation finished, you can now install Dash to Ubuntu Xenial, Wily, Vivid, Trusty and Precise via

```
sudo add-apt-repository ppa:dash.org/dash
sudo apt-get update
sudo apt-get install dashd dash-qt
```

Enjoy :smile:

**Comment by UdjinM6** [comment]
Yay! Success!

![screen shot 2016-07-01 at 14 04 28](https://cloud.githubusercontent.com/assets/1935069/16519878/34a1e03e-3f9d-11e6-80ea-e1d9b855321c.png)
