### ISSUE TITLE
Feature request: Support transactions that require signatures of both the sender and receiver

### ISSUE THREAD

**Issue by destenson** [dashpay/dash#894]
I would like to propose that Dash add the concept of multi-signature transactions (in addition to multisig wallets). A multi-signature transaction would be a transaction that requires the valid signature of all parties involved before it is actually committed to the blockchain as a valid transaction. A requester or recipient could be any valid address, not just multi-signature wallets. The transaction can be initiated by either the payer or the payee.

Requests for payment can be initiated by party A with a valid signature (or all required signatures if initiated by a multisig wallet) & when party B also signs the request, the actual transfer of funds from B to A will occur like a normal transaction. This will add invoicing as an intrinsic feature to Dash.

Outgoing payments to a third-party can also be multisig. In that case, the request is for acceptance of payment, and the transfer is completed when the recipient signs the transaction. Since the transfer is not valid until all parties sign, this allows the funds for the transaction not to be committed until the recipient accepts the payment. If funds are not available when the transaction is adequately signed, it will be rejected by the blockchain due to insufficient funds. A signatory can also rescind their signature before the transaction is accepted by all parties. This allows a fund transfer to be cancelled before payment is accepted. This is a feature that is missing from all major cryptocurrencies.

**Comment by wrapperband** [comment]
How far is the FTC solution from your requirements? (http://forum.feathercoin.com/topic/8327/guide-feathercoin-wallet-ppa-and-binaries-on-ubuntu-and-debian-linux). 
http://forum.feathercoin.com/topic/7870/guide-how-to-use-feathercoins-multi-signature-address-page

**Comment by demodun** [comment]
What about this?

**Comment by destenson** [comment]
A clearer and more thorough explanation of this feature can be found [here in this thread](https://github.com/monero-project/monero/issues/881#issuecomment-351917989) requesting the same feature in Monero.

**Comment by 10xcryptodev** [comment]
The thread was closed on Monero request with the arguments that should be valid here.

I think that should be closed here too

**Comment by PastaPastaPasta** [comment]
Closing, this is more appropriate for something like a DIP. Please create a DIP with the standard, then an implementation here can be considered
