### ISSUE TITLE
[GUI] Information window glitch

### ISSUE THREAD

**Issue by akijuh** [dashpay/dash#899]
v0.12.1.0-025f090
Menu -> Tools -> Information -> window blockchain text glitch.

![glitch](https://cloud.githubusercontent.com/assets/6022297/16611619/286f681e-436b-11e6-9bc0-696a149cef62.png)

**Comment by akijuh** [comment]
Also masternodes total row is misaligned.

**Comment by schinzelh** [comment]
Yep, I've introduced this in #897 ^^

Thanks for reporting
