### ISSUE TITLE
Dash Core qt crash

### ISSUE THREAD

**Issue by akijuh** [dashpay/dash#900]
Win 7 64bit - v0.12.1.0-025f090

Dash Core qt crash every time when you switch **on** 'Show Masternodes Tab' option
in the middle of syncing masternodes process.

To replicate this bug:
Make sure you have switched **off** 'Show Masternodes Tab, then close wallet.
Start wallet, switch **on** 'Show Masternodes Tab' in wallet options, do not close options yet,
wait when synchronizin masternodes start then close options window with ok,
and close also wallet, crash occur.

**Comment by schinzelh** [comment]
Likely related to #897 as well - i broke the Debug Window

**Comment by akijuh** [comment]
This is related to masternodes tab, and crashing was occuring in the earlier versions also,
but now i figured out why and when crash occurs.
@UdjinM6 should find this fast, its his code :)

**Comment by schinzelh** [comment]
Gotcha, so i am not the bad boy here :)

**Comment by UdjinM6** [comment]
Yep, reproduced, will provide a fix (and probably slight refactoring).
Thanks!
