### ISSUE TITLE
Testnet 12.1 win-10-64bit  InstantSend related

### ISSUE THREAD

**Issue by Comodore125** [dashpay/dash#929]
Some time ago, when I was testing 12.1 I discovered bug/feature? 

After the client went offline InstandSend was not received it was only took as regular transaction. So when a client receives IS transaction and goes offline for just a short span of miliseconds it could result into this. Into IS transaction being just regular one. It is pretty bad service for the fee 0.01 dash

I think this is bug. Why is IS transaction relayed into network just once? Why are the clients not receiving it when the could need it?

**Comment by UdjinM6** [comment]
Fixed by #2051
