### ISSUE TITLE
crash in ProcessMessages, 0.12.0.58

### ISSUE THREAD

**Issue by ralphtheninja** [dashpay/dash#933]
From `~/.dash/debug.log`. Unfortunately it's the only information I have.

```
2016-08-10 13:06:50 CActiveMasternode::SendMasternodePing() - Relay Masternode Ping vin
 = CTxIn(COutPoint(8a131e20b4674335431e1dc4a01a6c3dfe0ef6eb03868b58bea98c027d4a242b, 1)
, scriptSig=)
2016-08-10 13:06:50 

************************
EXCEPTION: St9bad_alloc       
std::bad_alloc       
dash in ProcessMessages()       
```

**Comment by schinzelh** [comment]
Thanks for submitting, the debug.log does not help much though. The interesting part is
```
************************
EXCEPTION: St9bad_alloc       
std::bad_alloc       
dash in ProcessMessages(
```

but it doesnt tell much :-)

**Comment by tgflynn** [comment]
Was your node running on a machine with a quite small amount of memory ?

This looks the kind of error one would see if the process ran out of memory.

**Comment by ralphtheninja** [comment]
> Was your node running on a machine with a quite small amount of memory ?

It has 1Gb of memory and the process have never exceeded 500Mb, so it wouldn't fail unless the process was trying to allocate 500Mb, which feels unlikely.

**Comment by tgflynn** [comment]
Is this repeatable at all, or did it only happen once ?

**Comment by tgflynn** [comment]
I think it's probably memory exhaustion.  This certainly wasn't the only running process and the kernel needs memory too.  1 GB may be just too tight for all this unless you have swap space enabled (but that might be very slow if more memory is actually needed often).

**Comment by ralphtheninja** [comment]
> Is this repeatable at all, or did it only happen once ?

Only happened once.
