### ISSUE TITLE
Testnet  syncing

### ISSUE THREAD

**Issue by Comodore125** [dashpay/dash#996]
You probably know that, but I just decided to test latest build v0.12.1.0-5e564e1 
And it works, it is stable, but **syncing is stuck at 0 hours so no MNs are connected**.

**Comment by tgflynn** [comment]
It should help if you add the following line to dash.conf:

addnode=52.90.74.124:19999

Even with this it might take a while for it to find the right peers because many nodes are still running older versions that are on the other chain fork.

**Comment by Comodore125** [comment]
adding node helped in miliseconds it started another phase of syncing and in tens of seconds it was fully synced.
